### ISSUE TITLE
Can (seemingly) deploy containers on deactivated hosts

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#100]
I accidentally deactivated a host (misclicked, and didn't even realize it - warning 1).

Warning 2 is that I then tried to deploy docker containers. After setting up the container name, port forwarding etc. I clicked create, and nothing happened. Confused! 

A simple solution would be to to disallow container creation when a host is deactivated.

**Comment by hibooboo2** [comment]
This Is no longer an issue with the latest version. Hosts now lose the add container when they are inactive.

**Comment by vincent99** [comment]
Fixed in rancherio/ui#64
