### ISSUE TITLE
After adding new registry, the email/username doesn't immediately show up. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1003]
v0.22.0-rc2

Steps to Reproduce:

1. Add Registry
Result: Email and Username show "None" instead of showing the email and username. If I click on anything in the page, it populates those fields

Expected Result: Email and Username should show up immediately after clicking Create.

![screen shot 2015-06-01 at 9 51 43 am](https://cloud.githubusercontent.com/assets/11410997/7918089/d357e634-0843-11e5-838e-32e9dceff725.png)

**Comment by tfiduccia** [comment]
Build from master - June 9th
Verified fixed
