### ISSUE TITLE
When cloning a service that has labels for host affinity set , the UI does not show this label. 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1005]
Server Version - build from master 06/01

Steps to reproduce the problem:

Create a service with label for host affinity  set - "io.rancher.scheduler.affinity:host_label" 
Clone this service.
When the "Add Service" page is shown, UI does not include the existing label - "io.rancher.scheduler.affinity:host_label" .

But when the service cloned , i see the "io.rancher.scheduler.affinity:host_label" set for the service.

Expected Behavior:
When service is cloned , " "Add Service" page should show  the existing label - "io.rancher.scheduler.affinity:host_label".

**Comment by sangeethah** [comment]
Tested with v0.23.0-rc1:
This issue is still reproducible.

**Comment by vincent99** [comment]
User labels are cloned now.  System ones (`io.rancher.*`) are not because they will be put into the scheduling UI eventually.

**Comment by vincent99** [comment]
The global and scheduling-related labels should be cloned now in to the UI.  If there are additional system labels that do not have controls in the UI they will not be cloned, but I don't know of any, or that they necessarily should be cloned.

**Comment by tfiduccia** [comment]
v0.23.0-rc5
Labels are cloned in services
Verified Fixed
