### ISSUE TITLE
We should not allow for setting/updating scale for global services.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1008]
Server version - Build from master - 06/01

Currently we are allowed to scale up / scale down services that are created with global option set to "true".

Also when creating a service with global option set , API should error out when scale is set.

**Comment by vincent99** [comment]
FYI, the scale up button/slider is hidden in the UI now in https://github.com/rancherio/ui/pull/183

**Comment by will-chan** [comment]
UI might be good enough.

**Comment by tfiduccia** [comment]
Need to remove the scale from the Service Details page as well.

**Comment by tfiduccia** [comment]
v0.23.0-rc5
Verified fixed
