### ISSUE TITLE
UI - Allow users to add either set scale or set global to true when adding a service.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1009]
Server version - Build from master 06/01

UI should allow for users to set a scale or  set global to true when adding a service.
Currently , I am allowed to set any scale for a service that gets marked as global.

This results in the scale being different from the actual number of instances that get spawned for the service.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/7926196/c61a9bca-0883-11e5-952a-b38a51070b8b.png)

**Comment by sangeethah** [comment]
On the latest master UI , we are allowed to set only scale/global when  creating a service.
