### ISSUE TITLE
Windows is flickering because scrollbar is (re)appearing

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#101]
When I open a shell window (what an awesome functionality!) there is a vertical scrollbar flickering on the right side. 

It is reproduced in fullscreen window on 1280x1024 monitor and in smaller windows on 1920x1080 monitor, but  1920x1080  it doens't happen. 

I also had it with the normal http://localhost:8080/static/hosts url (overview of hosts). Quite annoying to the eye... 

Reproduced it with chrome Version 40.0.2214.93 (64-bit) and Firefox 35.0.1

**Comment by ibuildthecloud** [comment]
@vincent99 Has this been fixed in master?

**Comment by feliksik** [comment]
seems closed in latest ;-) thanks to darren for pointing me to it

**Comment by vincent99** [comment]
(yes)
