### ISSUE TITLE
When a project is created and service is created but not activated yet , project state is "Degraded"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1010]
Server version - Build from master 06/01

Steps to recreate the problem:
Create a project.
Create a service. Do not activate it.
We see the project in "Degraded" state.

Should there be a different status to track the state of the project when the service has not been activated in a project? "Degraded" is used to indicate that there is some problem with the service scale that needs to be looked in to and does not seem to fit this use case.

**Comment by will-chan** [comment]
Maybe for the Degraded status, we only check against active services and ignore all non-active services.

**Comment by vincent99** [comment]
But if you have a service that is doing something and someone accidentally deactivates it, it would say the environment is "active" even though your app is broken..

**Comment by will-chan** [comment]
We can leave it as is and get feedback from users before changing anything.
