### ISSUE TITLE
When service is activated , containers are launched sequentially.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1011]
Server version - build from master at 06/01

Steps to reproduce the problem:
Create a service with scale 3 using an image that is not downloaded to any host.
Notice that the first container gets started and no other container gets launched until the first container gets "running" state which took a long time since it was downloading images.

Expected Behavior:
We should see all the containers of the service getting launched in parallel.

**Comment by alena1108** [comment]
The bug happens because instance of the same services are treated as separate deployment units, and the start of the next one isn't scheduled before the the previous one is started. Will fix by moving out "waitForStart" logic on the deploymentUnit level.

**Comment by sangeethah** [comment]
Tested with server version - rancher/server:v0.23.0-rc2 
Create a service with scale 3 using an image that is not downloaded to any host.
All 3 containers get to the same host because of #1017 , but I see all the containers get launched in parallel and waiting for the image to get downloaded.

Closing this issue.
