### ISSUE TITLE
All containers of the service land in the same host when no labels are specified

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1017]
Server Version - V0.23.0-rc1

Steps to reproduce the problem:
I have 3 hosts in my set up.
Create a service with no labels ( global is not set and no affinity host labels) and activate the service .
I see all the containers of the service always go to the same host.
I tried at least 5 times and see that containers of the same service land in the same host.

**Comment by sonchang** [comment]
I just merged fix into master.  Should be available in the next build

**Comment by sangeethah** [comment]
Reopening this issue.
Tested with server version - rancher/server:v0.23.0-rc2
Create a service with no labels ( global is not set and no affinity host labels) and activate the service .
I see all the containers of the service always go to the same host.

**Comment by sonchang** [comment]
Just merged in

**Comment by sangeethah** [comment]
Tested with Server Version - V0.23.0-rc5

When services are created with scale and no other scheduling policies , I see containers being deployed in different hosts.
