### ISSUE TITLE
Not able to edit  "DNS" service.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1018]
Server version - V0.23.0-rc1

Steps to reproduce the problem:
Create service S1
Create a DNS service linked to S1.
Create service S2 linked to DNS service.
Activate all the services.

Try to edit DNS service.
I am redirected to http://104.197.53.105:8080/static/fail

Error
Property set failed: object in path "labelResource" could not be found or was destroyed.
Reload to try again or log out

**Comment by tfiduccia** [comment]
v0.23.0-rc5
Verified fixed, can get to edit screen
