### ISSUE TITLE
Amazon EC2: Added host logs and graphs not working

### ISSUE THREAD

**Issue by VogonogoV** [rancherio/rancher#1019]
Steps to reproduce:

1. Start an EC2 instance with for example Ubuntu Server (ami-47a23a30)
 - Make sure TCP ports `22`, `8080`, `9345`, `9346` are open in the security group
2. SSH to the instance and:
 - Install docker: `wget -qO- https://get.docker.com/ | sh`
 - Start rancher server (as per installation guide): `sudo docker run -d --restart=always -p 8080:8080 rancher/server`
 - Open a browser and go to: `<your-ec2-public-dns-address>:8080`
3. Add Host
 - Select Amazon EC2, enter access and secret key
 - Use rancher-machine security group
4. Wait for the instance to get registered in Rancher, while waiting:
 - Verify that both EC2 instances have the right security groups and open ports
 - Try to figure out if you can ssh to the just created EC2 instance until you find out is created a new key pair and you don't have the key
5. Go to the just added host in the rancher interface
 - CPU and memory utilization will stay at "connecting"
 - Verify with different browsers to make sure its not a browser issue
6. (Optional) Add a container to the host
 - As an example enter image name `jenkins`
 - Open port `8080` in the security group rancher-machine
 - Go to `<your-other-ec2-public-dns-address>:8080` and verify Jenkins is running
7. Go to the Jenkins container in the Rancher web interface
 - Verify graphs will stay at "connecting"
 - Try to "View logs" and see that it stays at "Initializing"

Rancher server:
```
$ sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
Rancher interface shows the following information about the added host:
```
Kernel 3.13.0-48-generic
Docker 1.6.0, build 4749651
```
Please let me know if you need more information. Did I forget something/do something wrong? Is this a docker 1.6.0/1.6.2 incompatibility?

**Comment by deniseschannon** [comment]
For step 1, you should only need the `22`, `8080` port for the security group running Rancher Server.

For step 4, after the host is created, we provide the key to ssh into the host inside the machine config. It can be downloaded in the dropdown menu of the host. You can ssh in using 'ssh -i id_rsa  ubuntu@<ip_of_host>.

I followed your instructions exactly as you did. Did you make any changes in the security groups for rancher-machine and allow Rancher to create the security group?

For step 5 & 7, I am able to view the graphs. 

@vincent99 any other reason why his graphs wouldn't show up for host or container?

There is a known issue about the Docker build on the UI showing the incorrect version. So it won't be a compatibility issue. https://github.com/rancherio/rancher/issues/912

**Comment by vincent99** [comment]
The other thing that could be wrong is that the hosts registered into the server with a non-public IP.  The browser is trying to open up a connection direct to the IP address shown for the host on `:9345` to load those states.  You can also open up the browser dev-tools network tab and see the websocket being opened.

**Comment by cjellick** [comment]
Should be addressed by #777

**Comment by VogonogoV** [comment]
> For step 1, you should only need the 22, 8080 port for the security group running Rancher Server.

Ok.

> For step 4, after the host is created, we provide the key to ssh into the host inside the machine config. It can be downloaded in the dropdown menu of the host. You can ssh in using 'ssh -i id_rsa ubuntu@.

Ah great.

> I followed your instructions exactly as you did. Did you make any changes in the security groups for rancher-machine and allow Rancher to create the security group?

No changes to the rancher-machine group have been made, Rancher created the security group.

```
Type			Protocol	Port Range	Source	
Custom TCP Rule	TCP			2376		0.0.0.0/0
Custom UDP Rule	UDP			4500		0.0.0.0/0
Custom TCP Rule	TCP			9345 - 9346	0.0.0.0/0
SSH				TCP			22			0.0.0.0/0
Custom UDP Rule	UDP			500			0.0.0.0/0
```

> The other thing that could be wrong is that the hosts registered into the server with a non-public IP. The browser is trying to open up a connection direct to the IP address shown for the host on :9345 to load those states. You can also open up the browser dev-tools network tab and see the websocket being opened.

You are right, the browser is trying to open a web socket to the docker ip 172.17.42.1, when I go to the actual external ip on :9345 I get a "Failed authentication" which is probably correct because I don't provide a token.

**Comment by deniseschannon** [comment]
ok. it sounds as if rancher agent picked up the wrong IP, which happens occasionally. with the fix in #777, the stats won't be relying on the IP picked up by rancher agent so it should fix your issue. 

Have you tried to launch another EC2 instance to see if it works? Most of my instances have been fine. 

Also, what version of rancher are you running? You can do a `docker inspect` on the rancher server and provide the value of the environment variable: `CATTLE_RANCHER_SERVER_IMAGE`.

**Comment by VogonogoV** [comment]
>Have you tried to launch another EC2 instance to see if it works? Most of my instances have been fine. 

I tried 3, maybe I'm just unlucky.

The `CATTLE_RANCHER_SERVER_IMAGE` is `v0.22.0-rc2`.

>ok. it sounds as if rancher agent picked up the wrong IP, which happens occasionally. with the fix in #777, the stats won't be relying on the IP picked up by rancher agent so it should fix your issue. 

Great, thanks for the support :)

**Comment by adamkdean** [comment]
I'm getting this issue with `CATTLE_RANCHER_SERVER_IMAGE=v0.24.0` and UI versions:

    Rancher	v0.24.0
    Cattle	v0.56.0
    User Interface	v0.28.0
    Rancher Compose	latest
    Machine Service	v0.13.0 (docker-machine v0.3.0-dev-packet-rc2)

I have two NICs per VM; eth0 is an IP on 192.168.9.0/24 and is accessible by my local machine, eth1 is on 10.10.10.0/24 and is accessible from the main Rancher server along with the individual Rancher nodes, but not from my local machine.

I saw that there was a fix but this doesn't appear to be working for me. I'm happy to try out some fixes if you have any ideas.

**Comment by deniseschannon** [comment]
@adamkdean are you also using amazon EC2 instances? When you add your VMs, are you adding custom hosts or using the EC2 deployment on the Rancher UI? 

If you are adding custom hosts (ie running the docker command to launch rancher agent), you can add `-e CATTLE_AGENT_IP=<accessible_ip>` to the command to pick up the correct IP.
