### ISSUE TITLE
DockerHub with Private Registries.

### ISSUE THREAD

**Issue by jwhitcraft** [rancherio/rancher#1021]
When using DockerHub with private registries, it keeps on telling me: `500 Server Error: Internal Server Error ("Could not get container for 0be613fc-dd9d-42da-917f-d3a32679774a"` when i enter in `docker:<my registry name>/<my image name>:latest` for the image to use.

I have setup the registry in Rancher and on the host that i'm trying to deploy to.  Am I missing something?

**Comment by hibooboo2** [comment]
@jwhitcraft which version of rancher/server are you using? if running in a docker container just do ```docker inspect```. Need the value of ```CATTLE_RANCHER_SERVER_IMAGE ```

**Comment by jwhitcraft** [comment]
@hibooboo2,

I am running `CATTLE_RANCHER_SERVER_IMAGE=v0.22.0-rc2` and i used this command to start the server: `docker run -d --restart=always -p 8080:8080 rancher/server`

**Comment by hibooboo2** [comment]
Ok. So is your registry one through say quay.io, or are you hosting your own?

**Comment by jwhitcraft** [comment]
it's dockers private registry, and even then, if i goto the machine and do a `docker pull <registry>/<image>` after i login, it pulls fine, but when i try and do it though Rancher, i always get the same error.

**Comment by hibooboo2** [comment]
Hmm.. So you can do a docker pull on the box. But not when using rancher.

**Comment by jwhitcraft** [comment]
Correct.  I've tried on two different hosts and i get the same error.

**Comment by hibooboo2** [comment]
Can you send me more of the logs from your server as this seems to not be a problem with pulling it is something else.

**Comment by jwhitcraft** [comment]
here is the full log from the server: https://gist.github.com/jwhitcraft/e0deee5e23c8bd7c5c39

here is the full log from the agent: https://gist.github.com/jwhitcraft/71e810035ec5d051fded

**Comment by hibooboo2** [comment]
So if you pull the images first on each host and then try launching the containers does that at least work? Just wanting to make sure.

**Comment by jwhitcraft** [comment]
@hibooboo2, it does not.  It seems like thinks it's missing a layer or something.

**Comment by hibooboo2** [comment]
Yeah that is what it looked like based on the rancher-agent logs. Hard to say since I can't duplicate this locally without a registry using your setup.

**Comment by jwhitcraft** [comment]
Hrmm, since i'm just in the testing phase, i'll delete the registry from docker and re-push it to see if that solves it.

**Comment by hibooboo2** [comment]
ok

**Comment by jwhitcraft** [comment]
It seems to only be an issue when i link it to my mysql container (not created via Rancher)  I'll try this locally.

**Comment by jwhitcraft** [comment]
so, i just created a new machine on digital ocean and setup mysql and my site again and it worked fine.  I am using the managed networking now, where as before i was using bridged.  I'll chalk this up to trying to use an existing docker install vs a fresh one.

**Comment by hibooboo2** [comment]
Glad you were able to fix it.
