### ISSUE TITLE
Host stuck in activating state forever , even after rancher agent is running.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1029]
Server version - rancher/server:v0.23.0-rc2

steps to reproduce the problem:

Added a digital Ocean machine with labels  (name = value) . Host got added successfully thought it took a long time.

Added another digital Ocean machine with labels  (name = value) . Host is stuck in "activating" state for more than 30 minutes now. I see the rancher agent is already installed and is running on the machine,

Added another digital Ocean machine without any labels . Host is stuck in "activating" state for more than 30 minutes now. I see the rancher agent is already installed and is running on the machine,

**Comment by will-chan** [comment]
Wasn't this resolved Sangeetha?

**Comment by sangeethah** [comment]
Server version - rancher/server:v0.23.0-rc5

This issue is not reproducible anymore.

I was able to add many Digital Ocean machines with and without labels and had no issues.
