### ISSUE TITLE
Shell not working

### ISSUE THREAD

**Issue by ict4ngo** [rancherio/rancher#103]
Whatever container I choose I get  *Connecting...*  forever.

I can connect through the host  using docker exec -ti ...

container are started  with YES -t -i 

----
docker --version
Docker version 1.5.0, build a8a31ef

**Comment by hibooboo2** [comment]
Which rancher version are you using? How did you deploy rancher?

**Comment by ict4ngo** [comment]
I manually deploy it

docker images | grep rancher
rancher/server           latest              442370fd5d8f        2 weeks ago         354.9 MB
rancher/server           v0.5.0              442370fd5d8f        2 weeks ago         354.9 MB
rancher/server           v0.5.0-rc1          442370fd5d8f        2 weeks ago         354.9 MB
rancher/agent            latest              3d409ba796f9        3 weeks ago         285.1 MB
rancher/agent            v0.3.1              3d409ba796f9        3 weeks ago         285.1 MB
rancher/agent-instance   v0.1.0              545091ebf275        3 months ago        502 MB

**Comment by hibooboo2** [comment]
Are you using boot2docker by chance?

**Comment by ict4ngo** [comment]
nope a fresh ubuntu 14.04 in a KVM machine

**Comment by hibooboo2** [comment]
Ok One second

**Comment by hibooboo2** [comment]
When you are launching the container for the server which command did you use?

**Comment by ict4ngo** [comment]
docker run -d -e VIRTUAL_HOST=rancher.test --name rancher_test -p 8080:8080 rancher/server

**Comment by hibooboo2** [comment]
It seems to me that the problem may be arising from the way you are registering rancher agent to the host. And as a result the websocket that the exec connects over is not able to connect. If you are able to do a google hangout or something i can try to further debug this with you, however using the setup you specified with the version of rancher/server and rancher/agent you used i was unable to replicate this behavior just now unless the agent is improperly registered. This is something that I dealt with when writing the container logs feature. When the UI that you are using cannot make a websocket connection to the ip that rancher agent is registering itself at you get this error.

**Comment by ict4ngo** [comment]
I sent you the invite

**Comment by hibooboo2** [comment]
Where at?

**Comment by hibooboo2** [comment]
Got it

**Comment by hibooboo2** [comment]
If the networking stack between the UI, Host, and cattle has firewalls and other non 'flat' structures then this issue arises.

**Comment by ict4ngo** [comment]
thanks, rancher was running behind a reverse proxy
