### ISSUE TITLE
Rancher 2

### ISSUE THREAD

**Issue by ds0nt** [rancherio/rancher#1030]
![img_20150604_091715](https://cloud.githubusercontent.com/assets/1015732/7975659/aa935a18-0a9a-11e5-935f-293151a10832.jpg)

**Comment by ds0nt** [comment]
Meow

**Comment by ibuildthecloud** [comment]
Laser cats.... I like where you're going with this.

**Comment by clemenko** [comment]
Thunder chicken?

**Comment by vincent99** [comment]
I for one welcome our new laser cat overlords.

![image](https://cloud.githubusercontent.com/assets/753917/8011238/e81b1ee4-0b6b-11e5-98a6-93205dac3d28.png)

**Comment by ds0nt** [comment]
Issue closed to non-felines.
