### ISSUE TITLE
Labels are not added when creating host

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1032]
v0.23.0-rc2
Steps:
1.  Go through an EC2 host setup (this happened with DO as well)
2.  On last page, add a couple of labels
3.  Create
4.  Edit host

Results:
There are no labels

Expected:
Should have the labels you added during the create

**Comment by sangeethah** [comment]
This is duplicate of #999 . This issue is still not in v0.23.0-rc3 since we need new version of go-machine to be packaged,
