### ISSUE TITLE
Service set to Global, add new host, no new service container created

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1036]
v0.23.0-rc2
Steps:
1.  Have at least 2 hosts
2.  Create a service and set Always run one instance of this container on every host
3.  Start service
4.  Add another host

Results:
The host is added but the service container is not created.

Expected:
When I add a host, a service container should be created from the Global service.

**Comment by sonchang** [comment]
I'll take a look!

**Comment by tfiduccia** [comment]
v0.23.0-rc5
Verified fixed
