### ISSUE TITLE
Unable to load CPU and Memory info

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#104]
I am unable to see CPU and memory statistics for Rancher nodes, When I load the page the loading icon keeps spinning.

I am running rancher on an AWS Centos AMI with docker 1.5.0.

Rancher server docker ps

    CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES
    890c5b7ea408        ubuntu:14.04.1                  "bash"                 12 minutes ago      Up 12 minutes                                                      f52012ba-cb85-4be8-9573-a9457170a276
    e1e46873de57        rancher/agent-instance:v0.1.0   "/etc/init.d/agent-i   12 minutes ago      Up 12 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   00ba02fa-c04e-4f2a-824b-9a140849e6a0
    b0eefda478c1        rancher/agent:v0.3.2            "/run.sh run"          21 minutes ago      Up 21 minutes                                                      rancher-agent
    6039e08850c1        rancher/server:latest           "/usr/share/cattle/c   38 minutes ago      Up 38 minutes       0.0.0.0:8080->8080/tcp                         prickly_newton

Rancher Node docker ps

    docker ps
    CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES
    890c5b7ea408        ubuntu:14.04.1                  "bash"                 12 minutes ago      Up 12 minutes                                                      f52012ba-cb85-4be8-9573-a9457170a276
    e1e46873de57        rancher/agent-instance:v0.1.0   "/etc/init.d/agent-i   12 minutes ago      Up 12 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   00ba02fa-c04e-4f2a-824b-9a140849e6a0
    b0eefda478c1        rancher/agent:v0.3.2            "/run.sh run"          21 minutes ago      Up 21 minutes                                                      rancher-agent
    6039e08850c1        rancher/server:latest           "/usr/share/cattle/c   38 minutes ago      Up 38 minutes       0.0.0.0:8080->8080/tcp                         prickly_newton

![screen shot 2015-02-19 at 12 46 23 pm](https://cloud.githubusercontent.com/assets/204682/6272416/68250abc-b835-11e4-8b65-d2e6056d9225.png)

**Comment by usmanismail** [comment]
Figured it out.
Rancher uses other ports than 8080 which were blocked by the Amazon Security Groups.

**Comment by cjellick** [comment]
Glad you figured it out. We were just about to reply with that same answer.
We've opened https://github.com/rancherio/ui/issues/69 to more clearly indicate that there is a connection failure instead of jsut spinning.

Thanks for reporting.

**Comment by usmanismail** [comment]
Are there docs on the complete set of ports that are used, which need to be open to the cluster and which need to be open to the browser client? I don't want to have to open unused ports.

**Comment by cjellick** [comment]
@usmanismail We just updated the readme here: https://github.com/rancherio/rancher#register-docker-nodes

9345 and 9346 are the only ports that need opened from the compute nodes to the Internet. The api node requires port 8080.

We don't anticipate opening more ports than this.

**Comment by ibuildthecloud** [comment]
For intra node communication ports 500 and 4500 both UDP should be open.  This is to allow nodes to create ipsec tunnels between each other.

**Comment by usmanismail** [comment]
Thank you
