### ISSUE TITLE
Click here link takes you to generic Github page, which won't work for Enterprise

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1045]
v0.23.0-rc1
Steps:
1.  Go to Access Control page
2.  Click on Click here link

Results:
Takes you to https://github.com/settings/developers.  This won't work for Enterprise customers.

Expected:
Maybe we should add some text or something in documentation that tells customers how to setup on their enterprise site.

**Comment by vincent99** [comment]
Added text for enterprise.

**Comment by tfiduccia** [comment]
build from master - June 10th
Verified fixes
