### ISSUE TITLE
Can't create packet host/machine

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1047]
v0.23.0-master
Steps:
1.  Go to Hosts
2.  Try to create a packet machine/host

Results:
Exit status 1.  As soon as I'm done setting up, it just bombs.  Never even looks like it gets to the first step.

Expected:
Should create

Comments:
I am authenticated and using an enterprise account.

**Comment by wlan0** [comment]
This was a non-issue. The authentication step was failing and the error message did not indicate it. Will track the fix for better error messages here https://github.com/rancherio/rancher/issues/1048
