### ISSUE TITLE
Inactive Credential has a blue icon instead of red.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1049]
v0.23.0-rc4

Activating and Inactive icons are blue instead of red.

![screen shot 2015-06-04 at 11 49 28 am](https://cloud.githubusercontent.com/assets/11410997/7991823/db99ff26-0aaf-11e5-9815-530b182ad125.png)

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
