### ISSUE TITLE
Images that require credentials can be reused even if registry is inactive/deleted. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1051]
v0.23.0-rc4

Steps To Reproduce:
1. Active Credential
2. Create container on Host using image that requires credentials
3. Deactivate credential
4. Repeat Step 2 with same image

Result: Container is launched

Expected Result: If I de-activate a credential, I'd expect no images from my registry would be able to launch containers.

Note: I understand that this is hard to control as we don't remove images. But I don't think we can say definitively that we don't use those credentials. 

Maybe the solution is to just document this use case?

**Comment by deniseschannon** [comment]
@ibuildthecloud @hibooboo2 any thoughts?

**Comment by hibooboo2** [comment]
The thing is docker only needs credentials to pull an image. Once it is pulled anyone can use it on the host.

**Comment by deniseschannon** [comment]
I've documented this scenario. 

Based on this scenario, there could be a request to be able to delete images from a host, but will wait for the request.
