### ISSUE TITLE
Not able to deactivate a service that is stuck in "Activating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1054]
Server version - built from master jun/04

Steps to reproduce the problem:
Add a service with a scale and scheduling policy that cannot be satisfied.
test1 is the name of this service with scale 8 when I had only 5 hosts in the set up.
Following is the label i used:
"labels": {
"io.rancher.scheduler.affinity:container_label_ne": "io.rancher.service.name=test1",
},
Service is stuck in "activating" state.
Now try to "Stop" the service.
I see the status changes to "Deactivating" and then back to "Activating" and then it is stuck in that state forever.

**Comment by alena1108** [comment]
Logs?

**Comment by sangeethah** [comment]
Tested with build from master - jun/10.

I am able to de active a service that was stuck in "activating" state successfully.
