### ISSUE TITLE
Service stuck in "removing" state when it has instances marked as being "unhealthy".

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1055]
Server version - Built from mater - Jun/04

Steps to reproduce the problem:
Created a service with health check policy enabled. I had a non existent file name for health check url.
All the containers in my set up are marked as "unhealthy" which is as expected.
When I try to delete this service , it is stuck in "removing" state forever.

**Comment by alena1108** [comment]
@sangeethah I can't reproduce the problem. Could you attach the logs for the bugs like that in the future? It might be a race condition, and w/o the logs its impossible to tell of what went wrong.

**Comment by sangeethah** [comment]
The behavior i actually is the following:

When I remove a service that has unhealthy instance , I see that lot of instances get created and destroyed before it gets removed.
After a while , i see the service being marked "removed" , I still see instances relating to this service being created.


mysql> select id,name,state from instance  where name like "%test_testheatlthrem%";
+-----+-----------------------+----------+
| id  | name                  | state    |
+-----+-----------------------+----------+
| 231 | test_testheatlthrem_1 | purged   |
| 232 | test_testheatlthrem_2 | purged   |
| 235 | test_testheatlthrem_3 | purged   |
| 236 | test_testheatlthrem_1 | purged   |
| 239 | test_testheatlthrem_2 | purged   |
| 240 | test_testheatlthrem_4 | purged   |
| 243 | test_testheatlthrem_1 | purged   |
| 244 | test_testheatlthrem_3 | purged   |
| 247 | test_testheatlthrem_1 | purged   |
| 248 | test_testheatlthrem_2 | purged   |
| 251 | test_testheatlthrem_1 | purged   |
| 253 | test_testheatlthrem_3 | purged   |
| 254 | test_testheatlthrem_1 | purged   |
| 257 | test_testheatlthrem_2 | purged   |
| 259 | test_testheatlthrem_3 | purged   |
| 262 | test_testheatlthrem_1 | purged   |
| 263 | test_testheatlthrem_2 | purged   |
| 266 | test_testheatlthrem_3 | purged   |
| 267 | test_testheatlthrem_4 | purged   |
| 270 | test_testheatlthrem_1 | purged   |
| 271 | test_testheatlthrem_2 | purged   |
| 274 | test_testheatlthrem_1 | purged   |
| 275 | test_testheatlthrem_3 | purged   |
| 278 | test_testheatlthrem_2 | purged   |
| 279 | test_testheatlthrem_3 | purged   |
| 281 | test_testheatlthrem_2 | purged   |
| 283 | test_testheatlthrem_1 | purged   |
| 287 | test_testheatlthrem_1 | purged   |
| 288 | test_testheatlthrem_2 | purged   |
| 289 | test_testheatlthrem_1 | purged   |
| 290 | test_testheatlthrem_2 | purged   |
| 293 | test_testheatlthrem_1 | purged   |
| 295 | test_testheatlthrem_2 | purged   |
| 299 | test_testheatlthrem_1 | purged   |
| 300 | test_testheatlthrem_2 | purged   |
| 302 | test_testheatlthrem_2 | purged   |
| 304 | test_testheatlthrem_2 | purged   |
| 305 | test_testheatlthrem_3 | purged   |
| 309 | test_testheatlthrem_1 | purged   |
| 310 | test_testheatlthrem_4 | purged   |
| 314 | test_testheatlthrem_2 | purged   |
| 315 | test_testheatlthrem_2 | purged   |
| 316 | test_testheatlthrem_3 | purged   |
| 319 | test_testheatlthrem_1 | purged   |
| 320 | test_testheatlthrem_2 | purged   |
| 321 | test_testheatlthrem_2 | purged   |
| 322 | test_testheatlthrem_3 | purged   |
| 323 | test_testheatlthrem_4 | purged   |
| 324 | test_testheatlthrem_5 | purged   |
| 325 | test_testheatlthrem_1 | purged   |
| 326 | test_testheatlthrem_2 | purged   |
| 327 | test_testheatlthrem_3 | purged   |
| 328 | test_testheatlthrem_1 | purged   |
| 329 | test_testheatlthrem_2 | purged   |
| 330 | test_testheatlthrem_3 | purged   |
| 331 | test_testheatlthrem_1 | purged   |
| 332 | test_testheatlthrem_2 | purged   |
| 333 | test_testheatlthrem_3 | purged   |
| 334 | test_testheatlthrem_1 | purged   |
| 335 | test_testheatlthrem_4 | purged   |
| 336 | test_testheatlthrem_1 | purged   |
| 337 | test_testheatlthrem_2 | purged   |
| 338 | test_testheatlthrem_3 | purged   |
| 339 | test_testheatlthrem_1 | purged   |
| 340 | test_testheatlthrem_4 | purged   |
| 341 | test_testheatlthrem_1 | purged   |
| 342 | test_testheatlthrem_2 | purged   |
| 343 | test_testheatlthrem_2 | purged   |
| 344 | test_testheatlthrem_3 | purged   |
| 345 | test_testheatlthrem_1 | purged   |
| 346 | test_testheatlthrem_2 | purged   |
| 347 | test_testheatlthrem_1 | purged   |
| 348 | test_testheatlthrem_2 | purged   |
| 349 | test_testheatlthrem_2 | purged   |
| 350 | test_testheatlthrem_3 | purged   |
| 351 | test_testheatlthrem_1 | purged   |
| 352 | test_testheatlthrem_2 | purged   |
| 353 | test_testheatlthrem_1 | purged   |
| 354 | test_testheatlthrem_3 | purged   |
| 355 | test_testheatlthrem_2 | purged   |
| 356 | test_testheatlthrem_1 | purged   |
| 357 | test_testheatlthrem_3 | purged   |
| 358 | test_testheatlthrem_2 | purged   |
| 359 | test_testheatlthrem_1 | removed  |
| 360 | test_testheatlthrem_2 | removed  |
| 361 | test_testheatlthrem_3 | removed  |
| 362 | test_testheatlthrem_4 | removed  |
| 363 | test_testheatlthrem_1 | removed  |
| 364 | test_testheatlthrem_2 | removed  |
| 365 | test_testheatlthrem_5 | removed  |
| 366 | test_testheatlthrem_6 | removed  |
| 367 | test_testheatlthrem_1 | running  |
| 368 | test_testheatlthrem_2 | running  |
| 369 | test_testheatlthrem_3 | starting |
+-----+-----------------------+----------+
94 rows in set (0.00 sec)

mysql> select id,name,state from service where name="testheatlthrem";     
+----+----------------+---------+
| id | name           | state   |
+----+----------------+---------+
| 26 | testheatlthrem | removed |
+----+----------------+---------+
1 row in set (0.00 sec)

mysql>

**Comment by sangeethah** [comment]
The same behavior is also seen when trying to stop a service that has unheathy instances. After a long time , i see the service marked as being in "inactive" state. Even after this , I see instances being started and destroyed for this service. 

from instance table:
+-----+-----------------------+----------+
| id | name | state |
+-----+-----------------------+----------+
| 433 | test_testheatlthrem_1 | starting |
| 434 | test_testheatlthrem_2 | starting |
+-----+-----------------------+----------+
271 rows in set (0.00 sec)

mysql> select id,name,state from service where name="testheatlth";                 
+----+-------------+----------+
| id | name        | state    |
+----+-------------+----------+
| 25 | testheatlth | inactive |
+----+-------------+----------+
1 row in set (0.00 sec)

**Comment by sangeethah** [comment]
Tested with build from master - Jun/10.
I am able to successfully Delete services that have unhealthy instances.
I am also able to successfully Stop services that have unhealthy instances and then delete the service.

**Comment by Robbie1977** [comment]
I've had the same problem since v1.5.8 and has remained during multiple rancher server upgrades. Now on:

Component | Version
-- | --
Rancher | v1.6.2
Cattle | v0.181.4
User Interface | v1.6.5
Rancher CLI | v0.6.1
Rancher Compose | v0.12.5

The actual instances were never healthy and got deleted and purged in attempts to resolve the 'removing' state several versions ago so now simply have a service with no instances stuck 'removing'. 

Let me know what other details you require?
