### ISSUE TITLE
Is it possible to use a simple PaaS like Dokku with Rancher?

### ISSUE THREAD

**Issue by eneko89** [rancherio/rancher#1056]

**Comment by vincent99** [comment]
Yes?  If you use Dokku on a host the containers it starts will show up in Rancher.

**Comment by deniseschannon** [comment]
@eneko89 We haven't tested out Dokku with Rancher, but with the native docker integration (available in Beta), any containers created outside of Docker will automatically show up in Rancher. 

http://rancher.docs.rancher.com/docs/native-docker/
