### ISSUE TITLE
service_name used in scheduling should be restricted to the project in which the services are being created.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1057]
Server version - Build from master - jun 04

Steps to reproduce the problem:

Create project1.
Create service1 with name "test"  and requestedHostId set to host1.

Create project2.
Create service1 with same name "test" and requestedHostId set to host2.
Create service2 with scale 2 and scheduling policy set to "host must have a service with name "test".

We see 1 container of service2 being launched in host1 and another 1 in host2.

Expected Behavior:
Both containers of service2 should be launched in host2.

**Comment by will-chan** [comment]
Might be better to have UI automatically add the labels required to schedule against services of the same project.

**Comment by vincent99** [comment]
There is no current label that works correctly for this for me to set.

**Comment by sonchang** [comment]
Looks like this should be split into several separate issues.

1) In the UI, the dropdown for the list of services should be scoped to the environment ("project").  So within the API, something like: http://localhost:8080/v1/projects/1a5/environments/1e4/services

2) In terms of the labels generated, cattle currently generates:
"io.rancher.service.name": "s1"
"io.rancher.environment.name": "p1"

Unfortunately, this isn't enough for the "must not" and "should not" conditions for service name.  I can modify cattle so that it also generates:
"io.rancher.env_service.name": "s1_p1"

@vincent99 How does this sound?

**Comment by sonchang** [comment]
Either that or we can create a new affinity rule specifically for service name.  Since a string concatenation of the environment name and service name isn't perfect.

**Comment by vincent99** [comment]
A combined field makes sense to me... @ibuildthecloud?  For string concat it would have to be a separator character that isn't allowed in an environment name (which is I think the rules of a DNS label plus underscore?).  Maybe slash?

**Comment by sonchang** [comment]
Yeah.  Looks like underscore might be allowed.  I'll switch it to a slash for now.

**Comment by ibuildthecloud** [comment]
@sonchang We should support the following variables in the container labels:

```
foo=${project_name}blah${service_name}
```

project_name should be the current project (which is actually environment in the code) of the container.  And similarly service_name should resolve to the current service.

**Comment by sonchang** [comment]
Cattle changes are in.  Reassigning to @vincent99 for UI changes

**Comment by vincent99** [comment]
UI changed in https://github.com/rancherio/rancher/issues/1148

**Comment by sangeethah** [comment]
Tested with latest build from master:

In scheduling section, We now have the service name drop down show "environment_name/service_name".
When  creating service , I pick scheduling option for "host must have service name Test1/test1" where Test1 - is the project name and "test1" is the service name in this project.
When i start the service , containers fail to deploy because of not being able to find placement. 

Following label set on the service  has "%2" instead of "/" -
io.rancher.project_service.name=Test1%2Ftest1

**Comment by vincent99** [comment]
https://github.com/rancherio/ui/pull/207

**Comment by sangeethah** [comment]
Tested with latest UI changes from master.

Host1 with label - name1=value1
Host2 with label - name1=value2

Environment - Test1 
Created a service - test1 with scheduling policy set to host must have host-label "name1=value1" , so all containers of this service land on Host1.
Environment - Test2
Created a service - test1 with scheduling policy set to host must have host-label "name1=value2", so all containers of this service land on Host2.


Created service in environment - Test1 . 
Pick scheduling option for "host must have service name Test1/test1" 
When i start the service , all containers of the service gets created on the Host1 as expected. 

Created service in environment - Test1 . 
Pick scheduling option for "host must have service name Test2/test1" 
When i start the service , all containers of the service gets created on the Host2 as expected.
