### ISSUE TITLE
Deleting host, degrades service with scaling and scheduling rule

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1058]
v0.23.0-master

Steps:
1.  Create 3 host, all three should have a label where kind = testhost
2.  Create a service 
           scale = 2 (Run 2 containers)
           Scheduling = The host "must" have a "host label" of "kind" = "testhost"
3.  Activate service
4.  Delete one of the host where the service is running

Results:
The Service is degraded and now only contains 1 container

Expected:
On delete of host, it should start up another container to meet the scale criteria

**Comment by sonchang** [comment]
Fix just merged into master

**Comment by tfiduccia** [comment]
build from master - June 11th (afternoon)
Verified fixed
