### ISSUE TITLE
[UI] Feature Request: Edit service/container after creation

### ISSUE THREAD

**Issue by Zaephor** [rancherio/rancher#1060]
Would love to be able to edit more settings of an existing container after creating it, I assume that it's coming but wanted to at least put a ticket in for it. I'd be happy with it even just being via the API endpoints for now before ending up in the GUI.

I mention it because I've had to recreate the same container about 4 times in a row because I forgot(in order, but not at the same time): the environment vars, the remote service link, the image itself... And after the first time expected to be able to just click edit to change the environment variable and reboot the container. So far it's just encouraging me to double check what I'm doing and get it right the first time.

**Comment by ibuildthecloud** [comment]
If you have a created service or container you can clone it and then edit the parameters before create.  Just click the circle and select "clone".  The problem with editing a lot of this stuff is that Docker also doesn't allow you to edit it.  So right now clone is the best we've got.

**Comment by vincent99** [comment]
Unfortunately Docker containers are immutable (not changeable) after creation.  The only things you can edit are things that we store that aren't really part of the container (name, description) or are accomplished with magic the network agent enables (linked container destinations).

This includes rebooting, it's still the same container if you stop and start it.  So you pretty much have to remove and recreate a container to change anything else.

There is a "Clone" action in the UI that will basically pre-fill the "add container" screen with all the setttings from an existing container.  So if you forget one thing you can clone the container, change it, and then delete the old container.  Which is roughly what you'd do in the docker CLI, hit the up arrow a couple times to get the previous command and change it.

**Comment by vincent99** [comment]
bah, you win this round @ibuildthecloud.

**Comment by Zaephor** [comment]
Ahhh ok, yea i figured fake the front end as "editing" the container, but in the backend destroy and recreate it. I was thinking of the experience of editing a docker-compose.yml file to make changes to my running containers on a host. From a "not paying attention" perspective, it feels like I'm editing the config file of my server and saving it, even though it's destroying and creating stuff on file save.

Versus the experience here, which is a little closer to "Ooops I smeared paint in the wrong part of the canvas, hand me another blank canvas"

Thanks @ibuildthecloud & @vincent99 on the clone button, I hadn't thought to click it as I assumed it too would only let me edit the Name and Description, or was going to just create item_02.

**Comment by deniseschannon** [comment]
@Zaephor I'm going to close this issue as @ibuildthecloud and @vincent99 have given the reasoning why you can't edit containers/services after creation and how to launch a similar container (by cloning).

**Comment by JulianKingman** [comment]
Does clone preserve volumes? It would be a shame to clone only to find all the data lost.

As @nlhkh has said [elsewhere](https://github.com/rancher/rancher/issues/2180), the Tutum behavior that gives the illusion of editing, while actually deleting and starting up new containers is really slick, something that I really look forward to in rancher's future. @Zaephor's canvas metaphor is very fitting.

**Comment by vincent99** [comment]
This thread is very old.  The "illusion of editing" you want is the Upgrade action on services.

**Comment by JulianKingman** [comment]
Just figured that out, thanks! Upgrades work great.
