### ISSUE TITLE
Feature request: Blacklisting hosts from being scaling targets for a service

### ISSUE THREAD

**Issue by Zaephor** [rancherio/rancher#1061]
I'm experimenting with a cluster of systems, 3 at DO, 1 sitting next to me, 1 VM elsewhere and depending on the time of day a dedicated colo box. Loving the ease that this offers for mixing them all and figuring out how I can offer this to my customers.

But I'd really like to be able to flag the box sitting next to me as a private host, not a public one so that the load balancer doesn't scale to it, or really any container trying to expose ports publicly. I know we can't easily generalize a container by it's contents, so was thinking that detecting host ports being called might be an effective way to handle it.

Alternatively, a dropdown list of hosts for a blacklist or whitelist that the user configures could ease the issue.

**Comment by vincent99** [comment]
This can be accomplished with host labels + scheduling rules in this week's `0.23.x` release.  We haven't tagged a stable version yet but it should be in the next day or two.

Labels can be any key/value so you'd mark the host `private=true`, or `location=myhouse, or whatever makes sense to you.  Then you can add scheduling rules to hosts/containers that say e.g. "The host must not have the label private=true", and the containers will be put on to only hosts that meet the rules.

**Comment by Zaephor** [comment]
Ahhh I probably need to start playing in the beta playground huh? Probably already covered and coded the next set of wishlist items I haven't thought up yet.

**Comment by deniseschannon** [comment]
@Zaephor We just tagged latest this morning, so you should be able to do exactly what you want in the new features. We will be releasing some documentation in the next week or two to help users as we've started to add in a lot of features that may or may not be intuitive. 

Feel free to open a new issue for any specific questions you might have with our new host labels and scheduling rules.
