### ISSUE TITLE
Mouse Events Do Not Work On Main Menu In Chrome

### ISSUE THREAD

**Issue by mkubarycz** [rancherio/rancher#1063]
When using the rancher UI in chrome, main menus do not respond to mouse clicks.

![image](https://cloud.githubusercontent.com/assets/6887372/8005665/99b3b236-0b5a-11e5-8951-e8d9a1372157.png)

![image](https://cloud.githubusercontent.com/assets/6887372/8005588/c96e24da-0b59-11e5-9c53-081aef21882f.png)

![image](https://cloud.githubusercontent.com/assets/6887372/8005594/d70d4292-0b59-11e5-9215-23e812c25345.png)

It seems like div.dropdown-backdrop is sitting on top of the menu.

![image](https://cloud.githubusercontent.com/assets/6887372/8005628/28bae90a-0b5a-11e5-8cf6-ca3df05d8790.png)

Work-around has been to disable fixed positioning for div.dropdown-backdrop

**Comment by vincent99** [comment]
I'm guessing you have a laptop with a touchscreen?  Bootstrap only adds that `dropdown-backdrop` element `if ('ontouchstart' in document.documentElement)`.  Anyway, z-index fight, I'll increase the menus.

**Comment by vincent99** [comment]
@tfiduccia We should do at least a quick pass on something like an iPad before beta to make sure everything is still usable on touch-only devices.

**Comment by mkubarycz** [comment]
Confirmed on the touch screen.  I am using a surface pro 3.

**Comment by vincent99** [comment]
Ok thanks @mkubarycz .. changed in master and will be in the next build.

**Comment by tfiduccia** [comment]
build from master - June 10th
Checked out menus on touch screen - Verified fixed
