### ISSUE TITLE
Balancer and Service Alias targets are not saving on create

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1065]
v0.23.0-rc1
Steps:
1.  Create and start a service
2.  Create a Service Alias with a target to the service you just created
3.  Start the Service Alias
4.  Create a Service Balancer with a target to the service you just created
5.  Start the balancer

Results: 
The target is not showing or saved.  I have to edit and reassign the target to get it show up.

Expected:
Target should save.

**Comment by alena1108** [comment]
Fixed in master; not sure what release its gonna go to

**Comment by tfiduccia** [comment]
v0.23.0-rc6
Verified fixed
