### ISSUE TITLE
After creating Service with Service Link, the As Name is no longer visible and field is not editable.

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1067]
v0.23.0-rc1
Steps:
1.  Create a service and start it
2.  Create another service and link to the first service, put "TestName1" in the As Name field for link
3.  Create and start service
4.  Edit or Clone Service

Results:
Notice the "As Name" field is blank and not editable.

Expected:
Name should save and be editable

**Comment by vincent99** [comment]
This is half fixed.. you can edit but I don't know the old name you gave the link yet until https://github.com/rancherio/cattle/pull/573 is merge and support is added to the UI.

**Comment by vincent99** [comment]
Can you create a separate issue for not being able to see the existing link name?

**Comment by alena1108** [comment]
@tfiduccia @vincent99 the fix is already in master; but you can file the bug to keep track of the issue.

**Comment by tfiduccia** [comment]
v0.23.0-rc6
Verified fixed
