### ISSUE TITLE
Add/remove of targets when editing an External Service is not working.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1069]
Server version - V0.23.0-rc5

Steps to reproduce the problem:
Create External Service with 2 targets.
Activate service.
Edit Service and add a new target.
The newly added target is not show as part of the External service.

Edit Service and remove an existing target.
Removed  target is still shown as part of the External service.

**Comment by vincent99** [comment]
https://github.com/rancherio/cattle/pull/566

**Comment by will-chan** [comment]
Is this just an UI part now that Alena has merged her PR?

**Comment by sangeethah** [comment]
Server version - V0.23.0-rc6 also has this problem,

**Comment by will-chan** [comment]
ok..reassigning back to Alena.

**Comment by sangeethah** [comment]
With V0.23.0-rc6:

When i edit an external service , i see UI sending the address - "7.6.6.6.7" that was added:

{id: "1s6", type: "externalService", name: "Extserv1", state: "active", accountId: "1a5",…}
accountId: "1a5"
consumedServicesUpdated: 0
created: "2015-06-06T05:20:12Z"
createdTS: 1433568012000
description: "Extserv1"
environmentId: "1e1"
externalIpAddresses: ["10.42.73.225", "10.42.183.226", "7.6.6.6.7"]
headers: null
id: "1s6"
kind: "externalService"
name: "Extserv1"
removeTime: null
removed: null
state: "active"
transitioning: "no"
transitioningMessage: null
transitioningProgress: null
type: "externalService"
uuid: "7e805185-e57e-4396-bf9f-f81e69dcdd58"

But DB does not have this:
ysql> select * from service_expose_map where service_id=6;
+----+------+------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+------------+-------------+------------+---------------+
| id | name | kind             | uuid                                 | description | state  | created             | removed | remove_time | data | service_id | instance_id | account_id | ip_address    |
+----+------+------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+------------+-------------+------------+---------------+
| 12 | NULL | serviceExposeMap | 36850740-34c1-476a-83b0-fc590faddd99 | NULL        | active | 2015-06-06 05:20:17 | NULL    | NULL        | {}   |          6 |        NULL |          5 | 10.42.183.226 |
| 13 | NULL | serviceExposeMap | 2ef0836e-e4f5-4572-a353-7991cd198b44 | NULL        | active | 2015-06-06 05:20:17 | NULL    | NULL        | {}   |          6 |        NULL |          5 | 10.42.73.225  |
+----+------+------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+------------+-------------+------------+---------------+
2 rows in set (0.00 sec)

**Comment by alena1108** [comment]
The fix is not a part of RC6; its a part of master - got merged late at night

**Comment by sangeethah** [comment]
Tested on lastet master build.
Adding/removing of targets when editing an External Service is working as expected.
