### ISSUE TITLE
Switching between scheduling options causes UI failure

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1071]
v0.23.0-rc5

Steps to Reproduce
1. Add Container
2. Go to scheduling tab
3. Add a scheduling a rule for input, but don't add in anything
4. Click on 'Run on a specific host'
5. Click back on 'Automatically pick a host matching scheduling rules'

Result: The + button is no longer visible so unable to add rules and if I try to click on any other link it doesn't load properly unless i refresh the page.

Expected result: The + button to appear. Clicking on other pages would load like normal.

**Comment by vincent99** [comment]
Same as #1091..

**Comment by tfiduccia** [comment]
Build from master - June 9th
Verified fixed
