### ISSUE TITLE
As Name field for Service is not showing in Edit or Clone

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1074]
v0.23.0-rc1
Steps:
1. Create a service and start it
2. Create another service and link to the first service, put "TestName1" in the As Name field for link
3. Create and start service
4. Edit or Clone Service

Results:
Notice the "As Name" field is blank

Expected:
"As Name" should save

**Comment by vincent99** [comment]
This ends up being a much bigger change to switch the way service dependencies are tracked from following the `consumedservices` links to loading the `serviceConsumeMap` resources separately and correlating.  So re-check that all the views show all the consumed services correctly.

Also the box view shows the alias now:
![image](https://cloud.githubusercontent.com/assets/753917/8115808/d421315a-1032-11e5-81f6-32e2642d5cd2.png)

And the graph view on the line:
![image](https://cloud.githubusercontent.com/assets/753917/8115921/b71cbfd8-1033-11e5-9c15-986bd666c7bd.png)

**Comment by vincent99** [comment]
https://github.com/rancherio/ui/pull/205

**Comment by tfiduccia** [comment]
build from master - June 11th
Verified fixed
