### ISSUE TITLE
Editing a service link name , does not result in the service name link being changed.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1076]
Server version - v0.23.0-rc6

Create a service S1.
Create another service S2 and link to service S1 with service name as "abc".
Edit service S2.
Service link name shows as blank which is tracked in #1074.

When u enter another name for this service link , the changed name is not stored in service_expose_map.

**Comment by alena1108** [comment]
@sangeethah thats a valid bug - we should update dns on link rename. Just one correction - the link name is stored in service_consume_map.

**Comment by sangeethah** [comment]
Tested with build from master - jun/08

Create a service S1.
Create another service S2 and link to service S1 with service name as "abc".
Edit service S2.
Enter another name for this service link say "xyz".

Service link name is changed.

From the containers of service S1, DNS resolution for "abc" fails and DNS resolution for "xyz" succeeds and resolves to containers in S2.
