### ISSUE TITLE
Add a initial "splash" page on first login

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#1078]
We need to add a "splash" page so to speak upon first login to describe what the user should do.  It should include a description what Rancher is (Services and Infrastructure).  Perhaps include some buttons to add your first host.

Text to add:

* Adding Your First Host

Before adding your first service or launching a container, you must add at least a single Linux host that supports Docker 1.6+ and be able to reach the Rancher server via HTTP.   Rancher supports adding Linux hosts in the form of a virtual or physical machine from any public cloud providers, privately hosted clouds, or even baremetal servers. [Learn More](http://rancherio.github.io/rancher/docs/infrastructure/hosts/)

[Getting Started Add Host Button]

* Adding your First Service

A service is simply a group of containers created from the same Docker image but extends Docker's "link" concept to leverage Rancher's lightweight distributed DNS service for service discovery.  A service also is also capable of leveraging other Rancher built-in services such as load balancers, health monitoring, upgrade support, and HA. [Learn More](http://rancherio.github.io/rancher/docs/services/projects/adding-services/)

[Getting Started Add Service Button]

**Comment by tfiduccia** [comment]
Build from machine - June 13th
 -- requested he remove extra "also" in Service Get Started text
Verified fixed.
