### ISSUE TITLE
Description example typo: "Alternat" instead of "Alternate

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1088]
v0.23.0-rc6

Typo in the example text in the description textbox.

![Uploading Screen Shot 2015-06-08 at 11.09.32 AM.png…]()

**Comment by vincent99** [comment]
The screenshot didn't upload, but this was in "Add service alias".

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
