### ISSUE TITLE
Support proxy for 9345/9346 compute node traffic

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#109]
Users have asked for a proxy to route traffic from public internet to compute nodes which may be on a private network.

The traffic on 9345/9346 is for the host api and the console agent.

**Comment by cjellick** [comment]
Random discussion notes on the subject:
vincent: I'm assuming there's a Websocket proxy library for Java somewhere so it would be a proxy in the standard :8080 API?

craig: ...would keep things simple, though a java app server might not be the "best" tool for proxying like that

vincent: I guess a separate proxy on :9345 would work too, just trying to minimize the number of ports we have to ask people to open (and at big companies there's a good chance $random_port will be blocked). It could probably be done with url-matching magic and nginx/haproxy in front of java

**Comment by vincent99** [comment]
This should support (or require) SSL as well

**Comment by vincent99** [comment]
@cjellick @ibuildthecloud Can we close this now with #145 ? SSL will need to be added in general.
