### ISSUE TITLE
The + button in Scheduling Rules disappears and gets stuck

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1091]
v0.23.0-rc6

Similar to https://github.com/rancherio/rancher/issues/1071, but this is at an individual container level.

Steps to Reproduce
1. Click to Add Container
2. Click on the + to add a rule to the "Automatically pick a host matching scheduling rules". 
3. Click on "Run on a specific host" option.
4. Click back on the "Automatically pick a host matching scheduling rules". 

Result: The + button is no longer visible and if I click around the site, it's stuck.

**Comment by vincent99** [comment]
Fixed.. it's caused by the row you add on step 2 being empty, then failing to parse that when coming back on step 4.

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
