### ISSUE TITLE
When a service link is removed, the service is removed from the graph instead of the link

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#1092]
You need 2 browser windows to see this...

  - Open up a project in 'box' view in one window
  - Open up the same project in 'graph' view in another
  - Add service 'a'
  - Add service 'b' linked to 'a'
  - Edit service 'b' and remove the link
  - 'b' disappears from the graph instead of the line between 'b' and 'a'.

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
