### ISSUE TITLE
When host is stuck in "deactivating" state , there is no option provided to delete the host.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1098]
Server version - Build from master - Jun/08

Steps to reproduce the problem:

Added a Digital Ocean machine.
Created few containers on this host.
Stopped the Digital Ocean VM.

Host continues to show that it is in Active state.
Tried to deactivate the host , which results in host being stuck in "deactivating" state.
 
There is no option provided to delete this host.

Earlier , we were provided with an option to delete the host , even when the host was in deactivating state - Refer to #701.

We should be allowed to delete the host , even when it is stuck in "Deacticating" state ?

**Comment by sangeethah** [comment]
![screen shot 2015-06-08 at 5 01 15 pm](https://cloud.githubusercontent.com/assets/4266958/8047990/10c3352e-0e01-11e5-9fa8-df7d328a003f.png)

**Comment by sangeethah** [comment]
I am able to use the API to delete the host that is still stuck in "Deactivating" state.
Marking this as UI issue .

**Comment by vincent99** [comment]
Not a bug in the UI.  You can use it from the API because it always shows a delete button, and the intent of the API is that DELETE always works.  And it happens to work in this case.  But the action isn't showing in the UI because the API does not say the `remove` action is available from `deactivating`.  This may change with #384.

**Comment by vincent99** [comment]
@ibuildthecloud do you want to make the `remove` action show up on the transition states, or should I just ignore the API action and make delete always available?

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc2

Added a Digital Ocean machine.
Created few containers on this host.
Stopped the Digital Ocean VM.

Host now gets into "reconnecting" state.
When in "Reconnecting" state , I see an option to "Deactivate" the machined.
I am able to deactivate the  machine at which point I see the "Delete" option presented.

**Comment by cusspvz** [comment]
This happened with me on `1.0.0` version. 3 Hosts were stuck on "deactivating" state.
