### ISSUE TITLE
Question: Service Alias / DNS

### ISSUE THREAD

**Issue by willowandcreek** [rancherio/rancher#1104]
Hi,

Got a quick question. When I add a service alias am I supposed to be able to ping it from the containers? I added two services called 'service1' and 'service2'. Then I added an alias to service1 called 'alias1'. From service2's shell I am able to ping service1 and from service1's shell I am able to ping service2. However I am not able to ping alias1 from either of the service shells.

**Comment by willowandcreek** [comment]
After the feedback on https://github.com/rancherio/rancher/issues/1105 I noted that I am able to ping containers if they are linked. However using the alias I am not able to ping when the containers aren't linked.

**Comment by vincent99** [comment]
DNS entries are only put in for services (and service aliases) that are linked.  This helps ensure that you are correctly declaring the dependencies you have, and will allow us to restrict network access to just the things that declared a need for it in the future.

**Comment by willowandcreek** [comment]
Ah gotcha. Thanks for the clarification. Appreciate it.
