### ISSUE TITLE
Question: Service Links

### ISSUE THREAD

**Issue by willowandcreek** [rancherio/rancher#1105]
Hi,

I am not able to get service linking to work for some reason. These are the steps I follow:

1. Create a service called 'api1' which exposes port 8080 via Dockerfile and mapped to port 7575 on Rancher's UI
2. Start api1 service
3. Create a service called 'web1' which has a service link to 'api1' named 'api'
4. Start web1 service

In web1's stdout I have dumped all environment variables and I do not see api1's linking information. When I try via regular 'docker run' on my machine I am able to see the links. Am I doing something wrong when setting it up on Rancher? I am using v0.23.0-rc6

**Comment by sangeethah** [comment]
You should be able to reach containers in service - 'api1'  from all containers in service -web1 using the service link's name  - "api".
From containers in web1 service , you should be able to access api:8080

Note - There is no need to map exposed ports for service linking to work.

**Comment by alena1108** [comment]
@willowandcreek service links in Rancher get resolved using Rancher DNS server; not through the environment variables. The way DNS works, is every entry of api1 service becomes a DNS A record for every instance of the web service, so from your web instances "api1" name should get resolved to api1 service's instances

**Comment by willowandcreek** [comment]
Thanks for the clarifications :smile: I am indeed able to ping linked containers.
