### ISSUE TITLE
Update DockerMachine to 0.3.0

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#1106]
Docker Machine plans to ship 0.3.0 on 6/16.

https://github.com/docker/machine/releases/

**Comment by wlan0** [comment]
tested, positive cases

1. Adding hosts 
    1.1. digitalocean - OK
    1.2. rackspace - OK
    1.3. packet - OK
2. deleting hosts
    2.1. digitalocean - OK
    2.2. rackspace - OK
    2.3. packet - OK

failure cases

1. Set wrong API key on a digitalocean host - got error status - "exit status 1" (is this expected?)

**Comment by sangeethah** [comment]
Tested with server version - V0.23.0-rc2.

root@97c16797b4be:/# docker-machine -v
docker-machine version 0.3.0-dev (ccb7f0a)
root@97c16797b4be:/# go-machine-service -v
go-machine-service	 gitcommit=480875d
root@97c16797b4be:/# 

Existing set of validation test cases for digital Ocean machine and amazon ec2 machines work fine.
