### ISSUE TITLE
[Install] [Agent] Warning when launching Rancher agents. 

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#111]
I get an error very similar to Issue 33 when starting Rancher Agent containers I get the following error. Nothing seems to fail but I wanted to highlight the error. The message is slightly different from 33 so I created a new issue. 

    FATA[0082] Error response from daemon: Cannot destroy container 9667b5eaa5e4f0bfcaa649eaf8734c6a46faff9208f4e257cc13b1db215b7ba1: Driver devicemapper failed to remove root filesystem 9667b5eaa5e4f0bfcaa649eaf8734c6a46faff9208f4e257cc13b1db215b7ba1: Device is Busy

My Docker Version: 

        docker --version
        Docker version 1.5.0, build a8a31ef

My Docker Info:

	docker info
	Containers: 3
	Images: 45
	Storage Driver: devicemapper
	 Pool Name: docker-202:1-263382-pool
	 Pool Blocksize: 65.54 kB
	 Backing Filesystem: extfs
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 1.327 GB
	 Data Space Total: 107.4 GB
	 Metadata Space Used: 2.855 MB
	 Metadata Space Total: 2.147 GB
	 Udev Sync Supported: false
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.82-git (2013-10-04)
	Execution Driver: native-0.2
	Kernel Version: 3.14.27-25.47.amzn1.x86_64
	Operating System: Amazon Linux AMI 2014.09
	CPUs: 1
	Total Memory: 996.3 MiB
	Name: ip-172-30-0-129
	ID: JNCJ:4X3R:4LZT:KVTZ:ID4E:ZQUN:BQ66:C2KF:LLWF:WTCV:EA7Z:6PRS

**Comment by feliksik** [comment]
I have the same issue, but using the aufs storage driver. Note it happens both on docker 1.4.1 and 1.5.

```
$ IFACE=eth0
$ AGENT_IP=$(ifconfig $IFACE | grep "inet addr" | tr " " "\n"| grep addr| cut -d: -f2)
$ SERVER_IP=10.1.3.4
$ docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e CATTLE_AGENT_IP=$AGENT_IP rancher/agent http://$SERVER_IP:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU

Rancher State
e8a5c2ec847e89038621bf27bc2d259f4b145f7698482cffa95d9123e56cf265
FATA[0001] Error response from daemon: Cannot destroy container a7caf8381d9e3b7c868355ea74fa032772dea4ef0721cbd19d6713e768728715: Driver aufs failed to remove root filesystem a7caf8381d9e3b7c868355ea74fa032772dea4ef0721cbd19d6713e768728715: rename /var/lib/docker/aufs/mnt/a7caf8381d9e3b7c868355ea74fa032772dea4ef0721cbd19d6713e768728715 /var/lib/docker/aufs/mnt/a7caf8381d9e3b7c868355ea74fa032772dea4ef0721cbd19d6713e768728715-removing: device or resource busy 
FATA[0003] Error response from daemon: Cannot destroy container f59c0974786a157d47d9c5e8afd90fb107cc9296e7b72428528ecca53f87736a: Driver aufs failed to remove root filesystem f59c0974786a157d47d9c5e8afd90fb107cc9296e7b72428528ecca53f87736a: rename /var/lib/docker/aufs/mnt/f59c0974786a157d47d9c5e8afd90fb107cc9296e7b72428528ecca53f87736a /var/lib/docker/aufs/mnt/f59c0974786a157d47d9c5e8afd90fb107cc9296e7b72428528ecca53f87736a-removing: device or resource busy 

```


``` $ docker info
Containers: 4
Images: 75
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 103
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 7.798 GiB
Name: vm-client-esri-001
ID: VQLO:S4ZG:6XUX:ZN4Q:ZHDV:GPTN:YDSB:YFJ4:Z4ZP:YUOZ:DFUS:LR7C
```


```
$ docker info
Containers: 2
Images: 35
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
Execution Driver: native-0.2
Kernel Version: 3.13.0-35-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 7.798 GiB
Name: vm-client-esri-003
ID: Y3AA:I4ME:XOJD:C3ZD:KPYW:IZAI:2R2Q:JZ5H:5DL3:MKAP:ECRH:WNQ7
WARNING: No swap limit support

```

It is somehow a docker issues that has been mentioned and supposedly solved many times before, but I think Rancher doing the dance with the different Agent containers triggers this in particular. Everything seems to work fine, though. It's just a bit confusing.

**Comment by deniseschannon** [comment]
By using the command in the UI (per #267), these warnings are eliminated.
