### ISSUE TITLE
"-" is allowed in service name which causes the docker-compose to error out when using the generated docker-compose.yml file.  

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1113]
Server version - Build from master - jun/09

Create a service with name that has "-" like "test-1234".
Use the generated docker-compose.yml with docker-compose to launch the container.
Following error message is seen:

Invalid service name "test-1234" - only [a-zA-Z0-9] are allowed

**Comment by ibuildthecloud** [comment]
That seems like a `docker-compose` bug if that is the case.  Service names should be `[a-zA-Z0-9][a-zA-Z0-9_.-]`  That is what docker itself allows

**Comment by alena1108** [comment]
There is already a bug in docker-compose for that:

https://github.com/docker/compose/issues/1519
