### ISSUE TITLE
Containers that are part of services with anti-affinity scheduling could get destroyed when host labels get added.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1114]
Server version - Build from master - jun/09

Steps to reproduce the problem:
Had 3 hosts with no label.
Created a service with "Always run one instance of this container on every host" and scheduling set to host must not have host label set to  test1=value1.
containers get created on all 3 hosts.

Add host label "test1=value1" to one of the host.
When the label gets added , we see the container on this host being destroyed.

Should there any kind of warning/confirmation that needs to be presented to the user , before containers get removed ?

**Comment by sonchang** [comment]
Just noting here that this only happens with the global service

**Comment by sonchang** [comment]
I can change it so that those containers aren't removed, but I think that may be a worse behavior.
I think we'll need to figure out whether we want to implement some warning/confirmation mechanism or not or whether the global feature will just be superseded by the trigger mechanism?

**Comment by sonchang** [comment]
Related issue #1006

**Comment by sangeethah** [comment]
Tested with v0.25.0-rc1:

Had 1 host with  label= "test2=value2" and other 2 hosts - h1 and h2 had label="test1=value1" .
Created a service with "Always run one instance of this container on every host" and scheduling set to host must not have host label set to test2=value2.
Containers get created on 2 hosts - h1 and h2.

Add host label "test2=value2" to both host h1 and h2.
When the label gets added , containers in h1 and h2 do not get destroyed as expected.
