### ISSUE TITLE
Error when creating a service from cloning a service and changing the "value" field in scheduling .

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1116]
Server Version - build from master - jun/09

I had a service with "Always run one instance of this container on every host" set and scheduling set to host must not have host label set to test1=value1.
Clone this service .
Changed the name of the service and in scheduling changed "value" filed from value1 to value2 .
Click on "Create".

Error message - "Validation failed: secondaryLaunchConfigs" seen.
![screen shot 2015-06-09 at 11 40 33 am](https://cloud.githubusercontent.com/assets/4266958/8066629/86e83906-0e9d-11e5-8630-4dacfe5d9187.png)

**Comment by vincent99** [comment]
Dupe #1136.
