### ISSUE TITLE
Set as my login Environment doesn't work after 1st change

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1117]
Steps:
1.  Create a Environment called Environment1
2.  In Manage Environments, set Environment1 as your Login Environment
3.  Logout and log back in (you will be sent to Environment1)
4.  Go back to Manage Environments and set Default as your Login Environment
5.  Logout and log back in

Results:
You are still sent to Environment1 instead of Default.  If you go to Manage Environments, Environment1 is set as your Login Environment.

Expected:
Default should be your login environment.

**Comment by vincent99** [comment]
@hibooboo2 This is the uniqueness constraint thing on userPrefs..  Please send back to @tfiduccia when it's fixed in master.

```javascript
{
  actions: {},
  code: "NotUnique",
  detail: null,
  fieldName: "name",
  id: "8753d5b1-73c2-4b28-bd7d-6cac68898401",
  links: {},
  message: null,
  status: 422,
  type: "error"
}
```

**Comment by hibooboo2** [comment]
Currently gdapi unique constraint doesn't exclude it self when doing the check for uniqueness. I have submitted a pr to gdapi that fixes this. And subsequently i will have to submit a pr to cattle to update this. I will ping @tfiduccia when it hits master.

**Comment by hibooboo2** [comment]
rancherio/cattle#609 Fixes this.

**Comment by tfiduccia** [comment]
build from master - June 12th
Verified fixed
