### ISSUE TITLE
rancher-compose.yml/docker-compose.yml should include information about NetworkMode(managed/bridge)

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1119]
Server version - Build from master jun/08

Create a service in managed network.
rancher-compose.yml/docker-compose.yml does not include any information about managed network.

When i use  docker-compose.yml to deploy the service , containers get created with "NetworkMode": "bridge" .
Should we expect the containers to be deployed in our managed network?

**Comment by will-chan** [comment]
* container mode will be supported with "sidekicks" are available.
* bridge and host mode can be supported when we implement #1101

**Comment by alena1108** [comment]
No, we should never expect that. Managed network translates to nothing in docker-compose.yml, and when docker-compose up is called, it should deploy containers in default docker mode.
