### ISSUE TITLE
Host info inconsistency

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#112]
![screen shot 2015-02-22 at 1 01 53 pm](https://cloud.githubusercontent.com/assets/204682/6319668/19b011dc-ba93-11e4-8ddc-edddd63a6743.png)

The host info sections on my Rancher server are inconsistent. In the agent on the left he host Info IP matches my eth0 interface.
	ifconfig
	docker0   Link encap:Ethernet  HWaddr 56:84:7A:FE:97:99
	          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
	          ....

	eth0      Link encap:Ethernet  HWaddr 0E:66:02:2F:C8:BF
	          inet addr:172.30.0.128  Bcast:172.30.0.255  Mask:255.255.255.0
	          inet6 addr: fe80::c66:2ff:fe2f:c8bf/64 Scope:Link
  
However on the agent on the right it matches my docker0 interface:

	ifconfig
	docker0   Link encap:Ethernet  HWaddr 56:84:7A:FE:97:99
	          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
	          ....

	eth0      Link encap:Ethernet  HWaddr 0E:AE:72:4C:2C:5A
	          inet addr:172.30.0.129  Bcast:172.30.0.255  Mask:255.255.255.0
	          inet6 addr: fe80::cae:72ff:fe4c:2c5a/64 Scope:Link

How is the Host IP selected and should it list the docker0 interface or the host internet interface?

**Comment by ibuildthecloud** [comment]
This is most likely related to your problem with https://github.com/rancherio/rancher/issues/110 too.  When a host registers with the server we try to be smart and detect the IP of the host.  Unfortunately we just aren't smart enough.  The way we do the detection is by looking at the client IP of the TCP connection.  What this means is the specific TCP route taken to get to the server impacts the registered IP.  So for the server on the right it appears the TCP connection was local, while the server on the left the TCP traffic was private to your VPC.

In the end, the best thing to do is to try forcing the host IP.  You don't need to delete the hosts, just rerun the agent registration docker command and add `-e CATTLE_AGENT_IP=<YOURIP>` to the docker run arguments.  It might take 5 minutes and a couple refreshes, but you should see the UI update with the correct IP.

**Comment by usmanismail** [comment]
That seems to have fixed it. I had one agent running on the same node as the Rancher Server. This agent used the docker0 interface to communicate with the Rancher server instead of the actual network interface.
