### ISSUE TITLE
service link name is not set in docker-compose.yml

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1120]
Server version - Build from master - jun/09

Steps to reproduce the problem:
Create service2.
Create service1 and link it to service 2 with name "linkme"

Service name is not being set in docker-compose.yml.

```
service1:
  ports:
  - 4444:22/tcp
  tty: true
  image: sangeetha/testclient
  links:
  - service2
  stdin_open: true
service2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
```

**Comment by sangeethah** [comment]
Tested with build from master - jun/10

I see the service link name now in the docker-compose.xml.
But when i use this docker-compose.xml to deploy comtainers , the service link name is not resolving to the linked container. 

For the following docker-compose.xml. , I am not able to access the web1 service from client1 using "hello" .But I am able to do it using "web1".

client1:
  restart: 'no'
  tty: true
  image: sangeetha/testclient
  links:
    web1: hello
  stdin_open: true
web1:
  restart: 'no'
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
web2:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true

```
declare -x SANGEETHAHARIHARAN1_WEB1_1_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x SANGEETHAHARIHARAN1_WEB1_1_NAME="/sangeethahariharan1_client1_1/sangeethahariharan1_web1_1"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT="tcp://172.17.0.11:80"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_443_TCP="tcp://172.17.0.11:443"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_443_TCP_ADDR="172.17.0.11"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_443_TCP_PORT="443"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_443_TCP_PROTO="tcp"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_80_TCP="tcp://172.17.0.11:80"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_80_TCP_ADDR="172.17.0.11"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_80_TCP_PORT="80"
declare -x SANGEETHAHARIHARAN1_WEB1_1_PORT_80_TCP_PROTO="tcp"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x WEB1_1_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x WEB1_1_NAME="/sangeethahariharan1_client1_1/web1_1"
declare -x WEB1_1_PORT="tcp://172.17.0.11:80"
declare -x WEB1_1_PORT_443_TCP="tcp://172.17.0.11:443"
declare -x WEB1_1_PORT_443_TCP_ADDR="172.17.0.11"
declare -x WEB1_1_PORT_443_TCP_PORT="443"
declare -x WEB1_1_PORT_443_TCP_PROTO="tcp"
declare -x WEB1_1_PORT_80_TCP="tcp://172.17.0.11:80"
declare -x WEB1_1_PORT_80_TCP_ADDR="172.17.0.11"
declare -x WEB1_1_PORT_80_TCP_PORT="80"
declare -x WEB1_1_PORT_80_TCP_PROTO="tcp"
declare -x WEB1_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x WEB1_NAME="/sangeethahariharan1_client1_1/web1"
declare -x WEB1_PORT="tcp://172.17.0.11:80"
declare -x WEB1_PORT_443_TCP="tcp://172.17.0.11:443"
declare -x WEB1_PORT_443_TCP_ADDR="172.17.0.11"
declare -x WEB1_PORT_443_TCP_PORT="443"
declare -x WEB1_PORT_443_TCP_PROTO="tcp"
declare -x WEB1_PORT_80_TCP="tcp://172.17.0.11:80"
declare -x WEB1_PORT_80_TCP_ADDR="172.17.0.11"
declare -x WEB1_PORT_80_TCP_PORT="80"
declare -x WEB1_PORT_80_TCP_PROTO="tcp"


root@592e3c1b1200:/# cat /etc/hosts
172.17.0.20	592e3c1b1200
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.18	sangeethahariharan1_web1_1
172.17.0.18	web1
172.17.0.18	web1_1
root@592e3c1b1200:/# 

```

**Comment by alena1108** [comment]
Its most likely a bug in the docker-compose. We follow the format defined in their official doc:

>links
>Link to containers in another service. Either specify both the service name and the link alias >(SERVICE:ALIAS), or just the service name (which will also be used for the alias).

>links:
 >- db
 >- db:database
 >- redis

**Comment by alena1108** [comment]
It actually a bug in our code. The links should have been exported as list of stings, not array. Fixing it.

**Comment by sangeethah** [comment]
Tested with build from master - jun 18

Following is the rancher-compose.yml file for service with service links:
```
testw1:
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
testc:
  restart: 'no'
  tty: true
  image: sangeetha/testclient
  links:
  - testw1:testlinkme
  stdin_open: true
```
root@f9c6b236edbb:/# cat /etc/hosts
172.17.0.5	f9c6b236edbb
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	sangeethahariharan1_testw1_1 efe48ac441d3
172.17.0.4	testlinkme efe48ac441d3 sangeethahariharan1_testw1_1
172.17.0.4	testw1_1 efe48ac441d3 sangeethahariharan1_testw1_1
root@f9c6b236edbb:/# 

From containers in  testc , I am able to access testw1 using both testlinkme and testw1_1
