### ISSUE TITLE
Can't edit container that contains port information

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1123]
build from master - June 9th
Steps:
1.  Create a container (alone or through service) that has Port Map information
2.  Start container
3.  Edit container
4.  Click on Save

Results:
TypeError: Cannot read property '__ember_meta__' of undefined

Results:
No error

**Comment by flaccid** [comment]
This is also happening for me. When I look at the ajax PUT it doesn't seem to contain the change of the port mapping I wanted to save.

**Comment by vincent99** [comment]
There's either more to this or I fixed it already...  Can you check again @tfiduccia

**Comment by tfiduccia** [comment]
build from master - June 11th (morning)
Verified fixed
