### ISSUE TITLE
When port mapping a TCP and UDP are bound to the same port, it ignores the first protocol of the ports.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1124]
v0.23.0-rc6

Debugging #1100 and found that when you port map for TCP and UDP on the same port, it ignores the UDP port.

Steps to Reproduce:
1. Create a container with the following ports:
5665 5665/tcp
5665 5665/udp
2. Only the TCP rule is programmed in the iptables of the host. There is no rule for UDP. 

Note: When I view the container details, the UDP rule is not visible so it doesn't look like it even got saved, but when I edit the container, I can see both port mappings.

If I put UDP first and TCP second, then the UDP rule is programmed and the TCP is ignored.

**Comment by joshuacox** [comment]
closed #1100 as I can do without tcp and udp in that case.   But in there I mention "DNS uses udp primarily, except in the case of zone transfers in which you surely want tcp on, you don't just fire and forget a zone transfer". And certainly on my list of things to do is spin up a DNS cluster on rancher.  Let me know if I can supply any more info on my end.

**Comment by vincent99** [comment]
@will-chan I'd probably keep this in beta;  DNS is just one example you might want TCP + UDP on the same port for.  And any somewhat large DNS response (4kb) requires TCP, not just zone transfers.

**Comment by ibuildthecloud** [comment]
Oh yeah, this is just stupid dumb logic.  The first port for each private port wins and no others get configured.  So doing 1234->80/tcp and 2345->80/tcp results in just 1234->80/tcp.  Man, too much crazy late night drunken programming apparently.  This is a simple fix.

**Comment by deniseschannon** [comment]
verified fix in v0.24.0-rc2
