### ISSUE TITLE
Removing member causes a Internal Server Error (500) for member

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1125]
build from master - June 9th
Steps:
1.  As Admin, create 1 environments (call then Env1 & Env2) and add rancherdev as a member
2.  Login as rancherdev in separate browser and go to Env1, Services page
3.  As Admin, edit Env1 and remove rancherdev as member
4.  As rancherdev, click on Infrastructure

Results:  Error page with Internal Server Error (500)

Expected:  No error and should take them to Manage Environment page or Env2 services page.

**Comment by will-chan** [comment]
I assume the member isn't actually removed?

**Comment by hibooboo2** [comment]
This is resolved with rancherio/cattle#599

**Comment by hibooboo2** [comment]
This is now on master.

**Comment by tfiduccia** [comment]
build from master - June 10th (afternoon)
Verified fixed
