### ISSUE TITLE
How to modify the environment vars of container with Rancher?

### ISSUE THREAD

**Issue by cnzg** [rancherio/rancher#1132]
I added a mysql container with password=A, 
but now i want to modify its password to B.

So, whether Rancher provide function to modify vars of container? Maybe this is a request:)

**Comment by vincent99** [comment]
Rancher does not have that because Docker doesn't.  You can clone a container from the UI though, which is like adding  a new one but with all the settings defaulted to the same as they were in the original container.

**Comment by cloudnautique** [comment]
Is the purpose of the change so that linked containers get the updated password? 

Following the conventions of Docker, you can't change the environment variables on a container once it is created. Once it is running there is no guarantee the process would re-read it.

**Comment by cnzg** [comment]
@cloudnautique Yes, i think Rancher can be used as a PaaS platform, user donot care the database is running on a container or vm. Actually this is not a issue, just a request. Otherwise we need develop to invoke Rancher/Docker API which can recreate a database container for this scenario.

**Comment by deniseschannon** [comment]
Since Docker doesn't allow changing the env variables, we won't be implementing the ability.

**Comment by konsumer** [comment]
Docker version 1.12.3 has these for `run`:

```
-e, --env value                   Set environment variables (default [])
      --env-file value              Read in a file of environment variables (default [])
```

It would be neat if there was something in the Rancher UI.

**Comment by vincent99** [comment]
@konsumer there is UI to *define* environment variables (in the "Command" tab of add container/service).  This issue was about *modifying* their values on an existing running container.

**Comment by konsumer** [comment]
Aha! That's rad. Thanks!

**Comment by wentfar** [comment]
So，the conclusion is，we still can't change Env Variables since the pod is created?

**Comment by wentfar** [comment]
> @konsumer there is UI to _define_ environment variables (in the "Command" tab of add container/service). This issue was about _modifying_ their values on an existing running container.

So，the conclusion is，we still can't change Env Variables since the pod is created?
