### ISSUE TITLE
Running Containers show up in UI with state as "?" because of health_state in "initializing" state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1134]
Server version - build from master 06/10

Start  a container.
when the container gets deployed, it shows up with state as "?" in UI because of health_state in "initializing" state.

select state,health_state , name from instance;
| running | initializing | test234                              |
| running | initializing | hello123                             |
+---------+--------------+--------------------------------------+
![screen shot 2015-06-10 at 10 39 48 am](https://cloud.githubusercontent.com/assets/4266958/8089492/0eaaa774-0f5d-11e5-84f3-5967d72ddf91.png)

**Comment by vincent99** [comment]
UI in master will now show initializing as the bell icon and degraded, and null as normal/active in rancherio/ui#199

**Comment by alena1108** [comment]
Java part is fixed - instances with no healtcheck configured, will get null health state

**Comment by ibuildthecloud** [comment]
Why can't they just be healthy and not null

**Comment by ibuildthecloud** [comment]
On create set the state to healthy, as it was before, and on start for containers with health checks set the state to initializing.

**Comment by vincent99** [comment]
Why have a health state that's lying for containers with no check?

**Comment by tfiduccia** [comment]
Verified that containers/services with no health check info are now showing as running instead of initializing.  Sangeetha, are there other scenarios you would like to test?

**Comment by sangeethah** [comment]
Tested with server version - v0.24.0-rc1

When health checks are not enabled for services , the container's  health_state is now set to "NULL".
UI shows "running" state as expected.

mysql> select name,state,health_state from instance; 
+---------------+---------+--------------+
| name          | state   | health_state |
+---------------+---------+--------------+
| prj1_serv1_1  | running | NULL         |
| prj1_serv1_2  | running | NULL         |
| Network Agent | running | NULL         |
| Network Agent | running | NULL         |
+---------------+---------+--------------+
4 rows in set (0.00 sec)

mysql>
