### ISSUE TITLE
Listeners are not showing up in the LB Config details page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1135]
build from master - June 10th
Steps:
1.  Create a Load Balancer
2.  Click on LB name to get to details page
3.  Click on the Config tab

Results:
Nothing in Listeners ()

Expected:
Listening Port information should be in there

**Comment by vincent99** [comment]
(this broke when I made a change to show only un-removed ones in lbconfigs)

**Comment by tfiduccia** [comment]
build from master
Verified fixed
