### ISSUE TITLE
Cloning  a service that has health check enabled and creating it  fails with "Validation failed: secondaryLaunchConfigs" error.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1136]
Build from master - jun/10

Steps to reproduce the problem:
Create a service with scale 3 with health check enabled ( by providing port).
Activate service.
Clone this service , change the name of the service and clck on "create".
I get this error message - "Validation failed: secondaryLaunchConfigs" error.

I noticed that port field on the " health check" panel is missing.

![screen shot 2015-06-10 at 11 17 00 am](https://cloud.githubusercontent.com/assets/4266958/8090432/c8bf7bee-0f62-11e5-803e-7817a2b0919b.png)

**Comment by vincent99** [comment]
Healthcheck is irrelevant.. secondaryLaunchConfigs is just null in the existing service so that is cloned, but the field isn't allowed to be null in the schema so the API rejects it on create.

**Comment by tfiduccia** [comment]
Build from master - June 11th (morning)
Verified fixed - Can clone Service and Container with Health Check info in it.  Entered separate bug for Port field missing in cloned container.
