### ISSUE TITLE
Can't delete Balancer Config Listeners

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1140]
Build from Master - June 10th
Steps:
1.  Go to Balancer Configs page
2.  Click on Add Config
3.  Create a Balancer with 2 Listening Ports
4.  Click Create
5.  Edit Balancer and remove one of the Listening Ports

Results:
Listening port does not delete

Expected:
Listening port should delete

**Comment by vincent99** [comment]
Works for me™

**Comment by tfiduccia** [comment]
build from master
Verified fixed
