### ISSUE TITLE
Clean install host IP is wrong

### ISSUE THREAD

**Issue by 5an1ty** [rancherio/rancher#1152]
I just installed the rancher server and a host on the same machine to test and it pops up as expected under hosts, only it's IP address is incorrect. As IP it shows:

 172.17.42.1 

That's the IP address of the docker0 network interface. Is this a bug or a misconfiguration on my part?

After some googling I tried adding:
-e CATTLE_AGENT_IP=MYSERVERIP

and when I use docker logs of the created host, it's stuck at:

INFO: Running Agent Registration Process, CATTLE_URL=http://MYSERVERIP:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 3
INFO: docker info: Images: 95
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 101
WARNING: No swap limit support
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.16.0-38-generic
INFO: docker info: Operating System: elementary OS Freya
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 15.61 GiB
INFO: docker info: Name: insanity
INFO: docker info: ID: TGNR:ITTU:DK2P:4XAJ:JXE2:I7ID:WSIK:66JA:XDJJ:3GXQ:6WV2:6YP6
INFO: Attempting to connect to: http://MYSERVERIP:8080/v1
ERROR: http://MYSERVERIP/v1 is not accessible

**Comment by deniseschannon** [comment]
Instead of putting in "MYSERVERIP", you need to put in the actual IP of the Rancher server (i.e. 172.0.0.1) when you register the host.

**Comment by 5an1ty** [comment]
I just did that as an example, I used my real IP everywhere I mention MYSERVERIP.

**Comment by deniseschannon** [comment]
If you run docker agent command without the "-e CATTLE_AGENT_IP=MYSERVERIP" it won't work if you stop the agent and restart it with the "-e". 

Did you try to run the agent command as a new container?

**Comment by 5an1ty** [comment]
Yes I didn't try stopping and starting always recreate form scratch for example:
sudo docker run -d --privileged -e CATTLE_AGENT_IP=MYSERVERIP -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://MYSERVERIP:8080/v1/scripts/F83B7FB3F682E0D75AEB:1434049200000:fAR3lTg4BOl7OSHH5LH3XSWl8s0

I tried using curl MYSERVERIP:8080 from the agent container and it results in connection timed out while pinging MYSERVERIP works just fine.

Strange...

**Comment by 5an1ty** [comment]
ok my iptables got seriously messed up in:
iptables -T nat -L

flushed all CATTLE chains and it's working as expected :+1:

**Comment by corn13read** [comment]
that's what happens when you chain up them cattle

**Comment by 5an1ty** [comment]
@corn13read hahaha

**Comment by deniseschannon** [comment]
@5an1ty glad you got it's working. :)
