### ISSUE TITLE
UI - Linked services in a service div are not wrapped

### ISSUE THREAD

**Issue by stephenlawrence** [rancherio/rancher#1166]
If I add a number of linked services to one of my services and view that in the services page, the linked services all appear on a single line instead of wrapping properly. 

![screen shot 2015-06-11 at 1 44 12 pm](https://cloud.githubusercontent.com/assets/1699704/8117848/38948382-1040-11e5-98ca-704d2be7f835.png)

**Comment by stephenlawrence** [comment]
Pull request:
https://github.com/rancherio/ui/pull/204

**Comment by vincent99** [comment]
Changed in rancherio/ui#207

**Comment by tfiduccia** [comment]
Failed - still not wrapping for me

**Comment by vincent99** [comment]
now with more break-word, since dns labels don't have much breakable in them..

**Comment by tfiduccia** [comment]
v0.24.0-rc4
Verified fixed
