### ISSUE TITLE
Service Reconcile should be triggered by service container stop/destroy

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1181]
Server version - V0.24.0-rc1

Steps to reproduce the problem:
Create a service with health check enabled and scale 4.

Scenario 1:
Stop one of the containers.
Health check should detect this container as being unhealthy and start this container to maintain the scale of the service.

Scenario 2:
Delete one of the containers.
Health check should detect the deleted container and start a new container to maintain the scale of the service.

**Comment by alena1108** [comment]
Its not the heatlcheck responsibility to trigger service restart in this case. The correct way of saying it would be - service instance.stop/start should trigger service reconcile (the scale should match at the end)

**Comment by sangeethah** [comment]
Tested with build from master jun/12.

Create a service without health check on with some scale like 5.
Stop one of the instances.
After 20-30 secs , stopped instance is started automatically.
Destroy one of the instances.
After 20-30 secs , we see a new instance being spawned for the service.

Also tested scenarios were Multiple instances were stopped and destroyed and made sure that scale adjusted automatically.

Same set of test cases were also done for services with health check turned on.
