### ISSUE TITLE
How can I remove scheduled containers?

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#1186]
If I setup a schedule to run a container on all hosts with label=X, how do I remove this schedule such that at a later point when I launch a host with label=X it does not run the scheduled container?

**Comment by vincent99** [comment]
Labels cannot be changed on a service...  But you can clone the service, change the labels, save that, and delete the old service.

**Comment by usmanismail** [comment]
I meant outside a service. When launching a container I can use the "Automatically pick a host matching scheduling rules"... Option. This will run a container on the hosts as they come up. How do I modify or edit these rules? If there are no hosts then there will be no container running for me to modify labels on.

**Comment by usmanismail** [comment]
I misunderstood the intent of the scheduling feature making this issue invalid

**Comment by deniseschannon** [comment]
Just to clarify for you and others, if using the "Always run one instance of this container on every host" it means that any hosts that match the scheduling rules will have the service added or even removed (if you decided to remove label=X on that host).

**Comment by deniseschannon** [comment]
Edit: I've just found out that it only triggers additional containers when adding a label=X, but we will not do any removing of containers. So if you removed the label=X, the container will still remain on the host.
