### ISSUE TITLE
masterless design possible?

### ISSUE THREAD

**Issue by corn13read** [rancherio/rancher#119]
I'm worried about master failure...

What about integrating something like [registrator/consul](https://github.com/gliderlabs/registrator) where you don't need a master at all? Or are there plans for future for this?

**Comment by sheng-liang** [comment]
Rancher does not require a master. Everything used to run Rancher can be clustered and scaled horizontally.

**Comment by corn13read** [comment]
So... What about the "management server"? Are there ways to have two or three of these? Sorry for the confusion.

**Comment by sheng-liang** [comment]
Yes. The management server is logically a single unit, and for simple developer deployments it is usually launched as a single container. But for production deployments you can have a multi-container/multi-host clustered deployment of the management server itself.

Sheng

**Comment by corn13read** [comment]
I see, great, I'll look into figuring that out. THANKS

**Comment by usmanismail** [comment]
@sheng-liang Is this as trivial as running multiple Rancher Servers behind a load balancer and pointing the compute nodes to the load balancer IP? 

Do we need to enable UDP and/or Web socket forwarding on the load balancer?

**Comment by cloudnautique** [comment]
@usmanismail, once you have multiple servers you need shared redis, zookeeper and database.

 Clients(ui mostly) connect to the compute nodes over web sockets. Udp is for the networking between nodes. 

So load balancing the management cluster will be pretty standard port 80/8080/443.
