### ISSUE TITLE
Digital Ocean Private Key

### ISSUE THREAD

**Issue by jwhitcraft** [rancherio/rancher#1191]
Hello,

I created a new host on Digital Ocean from the App, but I need to get access to the host file system and I'd like to use the public/private key that Rancher created for the host, is there a way to get it out of Rancher?

**Comment by sangeethah** [comment]
In UI ,  host entry ha an option "Machine Config" which allows you to download the keys required to access the machine using "root". 
You will have root access to the Digital Ocean instance using the id_rsa file.

**Comment by jwhitcraft** [comment]
awesome, thanks!
