### ISSUE TITLE
Adding a label with Key named Type adds 4 extra labels

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1198]
build from master - June 12th
Steps:
1.  Build an Amazon EC2 machine/host with a label that has Key = Type, Value = ABC
2.  Edit host

Results:
Besides the two labels I added, there are an extra four labels with no values showing up:
![image](https://cloud.githubusercontent.com/assets/11514927/8137994/2c9a9a46-10fc-11e5-9182-a81f4ff0c292.png)

Expected:
No extra labels

**Comment by vincent99** [comment]
`type` is a bad word...  Changed host, machine and container to not turn the labels object into a model if it has a `type` key.

**Comment by tfiduccia** [comment]
build from master - June 13th
Verified fixed
