### ISSUE TITLE
Copying docker-compose and rancher-compose from UI loses newline

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/rancher#1208]
If I click the icon to copy the text I lose newline characters.
If I directly highlight and copy the text then I see newlines.

**Comment by vincent99** [comment]
Hmm, works on Mac OS.  Pretty sure this is because the API sends back the text with LF as a line separators; works fine for Mac and Linux, but Windows uses CR+LF.

I will change the UI to replace them, but we should also change the API responses @ibuildthecloud.

**Comment by ibuildthecloud** [comment]
@vincent99 do you want the API to return CRLF always or detect?

**Comment by vincent99** [comment]
CRLF always is fine, I think

**Comment by ibuildthecloud** [comment]
I hear Microsoft is listening to developers these days, maybe we can just convince them to change.

**Comment by tfiduccia** [comment]
build from master - June 13th
Verified fixed
