### ISSUE TITLE
Network Agent container name overlaps the menu dropdown

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1209]
v0.24.0-rc3

![screen shot 2015-06-12 at 9 02 58 pm](https://cloud.githubusercontent.com/assets/11410997/8142928/9231afbc-1146-11e5-926f-d43639016889.png)

**Comment by vincent99** [comment]
Hmm, this is a remnant from when they didn't have actions.

**Comment by tfiduccia** [comment]
build from master - June 13th
Verified fixed
