### ISSUE TITLE
docker-compose template generated by vew config is not accepted by rancher-compose

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#1211]
If you specify a Command through the UI when creating a service, and then go to the view config screen of your project to bring up the docker compose yaml for your service your get a entry like so:

    SomeService:
      command:
      - Some Command

This throws a syntax error when used with Rancher compose:

    Failed to parse service SomeService: yaml: unmarshal errors:
      line 2: cannot unmarshal !!seq into string

 as it is expecting:

    SomeService:
      command: "Some Command"

Either rancher compose should be ale to handle arrays or view config should be updated to generate a string instead of an array.

**Comment by sangeethah** [comment]
This is similar to the issue reported in - #1161

**Comment by sangeethah** [comment]
@usmanismail ,  With server version - v0.24.0-rc4 and rancher compose version - V0.1.2 , I am able to use docker-compose template generated by rancher and use it with rancher compose to create services.

**Comment by usmanismail** [comment]
Verified.
