### ISSUE TITLE
Invalid docker and rancher compose templates generated in view config for load balancers

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#1214]
The view config screen for LoadBalancer services generates the docker-compse.yml tempalate shown below. 

    SomeLoadBalancer:
      ports:
      - 80:80
      links:
      - SomeService
      stdin_open: true
      tty: true

This does not have an image specification which leads to the following error when launching containers from this template. 
![screen shot 2015-06-13 at 1 45 16 pm](https://cloud.githubusercontent.com/assets/204682/8145359/e7147d34-11d2-11e5-84b8-273bd9c44870.png)

Similarly the rancher rancher-compose template does not seem to have information about the fact that this is a Load Balancer and not a container service. See type container below instead of type Load Balancer.

![screen shot 2015-06-13 at 1 48 17 pm](https://cloud.githubusercontent.com/assets/204682/8145360/e714fb24-11d2-11e5-990c-ce7eed2ab3e4.png)

Is there an example of valid docker and rancher compose templates to generate load balancer instances?

**Comment by alena1108** [comment]
the cattle part has been fixed. Now we put image: rancher/load-balancer-service to the docker-compose.yml file. We are yet to generate this image and upload it to the same repo as our agent image goes to. But even with image present in the repo, and in the compose-file, no lb functionality will be provided when environment is brought up outside of Rancher.


Here are the images names we have to generate and uploaded:

rancher/dns-service
rancher/load-balancer-service
rancher/external-service

**Comment by sangeethah** [comment]
@usmanismail  , With server version - v0.24.0-rc4 and rancher compose version - V0.1.2 , I am able to use the docker-compse.yml and rancher-compose.yml generated by rancher server with rancher compose to create load balancer services.

**Comment by usmanismail** [comment]
Verified.
