### ISSUE TITLE
When removing one of the existing targets from "Service Alias" ,  we see the existing target being added twice.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1215]
Server version - V0.24.0-rc3

Steps to reproduce the problem:
Add a "Service Alias" with 2 targets - test1 and test2.
Start service.

Now edit the service and remove one of the target - "test2"
This results in "test2" being removed , but "test1" added twice to the dns.

![screen shot 2015-06-13 at 12 04 32 pm](https://cloud.githubusercontent.com/assets/4266958/8145637/65732798-11c4-11e5-93df-7010a202948b.png)

Sent from UI:
{serviceLinks: {test1: "1s1"}}

mysql> select * from service_consume_map where service_id=19;
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
| id | name  | kind              | uuid                                 | description | state   | created             | removed             | remove_time         | data | service_id | consumed_service_id | account_id |
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
| 17 | NULL  | serviceConsumeMap | 5c035778-bf00-4876-8ad3-cb90f6131297 | NULL        | active  | 2015-06-13 18:54:08 | NULL                | NULL                | {}   |         19 |                   1 |          5 |
| 18 | NULL  | serviceConsumeMap | 2a1a78ad-05ec-47e2-89dd-3044527e54fa | NULL        | removed | 2015-06-13 18:54:08 | 2015-06-13 18:56:22 | 2015-06-13 18:57:22 | {}   |         19 |                   7 |          5 |
| 20 | test1 | serviceConsumeMap | 49f1c5fa-6c16-467e-9222-0b4db2971546 | NULL        | active  | 2015-06-13 18:56:22 | NULL                | NULL                | {}   |         19 |                   1 |          5 |
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
3 rows in set (0.00 sec)

mysql>

**Comment by alena1108** [comment]
the bug cause is: the same service targets  - one with null and another with not null name, are treated as as diff targets; so the new one with not null gets created w/o the first one being removed.

**Comment by alena1108** [comment]
The other bug is - service link name is set although the UI doesn't send it. Also has to be fixed

**Comment by alena1108** [comment]
@vincent99 Vince, there seems to be the UI bug here as well. DNS/LB service links are being set as a map of links instead of a list of serviceIds; with the name defaulted to service.name. It should be changed as user doesn't specify this name, and we can't hardcode it to the service name as it can change.

**Comment by alena1108** [comment]
@vincent99 happens on edit only - on create serviceIds are being set, which is correct.

**Comment by sangeethah** [comment]
Tested with Server version - V0.24.0-rc4
When removing one of the existing targets from "Service Alias" , we donot see the issue of existing target being added twice.
