### ISSUE TITLE
When removing one of the existing targets from "LB services" , we see the existing target being added twice.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1216]
Server version - V0.24.0-rc3

Steps to reproduce the problem:
Add Lb services with 2 targets test1 and test2.
Activate service.
Remove one target - test2.
Once this is done  , we see LB service being linked with "test1" target 2 times.

![screen shot 2015-06-13 at 12 18 40 pm](https://cloud.githubusercontent.com/assets/4266958/8145696/dab3c7ae-11c6-11e5-9aa2-c07b7e6ae677.png)

**Comment by sangeethah** [comment]
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
| id | name  | kind              | uuid                                 | description | state   | created             | removed             | remove_time         | data | service_id | consumed_service_id | account_id |
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
|  6 | NULL  | serviceConsumeMap | 293a55b9-b153-49e0-83e6-ec15a1d06000 | NULL        | active  | 2015-06-13 18:06:32 | NULL                | NULL                | {}   |         13 |                  11 |          5 |
|  7 | NULL  | serviceConsumeMap | fb80367c-91f4-4e3b-8bb4-bbde09d282ca | NULL        | removed | 2015-06-13 18:06:32 | 2015-06-13 19:14:09 | 2015-06-13 19:15:09 | {}   |         13 |                  12 |          5 |
| 24 | test1 | serviceConsumeMap | 8dda90e9-8c70-400f-bc12-8bb55d32bef0 | NULL        | active  | 2015-06-13 19:14:09 | NULL                | NULL                | {}   |         13 |                  11 |          5 |
+----+-------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------+---------------------+------------+
3 rows in set (0.00 sec)

mysql>

**Comment by alena1108** [comment]
The same cause as https://github.com/rancherio/rancher/issues/1215

**Comment by sangeethah** [comment]
Tested with Server version - V0.24.0-rc4
When removing one of the existing targets from "LB services" , we do not see the issue of existing target being added twice.
