### ISSUE TITLE
Link environment variables do not show up for service links

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#1218]
When you link a service you should now get environment variable that are compatible with Docker links environment variables:

```
MYSQL_PORT=tcp://172.17.2.48:3306
MYSQL_PORT_3306_TCP=tcp://172.17.2.48:3306
MYSQL_PORT_3306_TCP_ADDR=172.17.2.48
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_PORT_3306_TCP_PROTO=tcp
```

Additionally the target containers environment variables should be copied to the environment of consuming container in the following fashion:

```
MYSQL_PORT=tcp://172.17.2.48:3306
MYSQL_PORT_3306_TCP=tcp://172.17.2.48:3306
MYSQL_PORT_3306_TCP_ADDR=172.17.2.48
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_PORT_3306_TCP_PROTO=tcp
```

More info on the environment variables: https://docs.docker.com/userguide/dockerlinks/

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc4

I am able to see all the docker link env variables as well as custom env variables being added to service when it is being linked.

Following variables get defined in containers of a service say service1 , which is linked to a service - "web123" with link name "weblink". This service has 2 env variables - web_test1=value1 and web_test2=value2 which is also is seen in service1:


declare -x TESTLINKS_WEB123_1_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x TESTLINKS_WEB123_1_ENV_web_test1="value1"
declare -x TESTLINKS_WEB123_1_ENV_web_test2="value2"
declare -x TESTLINKS_WEB123_1_NAME="/cattle/testlinks_web123_1"
declare -x TESTLINKS_WEB123_1_PORT="tcp://weblink:80"
declare -x TESTLINKS_WEB123_1_PORT_443_TCP="tcp://weblink:443"
declare -x TESTLINKS_WEB123_1_PORT_443_TCP_ADDR="weblink"
declare -x TESTLINKS_WEB123_1_PORT_443_TCP_PORT="443"
declare -x TESTLINKS_WEB123_1_PORT_443_TCP_PROTO="tcp"
declare -x TESTLINKS_WEB123_1_PORT_80_TCP="tcp://weblink:80"
declare -x TESTLINKS_WEB123_1_PORT_80_TCP_ADDR="weblink"
declare -x TESTLINKS_WEB123_1_PORT_80_TCP_PORT="80"
declare -x TESTLINKS_WEB123_1_PORT_80_TCP_PROTO="tcp"
declare -x TESTLINKS_WEB123_2_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x TESTLINKS_WEB123_2_ENV_web_test1="value1"
declare -x TESTLINKS_WEB123_2_ENV_web_test2="value2"
declare -x TESTLINKS_WEB123_2_NAME="/cattle/testlinks_web123_2"
declare -x TESTLINKS_WEB123_2_PORT="tcp://weblink:80"
declare -x TESTLINKS_WEB123_2_PORT_443_TCP="tcp://weblink:443"
declare -x TESTLINKS_WEB123_2_PORT_443_TCP_ADDR="weblink"
declare -x TESTLINKS_WEB123_2_PORT_443_TCP_PORT="443"
declare -x TESTLINKS_WEB123_2_PORT_443_TCP_PROTO="tcp"
declare -x TESTLINKS_WEB123_2_PORT_80_TCP="tcp://weblink:80"
declare -x TESTLINKS_WEB123_2_PORT_80_TCP_ADDR="weblink"
declare -x TESTLINKS_WEB123_2_PORT_80_TCP_PORT="80"
declare -x TESTLINKS_WEB123_2_PORT_80_TCP_PROTO="tcp"
declare -x WEB123_1_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x WEB123_1_ENV_web_test1="value1"
declare -x WEB123_1_ENV_web_test2="value2"
declare -x WEB123_1_NAME="/cattle/web123_1"
declare -x WEB123_1_PORT="tcp://weblink:80"
declare -x WEB123_1_PORT_443_TCP="tcp://weblink:443"
declare -x WEB123_1_PORT_443_TCP_ADDR="weblink"
declare -x WEB123_1_PORT_443_TCP_PORT="443"
declare -x WEB123_1_PORT_443_TCP_PROTO="tcp"
declare -x WEB123_1_PORT_80_TCP="tcp://weblink:80"
declare -x WEB123_1_PORT_80_TCP_ADDR="weblink"
declare -x WEB123_1_PORT_80_TCP_PORT="80"
declare -x WEB123_1_PORT_80_TCP_PROTO="tcp"
declare -x WEB123_2_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x WEB123_2_ENV_web_test1="value1"
declare -x WEB123_2_ENV_web_test2="value2"
declare -x WEB123_2_NAME="/cattle/web123_2"
declare -x WEB123_2_PORT="tcp://weblink:80"
declare -x WEB123_2_PORT_443_TCP="tcp://weblink:443"
declare -x WEB123_2_PORT_443_TCP_ADDR="weblink"
declare -x WEB123_2_PORT_443_TCP_PORT="443"
declare -x WEB123_2_PORT_443_TCP_PROTO="tcp"
declare -x WEB123_2_PORT_80_TCP="tcp://weblink:80"
declare -x WEB123_2_PORT_80_TCP_ADDR="weblink"
declare -x WEB123_2_PORT_80_TCP_PORT="80"
declare -x WEB123_2_PORT_80_TCP_PROTO="tcp"
declare -x WEBLINK_ENV_NGINX_VERSION="1.7.11-1~wheezy"
declare -x WEBLINK_ENV_web_test1="value1"
declare -x WEBLINK_ENV_web_test2="value2"
declare -x WEBLINK_NAME="/cattle/weblink"
declare -x WEBLINK_PORT="tcp://weblink:80"
declare -x WEBLINK_PORT_443_TCP="tcp://weblink:443"
declare -x WEBLINK_PORT_443_TCP_ADDR="weblink"
declare -x WEBLINK_PORT_443_TCP_PORT="443"
declare -x WEBLINK_PORT_443_TCP_PROTO="tcp"
declare -x WEBLINK_PORT_80_TCP="tcp://weblink:80"
declare -x WEBLINK_PORT_80_TCP_ADDR="weblink"
declare -x WEBLINK_PORT_80_TCP_PORT="80"
declare -x WEBLINK_PORT_80_TCP_PROTO="tcp"
