### ISSUE TITLE
Can't link services that have no port info.

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1225]
v0.24.0-rc4
Steps:
1.  Create a service using the ubuntu image
2.  Create another service using the ubuntu image and link it to the first one
3.  Start the services

Results:
The container for the second service (that is linked to first) will not create.  I get a weird error - : 5ff986b7-7390-42d8-bdaa-fc574376b880 : 'NoneType' object is not iterable

Expected:
Container should create.

Comment:  Looks like ubuntu not automatically creating a port like some of the other images might be the problem.

**Comment by deniseschannon** [comment]
I have a similar issue when doing the Wordpress example that we've outlined in the docs.

Service 1: mysql with env var `MYSQL_ROOT_PASSWORD=pass1`, name of service is `mysql`
Service 2: wordpress linked to mysql with env var `WORDPRESS_DB_HOST=mysql:3306` and `WORDPRESS_DB_PASSWORD=pass1`

Start services

Logs for wordpress container show:
```
6/14/2015 6:04:19 PMMySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
6/14/2015 6:04:22 PM
Invalid Date Invalid DateWarning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10
Invalid Date Invalid Date
Invalid Date Invalid DateWarning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10
Invalid Date Invalid Date
```

**Comment by ibuildthecloud** [comment]
@deniseschannon this has been resolved, correct?

**Comment by deniseschannon** [comment]
v0.25.0-rc2

verified @tfiduccia's example is fixed. My example is no longer relevant as no longer need to set the wordpress DB env variables
