### ISSUE TITLE
Environment variables will not be available for linked instances that get linked/created after service that links has been started.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1234]
Server version - V0.24.0-rc5

Steps to reproduce the problem:
Scenario 1:

Create service - "client". 
Start service.
Create service - "linkservice" with environment name - name1 - value1.
Start service.

Link service "client" to "linkservice".

This will not result in any docker env variables relating to exposed ports or user defined variable being created for containers in service "client".

Scenario 2:

Create service - "linkservice" with environment name - name1 - value1.(Do not start the service)
Create service - "client" with link to "linkservice". 
Start this service - "client".
Start service - "linkservice".

This will not result in any docker env variables relating to exposed ports or user defined variable being created for containers in service "client".

Scenario 3:

Create service - "linkservice" with environment name - name1 - value1 with scale2.
Start this service - "linkservice"
Create service - "client" with link to "linkservice". 
Start this service - "client".

At this point, you will see  docker env variables relating to exposed ports for 2 containers of service - "linkservice" 

Scale up "linkservice".

This will not result in docker env variables relating to exposed ports for the new container deployed for "linkservice".

**Comment by ibuildthecloud** [comment]
@sangeethah I think this is "won't fix."  This is the same behavior as docker-compose basically. Environment variables can not be changed after the fact.  In general links and env var will most likely be deprecated in Docker.

**Comment by sangeethah** [comment]
@ibuildthecloud ,This bug was logged to track this behavior we see. 
@deniseschannon , may be this is worth documenting as a known limitation(or behavior)
