### ISSUE TITLE
Authenticate with cookies instead of header

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#1255]
This changes the UI to both store and send the authentication token (JWT) identifying the logged-in user as a cookie.  Previously it stored it in `sessionStorage`, but that does not persist across browser windows so if you did 'open in new tab' on a link you would be logged out.

Also affects:
  - Turning access controls off and on
  - "View in API" actions and the endpoint link on the API screen.  The cookie automatically gets sent along if the API is on the same domain, so no special basic auth credentials are sent any more.
  - All the other stuff that was previous stored in `sessionStorage`is now in `localStorage` (which does cross browser tabs).  This includes the cache of github info, and current project id.
  - Since the account and project IDs are shared across tabs now, there is some bonus fun.
    - If you switch projects in one tab, all other tabs should switch too.
    - If you log out of one tab, all other tabs should log out.

**Comment by vincent99** [comment]
rancherio/ui#214

**Comment by tfiduccia** [comment]
v0.25.0-rc2
verified fixed
