### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jmreicha** [rancherio/rancher#126]
It's been awhile sincere I looked but when I was evaluating this originally there was no authentication mechanism so it was pretty wide open to the world.  Has this been addressed yet or I guess what is the best way to handle this?

**Comment by sidharthamani** [comment]
we have added authentication support now using Github OAuth -- https://github.com/rancherio/rancher/issues/45. We will be adding authentication using LDAP in the future and other community driven ones

**Comment by jmreicha** [comment]
Ah good to know, thanks.

**Comment by sidharthamani** [comment]
@jmreicha here's a demo on using authentication on rancher 

http://sidharthamani.github.io/rancher-stuff/2015/02/02/rancher-github_integration.html

Here's more information on how to use projects with Rancher

http://sidharthamani.github.io/rancher-stuff/2015/02/16/rancher-github_integration_2.html
