### ISSUE TITLE
Not able to access to host stats , container logs and shell after server was up for a while.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1263]
Server version - v0.24.0

I was able to access host stats , container logs and shell after the rancher server was brought up.
The server has been up for couple of days now.

Today I noticed that I am not able to  access host stats , container logs and shell from any of the 3 hosts in my setup.

Once the server was restarted , able to access  host stats , container logs and shell again.

**Comment by cjellick** [comment]
Was a deadlock issue. Addressed. @ibuildthecloud is cutting a release with this fixed now.

**Comment by sangeethah** [comment]
Tested with server version - v0.25.0-rc2.

3 of the servers have been running for more than 2 days now and I am still able to access  host stats  for all the hosts in the set up , container logs and shell for containers.
