### ISSUE TITLE
[rancher-compose] new lines not working for logs

### ISSUE THREAD

**Issue by jwhitcraft** [rancherio/rancher#1282]
After i do a `rancher-compose up <service>` and it starts spitting out the logs, it doesn't respect the new lines. I'm on OS X 10.10.

**Comment by jwhitcraft** [comment]
I'm using rancher-compose `v0.1.2`

**Comment by deniseschannon** [comment]
I have verified this is a bug with rancher-compose.

**Comment by deniseschannon** [comment]
Verified fix in v0.1.3 of Rancher-compose (now tagged as latest in Rancher) for Mac OS X and Linux.
