### ISSUE TITLE
Can't run any containers

### ISSUE THREAD

**Issue by brianclements** [rancherio/rancher#13]
I'm running rancher agents directly on my CoreOS cluster nodes. When trying to run anything via the web UI, I get the same error:

this was a busybox test container:
```
: 5d4dd585-1653-4746-a543-b92621bb1ae3 : Command '['/var/lib/cattle/pyagent/cattle/plugins/docker/net-util.sh', '-p', '6844', '-i', '10.42.121.21/16', '-m', u'02:ca:f9:6d:54:71', '-d', 'eth0']' returned non-zero exit status 43
```

then directly after, crosbymichael/dockerui:
```
: cefe9c9e-21d1-4fb2-9cdd-8910565fae0e : Command '['/var/lib/cattle/pyagent/cattle/plugins/docker/net-util.sh', '-p', '6845', '-i', '10.42.242.207/16', '-m', u'02:ca:f9:1d:b8:0e', '-d', 'eth0']' returned non-zero exit status 43
```
Those were both on my node01, I tried crosbymichael/dockerui on node02:
```
: 6b621368-9faa-4bc2-9f0d-07ba40f1b1b6 : Command '['/var/lib/cattle/pyagent/cattle/plugins/docker/net-util.sh', '-p', '5306', '-i', '10.42.120.197/16', '-m', u'02:ca:f9:9a:fa:aa', '-d', 'eth0']' returned non-zero exit status 43
```
The network agent downloads and runs just fine on each node however.

**Comment by deniseschannon** [comment]
The net-util.sh script masking issue was logged as a separate issue. https://github.com/rancherio/rancher/issues/23

The original issue of not able to launch a container should be fixed. @brianclements If you are interested in seeing when the masking issue is fixed, then please subscribe to this issue https://github.com/rancherio/rancher/issues/23.
