### ISSUE TITLE
[rancher-compose] unmarshal errors with generated compose.yml files and UI created Services using specific host

### ISSUE THREAD

**Issue by Mmdixon** [rancherio/rancher#1316]
I was able to create a service in the Rancher UI, and see the docker-compose.yml and rancher-compose.yml config files for the project.
However, using these config files with rancher-compose in the command line give the following errors:

```
rancher-compose --debug -p Infra restart testservice

DEBU[0000] Opening compose file: docker-compose.yml     
DEBU[0000] Opening rancher-compose file: rancher-compose.yml 
DEBU[0000] Found environment: Infra(1e7)              
DEBU[0000] Finding service testservice                     
INFO[0000] [0/1] [testservice]: Restarting                 
ERRO[0000] Failed to start testservice : json: cannot unmarshal number into Go value of type string 
ERRO[0000] Failed to start: testservice : json: cannot unmarshal number into Go value of type string 
FATA[0000] json: cannot unmarshal number into Go value of type string 
```

Rancher:v0.24.0
Cattle:v0.56.0
User Interface:v0.28.0
Rancher Compose:v0.1.3
Machine Service:v0.13.0 (docker-machine v0.3.0-dev-packet-rc2)

**Comment by deniseschannon** [comment]
Could you provide the rancher-compose.yml and docker-compose.yml files?

**Comment by Mmdixon** [comment]
The files are:
docker-compose.yml
```
testservice:
  ports:
  - 2424:2424/tcp
  - 2480:2480/tcp
  restart: 'no'
  tty: true
  image: maluuba/orientdb:2.0.8
  volumes:
  - /secondary/config/orient:/opt/orientdb/config
  - /secondary/data/orient:/opt/orientdb/databases
  - /secondary/logs/orient:/opt/orientdb/log
  stdin_open: true
```
rancher-compose.yml
```
testservice:
  scale: 1
  requestedhostid: 1

```

**Comment by deniseschannon** [comment]
Interesting enough, I tested this with all different versions of rancher-compose. Can you do a `rancher-compose -v` to share your version? 

I don't get this issue with rancher-compose v0.1.0. 

I get a panic error with v0.1.2. 

```
INFO[0000] [0/1] [testservice]: Restarting              
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x12c3ab]

goroutine 14 [running]:
github.com/rancherio/rancher-compose/rancher.(*RancherService).containers(0x208c02240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/rancher/service.go:514 +0x21b
github.com/rancherio/rancher-compose/rancher.(*RancherService).Restart(0x208c02240, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/rancher/service.go:523 +0x4e
github.com/rancherio/rancher-compose/librcompose/project.(*serviceWrapper).Restart(0x208bf8d80, 0x208c02210)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/service-wrapper.go:139 +0x1dd
github.com/rancherio/rancher-compose/librcompose/project.func·003(0x208bf8d80, 0x208c02210)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:147 +0x32
created by github.com/rancherio/rancher-compose/librcompose/project.(*Project).traverse
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:219 +0x21f

goroutine 1 [runnable]:
sync.(*WaitGroup).Wait(0x208bf8da0)
	/usr/src/go/src/sync/waitgroup.go:132 +0x169
github.com/rancherio/rancher-compose/librcompose/project.(*serviceWrapper).Wait(0x208bf8d80, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/service-wrapper.go:197 +0x46
github.com/rancherio/rancher-compose/librcompose/project.(*Project).traverse(0x208be0790, 0x208c021e0, 0x208c02210, 0x6ece10, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:231 +0x50b
github.com/rancherio/rancher-compose/librcompose/project.(*Project).forEach(0x208be0790, 0x2089580b0, 0x1, 0x1, 0x6ece10, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:203 +0x18e
github.com/rancherio/rancher-compose/librcompose/project.(*Project).Restart(0x208be0790, 0x2089580b0, 0x1, 0x1, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:148 +0xa2
github.com/rancherio/rancher-compose/app.ProjectRestart(0x208958180)
	/source/gopath/src/github.com/rancherio/rancher-compose/app/app.go:57 +0x9c
github.com/codegangsta/cli.Command.Run(0x5b9ac0, 0x7, 0x0, 0x0, 0x5f6a70, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0x20898c340, 0x208958000, 0xc, 0xc, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
	/source/main.go:131 +0xc76

goroutine 5 [chan send]:
github.com/rancherio/rancher-compose/rancher.generateColors()
	/source/gopath/src/github.com/rancherio/rancher-compose/rancher/service.go:649 +0x191
created by github.com/rancherio/rancher-compose/rancher.init·1
	/source/gopath/src/github.com/rancherio/rancher-compose/rancher/service.go:655 +0x25

goroutine 13 [chan receive]:
github.com/rancherio/rancher-compose/librcompose/project.(*defaultListener).start(0x208a71ea0)
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/listener.go:37 +0x7b
created by github.com/rancherio/rancher-compose/librcompose/project.NewProject
	/source/gopath/src/github.com/rancherio/rancher-compose/librcompose/project/project.go:41 +0x222

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0x2089d42c0)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0x2089d42c0)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc
```

And with the latest build of rancher-compose (from github), it works fine.

**Comment by Mmdixon** [comment]
The rancher-compose version I was using was: `rancher-compose version v0.1.2`, via the windows download link that the rancher UI provides.
I do get that panic error when trying to restart a service that does not exist, otherwise, the unmarshal error as above.

I tried with `rancher-compose version 0.1.0`, via the windows download link on the github release tag. And I get the same unmarshal error. I do not get an panic error however, when trying to restart a service that doesn't exist, but of course that doesn't do anything.

I tried the latest build of rancher-compose on linux, version ended up being `rancher-compose version 1b6b27b`. Same behavior as the 0.1.0 trial, same unmarshal error, and no panic error if the service doesn't exist.

@deniseschannon did you end up trying to restart a service that did exist on rancher?

**Comment by deniseschannon** [comment]
@Mmdixon I had no issues when restarting services that did exist on Rancher for either the build from rancher-compose or v0.1.2. 

No unmarshalling errors. I had copied and pasted your files, so not too sure why it's not working for me and not for you. The only difference would be that I'm using the MacOSX link for v0.1.2, but I would have assumed that doesn't cause the issue.

**Comment by deniseschannon** [comment]
@Mmdixon We released a v0.1.3 for rancher-compose that is now the latest. Since I was unable to reproduce, could you try testing with v0.1.3 to see if you are still seeing the same issue?

**Comment by Mmdixon** [comment]
Thanks for the update.
I got my same error again on windows with v0.1.3.
I also tried it on a Mac with rancher-compose v0.1.3 and got the same unmarshal error when trying a restart.

However, I did get it to work with a different approach.
The issue seems to come from if I make the Service in the UI, then use the generated {docker,rancher}-compose.yml files to try commands like `restart` or `stop`, it always fails with the unmarshal error.
But if I create the service purely from rancher-compose (i.e. starting with the `up` command) with compose files that are identical to what would of been generated, and the Service not existing in the UI, then it would work along with the other commands.

There is another issue though. Making a Service in the UI respects the `requestedhostid: 6` field, i.e. the container is started on host 6 (and puts that configuration in the compose config view). But I can't use rancher-compose with this approach as errors above.
However, if I try to make a service through rancher-compose it does not respect the `requestedhostid` in my compose file, i.e. it makes a container on host 1 instead of host 6, and even checking the compose config view, the field is missing, like it was never told a requested host. I tried something like `requestedhostid: 1h6` too, as that is the ID that appears in the API, but that didn't work either.

**Comment by deniseschannon** [comment]
We have taken out `requestedhostid` from rancher-compose, which is why it's not being respected. We have moved to using `labels` on the service to determine which hosts to use in rancher-compose. You can read more about it here: http://rancher.docs.rancher.com/docs/rancher-compose/scheduling/

I'm not sure if that's your unmarshal error as I was able to use the exact same yml files and have not been able to reproduce. 

When you are trying the `restart` is your service that was created in the UI, you shouldn't be required to do an `up` to `restart` or `stop` the service, but the yaml files will need to be in place in order to restart. Can you confirm if the files were already in place? Maybe there was some other files that it's trying to unmarshal?

**Comment by Mmdixon** [comment]
Ok, I am able to use rancher-compose as I wanted to now.

By using labels in the docker-compose.yml file instead of `requestedhostid` in the rancher-compose.yml file, it works fine without the unmarshal error.

So the error seems to come from if I make it in the UI and choose the scheduling option `Run all containers on a specific host  :`, that uses a `requestedhostid` instead of a label, and rancher-compose has problems with this field. But yeah, as you said rancher-compose has moved away from this field.

Thanks

**Comment by willseward** [comment]
I'm having the same problem on v0.2.6.

```
rancher-compose version v0.2.6
DEBU[0000] Opening compose file: dist/docker-compose.yml 
DEBU[0000] Opening rancher-compose file: dist/rancher-compose.yml 
DEBU[0001] Found stack: frogsaver(1e2)                  
DEBU[0001] Launching action for mysql-4-locked          
DEBU[0001] Launching action for api-v1-3-latest         
INFO[0001] Project [frogsaver]: Starting project        
DEBU[0001] Finding service mysql-4-locked               
INFO[0001] [0/2] [mysql-4-locked]: Starting             
ERRO[0001] Failed Starting mysql-4-locked : json: cannot unmarshal number into Go value of type string 
DEBU[0001] Finding service api-v1-3-latest              
INFO[0001] [0/2] [api-v1-3-latest]: Starting            
DEBU[0001] Found service api-v1-3-latest                
DEBU[0001] Finding service mysql-4-locked               
ERRO[0001] Failed Starting api-v1-3-latest : json: cannot unmarshal number into Go value of type string 
ERRO[0001] Failed to start: api-v1-3-latest : json: cannot unmarshal number into Go value of type string 
ERRO[0001] Failed to start: mysql-4-locked : json: cannot unmarshal number into Go value of type string 
FATA[0001] json: cannot unmarshal number into Go value of type string 
```
docker-compose.yml
``` yml
api-v1-3-latest:
  restart: 'no'
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: "io.rancher.stack_service.name=api-v1-3-latest"
  tty: true
  image: <redacted>
  links:
  - mysql-4-locked:mysql
  stdin_open: true
mysql-4-locked:
  restart: always
  environment:
    <redacted>
  tty: true
  image: mysql:latest
  volumes:
  - /var/lib/mysql:/var/lib/mysql
  stdin_open: true
```
rancher-compose.yml
``` yml 
api-v1-3-latest:
  scale: 1
mysql-4-locked:
  scale: 1
```

**Comment by deniseschannon** [comment]
@willseward I am unable to reproduce, but I did replace your image name for `api-v1-3-latest` to wordpress so that i could just get something to link to mysql. 

From the logs, it looks like you are reusing a stack/service name. Can you try in a new stack to see if it will work? Only links will be updated if you re-use the same stack/service name. The other changes won't be updated in Rancher. It's like "Editing" a service in the UI. 

```
api-v1-3-latest:
  restart: always
  labels:
    io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=testname/mysql-4-locked
  tty: true
  image: wordpress
  links:
  - mysql-4-locked:mysql
  stdin_open: true
mysql-4-locked:
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: '55'
  tty: true
  image: mysql:latest
  volumes:
  - /var/lib/mysql:/var/lib/mysql
  stdin_open: true
```

**Comment by willseward** [comment]
@deniseschannon 
Sorry about the late response.

I just tested this with v0.4.0 and rancher/server:v0.40.0.

My previous implementation failed as usual, but changing the stack name stood everything up as expected as you predicted. Unfortunately, this is not my preferred method of upgrading my services. I would like to keep everything inside one stack.
