### ISSUE TITLE
Agent number limit?

### ISSUE THREAD

**Issue by clemenko** [rancherio/rancher#1323]
Is there a limit to the number of agents that can be added to a server?  I tried to automate 20 and only 9 showed up.

**Comment by deniseschannon** [comment]
Just to clarify, you are talking about number of hosts, correct? If so, there is no limit.

**Comment by clemenko** [comment]
Correct. Let me test.

**Comment by deniseschannon** [comment]
We have had a server have 20 hosts before.

**Comment by clemenko** [comment]
I found the issue. Thanks!
