### ISSUE TITLE
Resource Groups / Views for server UI

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#134]
I would like to use a Rancher to cluster to host multiple unrelated sets of containers running on the same Rancher compute nodes. Currently with this model the Rancher Server UI would get cluttered with all these containers. It would be great to be able to tag containers to split them into logical groups which can then be used to filter the displayed containers. I envisage something very similar to AWS Resource groups.

**Comment by thaJeztah** [comment]
+1 I think this might well be possible once https://github.com/docker/docker/pull/9882 has been implemented?

**Comment by deniseschannon** [comment]
@usmanismail With the new services and project implementation, this would solve your original request in regards to the UI. You'd have multiple projects to split up the unrelated sets of containers. In each project, you could have services with a scale of 1 (or more if needed). Let me know if that solves what your needs to see if we might be able to close this issue.

**Comment by usmanismail** [comment]
It does.
