### ISSUE TITLE
Add Support for linode.

### ISSUE THREAD

**Issue by sfister** [rancherio/rancher#1349]
Would like to have support for linode added to the list of providers.

**Comment by vincent99** [comment]
That screen is essentially a frontend for docker-machine.  Linnode (or someone else) would need to contribute a [driver](https://github.com/docker/machine/tree/master/drivers) for it to be supported.

**Comment by deniseschannon** [comment]
I'm going to close this issue as there is a dependency for a driver to be added on docker-machine. When it's added, we could add support for it.

**Comment by bhhaskin** [comment]
it looks like the driver is being worked on. https://github.com/docker/machine/pull/268

**Comment by vincent99** [comment]
Docker is not accepting new drivers into machine proper anymore, they have a way they can be written as plugins.  We are working on supporting that so that you can choose to include whatever drivers you want without involving us.
