### ISSUE TITLE
Provisioning a host on Rancher server with SSL fails

### ISSUE THREAD

**Issue by apobbati** [rancherio/rancher#1350]
Steps to reproduce:

1) Create a Rancher Server setup according to #1151 (Basically a Nginx w/ SSL in front of Rancher)
2) Click on `Infrastructure` -> `Add Host`
3) Configure the host settings and click on `Create`
4) Check the logs and you will see something similar to the below.

```
14:15:57.484 [main] INFO  ConsoleStatus - [DONE ] [67664ms] Startup Succeeded, Listening on port 8081
time="2015-06-27T14:16:53Z" level=info msg="Setting log level" logLevel=info
time="2015-06-27T14:16:53Z" level=info msg="Starting go-machine-service..." gitcommit=480875d
time="2015-06-27T14:16:53Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://<my-rancher-server>/v1], statusCode [401]. Status [401 Unauthorized]. Body: [{\"id\":\"a0af77c7-251f-4e6e-bc22-6a083f804f28\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":401,\"code\":\"Unauthorized\",\"message\":\"Unauthorized\",\"detail\":null}]"
time="2015-06-27T14:16:53Z" level=info msg="Exiting go-machine-service..."
```

I am able to successfully navigate around the UI but can't do much of anything.

**Comment by apobbati** [comment]
Anybody else having this problem?

**Comment by cloudnautique** [comment]
@apobbati, in your nginx configuration are you passing the x-api-request-url header? That will update the schema to return the SSL url. Check out https://github.com/rancherio/rancher/issues/140#issuecomment-101131034? for instructions.

Also, did you set the https://rancher.example.com/v1/setings/api.host to a space " " ? There is a bug that forces http when that is set to a string value. #1380

**Comment by apobbati** [comment]
Thank you! It worked like a charm. I did not set the https://rancher.example.com/v1/setings/api.host to a space.
