### ISSUE TITLE
Host appear twice

### ISSUE THREAD

**Issue by moimael** [rancherio/rancher#1357]
Hi, 

I was trying to deploy a service, then I noticed that my Host was displayed twice and that some containers try to deploy on the second copy, which result in a failure.

![rancher](https://cloud.githubusercontent.com/assets/1479859/8404554/1c7ec330-1e4e-11e5-833c-989d3934867b.png)

**Comment by ianbytchek** [comment]
I had a similar issue, observed it after restarting the host.

**Comment by deniseschannon** [comment]
@moimael looks like you are using RancherOS. There is a known issue with v0.3.1 of RancherOS and the `/var/lib/rancher/` is ephemeral and gone on reboot. We are putting in a fix for v0.3.2, which will be coming out this week. #936 was the Rancher bug, which has been fixed. The RancherOS PR has already been merged. 

@ianbytchek Are you also using RancherOS?

**Comment by ianbytchek** [comment]
Yep.

**Comment by deniseschannon** [comment]
A RancherOS release has been made (v0.3.3), which contains the fix so that hosts will no longer duplicate on the screen upon restart of the host. Please refer to the [README](https://github.com/rancherio/os/blob/master/README.md) in our OS repository for more details.
