### ISSUE TITLE
Agent says: ERROR: http://10.1.3.4:8080/v1 is not accessible (but should say: Authentication failure)

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#136]
My agent won't connect to my server (might be related to #130)

```
# sudo docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e CATTLE_AGENT_IP=10.1.3.7 rancher/agent http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424991600000:U44wMQIpHVVCGYw7Kbgqh0doeg
INFO: Attempting to connect to: http://10.1.3.4:8080/v1
ERROR: http://10.1.3.4:8080/v1 is not accessible
ERROR: http://10.1.3.4:8080/v1 is not accessible
ERROR: http://10.1.3.4:8080/v1 is not accessible
```

but the server is reachable from the agent host:  
```
# curl -v http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424991600000:U44wMQIpHVVCGYw7Kbgqh0doeg
* Hostname was NOT found in DNS cache
*   Trying 10.1.3.4...
* Connected to 10.1.3.4 (10.1.3.4) port 8080 (#0)
> GET /v1/scripts/3635CE52990768911608:1424991600000:U44wMQIpHVVCGYw7Kbgqh0doeg HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.1.3.4:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-API-Schemas: http://10.1.3.4:8080/v1/schemas
< Vary: Accept-Encoding, User-Agent
< Content-Type: text/plain
< WWW-Authenticate: Basic realm="Enter API access key and secret key as username and password"
< Content-Length: 258
* Server Jetty(8.1.11.v20130520) is not blacklisted
< Server: Jetty(8.1.11.v20130520)
< 
#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
export CATTLE_REGISTRATION_SECRET_KEY="3635CE52990768911608:1424991600000:U44wMQIpHVVCGYw7Kbgqh0doeg"
export CATTLE_URL="http://10.1.3.4:8080/v1"
export DETECTED_CATTLE_AGENT_IP="10.1.3.7"
* Connection #0 to host 10.1.3.4 left intact
```

 
The server logs do not say anything after 
```
23:40:04.294 [main] INFO  ConsoleStatus - [DONE ] [17581ms] Startup Succeeded, Listening on port 8080
```
 
Is there a way to debug this?

**Comment by ibuildthecloud** [comment]
Try that curl command from inside a container.  Any chance docker0 is messed up?

**Comment by pshouse** [comment]
I had the same problem. Turns out if you configure access controls on the server, the agent fails the connectivity test in run.sh with a 401 error. Started a fresh server container with no access control and the agent started with no problems.

**Comment by feliksik** [comment]
@ibuildthecloud : I started an ubuntu container on the host, and can still perfectly reach the host. 


I just disabled the security control on the server, and now I can connect. So it seems to be an authentication issue. But this is not made clear in any way. 

Does it matter whether the URL I use to contact the server is in line with the URL specified in github? 
If I get the shell script with the export directives, does that mean that the authentication did at least succeed?

**Comment by feliksik** [comment]
I just deleted server and client, and now I get the worrying message: 

```
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
ERROR: http://10.1.3.4:8080/v1/scripts/3635CE52990768911608:1424721600000:3j74JpoznIP98r7ishstjWaaCU is not accessible
```

However, the server does show the client in the UI. So I'm not sure if there is actually something wrong, at all.

**Comment by ibuildthecloud** [comment]
@feliksik Let me explain how auth works.  I'm not sure if I totally follow your sequence of events so if I just explain the details maybe that will help.  In the README.md of Rancher we say to register a host with the following command

    docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://MANAGEMENT_IP:8080

If you click the "Add Host" button in the UI we give you a command like (notice the long random strings at the end)

    sudo docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://localhost:8080/v1/scripts/7AE22E31405688E533F4:1425056400000:MOGpr8ZsoQXpRstuwDfPOC5cI

Admittedly this is confusing and I think we may have to remove the instructions from the README.md and tell you just just follow the instructions on the UI.

The random string at the end is the registration token.  If you use a URL that does not have the registration token then you can only register with a server that does not have auth on.  If you have auth on you must use a URL with the registration token.

When an agent registers with or without the token, an account and corresponding access/secret key is created for the agent.  This means that every host in rancher has a unique set of credentials assigned to it.  The agent saves these credentials in the agent environment variables.  The difference between auth on and off is that if auth is off any agent can create credentials, if auth is on you must have the registration token to create an account.

Now the different scenarios of turning auth on or off:

If you have already registered a host with auth on or off  and then you switch auth to the opposite, the agents should still work.  This is because they created a credential on registration and they continue to use that credential.

If you wipe out the server and bring up a new server with auth off, the existing agents that are still trying to communicate with that IP will reregister themselves with the new server and create a new credential.

If you wipe out the server and bring up a new server with auth on, the existing agents will get stuck because their credential is bad and they don't have a registration token to register to the new server.

I hope that helps a bit.

**Comment by feliksik** [comment]
@ibuildthecloud thanks, your answer solves #138 so I closed it. 

So my conclusion is then: the agent says it cannot reach the server, which is incorrect; it would be more helpful it the agent says that there is an authentication failure.

**Comment by ibuildthecloud** [comment]
Yes that sounds good.  We should detect 401 and print an appropriate message.

**Comment by usmanismail** [comment]
I am seeing the same behavior with the not accessible error after setting up github oauth even if I use the registration token. See sequence of steps below. The curl works from inside a running rancher agent container as well as from host.

	docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://104.236.12.86:8080/v1/scripts/AE6F757B8475E1CDF8ED:1425265200000:nWQ1Uqsf3XBdYHK0hPQgAJHZIq0
	INFO: Attempting to connect to: http://104.236.12.86:8080/v1
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible

	curl http://104.236.12.86:8080/v1/scripts/C7AB12D134CFB0EBEAC3:1425265200000:0WudVGMxIUIjk3nH3GVyOVG0s
	#!/bin/sh

	export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
	export CATTLE_REGISTRATION_SECRET_KEY="C7AB12D134CFB0EBEAC3:1425265200000:0WudVGMxIUIjk3nH3GVyOVG0s"
	export CATTLE_URL="http://104.236.12.86:8080/v1"
	export DETECTED_CATTLE_AGENT_IP="104.236.224.92"

**Comment by cloudnautique** [comment]
The latest rancher/agent should be able to register with auth enabled.

**Comment by feliksik** [comment]
I unfortunately believe it is still flaky... it did work, but now stopped working. Still with the "not accessible" message, although the given url gives a nice list of 'export CATTLE' settings. 
Do note that I started the agent with  -e CATTLE_AGENT_IP=172.31.2.1  , and that the /v1/scripts/$KEY response body gives
export DETECTED_CATTLE_AGENT_IP="95.128.x.x". This does not necessarily mean it cares about this detected IP, right?

**Comment by ibuildthecloud** [comment]
If you've passed in the IP with CATTLE_AGENT_IP the detected one is not used.

**Comment by usmanismail** [comment]
That 172 address looks like the docker0 interface IP instead of the host one so this would only work if the agent was on the same node as the server

**Comment by feliksik** [comment]
@usmanismail : Yes it indeed looks like that, but in this case docker0 was on 172.16.x.x, and 172.31.x.x is a VPN

**Comment by deniseschannon** [comment]
@usmanismail With the updates in Rancher, I don't believe this should still be an issue. I'm going to close it. If you still have an issue with this, please re-open.

**Comment by munjalpatel** [comment]
I am still having the same issue.

**Comment by deniseschannon** [comment]
@munjalpatel Can you provide more details on:
1. Your set up? Rancher version? Are you running rancher server and agent on the same host? If so, did you connect your host following these directions: http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost

**Comment by feliksik** [comment]
I have this again: 

- rancher agent 0.8.1 -- Docker version 1.7.1, build 786b29d
- rancher server image id f829869b8e9d (2 weeks old now) -- Docker version 1.6.2, build 7c8fca2-dirty

server logs say (note we have both exit code 143 and 137)
```
2015-09-07 20:17:50,803 ERROR [:] [] [] [] [torService-6597] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [143] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 17141 Terminated              ${CATTLE_HOME}/config.sh "$@"
] 
2015-09-07 20:17:51,914 ERROR [:] [] [] [] [torService-6588] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [137] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 17355 Killed                  ${CATTLE_HOME}/config.sh "$@"
] 
2015-09-07 20:17:51,915 ERROR [:] [] [] [] [torService-6602] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [137] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 17353 Killed                  ${CATTLE_HOME}/config.sh "$@"
] 
2015-09-07 20:17:51,916 ERROR [:] [] [] [] [torService-6602] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [137] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 17349 Killed                  ${CATTLE_HOME}/config.sh "$@"
] 
2015-09-07 20:18:00,886 ERROR [:] [] [] [] [torService-6560] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [143] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 19067 Terminated              ${CATTLE_HOME}/config.sh "$@"
] 
2015-09-07 20:18:00,889 ERROR [:] [] [] [] [torService-6476] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [
configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:5], exit code [143] outpu
t [/var/lib/cattle/common/scripts.sh: line 76: 19666 Terminated              ${CATTLE_HOME}/config.sh "$@"
```


client logs say: 
```
(...)
INFO: docker info: ID: DBHU:IA74:OMHF:EHT7:YDWS:26WM:UTU6:APAA:DSFZ:JSLB:FY7V:QSKV
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://demo.feliksik.com/v1
ERROR: http://demo.feliksik.com/v1 is not accessible
ERROR: http://demo.feliksik.com/v1 is not accessible
ERROR: http://demo.feliksik.com/v1 is not accessible
client@vm-test-1:~$ curl http://demo.feliksik.com/v1
{"id":"b67d6fd3-90fe-42c6-ac7a-7bfc43981186","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
client@vm-test-1:~$ 

```

Please reopen.

**Comment by Edenshaw** [comment]
Still is happening to me

**Comment by Edenshaw** [comment]
I solved it :) 

I didn't have to disable Access Control, my problem was with the certificate and NGinx :s 

The problem was with the chain of validation of the certificate. Since I was also configuring a Docker registry server, in their tutorial they explained that it's important to bundle both certificates in case you face any problem.

It would be nice that this should be added to the documentation of rancher (SSL installation)

The solution:

* Concatenate the primary certificate and intermediate certificate:

You need to concatenate the primary certificate file (your_domain_name.crt) and the intermediate certificate file (IntermediateCA.crt) into a single pem or crt file by running the following command:

`cat your_domain_name.crt  IntermediateCA.crt >> bundle.crt`

Also (another clue to catch the problem) if you use curl, it should work without the -k parameter, and the validation of the certificates should return that everything is ok.

**Comment by magsol** [comment]
I am still receiving this error, but have not configured any server certificates (no SSL communication).

**Comment by Edenshaw** [comment]
Hi @magsol, can you provided the following information please:

- Is rancher and the host on the same machine? 
- The logs of the container
- If you try to use curl, what is the output of that command?

Best

**Comment by magsol** [comment]
@Edenshaw Host and Rancher server are physically distinct machines. Container logs for the Host:

```
[squinn@oneill ~]$ sudo docker logs c86

INFO: Running Agent Registration Process, CATTLE_URL=http://atlantis.cs.uga.edu:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.1
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.1
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.4
INFO: docker version: Git commit (server): 5604cbe
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 3
INFO: docker info: Images: 94
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-253:1-914074-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 107.4 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 6.861 GB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 100.5 GB
INFO: docker info: Metadata Space Used: 10.22 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.137 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.107-RHEL7 (2015-12-01)
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 3.10.0-327.4.4.el7.x86_64
INFO: docker info: Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
INFO: docker info: CPUs: 12
INFO: docker info: Total Memory: 125.7 GiB
INFO: docker info: Name: oneill.cs.uga.edu
INFO: docker info: ID: UY4Y:FFB5:T6BB:TGIN:WRKX:KBXL:DX2Z:WE23:NOAT:LIME:4ZPR:OBHV
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://atlantis.cs.uga.edu:8080/v1
ERROR: http://atlantis.cs.uga.edu:8080/v1 is not accessible
```

Output of curl:

```
[squinn@oneill ~]$ curl http://atlantis.cs.uga.edu:8080/v1
{"id":"61075094-3b89-4f11-9468-13e9eac002e3","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
```

**Comment by magsol** [comment]
Both Host and server run identical versions of Docker and RHEL 7, and I just upgraded the Rancher server to 1.1.0-dev2.

**Comment by Edenshaw** [comment]
Have you tried to reset some elements of docker (on the host) in order to re-try adding the host?

The elements I'm talking about are:

`sudo rm -rf /var/lib/rancher/state; sudo docker rm -fv rancher-agent; sudo docker rm -fv rancher-agent-state`

**Comment by magsol** [comment]
Huh! That first command did it! (the `rancher-agent` and `rancher-agent-state` weren't up) Thanks!

**Comment by Edenshaw** [comment]
Great, glad it worked

**Comment by rokka-n** [comment]
This problem is still alive and well. If the CATTLE_URL generated with https - agents can't register, logging "not accessible". They work fine with http type of URL.

**Comment by cloudsyjared** [comment]
Anyone coming from Google, hopefully you read this.

If you just setup Rancher and an NGINX reverse SSL proxy, you may be struggling to get the agent up and running on the master server.

https://github.com/rancher/rancher/issues/136#issuecomment-219436447

If you generated certificates like I did using letsencrypt, you need to stick the whole chain in NGINX, not just the cert.pem file

```
# ls
cert.pem  chain.pem  fullchain.pem  privkey.pem
```

So, for nginx config, you will use cert.pem as the key, and fullchain.pem as the cert. Cheers.

**Comment by m3talstorm** [comment]
I had the same issue:

Both the rancher server and agent installed on the same (Ubuntu:16.10) VM, the hostname of the VM was not resolveable in DNS, so under the admin->settings->'Host Registration URL' I selected 'Something Else' and typed in http://<IP address>:8080 (for now). Then go and add the host again, you have to grab the full docker run command including the long key at the end because it seems to be regenerated when the IP changes (?)
