### ISSUE TITLE
Can't connect my custom agent

### ISSUE THREAD

**Issue by Artenac2** [rancherio/rancher#1360]
I run my rancher server with the command: 
$ docker run -d -p 8080:8080 rancher/server

I use RHEL 7.1 and my docker version is 1.6.0.

When i go on my UI and i try to connect my agent. He can't connect to my hosts.

I go in logs of the agent and it block at this following line: 

INFO: Downloading https://github.com/rancherio/host-api/releases/download/v0.17.0/host-api.tar.gz current=

or at this one too : 

[scripts.sh:45] curl -s --connect-timeout 60 --retry 2 -L --retry 5 'https://github.com/rancherio/host-api/releases/download/v0.17.0/host-api.tar.gz?current='

He always loop with the same thing, and it can't download this files.

I tried to find a solution but nobody has my error. So if someone has a solution.

**Comment by Djiit** [comment]
Hi there, same error on CoreOS alpha (723.1.0). It loops undefinitely.

**Comment by Djiit** [comment]
If it can help, I just change networkd config with the right DNS server and that was OK for me.

**Comment by Artenac2** [comment]
It's works, thanks ! :)

**Comment by Djiit** [comment]
You're welcome !
