### ISSUE TITLE
Integrate Hipache in UI

### ISSUE THREAD

**Issue by moimael** [rancherio/rancher#1367]
It could be really usefull to integrate something like Hipache in Rancher UI.

It would allow to have multiple service on e.g port 80 and proxy them by name (like apache namevirtualhosts, maybe haproxy can do that)

Thanks !

**Comment by vincent99** [comment]
We are working on adding Host header and Request URI-based routing to the balancer, and then SSL termination.  (haproxy can do all of them)

Please follow #544 for updates.
