### ISSUE TITLE
Service on Host with certain label(s)

### ISSUE THREAD

**Issue by qrpike** [rancherio/rancher#1400]
It would be great if I could put my LB services on a particular host(s) with a label being: role=lbs. Reason being my DNS points to a particular public IP, so if this LB service moves, I'm kinda screwed. Since the LB proxys my service to the other hosts, its position doesn't really matter.

Is this possible? I've looked just about everywhere and couldn't find a solution.

Thanks!

**Comment by vincent99** [comment]
Regular services support this in the scheduling tab, but load balancer ones do not yet.  Please subscribe to #1305 to follow.
