### ISSUE TITLE
latest ui.js definition bug? 

### ISSUE THREAD

**Issue by sepiroth887** [rancherio/rancher#1427]
This morning my rancher UI won't load. Thought it was the nginx config, but it's not. JS throws an exception while loading ui.js: 

`Uncaught ReferenceError: Ui is not definedt @ lookup.js:17(anonymous function) @ ember.prod.js:4319(anonymous function) @ ember.prod.js:4345t @ ember.prod.js:2223n.topsort @ ember.prod.js:2334s.default.extend._runInitializer @ ember.prod.js:4344s.default.extend.runInitializers @ ember.prod.js:4316s.default.extend.boot @ ember.prod.js:4233s.default.extend.domReady @ ember.prod.js:4219a.run @ ember.prod.js:222a.join @ ember.prod.js:261u.join @ ember.prod.js:19060u.bind @ ember.prod.js:19123J.Callbacks.c @ jquery.js:3099J.Callbacks.d.fireWith @ jquery.js:3211J.extend.ready @ jquery.js:3417o @ jquery.js:3433`

**Comment by sepiroth887** [comment]
the ui.js file is located here: https://releases.rancher.com/ui/latest/assets/ui.js

**Comment by sepiroth887** [comment]
reverting back to 0.29.0 via rancher env args makes it work again.

**Comment by ibuildthecloud** [comment]
@sepiroth887 Will fix shortly thanks

**Comment by vincent99** [comment]
I've reverted the last commit for now, but @sepiroth887 you generally shouldn't be using `latest` unless also using an up-to-date `master` of all the other repos in rancher.  We don't intentionally break it but QA starts looking once things land in `latest`.

It also sometimes includes changes that require corresponding backend that are only in rancher/cattle master and will be included in the next week's release (this will happen this week, the service linking and load balancer APIs changed).
