### ISSUE TITLE
How can I lookup my cattle access key and secret key?

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#143]
The API docs give a curl command for the various actions but use placeholder variables for Cattle Access Key and Secret Key. How can I lookup these keys for my rancher server?

**Comment by sidharthamani** [comment]
http://rancher.io:8080/v1/apiKeys is the API to do that

**Comment by vincent99** [comment]
You can create a key in the API tab of the UI.  (`/v1/apikeys` works too, but you can't get there without already having an API key if GitHub auth is setup :smile:)
