### ISSUE TITLE
Port Mapping not working correctly on localhost

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#147]
If I use "Managed Network on Docker 0" My ports will not get exposed to the host machine then the ports are not exposed at all.

    9099ebb55a2d        ubuntu:14.04.1                  "/bin/bash"            About a minute ago   Up About a minute                                                  e28f166a-f486-4638-a289-267a937767a8

If I use Unmanaged Network port is exposed but not to the hostmachine
![screen shot 2015-03-04 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/204682/6490918/b213ba96-c277-11e4-8720-27fba1fe2507.png)

    3854e42ebc74        ubuntu:14.04.1                  "/bin/bash"            47 seconds ago       Up 46 seconds       6666/tcp                                       6843b19c-d1d5-41f1-b862-108e99f80a3d

**Comment by vincent99** [comment]
Try {Host IP}:7777, it should work.  Port mapping for managed networks is managed us and dynamic (you can click edit on the container to change the mapping).  The Docker CLI just does not know about this.

**Comment by usmanismail** [comment]
Ah, so localhost:7777 does not work and {Host IP}:7777 only works if requested from a different host. i.e. the forwarding is not working over the loopback interface. I need this feature because I have a set of services which call each other but they may or may not be on the same compute node. Linking isn't really an option as there is birectional communication in some use cases.

**Comment by vincent99** [comment]
Hmm, @ibuildthecloud can we tweak the iptables routing to allow that?

**Comment by feliksik** [comment]
I just ran into this as well, as our client has an issue with this.

**Comment by ibuildthecloud** [comment]
In Rancher what we do for our "managed network" is that we don't enable ports in Docker but instead manage the iptables rules ourselves.  This allows us to do dynamic port changes until Docker gets this functionality.  As a result this break localhost access.

The way Docker gets localhost access to work is that they launch a user space proxy.  For example you will see the following process if you run `docker run -it -p 1234:1234 ubuntu`

`docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1234 -container-ip 172.17.0.102 -container-port 1234`

At Rancher we've tried very hard to never let our networking cross into user space.  As a result we didn't want to do the same user space proxy.  This leaves us with three options, I welcome your feedback which you think is correct.

1. Don't support localhost
2. Launch the same Docker user space proxy
3. Enable /proc/sys/net/ipv4/conf/all/route_localnet which allows us to create iptables rules to route localhost

I think 3 is the correct approach but if this is host that is not 100% dedicated to Docker I'm not sure what the impact could be.

**Comment by usmanismail** [comment]
Stepping back our actual use case is to allow bidirectional network access between containers. Not Supporting localhost access is probably acceptable for the majority of cases if exposed but unlinked ports were available inside all containers on the host. Maybe through a separate dedicated virtual interface. The semantics of port collision could could be kept the same as with docker, i.e. you cannot expose the same port from two containers on the same host. I know bidirectional linking is a bit of an anti-pattern but it comes up often.

**Comment by usmanismail** [comment]
@ibuildthecloud If I was to follow 3 after enabling local routing what IP tables rule would I use? I have tried a few combinations of to no avail

    iptables -t nat -A CATTLE_PREROUTING -m addrtype --dst-type LOCAL -p tcp
         --dport 3001 -j DNAT --to-destination 10.42.95.192:8080

    iptables -t nat -D OUTPUT -m addrtype --dst-type LOCAL -p tcp -o vethbff9ea9 
        --dport 3050 -j REDIRECT --to-ports 8080
