### ISSUE TITLE
Communicate machine progress

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#156]
When machine is creating it outputs stuff on the screen.  This should be communicated back to the user.  There probably needs to be a small amount of framework change for this.  The go-machine-server can reply to the request event with "transitioning" : "yes" and "transitioningMessage" : "Machine output...".

**Comment by cjellick** [comment]
For reference, also captured here https://github.com/rancherio/go-machine-service/issues/10

**Comment by deniseschannon** [comment]
As of v0.12.0, machine progress has transitioning messages displayed to the user.
