### ISSUE TITLE
Exposed ports not listed in UI (or docker)

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#159]
I have a large number of services in the same compute node hence I have to assign sequential ports to each service. I have not found anywhere in the UI which tells me which container is mapped to which external ports. 

docker ps is also not an option as rancher port mappings do no show up on the host when I do a docker ps.

**Comment by vincent99** [comment]
Closing in favor of newer but similar #198, since it includes all the other things the container details should show.
