### ISSUE TITLE
Authorization, additional users don't see host

### ISSUE THREAD

**Issue by indeyets** [rancherio/rancher#160]
We have a fresh Vagrant-based setup. A single host inside.

Administrator enabled access-control and authorized one of github-organizations for accessing. Administrator sees the host after he is logged in.

Everyone else in this organization can log-in, but can not see the host.

We didn't create any projects. Host is in "default" one

**Comment by indeyets** [comment]
Direct link to host results in additional authorization request and (after second round of oauth) 404 page

**Comment by vincent99** [comment]
We need to make this friendly.  What's happening is that "default" is not a single project...  The administrator and each individual user have their own independent "default" projects.  The host you've added belongs to the administrator's, so only they have access to it.  And there's currently no way to grant access to others to a "default" project.

If you want a host shared with several people (today), you need to first create a project owned by a team/org, then add a new host to that project.

Will update later with proposed changes..

**Comment by ibuildthecloud** [comment]
FYI @feliksik We will track the "make github and projects" more user friendly here.

**Comment by deniseschannon** [comment]
@feliksik and @indeyets - We are re-designing the authorization/project access experience in this issue: https://github.com/rancherio/rancher/issues/189 This doesn't change the fact that you will need to create a project before being able to share hosts, but will address the authorization/project access needs.

**Comment by vincent99** [comment]
You won't have to explicitly create a new project to do that (once #189 is done).  Hosts and Containers will only be allowed to exist within a project, and you'll be able to add additional users/teams/orgs to any project. (currently the "default" project is special, it's not really a project and the resources are owned directly by the user account)

**Comment by vincent99** [comment]
@feliksik @indeyets This should be in the 0.17 release tomorrow (and :beta/:latest shortly thereafter):

When you first install Rancher and use it with Access Control disabled:
  - A "default project" is automatically created 
  - You can create and use multiple projects
  - All hosts/containers/etc go now belong to a project (they are not owned directly by a user anymore)

When you turn Access Controls on:
  - The user who turns it on becomes the Admin.
  - Existing projects created wile Access Control was off will belong to the Admin user.
  - Any project (including the default one) can have multiple member and owner GitHub user/team/orgs.
  - Members can see and use all the resources of a project.
  - Owners can change the project, add/remove members/owners, and delete the project.
  - The Admin user (who turned Access Controls on) can always see/manage/delete *all* projects.

**Comment by tfiduccia** [comment]
v0.18.1
Verified fixed
