### ISSUE TITLE
Private registry nitpicking

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#164]
- [x] Rename registryCredenatial.storagePoolId -> registryId
- [x] {registryCredential,registry} should be DELETE-able (resourceMethod "DELETE" in schema)
- [x] registryCredential.{publicValue,secretValue,email} seem like they should be editable

**Comment by hibooboo2** [comment]
@ibuildthecloud Comments before i start?

**Comment by hibooboo2** [comment]
Based on discussions in past with @ibuildthecloud and @cjellick 

* registryCredential should not be editable like and ssh key. You just delete and make a new one.

**Comment by ibuildthecloud** [comment]
I agree, do that :)

**Comment by vincent99** [comment]
I don't know if the API framework easily allows all these, but in the response to `GET /v1/registries/:id/credentials`:
  - The `resourceType` should be `registryCredential`, not `credential`
  - `createTypes` should only contain `registryCredential`
  - `createDefaults` should be populated with `registryId: ":id"`

**Comment by vincent99** [comment]
Also `GET /v1/registries/:id/credentials` doesn't appear to actually work, though `GET /v1/registries?include=credentials` does.

**Comment by vincent99** [comment]
Ping @hibooboo2 can you look at the outstanding parts of this?  The resourceType/createTypes/createDefault ones aren't that important, but `GET /v1/registries/:id/credentials` should really be fixed.

**Comment by vincent99** [comment]
I think `GET /v1/registries/:id/credentials` is probably the same as #395..
