### ISSUE TITLE
Authentication page redirects to 404

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#167]
If you create a project and select it (hosts view) and then go to access control (top-right button), you get 404. If you first select Default project, it works fine.

**Comment by deniseschannon** [comment]
@vincent99 Since we're fixing up the top menu, can we try to get this fixed with those changes?

**Comment by vincent99** [comment]
This should work with new projects..

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
