### ISSUE TITLE
rancher-proxy: terminal input does not work 

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#168]
I set up rancher-proxy (awesome!). The resource utilization is shown, and if I start a terminal for a proxy, it is shown with the hostname. Bottom of the modal window says "Connected". Everything looks fine. 

When I start typing, nothing happens. So the terminal function cannot be used.

**Comment by ibuildthecloud** [comment]
I will troubleshoot this.  Just to confirm.  The console pops up, you see a command line, but typing fails?

**Comment by ibuildthecloud** [comment]
I've been able to reproduce this.

**Comment by ibuildthecloud** [comment]
Fixed in rancher/host-proxy:v0.2.0.  The websocket messages were only be successfully copied in one direction, but not both.
