### ISSUE TITLE
After creating projects, it remains on the "Manage Project" page, it's confusing to figure out how to get to the new project space.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#190]
When you create a new project, it remains on the "Manage Project" page and the shown project in the drop down menu is whatever project that you were last in. 

![screen shot 2015-03-11 at 2 20 43 pm](https://cloud.githubusercontent.com/assets/11410997/6607145/d912c326-c7f9-11e4-93e5-b6a173404dfe.png)

In my screenshot, I had just finished creating testproject4. In the projects drop down, it shows testproject2. As a new user, it's not intuitive on how to get to my new project space.

Option 1: After creating a new project, immediately set the drop down menu to the new project space. You can either have the page refresh to the new project with the Hosts page showing OR remain on the Manage Projects page. 

Option 2: Have the project names on the project page be links so that it would automatically pull up the project page. This would another way to pull up projects instead of having to use the drop down. As a user,  you would know that by clicking on that link, it would automatically exit you out of the "Manage Projects" page into the project.

Option 3: Have an option in the project drop down (currently only has Edit and Delete) to "Go to Project" or something of that nature.

**Comment by vincent99** [comment]
Projects have a "Switch to this project" action now.  Also the Project dropdown is a little more prominent:  

![image](https://cloud.githubusercontent.com/assets/753917/7265458/336883a4-e84f-11e4-8470-9bef2c74dd85.png)

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
