### ISSUE TITLE
[UI] [Hosts] Weird UI for deactivating/deleting host that was already deleted in Digital Ocean.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#195]
I had killed my machine in digital ocean and the host shows up in Rancher as "Reconnecting". When I deactivate and delete, the status of the host has updated correctly, but the spinning gear and status bar indicate that it's still trying to do the last action. 

See the screen shot and the host's named "host2" and "gcehost2".

We need to improve the UI to show that we couldn't reach the machine. Either stop the spinning gear/status bar after we have failed to reach the host or show some other icon to indicate that the host can't be connected to it.

![screen shot 2015-03-12 at 1 30 37 pm](https://cloud.githubusercontent.com/assets/11410997/6627542/12d0febc-c8bc-11e4-9f44-e808f2ff2ee9.png)

![screen shot 2015-03-12 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/11410997/6627545/15204998-c8bc-11e4-84e0-9628af94b7bf.png)

**Comment by vincent99** [comment]
Need to look at the API entry for that host & machine.  If they're transitioning="yes" then the UI is "correct" and the state is wrong in the backend.

**Comment by deniseschannon** [comment]
Transitioning="no". When I tried to replicate the scenario, it took awhile before it got to the "inactive" state and transitioning="no". It started as "Deactivating" and transitioning="yes" and finally ended up in this state.

![screen shot 2015-03-12 at 12 22 58 pm](https://cloud.githubusercontent.com/assets/11410997/6626278/b1566c98-c8b2-11e4-9967-e39330cb84a1.png)

**Comment by steviee** [comment]
Hi,

you probably should not post public IP addresses.

Best regards,
Stevie

**Comment by deniseschannon** [comment]
Thanks @steviee for the suggestion. I've updated the comment with just the host images.

**Comment by vincent99** [comment]
@deniseschannon Can you get a host into this state and send me the IP via Slack to look at?

**Comment by vincent99** [comment]
@deniseschannon Can you still reproduce this?

**Comment by deniseschannon** [comment]
No I haven't seen it recently. I will re-open if I see it again.
