### ISSUE TITLE
What should happen with containers on deactivated hosts?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#197]
When I deactivate a host that has containers running on it, the containers page still shows that the state of the container as "running". 

Should it remain as "Running" or go to a different state to indicate that the host is not up?

If I attempt to Restart the container on the deactivated host, the container state on the container page shows up as "Stopping" and on the deactivated host, the gear and status bar are spinning for that container and shows "In Progress." 

![screen shot 2015-03-12 at 2 26 44 pm](https://cloud.githubusercontent.com/assets/11410997/6628603/2146c348-c8c4-11e4-9d30-72b06ff85207.png)

**Comment by vincent99** [comment]
(pre-dates, but) duplicate of #224.  `inactive` should just mean that new containers are not scheduled to that host, actions on existing containers should continue to work (but don't currently).
