### ISSUE TITLE
adding images from private repos

### ISSUE THREAD

**Issue by rydn** [rancherio/rancher#2]
Is it possible to create a container using a image that is kept on a private docker repository? At present when I try to add one I am told that the image format is invalid or something to that effect.

**Comment by dublx** [comment]
+1

**Comment by andreis** [comment]
+1

**Comment by brycekottke** [comment]
+1

**Comment by zbyte64** [comment]
:+1: :) Can't wait for #81

**Comment by gseven** [comment]
+1

**Comment by ibuildthecloud** [comment]
Here's an update on this issue.  The backend work will be done on Wednesday and the corresponding UI changes will be available the following Wed using the rancher/server:beta tag

**Comment by indeyets** [comment]
@ibuildthecloud this one is not bound to milestone, so… is it delayed?

**Comment by ibuildthecloud** [comment]
The first cut of the UI is now available in the rancher/server:beta tag.  The backend in that build was not really complete, but has since been merged to master.  We will probably cut another beta release today and expect to make it available as rancher/server:latest

**Comment by ibuildthecloud** [comment]
(Oops, comment and close buttons are far too close on a phone)

3/18 we expect private repos to be available as the latest tag.

**Comment by vincent99** [comment]
There will be further improvement coming to the UI, but private registry support is in last week's :latest release.

**Comment by buzted** [comment]
but where to set it up? i dont see an option for private images during the "add new container" process
