### ISSUE TITLE
Feature Request: Authentication

### ISSUE THREAD

**Issue by albertrdixon** [rancherio/rancher#20]
Nothing fancy, no accounts or preferences, just:

* UI - username/password.
* API - tokens

idk, maybe store these in a JSON file on the host? So something like: `$ docker run -v /opt/rancher/auth.json:/auth.json rancher/server`

Just thinking it might be nice to have the option of exposing externally rather than only available through VPNs and the like. Auth might be nice over VPNs anyways to keep pesky coworkers / family members / developers out.

**Comment by deniseschannon** [comment]
GitHub Authentication has been completed and API tokens added in if authentication is turned on. @albertrdixon The latest version has these features. If you feel as if it's not complete, please re-open.
