### ISSUE TITLE
[Machine] When creating Digital Ocean machines, the name and access token needs to follow the Digital Ocean requirements for name.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#204]
If the name/access token of the machine aren't valid in Digital Ocean, the machine still attempts to be created with no error messages. 

Couple of things can be updated to make the user experience better.

1. The UI could provide an error message if the name is not valid. Since there will be support for multiple cloud providers, I'm not sure if each provider has different validity for names of machines.

2. The UI should provide an error message if the access token is not the right length. Currently, nothing changes in the UI if the access token is not long enough. There is no attempt to create machine, but no indication of why the machine isn't starting to be created. An error message should appear indicating that the access token doesn't look valid.

3. During the creation of machine, we should have basic validation for name and access token. Any attempts to create machine that don't meet the requirements should be surfaced to the UI immediately. Examples include invalid name, invalid access token, potentially invalid/down region.

**Comment by vincent99** [comment]
Yes, the problem here is that every provider has different rules for everything and we will have no idea when they change.  Good errors would require API calls in rancher (or a generic proxy to each provider API) to actually talk to the provider before calling machine.  Machine itself has no way to do things like verify access credentials, list available regions/flavors/etc, or describe/test valid names.

Maybe this could be practical for the providers we consider "first class".

**Comment by cjellick** [comment]
I think we could have some reasonable "least common denominator" for host name, like alphanumeric + dashes, and a reasonable length.

Beyond that, the last major piece of "functionality" we need to implement is surfacing the errors that machine encounters up to the user. It's the second half of this issue: https://github.com/rancherio/go-machine-service/issues/10, which @will-chan did this past week.

@will-chan, if you're going to work on go-machine-service next week, I think this is the next most important thing to do. It will go a long way to improving the user experience.

**Comment by will-chan** [comment]
@cjellick I agree.  Error handling is next on my list.

**Comment by deniseschannon** [comment]
In v0.14.2, the error handling shows all these errors that were previously not shown.
