### ISSUE TITLE
rancher/server:beta, can't create host inside of a project

### ISSUE THREAD

**Issue by indeyets** [rancherio/rancher#206]
Trying `server:beta` because of custom registries support. Whenever I click "Register a new host" inside of a project I get "Error 404". It works fine for "default".

Under the hood it looks like request to `http://MY-IP-HERE:8080/v1/schemas/setting` which gets 404 encoded as json-document

**Comment by sangeethah** [comment]
We have a similar issue logged  - #185 - Add Host doesn't work when adding from Project View

**Comment by indeyets** [comment]
@sangeethah thanks. subscribed to that one
