### ISSUE TITLE
[Install] [Agent] When trying to launch agent with invalid management server ip address , the process hangs.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#208]
When trying to launch agent with invalid management server ip address , the process hangs.
I am not able to use control c to quit the process.

I am also not able to use any docker commands.

Following is the command (with invalid management server ip) I used to launch the process:
docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://http://104.154.94.20:8080

Expected Behavior:

The process should error out in such cases and not hang.

**Comment by deniseschannon** [comment]
By using the command in the UI (per https://github.com/rancherio/rancher/issues/267), the process will not hang.
