### ISSUE TITLE
Manage Projects UI issues (for non-project creators)

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#211]
Rancher Version: v0.11.1

I am accessing a project that was created by someone else. In my example screenshots, the actual owner was "RancherLabs". And I tried to change the owner to myself. 

When I click to Edit the project, it provides me UI to change the owner. If I try to select a different owner and click "Save". It doesn't save it (which is fine), but it just provides me with this error page. No message or reason of why I can't save. 

![screen shot 2015-03-16 at 1 15 24 pm](https://cloud.githubusercontent.com/assets/11410997/6676782/afd0203e-cbe7-11e4-860a-dd5a337b13be.png)

If I click on "Cancel", the UI will show the owner that I had tried to save and not the correct owner. If I refresh the "Manage Projects" page, it'll refresh to the correct owner.

![screen shot 2015-03-16 at 1 15 47 pm](https://cloud.githubusercontent.com/assets/11410997/6676707/35c1fd08-cbe7-11e4-9647-1f9545b2d835.png)

**Comment by hibooboo2** [comment]
This also seems to happen if you create a project yourself and then try to change the owner. It seem as if you just can't change owners.

**Comment by deniseschannon** [comment]
To clarify, @hibooboo2 is logged in as a user of the Rancher instance and not an admin. So the general statement would be if you are a user of the Rancher instance (not admin), you cannot edit the ownership of any projects (either ones created by yourself or ones that you have access to).

**Comment by hibooboo2** [comment]
Also seems that you cannot delete a project from the ui as well..  And yes @deniseschannon  That is correct.

**Comment by vincent99** [comment]
This should be better-er now with new projects

**Comment by tfiduccia** [comment]
v0.17.0
As a member you can no longer change any data in edit.
Verified fixed
