### ISSUE TITLE
[UI] [Private Registry] Refresh issues seen in "Private Registries" pages

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#214]
Version - V0.11.1

Refresh issues are seen in the following workflows:

1. In Private Registries page , Using "Add Private Registry" option , create a registry along with credentials.
When you are brought back to Private Registries page , the newly added registry shows "Credentials" as None even after having added 1 credential.

2.  In Private Registries page , Using "Add Private Registry" option , create a registry along with credentials.
When you are brought back to Private Registries page , follow the name link to get to the detail page of the registry that was added.
Credential details are missing in this view.

3. Use "Add a Credential" in the Private Registry detail page  to add credential to an existing registry. Once the user is brought back to the  Private Registry detail page , the credential that was added is not listed in this view.

**Comment by vincent99** [comment]
This is a bug in the API for `resource.change` events, the notification that the `registryCredential` has changed is being sent saying the type is `credential` (the parent type) when a credential is added, and there is no code in the UI to handle generic credentials changing so they never get added to the display.

**Comment by vincent99** [comment]
Fixed in rancherio/cattle#318

**Comment by tfiduccia** [comment]
Verified Fixed
