### ISSUE TITLE
[UI] [Container] Add container page lists  credentials in Inactive/removed/purged state

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#215]
Version - V0.11.1

Create a private registry with credentials.
Have the credential in Inactive/removed/purged state

When trying to create a container using "Add Container" option , credentials in Inactive/deleted/purged state are being listed.

Expected Behavior:
Only credentials in Active state should be listed

**Comment by vincent99** [comment]
Fixed in rancherio/ui#104

**Comment by tfiduccia** [comment]
Verified Fixed
