### ISSUE TITLE
[UI] [Private Registry] When deleting credentials for a private registry , the confirmation page has some random name assigned to the credential.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#216]
Version - V0.11.1

Create a private registry with credentials.
Have the credential in Inactive state and attempt to delete it.
Confirmation page that pops up has some random name assigned to the credential:

This is the content of the delete confirmation page:

Are you sure you want to delete:
1c22

**Comment by vincent99** [comment]
Every resource does this, if there's no name the ID is shown... can we combine with #210.

**Comment by sangeethah** [comment]
In this case , there is no way for us  to provide a name to the credential ? Should this be handled differently from the scenario where user has the ability to provide a name but had not provided it , which is the case in #210 ?

**Comment by vincent99** [comment]
Changed to show email and username (as available) in rancherio/ui#104

**Comment by tfiduccia** [comment]
Verified Fixed
