### ISSUE TITLE
Need ability to edit the username/password for Private Registry Credentials

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#217]
Version - V0.11.1

When the private registry credentials are created , there is no validation done on the username/password/email.

User may realize that there is a typo , once the credentials get used when creating containers and it fails.

Currently there is no way to edit the existing credentials. 
We are allowed to add another credential entry with the same user name. Is this the only way we want to accommodate for this use case?

**Comment by vincent99** [comment]
I remember we decided no, but not any good reason why... @wizardofmath?

**Comment by ibuildthecloud** [comment]
No we decided yes, but you can only edit username/password.  Not the registry id

**Comment by hibooboo2** [comment]
They are editable through the api, vincent just needs to create the ui for editing registry credentials.

**Comment by vincent99** [comment]
Registries allow editing a single credential in rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed
