### ISSUE TITLE
Purged credentials are listed in the "Private Registry" detail view.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#218]
Version - V0.11.1

Create a private registry with credentials.
Set the credential in Inactive state, delete it.
Credential is set to "Removed" state. Now purge this entry.
Once the  entry is in "Purged" state , there is no action that can be performed on this entry.So the list of actions available is empty. 

Should the Purged entries be hidden from this view ?

**Comment by ibuildthecloud** [comment]
We should probable change the life cycle of credentials.  Purge doesn't make any sense.  We should just have active, inactive, removed and the transitioning states.  You should be able to delete from active too.

**Comment by vincent99** [comment]
+1 for delete from active and less states

**Comment by vincent99** [comment]
The display of purged credientials is a bug in the API.. `GET /v1/registries?include=credentials` is returning purged items (#297)

**Comment by tfiduccia** [comment]
After purge, the registry is no longer showing up.

**Comment by vincent99** [comment]
This will not matter anymore with the upcoming registry simplifications..

**Comment by vincent99** [comment]
There is no longer a list of credentials in rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.21.1
Verified fixed
