### ISSUE TITLE
[UI] [Private Registry] [Container] Able to create a container with credential that is in Inactive state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#219]
Version - V0.11.1

Create a private registry with credentials.
Have the credential in Inactive state.

When trying to create a container using "Add Container" option , credentials in Inactive state is listed.
UI should not be listing this container . This bug is tracked in #215.

When I tried to use this credential for creating a container , we are allowed to use the inactive credential successfully to pull the image and start the container.

Expected Behavior:
Since the container is the Inactive state , we should expect the API to error out.

**Comment by vincent99** [comment]
Fixed in rancherio/ui#104

**Comment by tfiduccia** [comment]
Inactive credentials are not longer listed.  Verified fixed
