### ISSUE TITLE
Debian on GCE fails

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#22]
For some reason the arp proxying that Rancher uses does not seem to function on the default Debian images on GCE.  More investigation is needed here.

**Comment by cloudnautique** [comment]
@ibuildthecloud, is this still an issue?

**Comment by ibuildthecloud** [comment]
I believe so, I have not tried on Debian 7 again

**Comment by deniseschannon** [comment]
I just tested out the Debian GNU/Linux 7.8 (wheezy) amd64 with backports kernel and SSH packages built on 2015-05-26 and had no issues with launching and connecting Rancher.
