### ISSUE TITLE
[UI] [Container] If you start to add a container and leave the page, various settings are reset and others are not. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#221]
Rancher Version: v0.11.1

If I started to add a container and clicked out of the "Create Container" page, some options are reset while others are not.

Settings that are reset:
Name
Port Map
Command Tab: Command, User, Environment Vars
All options in the Volumes Tab, Networking Tab, Security/Host Tab

Settings that are not reset:
Select Image Location
Select Image Name
Command Tab: Console, Auto Restart

We should be consistent in resetting all options in the Advanced Options (i.e. Console/Auto Restart) on the "Create Container" page. It makes sense to keep the "Select Image" settings as what the user had previously used. 

Should the "Advanced Options" be collapsed every time you try to create a new container? This would have the user assume that all Advanced Options settings have been reset.

**Comment by vincent99** [comment]
Registry & Image not resetting was intentional, the rest should be reset.  Changed in rancherio/ui#109 (will be in v0.13.1 shortly):

- Console is reset to "-it"
- Auto restart set to 'never'
- Advanced is collapsed

**Comment by tfiduccia** [comment]
Memory Limit on the Security/Host Tab is not being reset.

**Comment by vincent99** [comment]
Fixed memory limit and entrypoint, I thinks that's all of them.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
