### ISSUE TITLE
[UI] [Container]  "Invalid Command" information on the UI doesn't disappear when I try to create a new container

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#222]
Rancher Version: v0.11.1

When creating containers, if I get an "Invalid Command" banner. I'm not exactly sure what is invalid due to the vague message. I also haven't been able to reproduce the message.

When I click on any other page and click back to the "Create Container" page (or push "Cancel") and then return to the "Create Container" page, the "Invalid Command" banner still shows up. 

The invalid banner should disappear when returning back to the "Create Container" page as all the options are being reset.

**Comment by vincent99** [comment]
This happens if you focus the command field and the leave it empty.. when you focus it the value that is saved in the model changes from null to an empty string, and the API rejects empty string.

**Comment by deniseschannon** [comment]
Okay, I've been able to reproduce so I get the Invalid Command banner.

When I cancel/exit the Create Container screen and click on "Create Container". The Invalid Command banner still exists even though my focus is defaulted back to "Name".

![screen shot 2015-03-17 at 1 55 47 pm](https://cloud.githubusercontent.com/assets/11410997/6697371/5bd8bede-ccad-11e4-9419-ab93815ea903.png)

When we click into the "Create Container", it should reset the page and remove the Invalid Command banner.

**Comment by deniseschannon** [comment]
Reproducing the issue will be fixed with https://github.com/rancherio/ui/issues/60

**Comment by vincent99** [comment]
Fixed the part where the error is still shown if you leave add container and come back in rancherio/ui#109 (will be in v0.13.1 shortly).  Empty string being an invalid command will be part of #239.

**Comment by tfiduccia** [comment]
Verified Fixed in v0.13.1
