### ISSUE TITLE
After removing the host from server, not able to add the same host to the same server version.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#225]
root@sangeetest-10acre-2:/home/sangeethahariharan1# docker stop 9ef8
9ef8
root@sangeetest-10acre-2:/home/sangeethahariharan1# sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://104.154.94.20:8080/v1/scripts/33CC57A21DDAF78C7A20:1426633200000:z8pgHPFDaQZsiCJgEFEywvwIA
9bea242e788d1dc7fac1cd287f9583946c246362bc60bc2ba7ca3b8a84f52907

**Comment by vincent99** [comment]
Did you remove it from the API too?  There is some state saved on the host in `/var/lib/rancher/state`, so when you re-run the agent I think you're trying to check-in as a host that has been marked as purged.  Try `rm -rf /var/lib/rancher/state`, then run the agent.

**Comment by sangeethah** [comment]
@vincent99  I see  /var/lib/rancher/state in the host . But this is an empty directory.
When I deleted this directory and re-ran the agent , I see that the hosts are being added to the server. 

Do we expect users to do this step manually , if they were to reuse a host that was removed from the server?

**Comment by vincent99** [comment]
@sangeethah It has hidden files (names starting with a dot) in it; `ls -al`.

@ibuildthecloud Can we clean up the state on remove (but how, since you've removed it and disconnected...) or make the registration script display a useful error telling you that this host has already been removed and how to zap the state to re-add it?

**Comment by vincent99** [comment]
Ping @ibuildthecloud can we make the registration offer to zap the state?

**Comment by cglewis** [comment]
`/var/lib/rancher/` doesn't exist on the server container, did the state folder move to somewhere else?

**Comment by vincent99** [comment]
It's still `/var/lib/rancher`, on the individual host (which is `10.123.92.10` for you in the other issue), not the `rancher/server` master.  There's a `state` folder in there with some dot-files, but you can just remove the whole `rancher` directory.

**Comment by cglewis** [comment]
@vincent99 ah, gotcha.  that worked, thanks!  also, I think that's probably fair for the most part, since if I had actually burned down that host and rebuilt it, I wouldn't have run into the problem.

**Comment by deniseschannon** [comment]
Verified fixed in v0.24.0-rc1
