### ISSUE TITLE
Not able to Execute Shell , View Logs and CPU/Memory Utilization for containers from project view

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#226]
Version - V0.11.1

Steps to reproduce the problem:

Create a project.
Log in to project view and create a container.
There is a bug #212 , that i am allowed to create a container in a host that does not belong to this project.

In the project view , I am able to list,stop,start,restart this container.

But not able to Execute Shell , View Logs and CPU/Memory Utilization for this container.
For Execute Shell and View Logs , i get a Error 404 Not Found.

When i try to view the details of the container , I see a "connecting..." string forever instead of CPU/Memory Utilization details.
![screen shot 2015-03-17 at 3 00 40 pm](https://cloud.githubusercontent.com/assets/4266958/6700212/e7004670-ccc7-11e4-9712-942a13f8ce47.png)

**Comment by sangeethah** [comment]
This container that belongs to the project is also listed in the Default view..
In this view , we are able to Execute Shell , View Logs and CPU/Memory Utilization for this container. This issue is seen only when in projects view.

**Comment by sangeethah** [comment]
This issue was created in the wrong repo. I have created  #226 in rancherio/rancher to track this issue.
Closing this issue.

**Comment by vincent99** [comment]
Open up the network tab of the browser's developer tools, but given that you created the container on a host that doesn't belong to you (#212) you're probably getting back an error when the API call is made to get the stats and then nothing is shown when it fails (#240).

**Comment by vincent99** [comment]
@deniseschannon Please update or close, if it's a container on a host you don't have access to then the backend should be rejecting you and I'm not very concerned about how the UI fails to not show you things you shouldn't have been able to create.  Is there a bug entered for being able to create a container on not-your host in the first place?

**Comment by deniseschannon** [comment]
@sangeethah filed this issue. @vincent99 Since projects is able to completely change, we need to wait until the new projects is merged to test if this still exists.

**Comment by vincent99** [comment]
Oops

This is really more the scheduler not restricting the host choice and not projects so it's probably still broken, but ok we can look with that.

**Comment by vincent99** [comment]
@sangeethah Can we close this in favor of #212?  I don't think we need to fix UI behavior for when you do something in what should be an impossible situation

**Comment by sangeethah** [comment]
Agreed @vincent99 . Closing this issue since we should never have to get into this situation of being able to launch containers in host that does not belong to you which is tracked in #212.
