### ISSUE TITLE
Container fails to start due to net-util.sh

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#23]
When you launch a container sometimes it fails with an obscure error involving `net-util.sh`.  This error is actually masking the real issue.  The container fails to start for some reason then the `net-util.sh` can not run because the container doesn't exist.  The typical error for why the container doesn't start is because `-it` is not currently (v0.2.0) supported from the UI.  If you try to run an image like `ubuntu` it will fail because it launches bash and assumes you have a tty or stdin open.

Two things need to be fixed

1) UI needs to support `-it`
2) `net-util.sh` needs to not mask the real error

**Comment by vincent99** [comment]
These were fixed sometime in the mysterious past..
