### ISSUE TITLE
Host icon is wrong when hosts register while on page

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#230]
If you are on the host view when a host is registered the icon is wrong. If you refresh the page it will be fine again.

![](https://cloud.githubusercontent.com/assets/1754002/5555135/6864281e-8c57-11e4-8d81-5623a08daa3a.png)

Related: rancherio/cattle#265

**Comment by tfiduccia** [comment]
v0.18.2
Verified fixed
