### ISSUE TITLE
[UI] Show Rancher managed containers differently than other containers

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#232]
Containers that are owned and managed by Rancher should be displayed differently, and should show a notice that you shouldn't mess with it unless you know what you're doing.

Related: https://github.com/rancherio/cattle/issues/136
Added to the API in rancherio/cattle#274

Related to https://github.com/rancherio/rancher/issues/187

**Comment by vincent99** [comment]
Managed containers are now hidden in rancherio/ui#105

**Comment by ibuildthecloud** [comment]
Totally hidden?  Or shown differently?

**Comment by vincent99** [comment]
...managed containers are now shown again, with gray text on the main host screen, and with the actions hidden, in rancherio/ui#106

**Comment by deniseschannon** [comment]
They are now grayed out with no drop down menu. This works for me.
