### ISSUE TITLE
Add validation against schema & input trimming to forms

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#239]
- [x] Trim user string inputs
- [x] Empty string on nullable fields should send null, not empty string
- [x] Validate field values against the schema
- [x] Report validation errors

**Comment by vincent99** [comment]
This is in this week's release,.  It's not perfect and there are probably a lot of fields that are missing constraints they could have in the schema, but it's a lot better than nothing.

**Comment by vincent99** [comment]
Missed assigning this over last week..

**Comment by tfiduccia** [comment]
v0.18.1
Verified fixed
