### ISSUE TITLE
Generate actions dropdown on demand instead of including on every item

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#241]
Currently each resource has it's own `<ul>` menu after the dropdown trigger. Much DOM nodes, very performant, wow.

**Comment by deniseschannon** [comment]
@vincent99 I must have copied this from the UI repo. Any idea what this means? :)

**Comment by vincent99** [comment]
@deniseschannon Yes.. Every menu for every resource is pre-rendered into the html right now.  It would be faster to just generate the one menu on demand when clicked.  Still relevant.

**Comment by vincent99** [comment]
The only way to verify this is by looking at the "Elements" tab of the dev tools, but this is done now.  Screens with a lot of resources that have dropdowns should be somewhat snappier.

**Comment by tfiduccia** [comment]
build from master - June 10th (afternoon)
Verified fixed.
