### ISSUE TITLE
In the detailed Container page, the host link doesnt work if you have accessed the shell

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#242]
Version: v0.11.1 

Steps to reproduce:
1. Start a container
2. Click on the container to go to its page
3. Click the execute shell button
4. close the execute shell dialog
5. click the < Container link in the top left.

Expected behavior:
Taken back to Container page

Actual behavior:
Execute shell dialog opens back up

**Comment by vincent99** [comment]
No more back buttons..

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
