### ISSUE TITLE
[UI] [Add Host] Is it possible to have the notch/pointer pointing to the selected Provider?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#245]
Version: v0.12.0

With the new Add Host page, when it first loads, as a user, it's not intuitive that the default showing is Custom and that I would need to/am able select the other providers logo to switch the instructions.

1. Can we move the Custom logo so that it's the first image? It's a bit strange that it defaults to the last image on the providers list. 

2. Can we have the notch/pointer that's under the images point to the images that is currently selected?  Here's a snapshot of the page and I created an arrow to point out the notch/pointer, I'm talking about.

![screen shot 2015-03-18 at 1 14 13 pm](https://cloud.githubusercontent.com/assets/11410997/6718453/081b493c-cd71-11e4-83f6-5c5b7f2ebf5b.png)

**Comment by vincent99** [comment]
1. DigitalOcean was supposed to be the default eventually.. changed in rancherio/ui#99

2. I'm leaning towards "no"?  We of course could, but there will likely be more drivers than fit on a single line soon, and then the arrow lining up with a box won't make as much sense.

**Comment by deniseschannon** [comment]
1. That's fine 
2. Can we remove the arrow then? Cause it appears as if should be pointing to what option you have selected?

**Comment by deniseschannon** [comment]
@vincent99 Should we remove the pointer/arrow? Since we only have 2 options right now, it looks like it should be doing something.

**Comment by vincent99** [comment]
@deniseschannon No?  That was the design from Nikita so we can ask her if you want, but it's exactly between the 2 choices and I don't think it's confusing.  (If anything it would be more confusing with an odd number of choices because it would be directly underneath the middle one)

**Comment by deniseschannon** [comment]
@vincent99 Spoke with Nikita and she is thinking that it will look less confusing when the UI is fixed so that the border of the icon is colored.

Created this issue: https://github.com/rancherio/rancher/issues/351
