### ISSUE TITLE
In final steps of creating machine, the state changes to Active and the transitioning state is turned off, but the static text is still making it seem like there are steps going on

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#250]
Version: v0.12.0

When the machine is all set up and complete, the state changes to "Active" and the transitioning states/messages are turned off. 

BUT the static text under the host name says "Waiting for host to check in". This makes it seem as if there are still steps to be done. 

Can we update the message to something else to indicate it's just waiting to get the host details? If that's what it's waiting on. I'm not exactly clear on what information it's waiting for.

![screen shot 2015-03-18 at 1 23 31 pm](https://cloud.githubusercontent.com/assets/11410997/6719238/719a6cd0-cd76-11e4-9ae6-5b057b65d6ec.png)

**Comment by vincent99** [comment]
There are still steps to be done...

At this point the Machine is active and it's lifecycle is done, so it's not transitioning anymore.  But a Machine with no Host is not really useful, so we're waiting for the agent that will have been started on the machine to make a requst to Rancher and cause a Host record to be created.  So it's sort of an odd situation where we're waiting for that to happen, but there's no resource with transitioning{Message,Progress} to watch.

**Comment by deniseschannon** [comment]
Is there a better static message we could put in? I know we use machine/host, but as a new user, I wouldn't necessarily know the exact differences between host/machine and it's a confusing message to me to the fact that we're waiting for host to check in, but the host looks active.

Could we change the static message to convey that we're just doing some final steps on our end?

'Final steps...' 
'Almost there...'

**Comment by vincent99** [comment]
Reminds me of
![image](https://cloud.githubusercontent.com/assets/753917/7288937/f93d48d4-e91d-11e4-92d6-7de530a86649.png)

**Comment by vincent99** [comment]
Changed to:

![image](https://cloud.githubusercontent.com/assets/753917/7844103/f1a778be-0462-11e5-8f8d-6eaf550b2fbb.png)

**Comment by deniseschannon** [comment]
Verified in v0.23.0-rc1.
