### ISSUE TITLE
DigitalOcean machine is stuck in "Bootstrapping" ("Installing Rancher agent") state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#251]
Version - V0.12.0

Registered a host - testnew1 using Digital Ocean.
When the host was still in the process of  being  created , Registered another host - testnew2 using Digital Ocean.
testnew2 machine got created successfully and went to "Active" state.

But the first host that was registered - testnew1 is stuck in "Bootstrapping" ("Installing Rancher agent") state forever.

![screen shot 2015-03-18 at 2 10 24 pm](https://cloud.githubusercontent.com/assets/4266958/6719676/8d341358-cd79-11e4-9440-f7fdd785dc33.png)

**Comment by deniseschannon** [comment]
With new Docker machine, this is no longer the case.
