### ISSUE TITLE
[UI] [Add Host] When loading on the Digital Ocean icon, focus on the Name text box.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#252]
Version: v0.12.0

In the Add Host page, when you click on the "Digital Ocean" icon or it opens in the "Digital Ocean" icon as selected, can we have the focus be on the "Name" text box so that the user could start typing in the box.

When it first loads up, it looks like this: 

![screen shot 2015-03-18 at 2 44 50 pm](https://cloud.githubusercontent.com/assets/11410997/6720149/6313cd80-cd7d-11e4-83a3-b687ac31c96d.png)

It should look like this so I could start naming it and tab down to create.

![screen shot 2015-03-18 at 2 44 39 pm](https://cloud.githubusercontent.com/assets/11410997/6720146/602793f4-cd7d-11e4-8b33-a18b5f5d186c.png)

**Comment by vincent99** [comment]
Added in rancherio/ui#99

**Comment by deniseschannon** [comment]
Fixed v0.13.0
