### ISSUE TITLE
[UI][Container] Execute Shell , View Logs and View in API options are missing. 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#256]
Version - V0.12.0

In Container view ,  Execute Shell , View Logs and View in API options are missing. 
![screen shot 2015-03-18 at 3 27 04 pm](https://cloud.githubusercontent.com/assets/4266958/6720744/460d138a-cd83-11e4-8cf9-cd792354f0f2.png)

**Comment by vincent99** [comment]
Fixed in rancherio/ui@75e3881
