### ISSUE TITLE
Username and password are not required parameters when creating a registry credentials

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#259]
Version - V0.12.0

username and password are not required parameters when creating a registry credentials.Only email is the required parameter.

Should username and password also be made required parameters ? May be email could be an optional parameter?

When i try to log in to quay.io using web , I can log in using username/password or email/password. This authentication mechanism could be different for different providers.

**Comment by vincent99** [comment]
@hibooboo2 Is there some case where you can login with just an email (no username and/or password)?

**Comment by hibooboo2** [comment]
So you are right all three can be optional, as there is no spec for required implementation of docker authentication from what i have read. But I am not 100% sure.

**Comment by vincent99** [comment]
More discussion in #921
