### ISSUE TITLE
[Install] [Server] FATA[0004] Error response from daemon: Cannot start container : no such file or directory 

### ISSUE THREAD

**Issue by lucker6666** [rancherio/rancher#26]
Server container start error

liang@liang-ubuntu:~$ sudo docker run -d -p 8000:8000 rancher/server
046ed8e413da7127c657a732d1f5901481436efa4ea9111440d224fce4481e3d
FATA[0004] Error response from daemon: Cannot start container 046ed8e413da7127c657a732d1f5901481436efa4ea9111440d224fce4481e3d: no such file or directory 
liang@liang-ubuntu:~$ sudo docker ps -a
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS               NAMES
046ed8e413da        rancher/server:latest   "/usr/share/cattle/c   20 seconds ago                                              fervent_turing      
liang@liang-ubuntu:~$ sudo docker start 04
Error response from daemon: Cannot start container 04: no such file or directory
FATA[0000] Error: failed to start one or more containers 
liang@liang-ubuntu:~$ sudo docker logs 04

**Comment by deniseschannon** [comment]
@lucker6666 Do you still need help with this? If so, please re-open as I'm going to close the issue.
