### ISSUE TITLE
[UI][Private Registry]  When email address is not passed when creating credentials in the "Add Private Registry" page , there is no error message and the page does not get dismissed.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#260]
Version - V0.12.0

Using "Add a Private Registry" option , create a private registry and a credential without email address (which is a required parameter).

No error message is presented to the user and the page does not dismiss itself either, Clicking on "Create" again does nothing.

The registry entry is actually created in this case without the credentials.

UI needs to do validation for the credential fields and present error message to the user , even before trying to create a private registry. Currently registry is created but credentials are not and the there is no notification of this failure to the user.
![screen shot 2015-03-18 at 6 09 02 pm](https://cloud.githubusercontent.com/assets/4266958/6722707/75b9ae3c-cd9b-11e4-9b89-db3030b93b5c.png)

**Comment by vincent99** [comment]
Fixed in rancherio/ui#104

**Comment by tfiduccia** [comment]
Verified Fixed
