### ISSUE TITLE
[ui][Private Registry][Credential] Add Credential page - Error message does not indicate why the validation failed when required fields are not entered.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#261]
Version - V0.12.0

When adding credentials to an existing private registry using "Add Credential" page do not enter emil address.
user is presented with "Validation failed" error message which is not very useful. It would be better to include the actual reason for the validation failure
![screen shot 2015-03-18 at 6 22 55 pm](https://cloud.githubusercontent.com/assets/4266958/6722759/40531156-cd9c-11e4-8774-9ba6e89e23bb.png)

**Comment by vincent99** [comment]
Changed in rancherio/ui#104 to show the field name ("Validation Failed: email").  #239 will add better validation in general to all forms to catch this before you've submitted to the API and gotten back an error in the first place.

**Comment by tfiduccia** [comment]
Verified Fixed
