### ISSUE TITLE
[UI][Private Registry][Container] Add Container - When selecting private registry that has only 1 credential, include information about the credential that is being used.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#262]
Version - V0.12.0

When adding container using private registry that has only 1 credential , currently there is no indication in this "Add Container" page about the credential that is being used.

It would be good to include information about the credential that is being used in this page.

**Comment by vincent99** [comment]
Added in rancherio/ui#104

**Comment by tfiduccia** [comment]
Email address and username for registry is showing.  Verified Fixed.
