### ISSUE TITLE
[UI][Container] - "Add Container" page shows empty entries for credentials when we have multiple credentials with only email address.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#263]
Version - V0.12.0

"Add Container" page uses username field to present the list of credentials to the user.
In case were we have multiple credentials with only email address , we see lot of blank entries for credentials and user will not be able to pick the right credential entry.
![screen shot 2015-03-18 at 6 33 41 pm](https://cloud.githubusercontent.com/assets/4266958/6722927/1110f064-cd9e-11e4-8fa2-51a6760bc79f.png)

**Comment by sangeethah** [comment]
This may not be an issue if we decide to have username as a required parameter for credentials. This issue is tracked in - #259

**Comment by vincent99** [comment]
Changed to show email + username, if present in rancherio/ui#104

![image](https://cloud.githubusercontent.com/assets/753917/6793913/a0d16dda-d188-11e4-83ed-4e6f32856c74.png)

**Comment by tfiduccia** [comment]
Verified Fixed
