### ISSUE TITLE
[UI][Container] - Confusing drop down menu for private registry selection for "Select Image".

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#266]
Version - V0.12.0

In "Add Container" page , drop down menu for private registry selection for "Select Image" shows the "address selected".But the dropdown has the name of the private registry which is confusing. Can we also include the "address selected" value along with the name of the private registry ?

![screen shot 2015-03-19 at 8 57 10 am](https://cloud.githubusercontent.com/assets/4266958/6734633/7a14115e-ce16-11e4-944e-701c0e9fdf67.png)

**Comment by vincent99** [comment]
Changed in rancherio/ui#104

**Comment by tfiduccia** [comment]
Verified Fixed
