### ISSUE TITLE
[Host] Installing Agent with Custom/Baremetal has different docker command for UI and for wiki

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#267]
Version: v0.12.0

Specifically, in the wiki, we use "--rm -it" and in the UI, it's not using those options and is using "-d". 

Command for setting up agent in the Wiki: 
docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://MANAGEMENT_IP:8080

Command for setting up in the UI:
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://107.170.224.57:8080/v1/scripts/1BE3E1C7EDD630FEF7CF:1426780800000:ks4QvYpemfbWwdzXUEOj5RFZgjs

**Comment by deniseschannon** [comment]
I suspect the changes between the UI and the Wiki may have been to address these bugs that have been filed. 

These issues were all using the wiki command. https://github.com/rancherio/rancher/issues/33, https://github.com/rancherio/rancher/issues/59, https://github.com/rancherio/rancher/issues/111, https://github.com/rancherio/rancher/issues/133, https://github.com/rancherio/rancher/issues/208

But the problem with using the UI command is that if the IP address is wrong/invalid, there will be no error message like the one filed in this bug. https://github.com/rancherio/rancher/issues/87

@ibuildthecloud Should we update the wiki and instruct users to use the command from the UI?

**Comment by vincent99** [comment]
Cattle generates the command that gets shown in the UI as of rancherio/ui@ec33962a1d2fc92b5288a6cb0e8e5e1395660043 , so removing UI label from this...

**Comment by ibuildthecloud** [comment]
@deniseschannon Yes, we should not have the registration command in any documents except the UI.  The README.md in rancherio/rancher needs to be updated too.

**Comment by deniseschannon** [comment]
I have updated the README.md to reference the UI to get the registration command.
