### ISSUE TITLE
[UI] [Host Setup] Host Setup page is not available after the initial setup

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#268]
Version: v0.12.0

With the updated "Add Host" page, the Host Setup page has no ability to be edited. 

Instead of putting it back in the "Add Host" page, could we create some kind of settings link in the UI to allow people to change the Host Setup page?

If we add it back in, we need to make sure that https://github.com/rancherio/rancher/issues/243 is fixed with the updated UI.

**Comment by vincent99** [comment]
Put into the user menu in rancherio/ui#101

![image](https://cloud.githubusercontent.com/assets/753917/6743900/b46bd930-ce5d-11e4-8b91-1446f5278b78.png)

**Comment by tfiduccia** [comment]
Verified Failed
