### ISSUE TITLE
User is given the option to create API keys when "Access Control" is not enabled for the server

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#269]
Version - V0.12.0

Can UI disable the option for creating a API key when "Access Control" is not enabled for the server , since there is no need for the API keys in the case?

**Comment by vincent99** [comment]
No?  They can be used while Access Controls are disabled, and will continue to work once it is enabled.

**Comment by sangeethah** [comment]
Closing this issue as per comments from @vincent99
