### ISSUE TITLE
[UI] [Projects] Projects are listed alphabetical in "Manage Projects" page, but not in dropdown menu

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#271]
Version: v0.12.0

Projects in the dropdown menu are organized by the sequence of when they are created. 

1. Should they be organized alphabetical as per the UI on the Manage Projects page?

2. Should we eventually have a search capability in the drop down in case a user has 100s of projects?

**Comment by vincent99** [comment]
Fixed in rancherio/ui#105

**Comment by tfiduccia** [comment]
Verified Fixed
