### ISSUE TITLE
[Containers]When container is created with Auto Restart set to "On failure, up to 5 times" , MaximumRetryCount is not set.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#273]
Version - V0.12.0

Create container with Auto Restart set to "On failure, up to 5 times" set.

When this container is examined with docker inspect command , following are the setting for RestartPolicy:

       "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "on-failure-cond"
        },

Max retry count is not set.

**Comment by sangeethah** [comment]
This seems to be UI bug. When i tried to use API to set the "MaximumRetryCount" parameter, it gets set on the container and docker inspect has this value set.

**Comment by vincent99** [comment]
Yes, the UI was never setting it in the restartPolicy sent to the API.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
