### ISSUE TITLE
[UI] [Container] If I stop and then start a container or restart a container, the dropdown icon remains visible.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#276]
Version: v0.12.0

When restarting or starting a container through the dropdown in the Hosts page, the dropdown icon doesn't disappear afterwards. All other options have the icon due to the refreshes/handling of background pages.

Note: After restart, the icon shows up sometimes but not others. I can get it on the stop/start of a container every time. 

![screen shot 2015-03-19 at 3 03 13 pm](https://cloud.githubusercontent.com/assets/11410997/6741964/153e7cd2-ce49-11e4-9dff-20d99cc08c47.png)

**Comment by vincent99** [comment]
@deniseschannon Can you still reproduce this?  The way the menu hovers is done was changed in the last release.

**Comment by deniseschannon** [comment]
@vincent99 Yes, I can still reproduce this in v0.16.0

**Comment by deniseschannon** [comment]
Just realized that Beta wasn't v0.16.0. It is fixed in v0.16.0.
