### ISSUE TITLE
Add ability to create new container from existing one

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#279]
Would like to be able to create a contain from a previously created container so I don't have to fill out all the same information again.

Should create container and be in create screen so I can change a field if I want to.

**Comment by deniseschannon** [comment]
This request would also fall along with https://github.com/rancherio/rancher/issues/221. 

Where we should create an option to clone/copy settings, but if you leave the container page, should all the settings be reset.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed - ability to  clone container feature added
