### ISSUE TITLE
Load Balancer Service

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#28]
### Overview

Load balancer is a key requirement for developers and ops who want to deploy large-scale applications. Load balancing support is notoriously uneven across different clouds. By offering a uniform, simple, and powerful load balancer solution, Rancher makes it possible for Docker developers to port applications easily across multiple clouds, or to use different cloud providers as independent resource pools to host highly available applications.

### Description

The basic flow of creating and using an HTTPS load balancer in Rancher is as follows:

1.	User uploads SSL certificates into Rancher
2.	User creates a load balancer using the uploaded SSL certificate
3.	Users adds Docker containers into the load balancer
4.	The system automatically monitors the amount of traffic going across the load balancer and can elastically boost its capacity as the traffic grows.

Rancher creates containers running HAProxy on Linux servers. The container listens on ports 80, 443, or other ports enables by the user and maps these ports to the ports on Linux servers. Linux server IP becomes load balancer VIP. Rancher monitors CPU, memory, and networking resources consumes by the HAProxy containers. Rancher monitors the load on HAProxy containers and automatically creates new HAProxy containers on additional Linux servers on demand.

Rancher load balancer service uses DNS-based load balancing to distribute traffic across multiple availability zones and across multiple HAProxy instances in the same availability zone. HAProxy instances are added into user’s DNS resolver. Rancher also automatically terminates HAProxy containers when load decreases. Once an HAProxy container dies, it is removed from the DNS resolver. DNS-based load balancing has the following advantages:

1.	It is much simpler compared with maintaining the same VIP across multiple hosts and multiple availability zones.
2.	It offers consistent failover behavior for global availability zone and local HAProxy container failures.

The advantages of DNS-based load balancing and complexities of traditional approaches to load balancing has led a lot of web companies to adopt DNS-based load balancing on their own. (https://www.loggly.com/blog/why-aws-route-53-over-elastic-load-balancing/)

### Background

It is useful to review the following documents which cover the basic concepts of load balancing and DNS failover:

1. [AWS Route 53 Developer Guide] (http://awsdocs.s3.amazonaws.com/Route53/latest/route53-dg.pdf)
2. [AWS Elastic Load Balancing Developer Guide] (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-dg.pdf)
3. [HAProxy Configuration Manual] (http://cbonte.github.io/haproxy-dconv/configuration-1.5.html)

#### CreateLoadBalancer

*CreateLoadBalancer* takes as input name of the load balancer, a list of listeners, a list of Linux servers used to host HAProxy containers, and returns a DNS name in the form of load_balancer_id.user_id.lb.rancher.io

Rancher internally uses AWS Route 53 service to host the DNS resolvers for *.lb.rancher.io

Because each Linux server has only one IP, each Linux server can only be used to create one load balancer.

The initial implementation may decide to create HAProxy on each Linux server and register them in DNS regardless of the load. The overhead of running a Docker container is small. This approach saves the effort of dynamically scaling up/down HAProxy containers.

#### CreateLoadBalancerListener

*CreateLoadBalancerListener* takes as input the following arguments:

* LoadBalancerPort
* BackendPort
* Protocol
* BackendProtocol
* SSLCertificateID

#### ConfigureHealthCheck

*ConfigureHealthCheck* must work both at DNS and HAProxy level. Refer to AWS ELB health check syntax for a possible design: http://docs.aws.amazon.com/cli/latest/reference/elb/configure-health-check.html

**Comment by nickschuch** [comment]
Will there be a separate project for this? I've been working on a load balancer myself (https://github.com/nickschuch/marco) and wouldn't mind reading through your code or collaborating.

**Comment by rancherio-gh-m** [comment]
The main thing we will be building is the orchestration of the load balancers in tandem with DNS.  Basically ELB+Route 53.  We won't be building the actual load balancer and was just going to go with HAProxy or Nginx.

I'll take a look at your project.  It would be nice if other people can plug in whatever load balancer/reverse proxy they want to use.  It's always good to see other projects and how they approach this problem.

On Jan 2, 2015, at 3:44 PM, Nick Schuch <notifications@github.com<mailto:notifications@github.com>> wrote:


Will there be a separate project for this? I've been working on a load balancer myself (https://github.com/nickschuch/marco) and wouldn't mind reading through your code or collaborating.

-

**Comment by ibuildthecloud** [comment]
The main thing we will be building is the orchestration of the load balancers in tandem with DNS. Basically ELB+Route 53. We won't be building the actual load balancer and was just going to go with HAProxy or Nginx. I'll take a look at your project. It would be nice if other people can plug in whatever load balancer/reverse proxy they want to use. It's always good to see other projects and how they approach this problem.

**Comment by nickschuch** [comment]
Absolutely, definitely wasn't trying to sell my project either. Just showing I have interest in the space :)

This sounds like an awesome feature!

**Comment by ibuildthecloud** [comment]
More information about this feature can be found here: https://github.com/rancherio/loadbalancer/wiki
