### ISSUE TITLE
[UI] Should the side bar colors for registries and API be the same?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#280]
The colors used for Private Registry and API are the same shade of blue or look almost the same.

Should they be different colors like how all the other items (host/container/volumes) are different?
![screen shot 2015-03-20 at 12 12 41 pm](https://cloud.githubusercontent.com/assets/11410997/6759082/9591c144-cefa-11e4-9454-755de999bb4d.png)

![screen shot 2015-03-20 at 12 12 50 pm](https://cloud.githubusercontent.com/assets/11410997/6759072/76a146ba-cefa-11e4-9205-94d996ff48a5.png)
![screen shot 2015-03-20 at 12 12 57 pm](https://cloud.githubusercontent.com/assets/11410997/6759073/77cf5af4-cefa-11e4-9288-64b3da8bb8ff.png)

**Comment by vincent99** [comment]
No but I don't have a different color from Nikita yet..

**Comment by vincent99** [comment]
Changed in rancherio/ui#103

**Comment by deniseschannon** [comment]
Fixed in v0.13.0
