### ISSUE TITLE
Container get removed after a minute if there is a problem with image name

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#282]
Create container with imageUuid docker:my-sql

Issue: Since the container gets automatically removed, if I am working on something else, it just disappears and I never see why.  It's very confusing.

Resolution: Don't do purge on the container, leave it in deleted/error state so I can still access log.  Don't allow restore on these containers.  Allow user to purge.

**Comment by vincent99** [comment]
This seems like it should follow the same behavior as `machine` resources now do, if there is an error creating they go into `state=error`.  The user can then manually delete, or use #279 to create a new container based on this one and fix whatever went wrong.

**Comment by vincent99** [comment]
This is discussed in the bigger-scope #384 and will go to error state when that is complete.
