### ISSUE TITLE
[UI] ISBAT select the host when I click on Create Container button on Containers page 

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#287]
On the Containers page, I can create a new container, but I cannot select which host it goes into.

I should be able to select the host.

Related #212

**Comment by deniseschannon** [comment]
It would probably make sense to have the ability to select 1 or many hosts.

Use case: someone wants to deploy multiple of the same type of containers on multiple hosts.

**Comment by vincent99** [comment]
@tfiduccia's request is fairly straightforward, we can just add a host dropdown into one of the advanced sections with a choice for "automatic".

Related is being able to set a quantity and deploy several at the same time

Deploying on "one of many" hosts is roughly Swarm/cluster support, which will be coming soon.  We could probably do "on all hosts of a cluster" with that too.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
