### ISSUE TITLE
[UI] In Container Details page the progress bar is over static text

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#290]
In container details page if i hit the restart button, the progress bar is on top of static text.

![screen shot 2015-03-20 at 5 58 59 pm](https://cloud.githubusercontent.com/assets/11514927/6763063/e9d09728-cf2a-11e4-9de7-99a2dbaddc32.png)

**Comment by vincent99** [comment]
Fixed in rancherio/ui#105

**Comment by tfiduccia** [comment]
Verified Fixed
