### ISSUE TITLE
[Ui/Api] Open api  ui with specified Apikey

### ISSUE THREAD

**Issue by hibooboo2** [rancherio/rancher#291]
It would be nice if we could open the api ui from the api key screen by just clicking on an api key so that we don't have to enter credentials.

**Comment by vincent99** [comment]
The secret key is only available at the time of apikey creation*, so there is no way for me to know what credentials to send (short of creating a new key pair every time).

(*: I know this isn't currently actually true and it is available, but it shouldn't be.)
