### ISSUE TITLE
[UI] Update account dropdown style

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#301]
![topright_interactions_userloggedin](https://cloud.githubusercontent.com/assets/753917/6814537/bbdc4f82-d23c-11e4-9b4e-372102c3a48b.png)
![topright_interactions_usernotloggedin](https://cloud.githubusercontent.com/assets/753917/6814538/bbde3342-d23c-11e4-84cc-c666a0e1104d.png)

**Comment by vincent99** [comment]
Changed in rancherio/ui#110

**Comment by tfiduccia** [comment]
v0.14.2
Verified fixed
