### ISSUE TITLE
When adding a new container (ie. doing docker pull) you must add :latest to the docker pull

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#304]
When adding a container, if a user specifies an image with no tag, the image name sent in the pull to docker must include the ":latest".  If you do not include the ":latest", all images with any tags are pulled and this takes forever and a lot of disk space.

**Comment by hibooboo2** [comment]
This bug no longer exists. Not sure when it did, but it is addressed. You can test your self, the code that ensures this is in [DockerImage.java](https://github.com/rancherio/cattle/blob/master/code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/client/DockerImage.java#L33)

**Comment by hibooboo2** [comment]
This bug no longer exists. Not sure when it did, but it is addressed. You can test your self, the code that ensures this is in [DockerImage.java](https://github.com/rancherio/cattle/blob/master/code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/client/DockerImage.java#L33) <@ibuildthecloud>

**Comment by deniseschannon** [comment]
Verified in v0.17.0
