### ISSUE TITLE
[UI] Colored bars under the menu items are not consistently showing up or hiding

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#305]
Version: v0.13.0

Under each menu item, there is a bar that sometimes has colors and sometimes not. I'm not sure what the design should be, but here are some screenshots.

Initial screen shot with no hosts.
![screen shot 2015-03-25 at 2 46 00 pm](https://cloud.githubusercontent.com/assets/11410997/6836268/d1da1d98-d2fd-11e4-9383-6ea6d464c9c2.png)

After clicking around the menu items with a host. 

![screen shot 2015-03-25 at 2 46 17 pm](https://cloud.githubusercontent.com/assets/11410997/6836272/d9a04142-d2fd-11e4-81d9-de6c1d2a119e.png)

After clicking on Containers/Volumes, then it removes the colored bar. 

![screen shot 2015-03-25 at 2 47 36 pm](https://cloud.githubusercontent.com/assets/11410997/6836293/085e7616-d2fe-11e4-8e07-f80c3e9a0c3d.png)

**Comment by deniseschannon** [comment]
Using chrome Version 41.0.2272.89 (64-bit)

**Comment by vincent99** [comment]
Fixed in rancherio/ui#108

**Comment by tfiduccia** [comment]
Cleared out cache and recheck and the bottom colored lines are not longer there.  Verified Fixed.
