### ISSUE TITLE
[UI][Private Registry] When creating credentials from "Add Credential" page , password is not saved.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#306]
Version - V013.0

Steps to reproduce the problem:

Create a private registry.

From Registry list view , open the registry view and use "Add Credential" page to add a new credential.
Try to create a container using this credential. Container fails to create because of not being able to pull the image.

password is not getting stored in credential table in "secret_value".

Following is the API request that is being sent from UI:
{type: "registryCredential", publicValue: "test555", privateValue: "test555", email: "test555",…}
email: "test555"
privateValue: "test555"
publicValue: "test555"
registryId: "1sp4"
type: "registryCredential"

**Comment by vincent99** [comment]
FIxed in rancherio/ui#108

**Comment by tfiduccia** [comment]
Verified fixed in V013.0

**Comment by deniseschannon** [comment]
@tfiduccia This is confusing that the version reported was v0.13.0 and it's fixed in v0.13.0. Is this actually fixed in v0.13.1?

**Comment by vincent99** [comment]
@deniseschannon No, this was found right after building v0.13.0; I cheated and changed the 0.13.0 tag to save Bill from re-doing the whole release process.  (I'll just stop doing that)  So it was found and fixed on two slightly different versions of 0.13.0.
