### ISSUE TITLE
When adding credential , there is no email format validation done for the email field.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#307]
Version - V013.0

There should be some basic email format validation check done when entering email for in Credential creation in "Add Registry" and "Add Credential" page.

**Comment by vincent99** [comment]
The field is called "email" but the registry can do whatever it wants with it and Docker does not require to actually be an email.

It's marked required in the API so you have to enter something in it now, but I don't want to get into does-it-look-like-a-valid-email when that isn't even a requirement from Docker.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
