### ISSUE TITLE
[UI][Private Registry] Adding an invalid image causes it to pull from the main Docker Hub

### ISSUE THREAD

**Issue by hany** [rancherio/rancher#308]
When trying to create a container from a private registry that does not exist or is invalid (for example, an invalid tag), after the addition fails, the error message seems to indicate it's trying to pull from Docker Hub:

Example URL: /static/containers/1i15

```
Removed
: 0aff729b-64b7-4ca7-9e70-1ca83df2b255 : Image [<INVALID IMAGE>] failed to pull : Error: image library/<INVALID IMAGE> not found
```

Further to this, trying to re-add a container with a proper tag, the process fails right away with the same error message, and it appears no requests are made to the private registry afterwards.

**Comment by ibuildthecloud** [comment]
Can you provide a specific example of an image name this failed with so that we can reproduce it?

**Comment by hany** [comment]
This only happens with a private registry. Unfortunately I can't open the
registry up to the public, however I suspect this affects all private
registries. If you can replicate, I can look into setting up a separate
private registry for testing.

Let me know.

On Thursday, March 26, 2015, Darren Shepherd <notifications@github.com>
wrote:

> Can you provide a specific example of an image name this failed with so
> that we can reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rancherio/rancher/issues/308#issuecomment-86407606>.
>


-- 

----
Hany Fahim
VM Farms
http://vmfarms.com
hany@vmfarms.com
1-866-278-0021 x700
Twitter: @vmfarms

**Comment by hany** [comment]
OK, this may actually be a UI bug. Doing some more testing, it appears that after attempting to create a container from a private registry, when navigating back to the `Containers` screen and trying to create another container, the `Select Image` drop down will already have the private registry selected, but any image you try to add will actually go to the main Docker Hub. If instead you click the drop down for `Select Image` to cycle back to `Docker`, then back to your private registry, it will actually fetch from it.

I hope this makes sense.

**Comment by sangeethah** [comment]
I am able to reproduce this issue. I will update the bug summary with [UI] tag to indicate that it is a UI issue.

**Comment by vincent99** [comment]
Fixed in rancherio/ui#109 (will be in v0.13.1 shortly)

**Comment by tfiduccia** [comment]
Verified fixed in v0.13.1

**Comment by vincent99** [comment]
@hany This is fixed if you re-pull `rancher/server:beta` or `rancher/server:v0.13.1` specifically.

**Comment by hany** [comment]
@vincent99 perfect, thanks folks!
