### ISSUE TITLE
[UI] [Container] launching new container has unclear error message: "Invalid: Undefined"

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#31]
Trying to launch a new container (ubuntu:14.04) with command /bin/bash but no specified user (it says "e.g. root" in grey) fails with the unclear error message "Invalid: undefined". 

It would be better to have an error like "you must specify a user".

**Comment by vincent99** [comment]
What's happening is if you focus the user field then the value in the model changes from null to empty string, which causes the server to send back:

```javascript
{
    "actions": {},
    "code": "MinLengthExceeded",
    "detail": null,
    "fieldName": "user",
    "id": "b8b40dc6-d1ef-4453-98f3-2a2564ebec59",
    "links": {},
    "message": null,
    "status": 422,
    "type": "error"
}
```

So the UI needs to make sure fields that are empty are null in the JSON, or the API needs to accept empty strings as not-defined.

**Comment by deniseschannon** [comment]
The "Invalid: Undefined" message has been fixed, but the remaining question is whether or not a user must be defined in order to run a command. I've logged a new bug for the remaining question. https://github.com/rancherio/rancher/issues/270
