### ISSUE TITLE
After adding a project, it remains on "Manage Projects" page with the new projects in "Registering" state. No refresh happens even though it's active. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#314]
v0.13.1

When I'm adding a project, the new project sits in "Registering" state and never gets updated/refreshed.

If I manually refresh the page, the project will show as "Active". 

![screen shot 2015-03-26 at 12 00 56 pm](https://cloud.githubusercontent.com/assets/11410997/6854645/cdfc1840-d3af-11e4-901c-628a95b3362c.png)

**Comment by deniseschannon** [comment]
I am logged in as a user to a Rancher instance and not as the admin.

**Comment by vincent99** [comment]
Normally a `resource.change` event is sent when something chnanges, but for projects it only works if you are the admin.  We knew this already so the UI tries to poll for changes on transitioning projects every 5 seconds, but it gets a 404 loading the project's self link (`/v1/projects/:id/`).  This should be fixable in #194.

**Comment by vincent99** [comment]
This should be better in new projects.

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
