### ISSUE TITLE
[api-ui] Null booleans

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#324]
@hibooboo2 created this issue in rancherio/api-ui.

You cannot create null booleans with the ui as it turns to false.

**Comment by vincent99** [comment]
I'm not sure if we have any actual examples of this in the API because it's usually a bad idea to have a nullable bool, but this was fixed in rancherio/api-ui@81d7e296caeb43cc8c1ec8a037fbd09124c32a87

**Comment by tfiduccia** [comment]
v0.14.2
Verified fixed in resourceType, githubconfig.
