### ISSUE TITLE
[Install] [Agent] When starting rancher-agent: FATA[0002] Error response from daemon: Cannot destroy container

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#33]
When you start the rancher-agent container, you see the following error:
```
FATA[0002] Error response from daemon: Cannot destroy container 446f0351cf1f378a6fc8d18fb220b453cb1e27812637e59bc337268ce4dfec05: Driver aufs failed to remove root filesystem 446f0351cf1f378a6fc8d18fb220b453cb1e27812637e59bc337268ce4dfec05: rename /mnt/sda1/var/lib/docker/aufs/mnt/446f0351cf1f378a6fc8d18fb220b453cb1e27812637e59bc337268ce4dfec05 /mnt/sda1/var/lib/docker/aufs/mnt/446f0351cf1f378a6fc8d18fb220b453cb1e27812637e59bc337268ce4dfec05-removing: device or resource busy
```
With different directory names, but you always get that error.
The error is misleading because the container ultimately starts fine.

Note that this is different than #26 but I suspect the two may be related. 

-----

$ docker info
Containers: 1
Images: 47
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 61
Execution Driver: native-0.2
Kernel Version: 3.16.4-tinycore64
Operating System: Boot2Docker 1.2.0 (TCL 5.4); master : 8a06c1f - Fri Nov 28 17:03:52 UTC 2014
CPUs: 8
Total Memory: 999.6 MiB
Name: boot2docker
ID: 3WJU:FUAI:G4QO:GPOQ:BHBV:NAII:MRO2:NMPG:MNWI:L5B2:SWXX:RVVM
Debug mode (server): true
Debug mode (client): false
Fds: 18
Goroutines: 18
EventsListeners: 0
Init Path: /usr/local/bin/docker
Username: ~redacted~
Registry: [https://index.docker.io/v1/]

-------
$ docker version
Client version: 1.3.1-dev
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 831d09f
OS/Arch (client): darwin/amd64
Server version: 1.3.1-dev
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 831d09f

-------
docker images rancher/agent
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rancher/agent       latest              61678f70cabd        2 weeks ago         271.2 MB

**Comment by Rjvs** [comment]
I'm having the same problem, with both v0.2.0 and v0.2.1.

$ docker info
Containers: 2
Images: 28
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 40
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 15.64 GiB
Name: machine
ID: M8VM:XHEO:5P5J:WTKX:IOWG:WEQQ:AXHQ:K5VH:OQI4:CDMB:DALR:Y6CO
WARNING: No swap limit support

$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by cjellick** [comment]
@Rjvs Sorry for delayed response! If you are having other problems, they may be different and this one may be just a red herring.

Note that the container that controls networking (will be using the rancher/agent-instance image) is not started until you start your first user container via the Rancher UI/API that uses the "Managed" networking option. 

Does the rancher-agent container stay up and running or does it keep restarting? If it stays up and running, it is likely configured and running correctly.

**Comment by deniseschannon** [comment]
By using the command in the UI (per #267), this warning no longer shows up. 

@Rjvs If you continue to have issues after trying the command from the UI, please feel free to open another issue.
