### ISSUE TITLE
rancher/agent on CoreOS

### ISSUE THREAD

**Issue by hany** [rancherio/rancher#338]
I realize this may not be the most popular OS to run Rancher on, but is there any docs or guidance on writing systemd unit files for running `rancher/agent`? Running the following container as instructed:

```
/usr/bin/docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 <URL>
```

Seems to launch their own containers and then exit, which conflicts with systemd.

Any help would be appreciated.

**Comment by ibuildthecloud** [comment]
CoreOS definitely is a supported distro.  Are you trying to the run the command from a unit file?  I could see how running from a unit file would definitely cause problems.

**Comment by hany** [comment]
Yes, that's the idea at least. Taking advantage of ["Global" units](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/#run-a-global-unit) in fleet is appealing, since I can ensure the Rancher agent runs on every host. Any suggestions?

**Comment by ibuildthecloud** [comment]
Have you tried a oneshot unit?  I don't know if those are compatible with global units.

**Comment by hany** [comment]
I was considering that. The issue is it can no longer track the container(s) once launched and restart if it fails, which I assume is the fundamental problem with systemd and Docker.

**Comment by ibuildthecloud** [comment]
The whole agent registration process is a bit magical at the moment (and really complex).  We've needed to change the process to simplify it and make it more easy to troubleshoot.  I will take this into consideration when we change it.  It should be more compatible with systemd.

Your right in that you'll have some problems getting systemd to monitor Docker containers, but the agent spawns the real agent container that is launched with `--restart=always`.  So Docker will ensure that the container stays running.

**Comment by hany** [comment]
OK, good to know. I will go with the `oneshot` route at this time. Thanks @ibuildthecloud!

**Comment by hany** [comment]
For those interested in the final unit file:

```
[Unit]
Description=Rancher Agent

[Service]
TimeoutStartSec=0
Type=oneshot
RemainAfterExit=yes
SuccessExitStatus=137
ExecStartPre=-/usr/bin/docker kill rancher-agent
ExecStartPre=-/usr/bin/docker rm rancher-agent
ExecStartPre=/usr/bin/docker pull rancher/agent:v0.5.2
ExecStart=/usr/bin/docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 <URL>

[X-Fleet]
Global=true
```

`SuccessExitStatus` is needed as the Docker client exits with `137` when the initial container exits after successful launch:

```
$ /usr/bin/docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 <URL>
...
$ echo $?
137
```

**Comment by ibuildthecloud** [comment]
The kill and rm in the ExecStartPre are not fully needed, they don't hurt, just not needed.  The docker run command will ensure that only one container named "rancher-agent" exits and that it is the correct version and configuration.

Glad to see the oneshot worked.  I really like Global Units in fleet, very handy approach.

**Comment by RVN-BR** [comment]
Is this still the correct way to run agent on a coreos cluster?

**Comment by deniseschannon** [comment]
@RVN-BR As far as I know, but we haven't tested out other ways.

**Comment by RVN-BR** [comment]
Hi... I tried the above but its not working... I'm going to have to dive deeper into this... for now its not really working... I got it to work once but whole cluster reported a single  IP to the rancher-ui, (3 hosts with the same IP), and then all fell offline shortly after...

tried getting rancher-server up there in a similar way but no dice...

fleet-ctil list-units shows no units... list-unit-files also shows nothing...

Trying to start the unit manually shows 
```
core@core-01 ~ $ fleetctl start rancher-server.service
Unit rancher-server.service
Triggered global unit rancher-server.service start
core@core-01 ~ $
core@core-01 ~ $
core@core-01 ~ $ fleetctl status
core@core-01 ~ $ fleetctl list-units
UNIT			MACHINE				ACTIVE		SUB
rancher-server.service	1763def3.../172.17.8.101	inactive	dead
```

Running the docker command straight into coreos works and rancher server is now up... (I only have 1 unit, but the server shouldnt be running XFleet Global... that was a mistake...

**Comment by RVN-BR** [comment]
I guess this is closed but there isnt really any conclusion?  Can anyone comment on what the appropriate way of ensuring rancher is correctly started/restarted as required in a coreos cluster?
