### ISSUE TITLE
[UI][API] No resource.change for API key as a Project

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#341]
Steps:
1.  Create a project
2.  Switch to that project
3.  Go to API page
4.  Click on Create an API key button

Results:
API key and password doesn't show up right away because resource.change event is not being fired

Expected:
No delay in seeing key and password

**Comment by vincent99** [comment]
This should be fixed in master/this week's release.

**Comment by tfiduccia** [comment]
v0.14.2
Verified fixes
