### ISSUE TITLE
Maxing out Project name messes up Menu

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#344]
![image](https://cloud.githubusercontent.com/assets/11514927/6872226/13693ee8-d465-11e4-84f9-61729e168b72.png)

Steps:
1.  Create a new Project
2.  Max out Project Name
3.  Click on Project Drop-down menu

Results:
Menu is messed up

Expected:
Smaller size limit for project or it should say "Beginning of Project Name ..."  with the ... to suggest there is more.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/7265514/f66ae810-e84f-11e4-994f-d9b82e6f619b.png)

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
