### ISSUE TITLE
[UI][Projects] Spaces in front of project name are being striped in project list but still exist

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#346]
Steps:
1.  Create multiple projects, name them ABC, CDE, FFF,
2.  Create a project with name  ZZZ (with extra space at beginning)

Results:
The project ZZZ is at top of list because of space, but the space doesn't show.

Expected:
Strip out any spaces that are at beginning.  This should also be done for description.  If this is not good then you need to show the space in the Project list so they don't look out of order.

![image](https://cloud.githubusercontent.com/assets/11514927/6872618/9db57d80-d467-11e4-8911-65cc9f012619.png)

**Comment by tfiduccia** [comment]
This should also not allow a project to have just spaces as the name.

**Comment by vincent99** [comment]
Name will be trimmed now on save, but it's not marked required in the API so you can still save a project with no name.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
