### ISSUE TITLE
[Containers] Containers/Network Agent fail to start

### ISSUE THREAD

**Issue by barkerd427** [rancherio/rancher#35]
I downloaded the images and ran them on a single host, but I have been unable to get Rancher to launch a container on the host. I have seen one container start, but it wasn't clear in the UI that it had started and it seemed to have failed before it actually succeeded. I keep getting this error:
![screen shot 2015-01-14 at 7 53 43 am](https://cloud.githubusercontent.com/assets/6106821/5739835/5cab8d20-9bc3-11e4-8f91-b2dc99e8ed21.png)

I'm not sure if there's an issue running on a single host, but I can't see why there would be. I haven't had time to look at the code to help diagnose the problem, so it could be something I'm just missing. I originally received errors from trying to run the container that may have been related to #13 when I used the default settings. I thought that issue may be resolved to some extent as there is an option for running `-it`. That doesn't seem to be the case. I then switched to running nginx with no additional options, and that started successfully once.

I think you guys should update the default settings to something that works without any changes. You could have your own nginx image that has some cool website saying how awesome we are for being able to start everything. With something like "Imagine how we'd react if we saw you open the peanut butter by yourself. Yeah, it's that easy." I look forward to seeing what you guys produce here.

**Comment by smw355** [comment]
Daniel,

Thanks for the feedback.  Darren, Sheng and I met with Daniel yesterday and talked with him a bit about Rancher and he graciously agreed to give it a try, could you or Bill take a look at the issue he’s hitting?

Best Regards,

Shannon Williams
shannon@rancher.com<mailto:shannon@rancher.com>
+1 650-521-6902

**Comment by ibuildthecloud** [comment]
@barkerd427 I'd love to help you trouble shoot this.  It appears our overlay networking is failing on your host.  If you post `docker info` and `docker version` and `docker images | grep rancher` that would help.  Also any output from `docker logs <YOUR_RANCHER_SERVER>`.

What you can try though is to just not use our overlay networking.  On the create container dialog just select "Unmanaged Network" on the create dialog.

**Comment by barkerd427** [comment]
So it started immediately when I used the "Unmanaged Network" option, which leads me to believe that the functions of pulling the image worked fine previously when there was a network overlay failure.

![screen shot 2015-01-15 at 8 26 37 am](https://cloud.githubusercontent.com/assets/6106821/5759039/5173b914-9c90-11e4-904b-d5ff0b6e84de.png)

![screen shot 2015-01-15 at 8 27 49 am](https://cloud.githubusercontent.com/assets/6106821/5759063/73a86bd8-9c90-11e4-99fb-6950efec4d72.png)

![screen shot 2015-01-15 at 8 28 35 am](https://cloud.githubusercontent.com/assets/6106821/5759072/8ee433a0-9c90-11e4-8bd1-bde5109cac5b.png)

And here's the logs: https://gist.github.com/barkerd427/eebc2f9b9ae2e4ec9567

**Comment by ibuildthecloud** [comment]
Looks like your running RHEL6.  We haven't really tried RHEL6.  In theory Rancher should run wherever Docker runs, but that theory hasn't held true quite yet.  We are still sorting through the slight differences in distros.  Currently we test on Ubuntu 14.04+, Fedora 21, CoreOS, and Centos 7.  For all of those we ensure we are using the latest Docker though and don't necessarily use the packaged version.  Right now we are almost always on the bleeding edge version.

Having said all that, I would like to know why this isn't working on RHEL6.  If you wouldn't mind could you send the /var/lib/cattle/agent.log file also (on the host).  Long term though it will be very difficult to support RHEL6 just because it is a 2.6 kernel.  We will also try to reproduce on our side with CentOS 6.

@cloudnautique Can you try running Rancher.io on CentOS 6?

**Comment by barkerd427** [comment]
Here's the output: https://gist.github.com/barkerd427/72b4795c9021cb8863ea

If you need more, then I can clear the log and rerun everything so the logs are cleaner. I didn't use a -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime, so the times are a little confusing for me to parse as to when I was doing my tests. May be a good note to add since you are logging to the host.

We don't have RHEL 7 yet, so I can't test it properly to see how it runs on a newer kernel. I will once I can get one provisioned.

**Comment by ibuildthecloud** [comment]
@barkerd427 The error is that we can't seem to set the mac.

```
Setting eth0 to 02:77:36:c6:54:f4
RTNETLINK answers: Device or resource busy 
```

Unfortunately netlink doesn't give useful error messages.  On the positive side, Docker 1.4 added support for setting the mac address, so we actually don't need to set the mac address in the way that we are doing it today.  I've created an [issue for this](https://github.com/rancherio/cattle/issues/135), we will see if we can quickly address this.  We do new releases of Rancher every Monday.

This raises a whole different issue with RHEL6 though.  RHEL6 is currently on Docker 1.3.  With the rate that we are moving atm it is not feasible to support older versions of Docker.  Next week we are probably going to only support Docker 1.4 as we are starting to use Docker 1.4 features.  When Docker 1.5 comes out well will immediately move to it.  You can run newer versions of Docker on RHEL but you just need to manually install the Docker binary.  More info at https://github.com/rancherio/rancher/issues/5

**Comment by barkerd427** [comment]
Thanks for the info @ibuildthecloud. RHEL 6 will, I assume, have 1.4 soon. I'm not sure what RHEL 7 uses atm, but I'm guessing it's not the latest either. Redhat is always a little slow to release a version. I'll try it out again when RHEL6 gets 1.4. I just checked and didn't see it available. Hopefully I'll have a RHEL 7 box in the next month that I can play around with.
