### ISSUE TITLE
GitHub team names do not have links to Github.com

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#350]
Steps:
1.  Go to add a Project
2.  Select a Team for owner
3.  Create

Results:
Team name is not a link

Expected:
Team name should be a link

**Comment by vincent99** [comment]
Need the `slug` property of teams added to the `/v1/tokens` responset to be able to generate the correct URL.

**Comment by vincent99** [comment]
Teams are now lined if you have access to the team, and the org name is linked even if you don't.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
