### ISSUE TITLE
[UI] [Host] In the Add Host page, the icons should have a colored border around the icon to give more emphasis on the selected icon.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#351]
Version: v0.13.0

In reference to discussions on https://github.com/rancherio/rancher/issues/245, I spoke with Nikita. She mentioned that the implementation of the UI design was slightly different than the design.

Icons should have a colored border around the selected icon to provide better emphasis on the selected icon.

**Comment by vincent99** [comment]
They borders are already different grays, but not the ones in the PSD (any more..).  I'll update them.  Also the custom one is dashed in the design.

**Comment by deniseschannon** [comment]
@vincent99 Based on the design, the logo color and border around the selected logo should be the same color as the  selected color for the menu. 

![screen shot 2015-03-27 at 1 27 01 pm](https://cloud.githubusercontent.com/assets/11410997/6876475/1dee6f3a-d485-11e4-9dfa-797177f36554.png)

**Comment by tfiduccia** [comment]
v0.16.2 (latest)
Verified fixed
