### ISSUE TITLE
DigitalOcean machine: Add validation for name to match their requirements

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#352]
v0.13.1

DO only allows:
200 character limit 
Only alphanumeric characters, dashes, and periods are allowed

We should validate for that in the Name field.

**Comment by will-chan** [comment]
go-machine will also return the correct error now instead of hanging starting with 0.14

**Comment by vincent99** [comment]
Added in rancherio/ui#153

**Comment by tfiduccia** [comment]
v0.20.1
Verified Fixed
