### ISSUE TITLE
Containers by Host should be listed alphabetically, with managed containers at the bottom

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#354]
v0.13.1

Currently on the Containers Page, Containers are listed by Creation time of Host, then creation time of container.

It would be easier for end user if it was Alphabetical.  Host name, then container name would be nice.

**Comment by vincent99** [comment]
(Combining with #467)

**Comment by deniseschannon** [comment]
This looks fixed in v0.23.0-rc1
