### ISSUE TITLE
[UI] [Add Host] When adding a DO machine, the combination of transitioning messages are not clear.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#355]
v0.13.0

When adding a host, we've moved the transitioning message to under the static text, but you can end up with conflicting messages.

In this example, we've already hit an error with setting up machine, but the static text is still  "Setting up machine" and the transition message is the error message. It takes awhile before the "Error creating machine" is displayed.

![screen shot 2015-03-26 at 9 27 21 am](https://cloud.githubusercontent.com/assets/11410997/6876050/0bb9faf4-d481-11e4-9a65-5a9c24d97bf1.png)

Can we just eliminate the static text message?

**Comment by vincent99** [comment]
This shouldn't happen any more now that machine errors are marked properly in the api.. the "setting up machine..." text only shows while still transitioning.

**Comment by deniseschannon** [comment]
Fixed in version v0.14.1.
