### ISSUE TITLE
When a private registry is selected, it's automatically selected whenever you open the registry dropdown.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#356]
Version v0.13.0

Steps to Reproduce
1. Create a Private Registry
2. Go to containers page.
3. Select the private registry. 
4. Open the dropdown and select the DockerHub registry

Result: The bar that displays what's selected is highlighted for DockerHub and for the registry that was previously selected.

Expected result: The selected bar will only show up on the selected item. 

![screen shot 2015-03-27 at 2 02 17 pm](https://cloud.githubusercontent.com/assets/11410997/6876972/e40f5f2c-d489-11e4-9f01-bc2a22b76a4d.png)

**Comment by vincent99** [comment]
That is the one that's selected, and you need some indication because all 3 of the choices shown are the same serverAddress..  But it should be a checkmark or something instead of the same blue active style.

**Comment by vincent99** [comment]
There is no longer a registry or credential picker in the UI as of rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.21.0
Verified fixed
