### ISSUE TITLE
When a private registry is selected with credentials and I return to the container, the credentials get reset to the first option.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#358]
Version v0.13.0

Steps to Reproduce:
1. Create a private registry with 2 credentials. 
2. Go to 'Add Container' to and select the private registry with the credential at the bottom of the drop down. 
3. Click on hosts.
4. Click on Add Container. 

Result: Private Registry name and image remain, but the credential has reset to the top credential on the list.

Expected Result: Since the private registry name and image are saved, the previously used credential should be saved.

**Comment by vincent99** [comment]
There is no longer a registry or credential picker in the UI as of rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed
