### ISSUE TITLE
[UI] [Access Control] The Access Control message is not user friendly in the menu.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#359]
Version: v0.13.0

The grayed out "Access Control is not configured" message is confusing to the user. As a user, it looks as if it's a setting that's something that can't be changed. 

![screen shot 2015-03-27 at 2 13 16 pm](https://cloud.githubusercontent.com/assets/11410997/6877160/992e2d60-d48b-11e4-9301-2d267ef3cff0.png)

The variations in gray in this menu doesn't help the user either.

**Comment by vincent99** [comment]
See #301

**Comment by deniseschannon** [comment]
Fixed in v0.14.1
