### ISSUE TITLE
[UI] [Private Registry] If I have a inactive credential in my private registry, it still shows up in the Add Container page.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#361]
v0.13.0

An inactive credential will still show up as an option to use for my Private Registry.

Steps to Reproduce:
1. Create a Private Registry with 2 credentials.
2. Go to the Private Registry details page.
3. Deactivate 1 of the credentials.
4. Try to add a container

Result: The inactive credential shows up as an option in the dropdown.

Expected Result: The inactive credential would be hidden.

**Comment by vincent99** [comment]
I think this was a dupe of an issue that was in last week's release, but only active credentials are shown now.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
