### ISSUE TITLE
If my last selected private registry is deactivated, it still shows up in the drop down as a selected option when it's not listed in the drop down list.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#363]
Version v0.13.0

If I use my private registry (test.io) to create a container and then go to deactivate the private registry, the 'Add Container' page will still show (test.io) as a selected item, when the item doesn't exist in my drop down.

Steps to Reproduce:
1. Create a private registry 
2. Go to Add Container and set the private registry to the newly created one.
3. Go to the private registry page and deactivate the private registry.
4. Go back to the 'Add Container' page

Result: The dropdown for image is still selecting your private registry even though it's not an option.

Expected Result: The dropdown should reset (probably to DockerHub).

In my image, the test.io private registry is not in the dropdown anymore because it's inactive.
![screen shot 2015-03-27 at 2 44 20 pm](https://cloud.githubusercontent.com/assets/11410997/6877600/c4dac118-d48f-11e4-9b0c-ae74e15a11da.png)

**Comment by vincent99** [comment]
There is no longer a registry or credential picker in the UI as of rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed
