### ISSUE TITLE
[UI] [Host] When I get an error for my access token, the error message doesn't disappear when I leave the Add Host page and come back.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#368]
Version: v0.13.1

Steps to Reproduce:
1. Try to add host with invalid DO token.
2. Don't add a host and click on Container page.
3. Click on 'Add Host' page again. 

Result: All fields are reset, but the error message still remains.

Expected Result: Error Message would disappear from the UI. 

Since the add host page resets everything upon loading, the error message also needs to be hidden on each loading of the page.

![screen shot 2015-03-30 at 9 44 07 am](https://cloud.githubusercontent.com/assets/11410997/6901329/52180d3c-d6c1-11e4-9fd4-03784c876ccf.png)

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
