### ISSUE TITLE
[Machine] - When attempting to add a Digital Ocean host with invalid access token, Transition Message does not have failure message returned from digital ocean.  

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#371]
Server Version -  v0.14.0

Steps to reproduce the problem:
Add a Digital Ocean machine with invalid token.

Machine creation fails and state of the machine is set to "error". Transition Message does not have failure message returned from digital ocean:

Machine details:

"data": {
"fields": {
"digitaloceanConfig": {
"accessToken": "*************",
"size": "1gb",
"region": "nyc3",
"image": "ubuntu-14-04-x64",
},
"driver": "digitalocean",
"transitioningMessage": "exit status 1",
"transitioning": "error",
},
},

Server logs indicating the error message returned by Digital Ocean:

time="2015-03-30T23:21:11Z" level=info msg="Creating Machine" eventId="b97d3462-4de5-4290-a83a-394b861a1a88" resourceId=1ph11 
time="2015-03-30T23:21:11Z" level=info msg="Cmd slice: [create -d digitalocean --digitalocean-image ubuntu-14-04-x64 --digitalocean-size 1gb --digitalocean-region nyc3 --digitalocean-access-token 1df630dee8cc8749c6627b5ab2be9232a60620c1a35dbedf818b6615c57da109 test-do]" 
time="2015-03-30T23:21:11Z" level=info msg="stdout: time=\"2015-03-30T23:21:11Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/bb332283-a5af-4562-97ea-013216c30248/machine/certs/ca.pem\" " resourceId: =1ph11 
time="2015-03-30T23:21:13Z" level=info msg="stdout: time=\"2015-03-30T23:21:13Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/bb332283-a5af-4562-97ea-013216c30248/machine/certs/cert.pem\" " resourceId: =1ph11 
time="2015-03-30T23:21:16Z" level=info msg="stdout: time=\"2015-03-30T23:21:16Z\" level=\"info\" msg=\"Creating SSH key...\" " resourceId: =1ph11 
time="2015-03-30T23:21:16Z" level=info msg="stdout: time=\"2015-03-30T23:21:16Z\" level=\"error\" msg=\"Error creating machine: POST https://api.digitalocean.com/v2/account/keys: 401 Unable to authenticate you.\" " resourceId: =1ph11 
time="2015-03-30T23:21:16Z" level=info msg="stdout: time=\"2015-03-30T23:21:16Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine and associated resources were properly removed.\" " resourceId: =1ph11 
time="2015-03-30T23:21:16Z" level=info msg="stdout: time=\"2015-03-30T23:21:16Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: =1ph11 
time="2015-03-30T23:21:16Z" level=error msg="Error processing event" err="exit status 1" eventId="b97d3462-4de5-4290-a83a-394b861a1a88" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph11

**Comment by deniseschannon** [comment]
Verified in v0.14.2
