### ISSUE TITLE
[Machine] - Amazon - When machine creation fails because of invalid access key , transition message does not include the full error message received from amazon.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#372]
Server Version - V0.14.0

Steps to reproduce the problem:

Scenario 1:

Try to add a Amazon host by providing invalid access key.

Machine creation fails with the state being set to "error", but the transition error message does not contain the full error message from amazon:

Machine detail from API:
"data": {
"fields": {
"virtualboxConfig": null,
"amazonec2Config": {
"vpcId": "vpc-44144621",
"accessKey": "*********",
"secretKey": "******",
"securityGroup": "testsangee",
},
"digitaloceanConfig": null,
"driver": "amazonec2",
"transitioningMessage": "exit status 1",
"transitioning": "error",
},
},

time="2015-03-30T23:45:25Z" level=info msg="stdout: time=\"2015-03-30T23:45:25Z\" level=\"error\" msg=\"Error creating machine: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials\\n\" " resourceId: =1ph15 

Scenario 2:

Try to add a Amazon host by providing invalid secret key.

Machine creation fails with the state being set to "error", but the transition error message does not contain the full error message from amazon .

Error message presented to user - "Error creating machine: Problem with AWS API call: Non-200 API response: code"

API:

"data": {
"fields": {
"amazonec2Config": {
"region": "us-east-1",
"instanceType": "t2.micro",
"zone": "a",
"rootSize": "16",
"accessKey": "************",
"vpcId": "vpc-44144621",
"secretKey": "G*******",
"ami": "",
"iamInstanceProfile": "",
},
"driver": "amazonec2",
"transitioningMessage": "Error creating machine: Problem with AWS API call: Non-200 API response: code",
"transitioning": "error",
},
},
Server logs having the full error message:

Server logs having the full error message:

time="2015-03-31T01:24:10Z" level=info msg="stdout: time=\"2015-03-31T01:24:10Z\" level=\"error\" msg=\"Error creating machine: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials\\n\" " resourceId: =1ph21

**Comment by deniseschannon** [comment]
Verified Fix in v0.14.2

There was 1 case where I got 'exit status 1' instead of the true error message. But I have been unable to reproduce. I will reopen if I see it again.
