### ISSUE TITLE
[Machine] - When name is not passed when creating machine , machine creation is stuck at "creating" forever - "runtime error: index out of range" encountered.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#373]
Version - V0.14.0

Steps to reproduce the problem:

Add a Amazon EC2 Host and do not provide name.
machine creation is stuck at "creating" forever .
 "runtime error: index out of range" is encountered.
 
Server logs:

time="2015-03-31T01:33:58Z" level=info msg="Creating Machine" eventId="43566aae-9444-4162-976f-4b580460eb15" resourceId=1ph23 
time="2015-03-31T01:33:58Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key ************ --amazonec2-secret-key ********** --amazonec2-vpc-id vpc-44144621 --amazonec2-region us-east-1 --amazonec2-zone a --amazonec2-instance-type t2.micro --amazonec2-root-size 16 ]" 
time="2015-03-31T01:33:58Z" level=info msg="stdout: NAME:" resourceId: =1ph23 
panic: runtime error: index out of range

goroutine 340 [running]:
github.com/rancherio/go-machine-service/handlers.filterDockerMessage(0xc20841f9a8, 0x5, 0xc2083f7aa0, 0x24, 0xc20841f9b0, 0x0, 0x0)
	/source/gopath/src/github.com/rancherio/go-machine-service/handlers/create.go:135 +0x25c
github.com/rancherio/go-machine-service/handlers.logProgress(0x7ff94c638b60, 0xc208036398, 0x7ff94c638b60, 0xc2080363a8, 0xc2081d3380, 0xc2083f7aa0, 0x24, 0xc2081e09c0, 0xc20841f9b0)
	/source/gopath/src/github.com/rancherio/go-machine-service/handlers/create.go:114 +0x410
created by github.com/rancherio/go-machine-service/handlers.CreateMachine
	/source/gopath/src/github.com/rancherio/go-machine-service/handlers/create.go:63 +0x868

**Comment by deniseschannon** [comment]
Verified Fixed in v0.14.2
