### ISSUE TITLE
EC2 Machine fails to use public ip of the instance when trying to ssh

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#374]
Version - V0.14.1

Steps to reproduce the problem:

Set up a new Rancher server instance .
Add an amazon host providing valid values for access key, secret key and vpcid,

Host addition is stuck in "creating" state forever , since it is stuck in the step of trying to ssh to instance on port 22 because of not using any ip address .

Tried to add another amazon host providing valid values for access key, secret key and vpcid,

Host addition is stuck in "creating" state forever for this attempt as well , since it is stuck in the step of trying to ssh to instance on port 22 because of not using any ip address .

From Rancher UI , deleted both the hosts that were stuck in "creating" state.

Attempted to add another amazon host providing valid values for access key, secret key and vpcid,

Host addition succeeds this time. This time docker-machine uses the right public ip address to ssh to instance on port 22 .

Server logs:
03:33:08.360 [main] INFO  ConsoleStatus - [DONE ] [96724ms] Startup Succeeded, Listening on port 8080
time="2015-03-31T03:40:00Z" level=info msg="Setting log level" logLevel=info
time="2015-03-31T03:40:00Z" level=info msg="Starting go-machine-service..."
time="2015-03-31T03:40:00Z" level=info msg="Initializing event router" workerCount=10
time="2015-03-31T03:40:00Z" level=info msg="Connection established"
time="2015-03-31T03:44:50Z" level=info msg="Creating Machine" eventId="9eb333a0-0355-4b33-b84f-24b1ca589e27" resourceId=1ph2
time="2015-03-31T03:44:50Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ******/qmeCf/bwkRrYYXT0B00WTlfyGbn --amazonec2-vpc-id vpc-***** --amazonec2-region us-east-1 --amazonec2-zone a --amazonec2-instance-type t2.micro --amazonec2-root-size 16 test55]"
time="2015-03-31T03:44:50Z" level=info msg="stdout: time=\"2015-03-31T03:44:50Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/47729824-8148-4cf7-b8a1-5f4dfac0ee01/machine/certs/ca.pem\" " resourceId: =1ph2
time="2015-03-31T03:44:52Z" level=info msg="stdout: time=\"2015-03-31T03:44:52Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/47729824-8148-4cf7-b8a1-5f4dfac0ee01/machine/certs/cert.pem\" " resourceId: =1ph2
time="2015-03-31T03:44:54Z" level=info msg="stdout: time=\"2015-03-31T03:44:54Z\" level=\"info\" msg=\"Launching instance...\" " resourceId: =1ph2
time="2015-03-31T03:44:55Z" level=info msg="stdout: time=\"2015-03-31T03:44:55Z\" level=\"info\" msg=\"Waiting for SSH on :22\" " resourceId: =1ph2
time="2015-03-31T03:54:42Z" level=info msg="Creating Machine" eventId="0f0e8959-7cd8-4dc1-b79a-64971060e1f3" resourceId=1ph3
time="2015-03-31T03:54:42Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ******/qmeCf/bwkRrYYXT0B00WTlfyGbn --amazonec2-vpc-id vpc-***** --amazonec2-region us-east-1 --amazonec2-zone a --amazonec2-instance-type t2.micro --amazonec2-root-size 16 test66]"
time="2015-03-31T03:54:42Z" level=info msg="stdout: time=\"2015-03-31T03:54:42Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/b8109823-d711-44fa-90e5-3a6fba25a129/machine/certs/ca.pem\" " resourceId: =1ph3
time="2015-03-31T03:54:43Z" level=info msg="stdout: time=\"2015-03-31T03:54:43Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/b8109823-d711-44fa-90e5-3a6fba25a129/machine/certs/cert.pem\" " resourceId: =1ph3
time="2015-03-31T03:54:46Z" level=info msg="stdout: time=\"2015-03-31T03:54:46Z\" level=\"info\" msg=\"Launching instance...\" " resourceId: =1ph3
time="2015-03-31T03:54:50Z" level=info msg="stdout: time=\"2015-03-31T03:54:50Z\" level=\"info\" msg=\"Waiting for SSH on :22\" " resourceId: =1ph3
time="2015-03-31T03:57:35Z" level=info msg="Creating Machine" eventId="649fe4b4-3f5e-42db-bd01-ae2f2064f0eb" resourceId=1ph4
time="2015-03-31T03:57:35Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ******/qmeCf/bwkRrYYXT0B00WTlfyGbn --amazonec2-vpc-id vpc-***** --amazonec2-region us-east-1 --amazonec2-zone a --amazonec2-instance-type t2.micro --amazonec2-root-size 16 test88]"
time="2015-03-31T03:57:35Z" level=info msg="stdout: time=\"2015-03-31T03:57:35Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/6dc53a95-16ad-453f-ae09-ebce0039eee5/machine/certs/ca.pem\" " resourceId: =1ph4
time="2015-03-31T03:57:44Z" level=info msg="stdout: time=\"2015-03-31T03:57:44Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/6dc53a95-16ad-453f-ae09-ebce0039eee5/machine/certs/cert.pem\" " resourceId: =1ph4
time="2015-03-31T03:57:52Z" level=info msg="stdout: time=\"2015-03-31T03:57:52Z\" level=\"info\" msg=\"Launching instance...\" " resourceId: =1ph4
time="2015-03-31T03:58:16Z" level=info msg="stdout: time=\"2015-03-31T03:58:16Z\" level=\"info\" msg=\"Waiting for SSH on 52.4.143.93:22\" " resourceId: =1ph4
time="2015-03-31T03:59:19Z" level=info msg="stdout: time=\"2015-03-31T03:59:19Z\" level=\"info\" msg=\"Configuring Machine...\" " resourceId: =1ph4
time="2015-03-31T04:00:52Z" level=info msg="stdout: time=\"2015-03-31T04:00:52Z\" level=\"info\" msg=\"\\\"test88\\\" has been created and is now the active machine.\" " resourceId: =1ph4
time="2015-03-31T04:00:52Z" level=info msg="stdout: time=\"2015-03-31T04:00:52Z\" level=\"info\" msg=\"To point your Docker client at it, run this in your shell: $(docker-machine env test88)\" " resourceId: =1ph4
time="2015-03-31T04:00:52Z" level=info msg="Machine Created" machineExternalId="6dc53a95-16ad-453f-ae09-ebce0039eee5" resourceId=1ph4
time="2015-03-31T04:00:52Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph4
time="2015-03-31T04:00:52Z" level=info msg="Machine config file created and encoded." destFile="/var/lib/cattle/machine/6dc53a95-16ad-453f-ae09-ebce0039eee5/test88.tar.gz" resourceId=1ph4
time="2015-03-31T04:00:52Z" level=info msg="Activating Machine" eventId="87521b7c-54e2-4bbb-94db-73b4f688c4ac" resourceId=1ph4
time="2015-03-31T04:00:53Z" level=info msg="Pulling rancher/agent:latest image."
time="2015-03-31T04:01:12Z" level=info msg="Container created for machine" containerId="52260f30e67d0fb85a0ac81350cf618d88a6c9a92d48c644a76f1369b80c7bcc" machineId=1ph4 resourceId=1ph4
time="2015-03-31T04:01:12Z" level=info msg="Rancher-agent for machine started" containerId="52260f30e67d0fb85a0ac81350cf618d88a6c9a92d48c644a76f1369b80c7bcc" machineExternalId="6dc53a95-16ad-453f-ae09-ebce0039eee5" resourceId=1ph4

**Comment by deniseschannon** [comment]
v0.23.0-rc1: New EC2 UI fixes this issue as the new UI creates a security group with `22` enabled or you can pick an existing group (with notes that `22` needs to be open).
