### ISSUE TITLE
[Machine][API/UI] - When adding hosts , name should be made a required parameter

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#379]
Server Version - V0.14.1

Steps to reproduce the problem:
Try to add an amazon EC2/Digital Ocean host without passing username.
In such cases we see that the machine is stuck in "creating" state.

Server encounters "runtime error: index out of range" which is tracked in . #373.

From API/UI prespective , we should not allow for machines to be created with no names. We either force users to provide a name / have the server generate a unique name for the hosts.

**Comment by tfiduccia** [comment]
v0.15.0
Verified fixed
