### ISSUE TITLE
Validation tests periodically fail

### ISSUE THREAD

**Issue by cloudnautique** [rancherio/rancher#38]
On a fresh build of a new cluster, the validation tests will experience errors/failures. The ping neighbors test will timeout while waiting for containers to provision. 

Linking test sometimes fails, though infrequently. 

Leaving bill-043-fedora cluster online. This cluster had 1 error and one failure during the test run. Second pass all tests were successful.

Needs more investigation.

**Comment by ibuildthecloud** [comment]
You can delete the hosts.  If you see a failed node don't rerun the tests as that typically fixes it and then there's nothing to debug

**Comment by deniseschannon** [comment]
@cloudnautique If this is still valid, please re-open. I couldn't see the cluster so I am assuming that it's been resolved.
