### ISSUE TITLE
Error while creating a project

### ISSUE THREAD

**Issue by lalyos** [rancherio/rancher#385]
I've created a 5 node racher cluster on GCE. i am able to start containers, but when i try to create a project, it fails, see logs:

https://gist.github.com/lalyos/e2de8cc11b6a71a63499

btw: #ranchermeetup was awesome!

**Comment by vincent99** [comment]
@hibooboo2 Can you look at @lalyos NPE stacktrace and fix the cause in the updated projects release?  GitHub has been getting DDOSed for days so it's likely related to failing to connect to them.

**Comment by vincent99** [comment]
Ping @hibooboo2

**Comment by vincent99** [comment]
@lalyos can you try again with v0.17?  We've significantly changed how projects work.

**Comment by hibooboo2** [comment]
@lalyos I believe this is fixed with the new projects. Patch. This was due to improper management of errors.
