### ISSUE TITLE
Add 2 DigitalOcean machines: one stuck in "Creating" state and another host got to "error" state with reason - error "installing docker: exit status 255"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#386]
Version - V0.14.1

Steps to reproduce the problem:

Add 2 Digital ocean hosts , so that both the machine creation are happening in parallel.

One of the machines (1ph21) failed to get created with error message "Error creating machine: error installing docker: exit status 255"

Other machine (1ph22) , was stuck waiting to SSH to the machine.
 

root@sangeenew-10acre-master-0:/home/sangeethahariharan1# grep "1ph22" logs
time="2015-03-31T18:04:15Z" level=info msg="Creating Machine" eventId="ca3d2323-cba8-4a0f-b9ad-e097555f5b35" resourceId=1ph22 
time="2015-03-31T18:04:15Z" level=info msg="stdout: time=\"2015-03-31T18:04:15Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/ebed8525-e7b8-4fa4-a728-0158695cd28e/machine/certs/ca.pem\" " resourceId: =1ph22 
time="2015-03-31T18:04:19Z" level=info msg="stdout: time=\"2015-03-31T18:04:19Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/ebed8525-e7b8-4fa4-a728-0158695cd28e/machine/certs/cert.pem\" " resourceId: =1ph22 
time="2015-03-31T18:04:32Z" level=info msg="stdout: time=\"2015-03-31T18:04:32Z\" level=\"info\" msg=\"Creating SSH key...\" " resourceId: =1ph22 
time="2015-03-31T18:04:33Z" level=info msg="stdout: time=\"2015-03-31T18:04:33Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" " resourceId: =1ph22 
time="2015-03-31T18:04:37Z" level=info msg="stdout: time=\"2015-03-31T18:04:37Z\" level=\"info\" msg=\"Waiting for SSH...\" " resourceId: =1ph22 

root@sangeenew-10acre-master-0:/home/sangeethahariharan1# grep "1ph21" logs
time="2015-03-31T18:04:15Z" level=info msg="Creating Machine" eventId="808940bc-f2a9-4b38-9285-4cebd6a3230a" resourceId=1ph21 
time="2015-03-31T18:04:15Z" level=info msg="stdout: time=\"2015-03-31T18:04:15Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/68a7fbb0-875c-49bc-8a97-2704fdd004a6/machine/certs/ca.pem\" " resourceId: =1ph21 
time="2015-03-31T18:04:22Z" level=info msg="stdout: time=\"2015-03-31T18:04:22Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/68a7fbb0-875c-49bc-8a97-2704fdd004a6/machine/certs/cert.pem\" " resourceId: =1ph21 
time="2015-03-31T18:04:30Z" level=info msg="stdout: time=\"2015-03-31T18:04:30Z\" level=\"info\" msg=\"Creating SSH key...\" " resourceId: =1ph21 
time="2015-03-31T18:04:31Z" level=info msg="stdout: time=\"2015-03-31T18:04:31Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" " resourceId: =1ph21 
time="2015-03-31T18:04:33Z" level=info msg="stdout: time=\"2015-03-31T18:04:33Z\" level=\"info\" msg=\"Waiting for SSH...\" " resourceId: =1ph21 
time="2015-03-31T18:06:41Z" level=info msg="stdout: time=\"2015-03-31T18:06:41Z\" level=\"info\" msg=\"Configuring Machine...\" " resourceId: =1ph21 
time="2015-03-31T18:09:48Z" level=info msg="stdout: time=\"2015-03-31T18:09:48Z\" level=\"error\" msg=\"Error creating machine: error installing docker: exit status 255\\n\\n\" " resourceId: =1ph21 
time="2015-03-31T18:09:48Z" level=info msg="stdout: time=\"2015-03-31T18:09:48Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine and associated resources were properly removed.\" " resourceId: =1ph21 
time="2015-03-31T18:09:48Z" level=info msg="stdout: time=\"2015-03-31T18:09:48Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: =1ph2 
time="2015-03-31T18:09:48Z" level=error msg="Error processing event" err="Error creating machine: error installing docker: exit status 255\\n\\n" eventId="808940bc-f2a9-4b38-9285-4cebd6a3230a" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph21 
root@sangeenew-10acre-master-0:/home/sangeethahariharan1#

**Comment by deniseschannon** [comment]
Docker Machine is much more stable. This issue hasn't been reproduced in awhile.
