### ISSUE TITLE
[Machine][UI][Amazon] - "Add Host" - Helper text for description field says "e.g. My DigitalOcean host"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#387]
Version - V0.14.1

![screen shot 2015-03-31 at 5 32 12 pm](https://cloud.githubusercontent.com/assets/4266958/6932318/721383ee-d7cc-11e4-87fe-fd5fedcfbe80.png)

**Comment by vincent99** [comment]
Changed in rancherio/ui#111

**Comment by sangeethah** [comment]
Server version - V0.14.2
Helper text is now -  "My EC2 host"
Closing this issue
