### ISSUE TITLE
[Machine][Amazon] - View logs/Execute Shell/CPU/Memory utilization is not functional for containers that are launched in amazon hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#389]
Server Version - V0.14.1

Steps to reproduce the problem:

Add Amazon host.
Deploy container.
Notice that view logs/Execute Shell/CPU/Memory utilization is not functional for containers that are launched in amazon hosts.

This is due to the security group of the ec2 host instance preventing traffic on TCP ports 9345 and 9346 and UDP ports 500 and 4500 .

Once these port are opened explicitly on the Security Group with which the ec2 instance was deployed , the functionality works.

Rancher server needs to either program these rules in Security Group automatically for the host instance Or notify users about the ports that need to be opened during the "Add Host" workflow for adding Amazon hosts.

**Comment by vincent99** [comment]
Added text info in rancherio/ui#114.

@cjellick or @will-chan maybe we can work on getting a hook added into https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L621-L668 to allow more ports so that they can be automatically added.

**Comment by tfiduccia** [comment]
v0.15.0
Text included in the Add Host to add security rules.  Verified fixed.
