### ISSUE TITLE
[UI] Remove Device Binding button is different then all other similar buttons

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#392]
v0.13.1
Steps:
1.  Create a container
2.  Go to Advanced Options, then Security/Host
3.  Add a Device Binding

Results:
The Remove Device Binding button is square and black.  In all other places it is a circle and blue.  You can go to Networking tab and look at Links, Resolving Servers and Search Domains for example.

Expected:
They should all look the same.

**Comment by vincent99** [comment]
Circle-ified

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
