### ISSUE TITLE
[UI][Container] Select a Network.... should not be a choice in dropdown

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#397]
v0.13.1
Steps:
1.  Create a container
2.  Go to Advanced Options
3.  Go to Networking tab
4.  Click on Network drop-down

Results:  There is a selection called "Select a Network to join the Container to...", that allows me to use as a selection.  If I select it, the container create will fail.

Expected:  This should not be selectable if not a valid choice.  I would just take the option out.  It's not the default anyway.

**Comment by vincent99** [comment]
Removed prompt

**Comment by tfiduccia** [comment]
v0.16.2 (latest)
Verified Fixed
