### ISSUE TITLE
Can't tell Authenticate button is disabled

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#398]
v0.13.1
Steps:
1.  Go to Settings page
2.  Make sure you are not Authenticated

Results:
The Authenticate with GitHub button does not look deactivated.  Even if you put the Client ID and Secret, the button just turns a slightly darker shade of blue.  It's really not noticeable.

Expected:
If the button is supposed to be inactive, make it grey or something more noticeable.

**Comment by vincent99** [comment]
Closing in favor of #223.
