### ISSUE TITLE
How to add a second Vagrant instance?

### ISSUE THREAD

**Issue by lukemarsden** [rancherio/rancher#4]
Hey there,

Rancher is extremely cool. Nice work.

It would be really useful to have explicit instructions on how to spin up two VMs in Vagrant with Rancher. Maybe you could provide an example Vagrantfile for two or more hosts?

If I wanted to do this manually, what would I need to do to tell Rancher hosts about eachother? Does it figure out group membership automatically based on the hosts in the CoreOS cluster?

Thanks!
Luke

**Comment by deniseschannon** [comment]
@lukemarsden Do you still need help with this? I'm going to close this as it's relatively old now. If you still need help, please re-open.
