### ISSUE TITLE
Docker Log Container Support

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#40]
* #36 [MERGE]
* Add validation tests and make sure new auth-token works.

**Comment by ibuildthecloud** [comment]
@will-chan why is rancherio/cattle#141 listed as merged?

**Comment by will-chan** [comment]
@ibuildthecloud that is what is committed by 1/28.  The code would be submitted as a PR and MERGED.

**Comment by will-chan** [comment]
Need to now add validation tests to merge the code.
