### ISSUE TITLE
[UX][Machine] When a Machine/Host fails to create, image should show fail

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#401]
![image](https://cloud.githubusercontent.com/assets/11514927/6953695/eb1b6780-d87f-11e4-937e-e4d80fecd806.png)

This machine failed to create because I put the name in wrong.  Once that happens:

1.  The green CREATING thing in top left should turn red and say fail.
2.  The animation showing progress should stop.

**Comment by vincent99** [comment]
This was fixed in 0.14, re-check after updating to today's build..

**Comment by tfiduccia** [comment]
v0.14.2
Verified fixed
