### ISSUE TITLE
DigitalOcean creation fails with "Error creating machine: exit status 255" 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#404]
Server version - V0.14.1

Steps to reproduce the problem:

Add Digitial Ocean host , providing valid values for all configuration parameters.
Sometimes , Machine creation fails with ""Error creating machine: exit status 255" .

Server logs for the failed machine:

time="2015-04-01T23:26:19Z" level=info msg="Creating Machine" eventId="d59ad9db-4ea5-49cb-b200-eecdcde6a9ea" resourceId=1ph175 
time="2015-04-01T23:26:20Z" level=info msg="stdout: time=\"2015-04-01T23:26:20Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/29a12cce-ba74-41e6-b3f2-7e5cd106bec7/machine/certs/ca.pem\" " resourceId: =1ph175 
time="2015-04-01T23:26:21Z" level=info msg="stdout: time=\"2015-04-01T23:26:21Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/29a12cce-ba74-41e6-b3f2-7e5cd106bec7/machine/certs/cert.pem\" " resourceId: =1ph175 
time="2015-04-01T23:26:29Z" level=info msg="stdout: time=\"2015-04-01T23:26:29Z\" level=\"info\" msg=\"Creating SSH key...\" " resourceId: =1ph175 
time="2015-04-01T23:26:30Z" level=info msg="stdout: time=\"2015-04-01T23:26:30Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" " resourceId: =1ph175 
time="2015-04-01T23:26:32Z" level=info msg="stdout: time=\"2015-04-01T23:26:32Z\" level=\"info\" msg=\"Waiting for SSH...\" " resourceId: =1ph175 
time="2015-04-01T23:27:35Z" level=info msg="stdout: time=\"2015-04-01T23:27:35Z\" level=\"info\" msg=\"Configuring Machine...\" " resourceId: =1ph175 
time="2015-04-01T23:29:42Z" level=info msg="stdout: time=\"2015-04-01T23:29:42Z\" level=\"error\" msg=\"Error creating machine: exit status 255\" " resourceId: =1ph175 
time="2015-04-01T23:29:42Z" level=info msg="stdout: time=\"2015-04-01T23:29:42Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine and associated resources were properly removed.\" " resourceId: =1ph175 
time="2015-04-01T23:29:42Z" level=info msg="stdout: time=\"2015-04-01T23:29:42Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: =1ph175 
time="2015-04-01T23:29:42Z" level=error msg="Error processing event" err="Error creating machine: exit status 255" eventId="d59ad9db-4ea5-49cb-b200-eecdcde6a9ea" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph175

**Comment by deniseschannon** [comment]
With docker machine's stability, this error doesn't happen as regular as before. Will re-open if we see it happening again.
