### ISSUE TITLE
404 error after auth if you have api set

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#405]
v0.13.1
steps:
1.  Go to API page
2.  Create a key
3.  Click on endpoint and enter key
4. Go to Access Control settings
5. Enter Client ID/Secret and click on Authenticate with GitHub

Results:  404 error page pops up

Expected:  Should not show 404 error page.

**Comment by vincent99** [comment]
Shouldn't happen with new projects / #303

**Comment by tfiduccia** [comment]
v0.17.0
Verified failed

**Comment by tfiduccia** [comment]
v0.18.2
Verified fixed
