### ISSUE TITLE
Name on settings menu does not show it's clickable

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#408]
v0.14.2
Steps:
1.  Go to access control and Authenticate with GitHub
2.  Go to settings menu

Results:
Your Github username is at the top, when you moved your mouse over it, it used to highlight blue so it showed it was clickable.  With the new menu design it does not do that.

Expected:
Name should change color to show it's clickable.

**Comment by deniseschannon** [comment]
We are now showing the avatar instead of the name and there is a carat next to the avatar.

Is that accetable? @tfiduccia 

![screen shot 2015-06-02 at 12 57 42 pm](https://cloud.githubusercontent.com/assets/11410997/7945666/17732458-0927-11e5-93bd-13e5ee7026fc.png)

**Comment by vincent99** [comment]
She meant this one..

![image](https://cloud.githubusercontent.com/assets/753917/7947130/f5a1cf88-092f-11e5-8970-ba43cf55b157.png)

It's currently a slightly different color than the name, and the cursor turns into a hand on the name.  It's also not terribly critical that you know you can get to your own github account that way...

**Comment by vincent99** [comment]
(if you look closely, you'll see a bonus bug where it shows the Administration header even though I'm not admin in that screnshot...)

**Comment by deniseschannon** [comment]
That's interesting to learn, so you only get the administration links if you're an admin? And what defines you as an admin vs. non-admin?

**Comment by vincent99** [comment]
The person who turned on access control is the admin, they become the `1a1` user.  It's possible to have more than one but only through the API at the moment.

**Comment by tfiduccia** [comment]
v0.23.0-rc1
Verified fixed
