### ISSUE TITLE
Image Registry goes back to docker when switching back to default from project

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#414]
v0.14.2

Steps:
1.  Authenticate
2.  Create a new project and go to that project
3.  Go to Registry and add quay.io
4.  Go to Host and add a container using quay.io as Image Registry and rancher/helloworld as image
5.  Create and click Add Container (notice image registry is still quay.io and image is rancher/helloworld)
6.  Switch back to Default project
7.  Click on Add Container

Results:
Image registry is back to docker: but the image is set to rancher/helloworld

Expected:
Either the Image registry should stay at quay.io or we need to clear out the image itself, so we don't lead the user into an error.

**Comment by tfiduccia** [comment]
Same as other bug were we should always keep the whole path or none at all

**Comment by vincent99** [comment]
There is no longer a registry or credential picker in the UI as of rancherio/ui#152.  The backend will automatically use a matching credential if present and the registry has to be typed/pasted into the image name.

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed
