### ISSUE TITLE
[UI][Machine] Purging a machine doesn't show change from delete state

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#416]
v 0.14.2

Steps:
1.  Create a new Machine/Host
2.  Deactivate, Delete the Machine/Host
3.  Click on Purge

Results:
The Purge remove the machine right away, but since we are looking at the host, it looks like it isn't doing anything.  The UI for that Machine/Host doesn't change at all from the Delete state.  You have to wait the minute to see the Host removed.  It ends up looking like Purge does nothing and you can keep clicking on it.

Expected:
Machine/Host to both Purge and be removed from UI.  Or change the UI state and remove the ability to keep clicking on Purge.

**Comment by deniseschannon** [comment]
The functionality of the purge button appeared to be working in v0.14.1 where the host would be deleted upon clicking on the purge button.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
