### ISSUE TITLE
No validation that credentials are correct when adding Registry

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#418]
v0.14.2

Steps:
1.  Go to Registries
2.  Add Registry
3.  Add a credential, but put in an invalid password

Results:
Registry is added and you don't know that your password is incorrect until you try to add a container using that credential and it fails.

Expected:
Validate credentials on create registry.

**Comment by vincent99** [comment]
This is not trivial, will require API support.

**Comment by vincent99** [comment]
Duplicate of #300.
