### ISSUE TITLE
In Container details I get 404 page when viewing logs after purge

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#419]
v0.14.2

Steps:
1.  Create a container
2.  Click on container name
3.  Stop & Delete container from left pane menu
4.  Click on Purge
5.  Click on View Logs

Results:
The page refreshes and shows that the container is purged, but the View Logs menu icon item is still available. After clicking on it, I get a 404 page.

Expected:
View Logs should not be available.

**Comment by vincent99** [comment]
View logs shouldn't be available on a purged container...

**Comment by hibooboo2** [comment]
This is fixed with pr rancherio/cattle#587

**Comment by hibooboo2** [comment]
This just hit master.

**Comment by tfiduccia** [comment]
v0.24.0-rc1
Verified fixed
