### ISSUE TITLE
Logging directly into project instead of Default after disabling access control

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#420]
v0.14.2

Steps:
1.  Enable Authentication and create a project
2.  Go to project and add a machine/host
3.  While in that project go to API & Keys
4.  Create an API key
5.  Click on API endpoint
6.  Use API key you just created
7.  Go to Default project
8.  Click on Access Control setting
9.  Disable Access control

Results:
Takes you to a 404 and when you reload you are in the project instead of default.  You can no longer get to Access Control.  API key is using project API key and messing up ability to work in Default.  The only way to get out of this state is to restart Chrome.

Expected:
Should leave you in default project.

**Comment by vincent99** [comment]
This shouldn't happen any more with #303.  You also don't have to create a key to see the API.

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
