### ISSUE TITLE
No volumes are mounted if container is defined with more than 1 volumesFrom

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#422]
v0.14.2

Steps:
1.  Add a mysql container named sql1
2.  Add another mysql container named sql2
3.  Add a hello-world container and go to Advanced Options/Volumes
4.  Add both sql1 and sql2 containers

Results:
If you add two containers in Volume, then the newly created container is not shared with any Volume.

Expected:
Should be shared with both volumes.

**Comment by vincent99** [comment]
(Not UI, the dataVolumesFrom array is being sent correctly).

Confirmed with different containers and different set of hosts though.

**Comment by sangeethah** [comment]
Another scenario that always results in no volumes being mounted on the containers:

create service4 with scale 2.
create service3 with scale 2 and dataVolumesFromService set to service4.
create service2 with scale 2 and dataVolumesFromService set to service3, service4.
create service1 with scale 2 and dataVolumesFromService set to service2, service3, service4.

Activate environment / Activate any of the services in the environment.
After all the services are activated , all the containers in service1 do not have volumedFrom set for them.

| 898 | test578302_test278359_1 | 5 | container | 7b69dd01-fff8-4c2a-8892-eda217d8e9f1 | NULL | running | 2015-05-20 17:30:18 | NULL | NULL | {"fields":{"imageUuid":"docker:sangeetha/testclient:latest","networkIds":[2],"labels":{"io.rancher.service.deployment.unit":"8074e4b9-0596-41de-9f25-c6f54b33686c","io.rancher.service.sidekick":"test_multiple","io.rancher.service.name":"test278359","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}8074e4b9-0596-41de-9f25-c6f54b33686c":null,"io.rancher.environment.name":"test578302"},"dataVolumesFrom":[897,896,895],"dataVolumesFromService":[373,372,371],"tty":false,"privileged":false,"stdinOpen":false,"transitioningMessage":"post network","transitioningProgress":95,"dockerHostIp":"104.197.37.13","dockerPorts":{"22/tcp":null},"dockerIp":"172.17.1.60","primaryIpAddress":"10.42.131.175"},"dockerInspect":{"State":{"Pid":4813,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-05-20T17:30:19.305828272Z","ExitCode":0},"Config":{"PortSpecs":null,"Hostname":"8c145d5b02b5","Entrypoint":null,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":false,"MacAddress":"02:fc:6f:c4:c3:68","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/usr/sbin/sshd","-D"],"StdinOnce":false,"AttachStdin":false,"Volumes":null,"MemorySwap":0,"Tty":false,"CpuShares":0,"Domainname":"","Image":"sangeetha/testclient:latest","Labels":{"io.rancher.environment.name":"test578302","io.rancher.service.deployment.unit":"8074e4b9-0596-41de-9f25-c6f54b33686c","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}8074e4b9-0596-41de-9f25-c6f54b33686c":"","io.rancher.container.uuid":"7b69dd01-fff8-4c2a-8892-eda217d8e9f1","io.rancher.service.name":"test278359","io.rancher.service.sidekick":"test_multiple","io.rancher.container.ip":"10.42.131.175/16"},"ExposedPorts":{"22/tcp":{}}},"HostsPath":"/var/lib/docker/containers/8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01/hosts","Args":["-D"],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/usr/sbin/sshd","HostnamePath":"/var/lib/docker/containers/8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01/hostname","VolumesRW":{},"MountLabel":"","RestartCount":0,"Name":"/7b69dd01-fff8-4c2a-8892-eda217d8e9f1","Created":"2015-05-20T17:30:19.197264142Z","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"docker0","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"fe80::fc:6fff:fec4:c368","GlobalIPv6Address":"","IPAddress":"172.17.1.60","PortMapping":null,"IPPrefixLen":16,"LinkLocalIPv6PrefixLen":64,"MacAddress":"02:fc:6f:c4:c3:68","IPv6Gateway":"","Gateway":"172.17.42.1","Ports":{"22/tcp":null}},"AppArmorProfile":"","Image":"9ac374da8c7e03f34a17e977d03c911b16f1a9d8aa48a4527ff6eaf2b0e3749f","LogPath":"/var/lib/docker/containers/8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01/8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01-json.log","HostConfig":{"PortBindings":null,"Dns":null,"Memory":0,"CgroupParent":"","Privileged":false,"Ulimits":null,"CpusetCpus":"","DnsSearch":null,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"PublishAllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"NetworkMode":"","ExtraHosts":null,"LxcConf":null,"Devices":null,"Binds":null,"MemorySwap":0,"PidMode":"","VolumesFrom":null,"CapDrop":null,"Links":null,"IpcMode":"","ContainerIDFile":"","SecurityOpt":null,"CapAdd":null,"LogConfig":{"Config":null,"Type":"json-file"}},"Id":"8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01","ResolvConfPath":"/var/lib/docker/containers/8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01/resolv.conf"},"dockerContainer":{"Status":"Up Less than a second","Created":1432143019,"Image":"sangeetha/testclient:latest","Labels":{"io.rancher.environment.name":"test578302","io.rancher.service.deployment.unit":"8074e4b9-0596-41de-9f25-c6f54b33686c","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}8074e4b9-0596-41de-9f25-c6f54b33686c":"","io.rancher.container.uuid":"7b69dd01-fff8-4c2a-8892-eda217d8e9f1","io.rancher.service.name":"test278359","io.rancher.service.sidekick":"test_multiple","io.rancher.container.ip":"10.42.131.175/16"},"Id":"8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01","Command":"/usr/sbin/sshd -D","Names":["/7b69dd01-fff8-4c2a-8892-eda217d8e9f1"],"Ports":[{"Type":"tcp","PrivatePort":22}]}} | active | NULL | NULL | 898 | NULL | NULL | 1 | stop | NULL | NULL | 2015-05-20 17:30:19 | CsNCPSiGnSHKaE9JeCozRJCorDPGnlgClALWawGUjTbqPvZ7Kopf2czQYZ4JgceYC90sRzpGXFWiir9SvE1JA | NULL | NULL | NULL | 8c145d5b02b506de0c02817869b3999fc6aadc8cebe89276000e9b0b57eceb01 | |

| 902 | test578302_test278359_2 | 5 | container | db5e84d7-1f56-4bc1-8130-14e8ccf718cb | NULL | running | 2015-05-20 17:30:25 | NULL | NULL | {"fields":{"imageUuid":"docker:sangeetha/testclient:latest","networkIds":[2],"labels":{"io.rancher.service.deployment.unit":"048329dc-9b35-45e2-a90e-51d1b0d83267","io.rancher.service.sidekick":"test_multiple","io.rancher.service.name":"test278359","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}048329dc-9b35-45e2-a90e-51d1b0d83267":null,"io.rancher.environment.name":"test578302"},"dataVolumesFrom":[901,900,899],"dataVolumesFromService":[373,372,371],"tty":false,"privileged":false,"stdinOpen":false,"transitioningMessage":"post network","transitioningProgress":95,"dockerHostIp":"104.197.53.105","dockerPorts":{"22/tcp":null},"dockerIp":"172.17.1.45","primaryIpAddress":"10.42.155.208"},"dockerInspect":{"State":{"Pid":7968,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-05-20T17:30:26.54611722Z","ExitCode":0},"Config":{"PortSpecs":null,"Hostname":"1a97d5f1ab21","Entrypoint":null,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":false,"MacAddress":"02:fc:6f:7b:72:4c","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/usr/sbin/sshd","-D"],"StdinOnce":false,"AttachStdin":false,"Volumes":null,"MemorySwap":0,"Tty":false,"CpuShares":0,"Domainname":"","Image":"sangeetha/testclient:latest","Labels":{"io.rancher.environment.name":"test578302","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}048329dc-9b35-45e2-a90e-51d1b0d83267":"","io.rancher.service.deployment.unit":"048329dc-9b35-45e2-a90e-51d1b0d83267","io.rancher.container.uuid":"db5e84d7-1f56-4bc1-8130-14e8ccf718cb","io.rancher.service.name":"test278359","io.rancher.service.sidekick":"test_multiple","io.rancher.container.ip":"10.42.155.208/16"},"ExposedPorts":{"22/tcp":{}}},"HostsPath":"/var/lib/docker/containers/1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50/hosts","Args":["-D"],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/usr/sbin/sshd","HostnamePath":"/var/lib/docker/containers/1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50/hostname","VolumesRW":{},"MountLabel":"","RestartCount":0,"Name":"/db5e84d7-1f56-4bc1-8130-14e8ccf718cb","Created":"2015-05-20T17:30:26.400664154Z","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"docker0","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"fe80::fc:6fff:fe7b:724c","GlobalIPv6Address":"","IPAddress":"172.17.1.45","PortMapping":null,"IPPrefixLen":16,"LinkLocalIPv6PrefixLen":64,"MacAddress":"02:fc:6f:7b:72:4c","IPv6Gateway":"","Gateway":"172.17.42.1","Ports":{"22/tcp":null}},"AppArmorProfile":"","Image":"9ac374da8c7e03f34a17e977d03c911b16f1a9d8aa48a4527ff6eaf2b0e3749f","LogPath":"/var/lib/docker/containers/1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50/1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50-json.log","HostConfig":{"PortBindings":null,"Dns":null,"Memory":0,"CgroupParent":"","Privileged":false,"Ulimits":null,"CpusetCpus":"","DnsSearch":null,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"PublishAllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"NetworkMode":"","ExtraHosts":null,"LxcConf":null,"Devices":null,"Binds":null,"MemorySwap":0,"PidMode":"","VolumesFrom":null,"CapDrop":null,"Links":null,"IpcMode":"","ContainerIDFile":"","SecurityOpt":null,"CapAdd":null,"LogConfig":{"Config":null,"Type":"json-file"}},"Id":"1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50","ResolvConfPath":"/var/lib/docker/containers/1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50/resolv.conf"},"dockerContainer":{"Status":"Up Less than a second","Created":1432143026,"Image":"sangeetha/testclient:latest","Labels":{"io.rancher.environment.name":"test578302","io.rancher.scheduler.affinity:container_label:io.rancher.service.deployment.unit{eq~}048329dc-9b35-45e2-a90e-51d1b0d83267":"","io.rancher.service.deployment.unit":"048329dc-9b35-45e2-a90e-51d1b0d83267","io.rancher.container.uuid":"db5e84d7-1f56-4bc1-8130-14e8ccf718cb","io.rancher.service.name":"test278359","io.rancher.service.sidekick":"test_multiple","io.rancher.container.ip":"10.42.155.208/16"},"Id":"1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50","Command":"/usr/sbin/sshd -D","Names":["/db5e84d7-1f56-4bc1-8130-14e8ccf718cb"],"Ports":[{"Type":"tcp","PrivatePort":22}]}} | active | NULL | NULL | 902 | NULL | NULL | 1 | stop | NULL | NULL | 2015-05-20 17:30:26 | ha3mJx8GbZDA6GmSmgbbD6tvNMpMU0LH1G91uMgMFlNMzUXj5rbuBDuPw0rz501mfmRdPXjn6Gxqhe9CEXw | NULL | NULL | NULL | 1a97d5f1ab2181755e5e51db50abfa1c18b816f12675ca902be09941f82e9f50 | |
