### ISSUE TITLE
[UI] Specify entrypoint when starting a container

### ISSUE THREAD

**Issue by mikehancock** [rancherio/rancher#426]
I am using Shippable to automate the process of building my application and dockerising it. The resulting dockerfile gets pushed to dockerhub upon a successful build, all well and good. 

This issue: https://github.com/Shippable/support/issues/981

details the reasons why I then have to specify an entrypoint when starting my docker image. There is no option in the UI, as far as I can see, to specify this. Is there something I am missing? Or is this a feature request? If so any idea how long it might take?

Thanks

**Comment by vincent99** [comment]
`endpoint` is in our app so it would just be adding a text field on the form.  @ibuildthecloud is there a reason we're not showing it today?

**Comment by ibuildthecloud** [comment]
No reason that it's not exposed.  We should add it to the UI

**Comment by mikehancock** [comment]
great, any idea how long it might take to get that pushed through to a release?

**Comment by mikehancock** [comment]
alternatively, since you say it's already in the API, could you provide a sample for posting a new container to the API? I notice the documentation link is marked as future.

**Comment by vincent99** [comment]
I should be able to add this tonight so it makes it into this week's beta release...

But to use the API:
  - Click on the API endpoint on that screen, which will bring you into the root of the API. [1]
  - Click on the "containers": ".../v1/containers" link
  - Click "+ Create" in the upper-right
  - You'll want at least a
    - `name`
    - `networkIds` (Managed)
    - `imageUuid` ("docker:blah")
    - And probably a `requestedHostId`
    - `entryPoint` is towards the bottom

[1]:  If you have access control on, you'll need to create an API key and copy/paste it into the Basic auth prompt.  And using keys like this can screw up the regular UI, so restart your browser afterwards until #303 is done.

**Comment by vincent99** [comment]
Added in rancherio/ui#113

**Comment by tfiduccia** [comment]
v0.15.0
Verified fixed in UI and that data is being passed in Post
