### ISSUE TITLE
HA/Failover containers?

### ISSUE THREAD

**Issue by janeczku** [rancherio/rancher#427]
I am wondering how rancher deals with nodes going down. What happens to the services/containers running on them?
For front-end services a load balancer obviously would take care of service availability. But what about linked backend containers? It would be great if rancher would automagically spin-up the affected container(s) on other available nodes and update the links with the parent container(s). Since it is already possible to share volumes with different containers, this is something that could even work with stateful applications.

**Comment by vincent99** [comment]
@janeczku Some of this functionality is available in the upcoming services capabilities.  Sharing volumes, however, is not possible across hosts, so it wouldn't help you reschedule a container onto a new host if one dies.

**Comment by deniseschannon** [comment]
@janeczku We recently released latest (today) with a lot of enhancement in services. With services, if one of the nodes (i.e. hosts) goes down, it will try and find another host to maintain the scale of the service. As @vincent99 mentioned, the sharing volumes would wouldn't work if the volume on a host did die. 

I'm going to close this issue as the latest release of services addresses your needs. If you have any bugs or need help with services, please feel free to open a new issue.
