### ISSUE TITLE
Show machine error instead of showing 'exit status1'

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#428]
v0.14.2

If I get an error that an existing machine already exists, the correct error is being hidden and is only showing 'exit status 1'.

Don't filter out the error message.

```bash
time="2015-04-03T16:57:35Z" level=info msg="stdout: time=\"2015-04-03T16:57:35Z\" level=\"error\" msg=\"Error creating machine: Machine denisetest1 already exists\" " 
resourceId: ="1ph19" 
time="2015-04-03T16:57:35Z" level=info msg="stdout: time=\"2015-04-03T16:57:35Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine 
and associated resources were properly removed.\" " resourceId: ="1ph19" 
time="2015-04-03T16:57:35Z" level=info msg="stdout: time=\"2015-04-03T16:57:35Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: ="1ph19" 
time="2015-04-03T16:57:35Z" level=error msg="Error processing event" err="exit status 1" eventId="e2fbdb89-5e24-4994-8738-1a4899164766" eventName="physicalhost.create;
handler=goMachineService" resourceId="1ph19" 
```

**Comment by deniseschannon** [comment]
Another issue where exit status 1 is being shown instead of the actual error.

```bash
time="2015-04-03T17:26:53Z" level=info msg="stdout: time=\"2015-04-03T17:26:53Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/4c2982ad-c89c-4aec-913b-4de
72019c28d/certs/ca.pem\" " resourceId: =1ph28 
time="2015-04-03T17:26:53Z" level=info msg="stdout: time=\"2015-04-03T17:26:53Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/4c2982ad-c8
9c-4aec-913b-4de72019c28d/certs/cert.pem\" " resourceId: =1ph28 
time="2015-04-03T17:26:54Z" level=info msg="stdout: time=\"2015-04-03T17:26:54Z\" level=\"info\" msg=\"Creating SSH key...\" " resourceId: =1ph28 
time="2015-04-03T17:26:55Z" level=info msg="stdout: time=\"2015-04-03T17:26:55Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" " resourceId: =1ph28 
time="2015-04-03T17:27:29Z" level=info msg="stdout: time=\"2015-04-03T17:27:29Z\" level=\"error\" msg=\"Error creating machine: OS type not recognized\" " resourceId: 
=1ph28 
time="2015-04-03T17:27:29Z" level=info msg="stdout: time=\"2015-04-03T17:27:29Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine 
and associated resources were properly removed.\" " resourceId: =1ph28 
time="2015-04-03T17:27:29Z" level=info msg="stdout: time=\"2015-04-03T17:27:29Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: =1ph28 
time="2015-04-03T17:27:29Z" level=error msg="Error processing event" err="exit status 1" eventId="84a41089-61ee-4c4c-98a9-496979db5915" eventName="physicalhost.create;
handler=goMachineService" resourceId=1ph28 
```

**Comment by sangeethah** [comment]
Server version - V0.15.1

I am still able to reproduce this issue occasionally. Digital Ocean is currently under maintenance and not allowing droplet creation.

I added 7 Digital Ocean Machines , all of them failed for the same reason.

3 of the machine failures provided the correct error message - " Error creating machine: GET https://api.digitalocean.com/v2/regions: 500 Looks like something went wrong. If this continues, please open a support ticket so we can help you out.".

But other 4 machine failures have error message - "exit status 1"

logs:
time="2015-04-10T20:46:45Z" level=info msg="Creating Machine" eventId=e20676ed-fabe-44eb-a778-e450a6bf203d resourceId=1ph20
time="2015-04-10T20:46:45Z" level=info msg="Cmd slice: [create -d digitalocean --digitalocean-access-token 221b602502f01ebb9bb06dd916068cf99dec300d6bd1a5d7491bca7d608564b1 test-51581]"
time="2015-04-10T20:46:45Z" level=info msg="stdout: time=\"2015-04-10T20:46:45Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/f5b72ed9-9b68-4e64-8023-09633aa92d25/certs/ca.pem\" " resourceId: =1ph20
time="2015-04-10T20:46:46Z" level=info msg="stdout: time=\"2015-04-10T20:46:46Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/f5b72ed9-9b68-4e64-8023-09633aa92d25/certs/cert.pem\" " resourceId: =1ph20
time="2015-04-10T20:46:50Z" level=info msg="stdout: time=\"2015-04-10T20:46:50Z\" level=\"error\" msg=\"Error creating machine: GET https://api.digitalocean.com/v2/regions: 500 Looks like something went wrong. If this continues, please open a support ticket so we can help you out. \" " resourceId: =1ph20
time="2015-04-10T20:46:50Z" level=info msg="stdout: time=\"2015-04-10T20:46:50Z\" level=\"warning\" msg=\"You will want to check the provider to make sure the machine and associated resources were properly removed.\" " resourceId: =1ph20
time="2015-04-10T20:46:50Z" level=info msg="stdout: time=\"2015-04-10T20:46:50Z\" level=\"fatal\" msg=\"Error creating machine\" " resourceId: =1ph20
time="2015-04-10T20:46:50Z" level=error msg="Error processing event" err="exit status 1" eventId=e20676ed-fabe-44eb-a778-e450a6bf203d eventName="physicalhost.create;handler=goMachineService" resourceId=1ph20

**Comment by sangeethah** [comment]
Marking it as "Resolved" since this fix is not available in 0.15.1
Will retest and close with later version that has this fix.

**Comment by deniseschannon** [comment]
Docker Machine is much more stable so haven't seen any errors in awhile. QA will be on the lookout if it happens again.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @sangeethah)
