### ISSUE TITLE
[LB] - When all the targets are in stopped/removed state , the port on the host continues to bound to the LB agent.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#430]
Version - V.14.2

Steps to reproduce the problem:

Create LB with 3 targets.
Stop all the 3 containers.
After this , the port on the host continues to be bound to the LB agent.
Even after the containers are removed , the port on the host continues to be bound to the LB agent.

Should the LB agent be stopped , since it is not servicing any container at this time ?
The port on the host that is pointing to the LB agent needs to be released.

**Comment by deniseschannon** [comment]
The comments on #430 would relate to this. 

@alena1108 wrote: 
It was designed this way to simply avoid more complicated logic. **Today haproxy lifecycle is controlled by adding/removing host to the load balancer. If we do it based on adding/removing listener/target, we will have to take care of more use cases** (On removal: if the listener removed is the last listener, or is the target removed is the last target; On creation: when target gets added, we should check if there is at least one listener there, etc). We can address this one later after major functional bugs are fixed.

**Comment by sangeethah** [comment]
Tested with server version - V0.16.0

Version - V.14.2

Create LB with 3 targets.
Stop all the 3 containers.
After this , the port on the host is released.LB agent continues to be running.

Started 1 container . This resulted in the LB rules being programed in LB agent and port being bound on the host.

 Delete this container. The port on the host is released. LB agent continues to be running. 

Works as expected. Closing this issue.
