### ISSUE TITLE
[UI][Machine] Incorporate new DO and EC2 addHost forms

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#433]
Incorporate some new changes to the AddHost screens for DigitalOcean and EC2.  Images can be found in the UI Final folder.

**Comment by will-chan** [comment]
Please include #389 in this as well.

**Comment by tfiduccia** [comment]
v0.15.0
Verified fixed.  Dividers, additional security text verified.  DO Options removed due to backend not completed.
