### ISSUE TITLE
LB - "LoadBalancerConfigIsInUse" error encountered when trying to delete lb.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#434]
Server Version - V0.14.2

Steps to reproduce the problem:

Create LB with LB configuration that has 1 listener associated with it.
Add 1 host to this LB.
Add 2 targets to this LB.
Add 1 listener to the LB configuration that is attached to this LB.
Try ti delete LB.

I see the following exception:

(ApiError(...), "LoadBalancerConfigIsInUse : LoadBalancerConfigIsInUse\n{'status': 409, 'code': u'LoadBalancerConfigIsInUse', 'links': {}, 'detail': None, 'actions': {}, 'message': u'LoadBalancerConfigIsInUse', 'type': u'error', 'id': u'0fdcfdd1-78c3-41f9-b6c5-0af8ad2fcf1d'}")

When I try to delete LB again , it succeeds.

**Comment by alena1108** [comment]
@sangeethah Sangeetha, please provide the cattle server logs. Also are you sure you didn't try to delete the load balancer config itself? This error is thrown when try to delete the config that is in use by existing load balancer.

**Comment by sangeethah** [comment]
I was actually trying to delete the loadbalancer config that was attached to LB in "active" state which was resulting in this error message.

Closing this issue , since the behavior seen is expected.
