### ISSUE TITLE
Same port cannot be used by 2 balancers/containers on the same host

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#435]
Server - V0.14.2

Steps to reproduce the problem:
Create LB1 with LB config that has LB listener with source port 8084.
Add 2 targets (con1,con2)
Add host h1.
Make sure that Lb is functional.
stop con1 and con2.

Create LB2 with LB config that has LB listener with source port 8084.
Add 2 targets (con3,con4)
Add same host h1.

LB rules are not functional.

Both the Lb agent's ipaddress and port are bound to port 8084. The newly added LB rule gets programmed later in the ip chain and does not take effect.

iptable rules from host:

-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8084 -j DNAT --to-destination 10.42.237.152:8084
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8085 -j DNAT --to-destination 10.42.237.152:8085
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8084 -j DNAT --to-destination 10.42.2.2:8084

**Comment by alena1108** [comment]
We don't restrict from adding the same rule for the same host. Its up to user to control it.

**Comment by sangeethah** [comment]
We should at least be giving some indication to user when there is an attempt made to add an LB listener with a port to a host where the port is already in use ?

**Comment by vincent99** [comment]
+1, I don't think we can just dismiss this.  Without validation or display the user has no confidence that the balancer they created will actually work on all the hosts it's deployed to.

**Comment by alena1108** [comment]
This problem is generic in Cattle. As there is no validation for ports conflicts, so instances with conflicting public ports are allowed to be deployed on the same host - this logic is being re-used by the load balancer. Its has to be fixed for sure, but on a bigger scale.

**Comment by alena1108** [comment]
Should be fixed with allocators port conflict fixes.

**Comment by alena1108** [comment]
Rephrasing: closing the bug as won't fix. In standalone Lb case, allocator doesn't perform any checks as we leave the decision of what host to pick, to the user.

**Comment by flaccid** [comment]
@alena1108 I agree, however could get a view added to the UI to show the host ports in use and by which containers, LBs etc.?

**Comment by ibuildthecloud** [comment]
@flaccid.  I think that sounds like a good feature.  @vincent99 containers now have a ports field that is readable.  It's not 100% correct but we could fix that.

**Comment by vincent99** [comment]
Seems like it would make sense on the host details screen to show the ports and what container they were bound to.
