### ISSUE TITLE
Docker machine integration for Digital Ocean requires access token to be entered for every launch

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#437]
Currently for Digital Ocean Host registration we need to enter the access token every time. It should be possible to enter the credential(s) once and then have them pre-configured for subsequent launches or selectable from a drop down.

**Comment by vincent99** [comment]
We don't really want to store your 3rd party credentials into the database at this point, but the UI can at least be updated to remember them in local (browser) memory across creates (until a page reload).

**Comment by vincent99** [comment]
Merging into broader #494
