### ISSUE TITLE
[UI][Container] - "Container" link lands on the action that was performed earlier , instead of landing on the container list view.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#439]
Server version - V0.14.2
[UI][Container] - "Container" link lands on the action that was performed earlier , instead of landing on the container list view.

Steps to reproduce the problem:

1. From Containers page , click on any container to launch the container detail page.
2. From container detail page , do some action like "Execute Shell"/"View log".
3. Close this action to get back to the container detail page.
4. Click on the "Container" link on this page.
5. It launches the action page from step 2.

Expected behavior:
It should launch the container list view.

**Comment by deniseschannon** [comment]
Already filed #242.
