### ISSUE TITLE
[LB] - When container is restarted , it  is not part of LB configuration any more.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#441]
Server Version - V 0.14.2

Steps to reproduce the problem:
Create LB with LB configuration that has 1listener attached to it.
Add 3 targets and 1 host to it.

Restart one of the containers.
When accessing the LB ipaddress , the restarted container is not reachable.

In LB agent, the server entry for the container gets removed from the "backend" node in /etc/haproxy/haproxy.cfg .

Expected Behavior:
After restart of container , the containers should still be reachable from the LB paddles.

**Comment by alena1108** [comment]
Hm, looks like restart - stop with chained start action - is not treated as stop/start sequence from processes stand point. As on instance.start we usually reconfigure the config. Good catch, @sangeethah

**Comment by sangeethah** [comment]
Server Version - V 0.16.0

Create LB with LB configuration that has 1listener attached to it.
Add 2 targets and 1 host to it.

Restart one of the containers.
When accessing the LB ipaddress , the restarted container is also accessible now.

Closing this issue.
