### ISSUE TITLE
Ability to deploy multiple hosts/containers at once with the same configuration

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#444]
Version v0.14.2

Similar to #369 and #279, it'd be nice if we could just deploy a specific number of hosts at once with the same configuration. Resolving the other issues, might eliminate this enhancement, but as a user if you are creating more than 1 additional host/container of same config, it might be annoying.

**Comment by deniseschannon** [comment]
For host, the slider in the UI allows for multiple hosts to be created at once. Or you can clone a host. 

For containers, multiple containers would be a service.

**Comment by vincent99** [comment]
You can also clone containers and services.
