### ISSUE TITLE
[UI][LB] - Not able to create an LB without health check (by clearing all field values).

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#445]
Version - Build from master on Apr 7

When attempting to create LB config ( as part of LB rule creation) , the Health Check tab has values for "Check Interval"/"Time Out"/"Healthy Threshold"/"Unhealthy Threshold" pre populated.

When i tried to clear all the values and create LB , creation of LB fails with - "Validation failed: interval" .

There should be a way for us to create LB config with no health checks.

**Comment by vincent99** [comment]
Closing in favor of duplicate #446 which has some discussion
