### ISSUE TITLE
[UI] [LB] Health Check tab is defaulted to certain settings, but it should default to nothing. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#446]
Version: Build from master (4/7/15)

LB Health Check is automatically defaulted with some parameters. We should default with no health check and have the user explicitly add the health check if desired.

Maybe have it started off with nothing and have a + button to expand and then show the Health Check policy.

Note: The user can only add 1 health check policy.

**Comment by vincent99** [comment]
AFAIK without a `healthCheckConfig` HAProxy will continue to blindly send traffic to dead/stopped containers, so a balancer without one is not particularly useful, especially as a default.

It could maybe be optional and defaulted to on, but I'm not sure what the use case for a checkless balancer most people would consider "broken" is.

**Comment by alena1108** [comment]
Vince is right. We should default the healtcheck, otherwise user will have to monitor his instances and remove the target for them when they become non-responsive. Healtcheck delegates it to haproxy

**Comment by vincent99** [comment]
Closing as intentional behavior.  However the URI part of the check will be updated in #468 so that the default is just a TCP connection check, not a HTTP request.
