### ISSUE TITLE
If I fail to create LB, it still gets saved as a config

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#448]
v0.15.0

Steps:
1.  Add a balancer
2.  Put in a host and a target but leave out listening port
3.  Click on create
4.  Leave Add a balancer and go to Configurations

Results:
The LB does not create and throws an error but the configuration for that balancer creates.  This can cause multiple configurations with the same name to be created as user fixes the problems and finally creates.

Expected:
Configuration should not save until LB is actually allowed to create as well.

**Comment by vincent99** [comment]
@tfiduccia Is there still a way to cause this in 0.17 now that there is client-side validation?

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed with validation
