### ISSUE TITLE
Configs in a removed state should not show up in Add

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#450]
v0.15.0

Steps:
1.  Delete a config
2.  Go to Add LB
3.  Select Re-use existing container drop-down

Results:
The removed config is still in the drop-down

Expected:
Configs in a removed state should not be in dropdown

**Comment by vincent99** [comment]
Related to #297 / #384.

**Comment by vincent99** [comment]
The dropdown now only shows configs in `state=active`.

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
