### ISSUE TITLE
[UI] [LB] On a LB, if I click 'Edit' nothing happens.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#453]
Version: Build from master (4/7/15)

Steps to Reproduce:
1. Create a LB.
2. Click on the dropdown in the upper right corner.
3. Click on 'Edit'

Result: Nothing happens.

Expected Result: Taken to the Edit page for the LB.

**Comment by vincent99** [comment]
Edit screen added (for name & description, the rest is on other screens)

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
