### ISSUE TITLE
[UI] [LB] In a LB, 'Remove Target' doesn't work. Nothing happens.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#455]
Version: Build from Master (4/7/15).

1. Launch a LB with a container (target).
2. Click on 'Remove Target' for the container.

Result: Nothing changes

Expected Result: Container should be removed from LB.

**Comment by vincent99** [comment]
Fixed on the main `/balancing/balancers` page, it worked on the Targets section of a particular balancer (`/balancing/balancers/:id/targets`)

**Comment by tfiduccia** [comment]
v0.16.0
Verified fixed
