### ISSUE TITLE
[UI] [LB] On an existing LB, 'Add Target' doesn't work 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#456]
Version: Build from Master

1. Create an LB. 
2. After the LB is created, 'Add Target'.

Result: Nothing happens

Expected Result: Ability to add another target. Question: Should this add a new container? Would we have the ability to select an existing container (similar to when setting up the LB)?

**Comment by vincent99** [comment]
Adding a target is only for an existing container (or an external IP).  This is fixed in rancherio/ui#115

**Comment by tfiduccia** [comment]
Build from latest 4/8/15
Verified fixed
