### ISSUE TITLE
On the LB, would like to see host names of hosts that are part of LB.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#457]
Version: Build from Master (4/7/15)

Instead of only seeing the number of hosts in a LB on the summary of LB page. It'd be nice to show all the hosts and status of the host.

![screen shot 2015-04-07 at 12 16 32 pm](https://cloud.githubusercontent.com/assets/11410997/7031800/1ba4749e-dd23-11e4-84c5-0a3f558aad3c.png)

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
