### ISSUE TITLE
[UI][LB] Removed LB is still showing up on Config page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#458]
v0.15.0

Steps:
1.  Create a LB with a new config
2.  Remove the LB
3.  Go to Config page

Results:
The Config is there and still shows the LB that was removed

Expected:
LB should no longer be referenced on Config page

**Comment by vincent99** [comment]
Related to #297 / #384.

**Comment by vincent99** [comment]
These are still coming back from the API but are now filtered out in the UI.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
