### ISSUE TITLE
[UI][LB] Edit on Config page does nothing

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#459]
v0.15.0
Steps:
1.  Go to LB Config page
2.  Click on Edit for one of the configs

Results:
Nothing happens

Expected:
Should go to edit page

**Comment by deniseschannon** [comment]
When showing the detailed LBConfig, the Edit link doesn't work either.
![screen shot 2015-04-07 at 1 02 46 pm](https://cloud.githubusercontent.com/assets/11410997/7032281/7d812f38-dd26-11e4-8cb9-fe1a3fb0a435.png)

**Comment by vincent99** [comment]
Added balancer config edit (name and description only)

**Comment by tfiduccia** [comment]
v0.16.0
Verified fixed
