### ISSUE TITLE
Feature: Support for public/private/hosted Docker registry

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#46]
Rancher currently supports the official Docker images from : https://github.com/docker-library

Rancher needs to provide support for:
* public and private DockerHub registry
* hosted Docker registry
* allow users to pull/push Docker images from/to the hosted Docker registry
* allow for multiple Docker registries

**Comment by sheng-liang** [comment]
It makes sense for Rancher to support multiple Docker registries. Some customers have that setup.

Sheng

**Comment by ibuildthecloud** [comment]
Just to clarify, Rancher.io currently supports public DockerHub, not just the official images.
