### ISSUE TITLE
[UI][LB] Should be able to delete Configs that have no associated LB

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#460]
v0.15.0

Steps:
1.  Create a LB with a new config
2.  Delete the LB
3.  Go to config page
4.  Try to remove config

Results:
Can't remove Config.

Expected:
Should be able to remove Config.

This might be related to #458, since the LB isn't removed from the config.

**Comment by vincent99** [comment]
Yes, there is an action to delete them but you can't trigger it if extra balancers in removed states show up, #297 / #384.

**Comment by vincent99** [comment]
Fixed by #458, since I ignore removed ones the logic for if you should be able to remove now works.

**Comment by tfiduccia** [comment]
v0.16.0
Verified fixed
