### ISSUE TITLE
[UI] [LB] Removed Target is still showing up on UI

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#462]
Version: Build from Master (4/7/15)

If I remove a target through the detailed LB page (only way because of #455), the target shows up as "Removed" on the Targets page.

In the API, the target is no longer a Load Balancer Target for this Load Balancer, but the UI still displays the target in the detailed version as Removed.

Option 1: Keep the removed container, Hide the 'Remove Target' dropdown.
Option 2: Remove the container when it's done.

![screen shot 2015-04-07 at 12 28 05 pm](https://cloud.githubusercontent.com/assets/11410997/7031813/2a736318-dd23-11e4-82f0-161a8c0a1280.png)

In the Load Balancer summary page, the container still shows up.

![screen shot 2015-04-07 at 12 29 03 pm](https://cloud.githubusercontent.com/assets/11410997/7031815/2e0f0f04-dd23-11e4-8582-36374fdba3f0.png)

**Comment by vincent99** [comment]
Related to #297 / #384.

**Comment by vincent99** [comment]
Removed targets are now filtered out by the UI.

**Comment by tfiduccia** [comment]
v0.16.0
Target removed - Verified Fixed
