### ISSUE TITLE
[UI] [LB] Remove host from LB doesn't work.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#463]
Version: Build from Master (4/7/15)

1. Create a LB with 2 hosts
2. Go to detailed LB page.
3. Click on Hosts link for LB.
4. Click on 'Remove Host'. Host is removed from API and LB Agent is removed.

Result: No change in UI.

Expected Result: Page to refresh to show that the host is being removed or the host has been removed.

**Comment by vincent99** [comment]
Doesn't work, or is removed but not reflected in the UI?

**Comment by deniseschannon** [comment]
It's working in the UI now. It was working in the API, but not UI.

Fixed in Build 4/8/15
