### ISSUE TITLE
Already annoying that I have to click on Balancing and then Balancers to get the summary page of Load Balancers

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#464]
Version: Build from Master (4/7/15)

As I've been testing, it's already annoying that every time I want to go back to Load Balancers, I have to click on Balancing, which takes me to this page.

![screen shot 2015-04-07 at 12 53 55 pm](https://cloud.githubusercontent.com/assets/11410997/7032145/903d4a4a-dd25-11e4-900f-1c5c3e8867a4.png)

And then I have to click on the 'Balancers'.

**Comment by vincent99** [comment]
It could default to going to the balancers section if there are any maybe?  There will be other stuff like global balancers here too and we didn't want to have several top-level boxes on the left for different parts of balancing.

**Comment by tfiduccia** [comment]
You could have a "don't show in future" checkbox at bottom.  So anyone that doesn't want to see it anymore can just check it.  It can be tied to a cookie, so if they want it back we can just tell them to delete the cookie.

**Comment by vincent99** [comment]
In the new UI they are currently 2 separate tabs so this page is gone.  We might further simplify by just removing the reusing saved configurations thing..

**Comment by tfiduccia** [comment]
v0.21.3
Verified fixed
