### ISSUE TITLE
[UI][LB] Have to refresh page to see LB create completion

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#465]
v0.15.0

Steps:
1.  Go to LB page (I'm unauthorized)
2.  Create LB
3.  Wait

Results:
LB will show processing until I hard refresh the page.

Expected:
LB should refresh when done creating.

**Comment by vincent99** [comment]
@alena1108 is still working on the API-side fix for this, but the UI now polls correctly for changes eventually, and I lowered the interval to 5 seconds for now for `loadBalancerListeners` and `loadBalancerTargets`

**Comment by tfiduccia** [comment]
Build from latest 4/8/15
Verified Fixed
