### ISSUE TITLE
[UI][LB] LB that uses an existing Config not showing up on Config page until hard refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#466]
v0.15.0

Steps:
1.  Create LB1 with new config
2.  Go to config page (see LB1's config and Used by says LB1)
3.  Go back to LB page and create LB2 and use LB1 config
4.  Go to config page

Results: LB2 not showing up in Used by until I do a hard refresh of page.

Expected:  LB2 should show up in LB1's config's Used by list automatically.

**Comment by vincent99** [comment]
Fixed in rancherio/ui#115

**Comment by tfiduccia** [comment]
Build from latest 4/8/15
Verified failed

**Comment by tfiduccia** [comment]
v0.15.0 beta
Verified fixed.
