### ISSUE TITLE
Change healthcheck URL to do method + path + version + host header

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#468]
Server - build from master on Apr 7

In "Add Load Balancer" page , "Check URL" has "http://example.com/health-check" as helper text.

The URI passed should be of the format - "http method" "uri" . Example of the health check uri i used - GET /hostname.html.

Also "Check URL" should be renamed to "Check URI"

**Comment by alena1108** [comment]
Vince, if HTTP method is not specified, its defaulted to OPTION on the haproxy side. And if option requests are rejected by the target web server, the request is always gonna fail. We might wanna show the dropdown with available methods to an end user - OPTION/GET/.. and construct the URI parameter as <method> <uri>.

**Comment by vincent99** [comment]
Ok that's kind of weird to call the field URI if it's really method+path+http version+http headers...

But anyway no normal human understands URL vs URI (and this isn't it), so it was intentional to label it URL.

Changing it to a drop down of methods and labeling it as a path + whatever other options are available sounds good, I can assemble them into the format haproxy wants.  I think the field should be called `httpRequest` or something in the API though.

**Comment by alena1108** [comment]
@vincent99 I directly translated the naming from haproxy..wasn't a good idea. What about "heathcheckRequest" for the name? Or would it be a tautology considering its the field of the object called healthCheck

**Comment by vincent99** [comment]
Are you doing any special processing or do you just do `option httpchk ${uri}`? The full form is several different properties for haproxy:

`option httpchk <method> <uri> <version>`

In the HTTP spec it's called the "Request-Line":

`Request-Line   = Method SP Request-URI SP HTTP-Version CRLF`

So how about calling it `requestLine`, and as far as naming is concerned we'll ignore the part where `<version>` might also contain CRLF and some HTTP headers.

**Comment by alena1108** [comment]
@vincent99 ok, lets call it request line as I just put "httpcheck <whatever is passed in this parameter>" to the haproxy config

**Comment by vincent99** [comment]
UI changed to produce method + uri + version + optional Host header.  The field in the API isn't renamed yet.

**Comment by tfiduccia** [comment]
v0.16.2 (UI / latest)
Verified Fixed

**Comment by vincent99** [comment]
Repoening to reverify because the field was renamed from uri -> requestLine...

**Comment by tfiduccia** [comment]
v0.18.1
Verified Fixed
