### ISSUE TITLE
[LB] - When empty uri is sent when creating LB , we get "503 Service Unavailable" when trying to access the LB ipaddress.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#469]
Server - build from mater on Apr 7

When creating LB , have some text and delete it from the "Check URL" field for LB config .
uri gets sent as empty string in this case:

healthyThreshold: 2
interval: 2000
responseTimeout: 2000
type: "loadBalancerHealthCheck"
unhealthyThreshold: 3
uri: ""
Lb rule gets created successfully.

But we get "503 Service Unavailable" when trying to access the LB ipaddress.

Following is the haproxy configuration in LB Agent:

backend 6cc3efd3-7f98-4bcd-b625-7884cb3d0691_backend
        mode http
        balance roundrobin
        timeout check 2000
        option httpchk 
        server 4948f728-b657-4601-805f-44246fa59628 10.42.230.203:80 check inter 2000 rise 2 fall 3
        server 88e9dfa5-0264-4c23-9965-e56d1fffd960 10.42.252.27:80 check inter 2000 rise 2 fall 3

**Comment by vincent99** [comment]
That is a valid `httpchk`, so it's using the defaults and making `OPTIONS / HTTP/1.0` requests, getting no response and marking all the targets as down...  With no targets up you get back 503 responses from HAProxy.

Not setting `httpchk` if the `uri` (soon `requestLine`) is empty/null makes sense.  The UI will either send null or the full `"<method> <uri> <version>"` form.

**Comment by sangeethah** [comment]
Tested with Server - V0.16.0

Created LB with LB config using the following health check policy having empty string as "uri" 
healthCheck: {interval: 2000, responseTimeout: 2000, healthyThreshold: 2, unhealthyThreshold: 3, uri: ""}
healthyThreshold: 2
interval: 2000
responseTimeout: 2000
unhealthyThreshold: 3
uri: ""
id: "1lbc4"
kind: "loadBalancerConfig"
lbCookieStickinessPolicy: null

When this LB is programmed in the LB agent , there is no "option httpchk" programmed in haproxy.cfg.

Lb rule works as expected.

frontend 7fd3168e-a063-4145-8c1d-caa180fde2e1_frontend
        bind 10.42.209.124:9102
        mode http
        default_backend 7fd3168e-a063-4145-8c1d-caa180fde2e1_backend

backend 7fd3168e-a063-4145-8c1d-caa180fde2e1_backend
        mode http
        balance roundrobin
        timeout check 2000
        
        server fd8ba599-c316-4732-aa35-5789f1aebec7 10.42.212.206:80 check inter 2000 rise 2 fall 3
        server 7b950fab-e022-4dda-98cb-9c89f8fb6549 10.42.159.222:80 check inter 2000 rise 2 fall 3
