### ISSUE TITLE
[LB][UI] - "Edit" option presented when LB is in "Removed" state

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#470]
Server - built from master on Apr 7

Steps to reproduce the problem:

Create LB.
Delete LB.
When it is "Removed" state , notice that there is "Edit" option available.

Expected Behavior:
When LB is in "Removed" state , do not show "Edit" option.

**Comment by vincent99** [comment]
Removed is (currently) the final state for a balancer so it shouldn't be visible in the first place when it's in that state (#458) to have seen the available actions.

**Comment by vincent99** [comment]
Removed balancers are now hidden

**Comment by tfiduccia** [comment]
v0.16.0
After delete, the LB is no longer visible.
Verified Fixed
