### ISSUE TITLE
[UI][LB] - Load Balancer Configurations - "Stickiness" value is interchanged between "Use Existing cookie" and "Create Cookie"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#473]
Server - Built from main on Apr 7

Steps to reproduce the problem:
Create  LB configuration choosing "Create new cookie" option.
When this LB configuration is listed in the "Load Balancer Configurations" page , stickiness column is set as "Use existing cookie".

Similarly , LB configuration created with "Use existing cookie" shows up as Lb configuration with stickiness as "Create new cookie" in "Load Balancer Configurations" page .

**Comment by vincent99** [comment]
Labeled backwards in the configs list, fixed in rancherio/ui#115

**Comment by tfiduccia** [comment]
Build from latest 4/8/15
Verified fixed
