### ISSUE TITLE
[UI][LB] - Add Load Balancer - Removed LB configurations are listed in "Choose an existing Balancer Configuration".

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#474]
Server - Built from master on Apr 7

Steps to reproduce the problem:
Create LB configuration.
Delete this configuration.
Add LB using "Choose an existing Balancer Configuration".
The deleted configuration is still listed in the UI.
When this configuration is chosen , LB is created successfully.

UI should not allow for creating LB with LB configuration that are in "Removed" state.

**Comment by vincent99** [comment]
Fixed in rancherio/ui#115

**Comment by tfiduccia** [comment]
v0.15.0
Verified fixed.  Configs in removed state do not show up in drop-down.
