### ISSUE TITLE
[UI] [LB] Update text in Load Balancers Intro Page

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#477]
Update the text content in the Load Balancers Intro Page.

Start with this text for now.

**Load Balancers**

Our Load Balancer distributes network traffic across a number of containers. This is a key requirement for developers and ops who want to deploy large-scale applications. Load balancing support is notoriously uneven across different clouds. By offering a uniform, simple, and powerful load balancer solution, Rancher makes it possible for Docker developers to port applications easily across multiple clouds, or to use different cloud providers as independent resource pools to host highly available applications.

The Load Balancer is created and managed by Rancher. For each host selected for a Load Balancer, a LB Agent (i.e. Load Balancer Agent) container is started and HAProxy software is installed in it. This container treated like a Rancher Container

**Load Balancer Configurations**

A Load Balancer Config is a configuration that is used to set up a Load Balancer. The Load Balancer Config includes Load Balancer Listener(s), a Health Check Policy and cookie policies (i.e. Stickiness). When a Load Balancer is created, the Load Balancer Config is used to create the HAProxy config in the HA Proxy software inside the LB Agent. The Load Balancer Config can be used in multiple Load Balancers. 

Note: If any change is made to the Load Balancer Config, it will be propagated on all Load Balancers using that Load Balancer Config.

**Load Balancer Listeners**

A Load Balancer Listener is a process that listens for connection requests. It is a one to one mapping of a port for the sources (i.e. hosts) to a port for the targets (i.e. containers/external public IPs) with protocols established for each port.  An algorithm is also selected for each listener to determine which target should be used.

**Comment by deniseschannon** [comment]
@alena1108 We'll probably need to review to see what exact content we should put on the intro page, but @smw355 wanted it to be updated before we push master to the latest tag

**Comment by vincent99** [comment]
Changed in rancherio/ui#116

**Comment by alena1108** [comment]
@deniseschannon 

* We should remove "Listeners" section as LB Listener is not a first class object in the UI.

* In the Load Balancer section, we should cover what "target" is as we already cover the host. Also I think we should highlight the key LB terms - Host, Target, Listener, Config.

* We should either stick to the full name - Load Balancer, or its abbreviation - LB - in the text, but don't mix both. 

* "This container treated like a Rancher Container" - this statement is vague. Plus its not really a regular container, but the system container. Meaning its lifecycle is controlled by Rancher system, not by the user. We can just say that on every host chosen for the Load Balancer, Rancher starts system container <name> with the haproxy software installed on it.

**Comment by deniseschannon** [comment]
I've only used LB when referring to the "LB Agent" as that is what the container name is called. I have updated to make it say Load Balancer Agent. Do we think it's intuitive that the "LB Agent" container is referencing the Load Balancer?

@alena1108  How's this sound as a revised intro page?

**Load Balancers**

Our Load Balancer distributes network traffic across a number of containers. This is a key requirement for developers and ops who want to deploy large-scale applications. Load balancing support is notoriously uneven across different clouds. By offering a uniform, simple, and powerful load balancer solution, Rancher makes it possible for Docker developers to port applications easily across multiple clouds, or to use different cloud providers as independent resource pools to host highly available applications.

The Load Balancer is created and managed by Rancher. For each host selected for a Load Balancer, a Load Balancer Agent container is started and HAProxy software is installed in it.  

The target of a Load Balancer can be any containers or any external IP address that you want traffic distributed for. 

 

**Configurations**

A Load Balancer Config is a configuration that is used to set up a Load Balancer. The Load Balancer Config includes Load Balancer Listener(s), a Health Check Policy and cookie policies (i.e. Stickiness). When a Load Balancer is created, the Load Balancer Config is used to create the HAProxy config in the HAProxy software inside the Load Balancer Agent. The Load Balancer Config can be used in multiple Load Balancers.

Note: If any change is made to the Load Balancer Config, it will be propagated on all Load Balancers using that Load Balancer Config.

A Load Balancer Listener is process that listens for connection requests. It is a one to one mapping of a port for the sources (i.e. hosts) to a port for the targets (i.e. containers/external public IPs) with protocols established for each port.  An algorithm is also selected for each listener to determine which target should be used.

**Comment by alena1108** [comment]
@deniseschannon Lets add system to  "Load Balancer Agent <system> container "

**Comment by deniseschannon** [comment]
@vincent99 I've updated the text in my comment with Alena's suggestion, can you update the text in the Load Balancer intro page?

**Comment by tfiduccia** [comment]
v0.16.0
Verified fixed
