### ISSUE TITLE
[UI] [Host] On Host Setup page, 'Cancel' doesn't do anything.

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#481]
Version: Build from Master 4/8/15

Click on Add Host.
Click on 'Cancel' on Host Setup page.

Result: Nothing happens.
Expected Result: Cancel would go back to Hosts page.

**Comment by vincent99** [comment]
Changed in rancherio/ui#117

**Comment by tfiduccia** [comment]
Build from latest 4/8/15
Verified Fixed
