### ISSUE TITLE
When trying to add an existing target again to an existing LB using "Add Target" option, no error message is presented to the user

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#487]
Server Version - V.0.15.0
Steps to reproduce the problem:

Create an LB with 2 targets say con1 , con2.
Use "Add Target" option and use "Add Container" option to add container.
Notice that both con1 and con2 is also presented in the list.

We should not be listing the containers that are already existing targets of this LB.

Try to pick "con1" an "con2" and click on "Add". Nothing happens in the UI.
At this point , server has returned an error , which is not being presented to the user.

Response from server:
Request URL:http://**********:8080/v1/loadbalancers/1lb55/?action=addtarget
Request Method:POST
Status Code:422 Unprocessable Entity

Expected Behavior:
1. Container list not be listing the containers that are already existing targets of this LB.
2. If (1) is not possible , we should show error message when server returns error.

Irrespective of whether option 1 is being implemented / not , we should be able to show the error message that server returns .

**Comment by tfiduccia** [comment]
build from master - June 9th
Failed

Still not doing anything and get this error in Developer tools;
POST http://130.211.145.194:8080/v1/loadbalancers/1lb3/?action=addtarget 422 (Unprocessable Entity)

**Comment by tfiduccia** [comment]
build from master - June 10th (afternoon)
Verified Fixed
