### ISSUE TITLE
[UI][Registry] Edit and Information page are going to blank page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#488]
v0.15.0
Steps:
1.  Create new registry
2.  Click on name
3.  Edit registry

Results:
Both actions take you to a blank Registry page

Expected:
Edit should take you to edit page and Information should take you to info page for that particular registry.

**Comment by vincent99** [comment]
Fixed in rancherio/ui@b366f25

**Comment by tfiduccia** [comment]
v0.15.1
Verified fixed
