### ISSUE TITLE
Support Cloud Providers

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#49]
Although Rancher is agnostic to where what cloud a host exist in or whether it is a bare metal machine, it does support various cloud specific features like adding a host (through Machine) or programming Route 53 from AWS.

Rancher needs to support a way to add a "Cloud Provider" so that these providers can be re-used by other features within Rancher.  Initial supported cloud providers should be AWS, Digital Ocean, and GCE.  Each cloud provider should minimally contain the credentials to access that cloud in order to execute cloud specific commands.

**Comment by nekinie** [comment]
Could RunAbove / Openstack be included in the initial supported cloud providers???

**Comment by will-chan** [comment]
Yeah, it shouldn't be very difficult to add new providers.

**Comment by vincent99** [comment]
(https://github.com/docker/machine/tree/master/drivers/openstack)

**Comment by imton** [comment]
Azure please
