### ISSUE TITLE
[UI][Machine] Add IPv6 and Private Networking for DO SFO1

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#490]
> Announcing IPv6 and Private Networking In SFO1
> 
> With our San Francisco region fully migrated to version 1.5 of our code base, we are excited to announce that both IPv6 support and private networking are now available for all Droplets in SFO1.
> 
> Both IPv6 and private networking can be enabled during Droplet creation or added to existing Droplets. If you'd like to give them a try, these easy-to-follow community guides will get you up and running:

**Comment by tfiduccia** [comment]
v0.16.0
IPV6, Private Networking, Backup all enabled.  All sending true through API
Verified Fixed
