### ISSUE TITLE
[UI][LB] - Purged containers still showing up on LB page as targets

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#492]
v0.15.0
Steps:
1.  Add a LB with a container target
2.  Purge the container

Results:
The container still shows up on the LB page as a purged target

Expected:
Should be removed

![image](https://cloud.githubusercontent.com/assets/11514927/7076691/f816d488-debf-11e4-9f9f-6c07c82a5c95.png)

**Comment by vincent99** [comment]
Symptom of #297..

**Comment by vincent99** [comment]
The lbtarget was in removed state but still displayed, fixed with other removed issues.

**Comment by tfiduccia** [comment]
Verified fixed v0.16.0
