### ISSUE TITLE
Remember Machine credentials for duration of session for all drivers

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#494]
When creating a Amazon EC2 machine, the subnetID is remembered but the Access Key and Secret key are not.  It would be nice if we remembered these fields for the duration of their session.

**Comment by vincent99** [comment]
Also DigitalOcean access token, and any other similar fields for future drivers.

**Comment by will-chan** [comment]
Our "clone" feature should be sufficient enough for this.
