### ISSUE TITLE
Utilization information on Host and Container not in same place

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#498]
v0.15.1
Steps:
1.  Click on Host name
2.  Click on Container name

Results:
Notice that the Host Information page, the Utilization stats are on the top.  In the Container Info page, they are on the bottom.

Expected:
Utilization stats should be in same place.

**Comment by vincent99** [comment]
Swapped the order when updating the look of the containers page in 0.18

**Comment by tfiduccia** [comment]
v0.18.2
Verified Fixed
