### ISSUE TITLE
[lb] - Sometimes Lb agent stuck in "removing" state when LB is deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#504]
Server version - V0.15.1

Steps to reproduce the problem:
Create an LB with hosts and targets using a configuration which has atleast 1 listener.
Tried to delete the LB.
Deletion of LB reports success , but the LB Agent i stuck in "removing" state.

mysql> select * from instance where id=107; 
| 107 | Lb Agent |          1 | container | 64698d12-6b4a-4c73-b6d2-f6c8db783491 | NULL        | removing | 2015-04-09 05:05:42 | NULL    | NULL        | {"fields":{"imageUuid":"docker:rancher/agent-instance:v0.3.0","requestedHostId":1,"networkIds":[2],"vnetIds":null,"privileged":true,"transitioningProgress":95,"dockerHostIp":"130.211.178.104","dockerPorts":{},"dockerIp":"","primaryIpAddress":"10.42.11.0"},"dockerInspect":{"State":{"Pid":0,"OOMKilled":false,"Paused":false,"Running":false,"FinishedAt":"2015-04-10T16:42:23.170884345Z","Restarting":false,"Error":"","StartedAt":"2015-04-09T05:05:43.597321332Z","ExitCode":129},"Config":{"PortSpecs":null,"Hostname":"daa0b0d6f72f","Entrypoint":null,"Env":["CATTLE_CONFIG_URL=http://146.148.52.135:8080/v1","CATTLE_AGENT_INSTANCE_AUTH=Basic NTc0MjcyQzQwRUJDNjhGQTk5REM6NzZjbmpHMUtIbkZySEtKNkxpd3NtbXhEekR4Y0F5aGRYMlA2QXZleQ==","RANCHER_IP=10.42.11.0/16","HOME=/","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":false,"MacAddress":"02:c5:2f:4a:31:10","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/etc/init.d/agent-instance-startup","init"],"StdinOnce":false,"AttachStdin":false,"Volumes":{},"MemorySwap":0,"Tty":false,"CpuShares":0,"Domainname":"","Image":"rancher/agent-instance:v0.3.0","ExposedPorts":{}},"HostsPath":"/var/lib/docker/containers/daa0b0d6f72f46c24caf555669769d0471306fe372d8601f728488c0dbd140b2/hosts","Args":["init"],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/etc/init.d/agent-instance-startup","HostnamePath":"/var/lib/docker/containers/daa0b0d6f72f46c24caf555669769d0471306fe372d8601f728488c0dbd140b2/hostname","VolumesRW":{},"RestartCount":0,"Name":"/64698d12-6b4a-4c73-b6d2-f6c8db783491","Created":"2015-04-09T05:05:43.463600251Z","ResolvConfPath":"/var/lib/docker/containers/daa0b0d6f72f46c24caf555669769d0471306fe372d8601f728488c0dbd140b2/resolv.conf","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"","GlobalIPv6Address":"","IPAddress":"","PortMapping":null,"IPPrefixLen":0,"LinkLocalIPv6PrefixLen":0,"MacAddress":"","IPv6Gateway":"","Gateway":"","Ports":null},"AppArmorProfile":"","Image":"adac278dca6dded6f965cf585b4bab3bd6bc0831a9f63c670b7058958e4dc8cd","HostConfig":{"CapDrop":null,"ContainerIDFile":"","NetworkMode":"","Links":null,"IpcMode":"","LxcConf":null,"PortBindings":null,"SecurityOpt":null,"CapAdd":null,"Binds":null,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"ReadonlyRootfs":false,"Devices":null,"Dns":null,"ExtraHosts":null,"PidMode":"","DnsSearch":null,"Privileged":true,"VolumesFrom":null,"PublishAllPorts":false},"Id":"daa0b0d6f72f46c24caf555669769d0471306fe372d8601f728488c0dbd140b2","MountLabel":""},"dockerContainer":{"Status":"Exited (129) Less than a second ago","Created":1428555943,"Image":"rancher/agent-instance:v0.3.0","Id":"daa0b0d6f72f46c24caf555669769d0471306fe372d8601f728488c0dbd140b2","Command":"/etc/init.d/agent-instance-startup init","Names":["/64698d12-6b4a-4c73-b6d2-f6c8db783491"],"Ports":[]}} | active           |    NULL |      NULL |      115 |        NULL | NULL     |       1 | restart                 |      115 | NULL   | 2015-04-09 05:05:43 | OKQsDJoiM2cDIB7L1XIa3fMEoiUOLM4BuhTnwbIgPsbtv6lXdI1mMLJpOYTiPScQ0bsaTPypdzzKCIGuysnYFg | NULL     | LoadBalancerAgent |                   NULL |

**Comment by alena1108** [comment]
Happens because in instance.stop handler in network(), when do port.deactivate, we don't exclude purged/removed ports from the list. And for lb.instance case there will be ports in removed state as we create/remove ports on demand based on listener being added/removed to/from load balancer config.

**Comment by sangeethah** [comment]
Server version - V0.16.0

Tried deletion of LB rules which are associated with multiple targets and listeners after removing and adding listeners. This issue is not seen anymore.

Closing this issue.
