### ISSUE TITLE
[LB][UI] -  Add LB - Should not show containers that are deployed with unmanaged network in "Add container" option

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#505]
Server Version - V0.15.1

Deploy a container in "unmanaged" network.
We are allowed to add Lb using this container.

UI should not show these containers , since we do not support LB for container in unmanaged network.

**Comment by vincent99** [comment]
@ibuildthecloud or @alena1108 I don't see any non-hacky way in the API to tell which network a container is on after create.  There's no `networks` link, the `ports` link returns an empty array, etc.  Can we add a `hasManagedNetwork: true/false` field, along the lines of `primaryIpAddress`?

The hacky way would be "has a `primaryIpAddress` and it starts with `10.`", which I will implement for now.

**Comment by sangeethah** [comment]
Tested with server version - V0.16.0

In "Add Load Balancer" page , I see that that the container dropdown does not list containers that are deployed in unmanaged network.

But when I try to add target to an existing LB , using the "Add Targets" page , the containers that are deployed in unmanaged network are still listed.

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
