### ISSUE TITLE
[LB][UI] - Add Load Balancer - Stickiness - Use existing cookie - PREFIX field needs to be a checkbox.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#519]
Server version - V0.16.0

In Add Load Balancer - Stickiness - Use existing cookie - PREFIX field is currently a text field.
If we enter true , it gets set. Any other text entered is taken as false . But it is not intuitive .

It would be better for this field to be a checkbox with default being not enabled .

**Comment by vincent99** [comment]
Oops.. it sounded like a string :smile:

**Comment by tfiduccia** [comment]
v0.16.2 (latest)
Verified Fixed
