### ISSUE TITLE
When trying to access edit page for Load Balancer Config page, we get redirected to an error page

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#520]
Server version - V0.16.0

Steps to reproduce the problem:

Balancing->Configurations-> choose any configuration-> From Balancer Config ->choose Edit option:

We get the following error message:

http://104.197.32.160:8080/static/fail

"Error
e.map is not a function
Reload to try again"

This happens always for the LB that is configure with stickiness.

**Comment by vincent99** [comment]
This is happening on configs that use `appCookieStickiness` ("Use existing cookie") because the config has a property named 'length' and JavaScript is a terrible language.  @alena1108 is going to rename the field in #540 and then I'll update the UI.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
