### ISSUE TITLE
Services auto-restart even if it's set to never

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#522]
v0.16.0
Steps:
1.  Create an Environment
2.  Add the Docker: hello-world as a service
3.  Make sure Auto-Restart is set to never
4.  Wait a few minutes
5.  Check the logs

Results:
The service ran twice

Expected:
Service to only run once

**Comment by tfiduccia** [comment]
This seems to happen to the first service you add to environment and can be seen better if you change scale to 6.  Then they will restart a few times.

**Comment by alena1108** [comment]
Tani, could you retest on the latest? Restart policy should be set on the service containers now

**Comment by tfiduccia** [comment]
This is still happening.  Although i don't think it's because of the restart policy.  For some reason, the containers in services will restart if they are automatically stopped until the Service is completely done starting.

Hello-world, just prints some data then stops.  If you have a high scale (like over 3 or 4), the first service container is created and stopped before the rest of the containers... it will then restart again until all containers are created and started.

**Comment by alena1108** [comment]
@tfiduccia right, thats the recently added feature. Service containers management (stop/start/destroy) should be triggered by the service operation (scaleup/scaledown/deacivate). If the container is stopped/destroyed from the outside (either by stop api, or on the docker side), the service will reconcile the deployment by bringing up the containers to match the scale. Closing the issue for now.
