### ISSUE TITLE
[UI][LB] Can't create LB using existing configuration

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#528]
v0.16.0
Steps:
1.  Create LB with new config
2.  Create another LB using previous LB's config

Results:
"sourcePort" is required
![image](https://cloud.githubusercontent.com/assets/11514927/7188631/21ac6718-e42e-11e4-9956-dccd4c1ca189.png)

Expected:
Should use scourcePort from previous LB's config

**Comment by vincent99** [comment]
Turned off validation checks of the new lbconfig when you're not going to use it anyway..

**Comment by tfiduccia** [comment]
v0.16.2 (latest)
Verified fixed
