### ISSUE TITLE
After editing container if I click on "< Container" link it takes me back to edit overlay

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#530]
v0.16.0
Steps:
1.  Go to Container list page
2.  Click on container name to get to container info page
3.  Click on edit icon and change something, Save
4.  Click on < Container link to get back to container list

Results:
Takes me back to edit overlay.

Expected:
Should take me back to container list page

Same thing happens if I choose View logs, or execute shell.

**Comment by vincent99** [comment]
No more back buttons..

**Comment by tfiduccia** [comment]
v0.21.3
Back links have been removed from new UI
Verified Fixed
