### ISSUE TITLE
Page doesn't refresh after removing host from LB info page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#531]
v0.16.0
Steps:
1.  Create LB
2.  Click on LB name to get to info page
3.  Click on Hosts
4.  Remove host

Results:  Until I do a hard refresh, the host still shows as active.

Expected:  Host to delete and not be active anymore

**Comment by vincent99** [comment]
@ibuildthecloud This seems to be a race condition in the events that get sent.

I get a `resource.change` for `loadBalancerHostMap` and one for `loadBalancer`.  I also do `?include=hosts` on the subscribe connection, so the balancer includes the hosts.  Sometimes the `loadBalancer` change includes the host that was removed, even if the event is received after the change for the map.

**Comment by ibuildthecloud** [comment]
I believe this is fixed in the latest rc.

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc4
Page refreshes after removing host from LB info page.
