### ISSUE TITLE
[UI][API Key] Restore API key not longer functions

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#533]
v0.16.0
1.  Set Auth on
2.  Create API key
3.  Go to container and click View in API
4.  Use key
5.  Go back and Deactivate, Delete then restore API key
6.  Go to Container and click View in API
7.  Use key

Results:
Key no longer works

Expected:
If after delete the key will no longer work, we shouldn't give them the option to restore it.

**Comment by vincent99** [comment]
The key is inactive after being restored.  You have to activate it before it can be used.

**Comment by tfiduccia** [comment]
I'm a dork.
