### ISSUE TITLE
[UI][Container] Entry Point field is missing in API call

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#534]
v0.16.0
Steps:
1.  Create a container with an entry point
2.  Look at the Post for Container

Results:
Entry Point is missing

Expected:
Should be an entry point in the post

**Comment by vincent99** [comment]
(@cjellick , fixed in the 0.16 release)

**Comment by tfiduccia** [comment]
v0.16.2 (UI / latest)
Verified fixed
