### ISSUE TITLE
[Container] - Not able to launch the CPU/Memory Utilization view for containers

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#537]
Server Version - V0.16.1

Steps to reproduce the problem:
Create a container.
Try to launch the CPU/Memory Utilization view for the container.
The UI keeps spinning and nothing gets rendered.

**Comment by vincent99** [comment]
This affects hosts with the new Docker 1.6 installed, the version of cAdvisor that we install doesn't support 1.6.

**Comment by vincent99** [comment]
cAdvisor updated in the host-agent to resolve this

**Comment by sangeethah** [comment]
Tested with  v0.16.3.
I am able to see the  CPU/Memory utilization view for containers.

Closing this issue.
