### ISSUE TITLE
ERROR client and server don't have same version, can not add custom host to server

### ISSUE THREAD

**Issue by ungarida** [rancherio/rancher#539]
I have a rancher/server:v0.16.2 running on a CoreOS node and I'm trying to connect another another CoreOS running rancher/agent:v0.5.2 on it.

Launching the command suggested from the UI:
```
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://addressedited/v1/scripts/820E56AAE501012575CF:1429228800000:i6G9O8N4uJ3vb1j9XpZcv2ZSSzw
```
I get error message:
```
time="2015-04-17T00:10:00Z" level="fatal" msg="Error response from daemon: client and server don't have same version (client : 1.16, server: 1.14)" 
Please ensure Host Docker version is >= 1.4.1 and container has r/w permissions to docker.sock
```

**Comment by ibuildthecloud** [comment]
What version of CoreOS are you running.  All CoreOS channels are Docker 1.5 right now and that should work.

**Comment by ungarida** [comment]
I using a CoreOS Stable on vultr.com but Docker version is 1.2.0, build fa7b24f.

**Comment by ungarida** [comment]
I was able to force update of CoreOS. For some reason now the client can't connect to server even if from the host I can download the bash script using the same URL.

**Comment by ungarida** [comment]
I was able to force update of CoreOS. For some reason now the client can't connect to server even if from the host I can download the bash script using the same URL.

**Comment by grigio** [comment]
Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17)

I get this with latest rancher/server and agent
