### ISSUE TITLE
Allow binding to a specific interface

### ISSUE THREAD

**Issue by hbokh** [rancherio/rancher#54]
On CoreOS v550.0.0 rancher binds to the `docker0` interface, which has an 172.17.x.y address.
I want to make rancher bind to `ens192`, which has a 192.168.x.y DHCP-leased address and is accessible inside my LAN-network.
Since I can not access the 172.17.x.y range directly, all containers binded to the network IN that host are unreachable.
Is binding to interface `ens192` an option somehow or is this a CoreOS-specific issue?

**Comment by ibuildthecloud** [comment]
@hbokh When the agent connects to rancher-server we auto detect the IP of the agent.  That doesn't always yield the right IP.  You can override this by setting `-e CATTLE_AGENT_IP=x.x.x.x` on the `docker run ... rancher/agent` command.  On CoreOS a lot of times this IP is populated in /etc/environment as PUBLIC_IP.

Does this help?

**Comment by hbokh** [comment]
Thank yo for the quick reply! That seems to work. Maybe add this in the README?
Anyway, I will close the issue.
