### ISSUE TITLE
Rename loadBalancerAppCookieStickinessPolicy.length

### ISSUE THREAD

**Issue by alena1108** [rancherio/rancher#540]
According to @vincent99, due to JavaScript's general suckyness as a language objects with a field name 'length' and arrays are kind of the same thing/hard to tell apart.

So will have to rename "length" to "maxLength"

**Comment by ibuildthecloud** [comment]
Darn you JavaScript!!!

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
