### ISSUE TITLE
Edit LB Config should allow for editing stickiness and health policies

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#541]
Server Version - V0.16.1

Steps to reproduce the problem:

Create LB configuration , as part of creating LB rule.
By default , health check policy is enabled.

Try to edit LB configuration. We are provided with option to edit only name and description.

**Comment by tfiduccia** [comment]
build from master - June 10th
This was fixed with another bug, all Balancer Config information is now editable.

Verified fixed
