### ISSUE TITLE
Typo for "Request Learn" option and is placed with "MODE"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#542]
Server version - V 0.16.1

Steps to reproduce the problem:
Create a LB configuration with "Use existing cookie".
 View the LB configuration.

 "Request Learn" option has a typo - "lean from request" and   is placed with "MODE". 
It should  be placed as different field with value true/false similar to PREFIX.

![screen shot 2015-04-16 at 2 57 47 pm](https://cloud.githubusercontent.com/assets/4266958/7194273/fb5888ac-e460-11e4-940b-8432748adaf4.png)

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
