### ISSUE TITLE
Fix command and commandArgs fields to more closely match docker Cmd

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#543]
We currently have two fields on our container API to represent the command that should be ran for a container:
* `command` - a string
*`commandArgs` - an array of strings

Docker has just one field:
* `Cmd` - an array of strings

We should change our api to match dockers. Currently, we (via the UI) don't even use the commandArgs field. If a user enters a command with multiple parts (ie `sleep 1 2 3`), it is all stored in `command` field as single string, but when it gets down to docker, docker will parse it and store it as four separate elements in the Cmd array.

**Comment by vincent99** [comment]
The UI has a shell parser for the `entrypoint` field now, so I can do the same to split the command into the array.

**Comment by tfiduccia** [comment]
v0.18.1
Verified Fixed
