### ISSUE TITLE
MachineConfig prompts for user keys in Access control enabled setup.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#546]
Server version - V0.16.3

Enable access control.
Add a Digital Ocean machine.
Try to fetch "Machine Config".
User is prompted to enter username/password.

Once the username/password is entered , then we are able to get the machine config.

Expected Behavior:

User should not be prompted for username/password when trying to download Machine Config.

**Comment by vincent99** [comment]
Changed to send auth token as query param if auth is on in rancherio/ui#126.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
