### ISSUE TITLE
Selecting hosts doesn't make sense if you have more than 1 scale

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#549]
v0.16.3

Steps:
1.  Add Service
2.  Go to Advanced Options - Security/Hosts

Results:
You can select a host, but if you set scale to more than 1, it will randomly pick other hosts.  Not sure this feature makes sense for this section.

**Comment by sangeethah** [comment]
requestedHostId parameter set in launchConfig parameter for create_service API is not honored.

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
