### ISSUE TITLE
Rename container names when editing environment and service name

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#551]
Server Version - V0.16.3

Steps to reproduce the problem:

Currently we allow for editing of environment name. This results in  the naming convention for the existing containers in the environment to go out of sync.

When  editing Environment names, all the containers part of all services under this environment needs to be renamed to reflect the change in environment.

**Comment by vincent99** [comment]
I don't really like the idea of not being able to rename things...

What about renaming all the containers on environment/service rename instead?

**Comment by sangeethah** [comment]
I have changed the bug description to allow for editing of environment , which should result in name of the containers belonging to this environment to be renamed to reflect the change in name.

**Comment by alena1108** [comment]
We should also allow modifying service's name

**Comment by sangeethah** [comment]
Server Version - V0.18.1
When editing environment and service names , the names of the containers belonging to the environment/service gets renamed.

**Comment by ozbillwang** [comment]
@sangeethah 

Did this feature implemented? 

>When editing environment and service names , the names of the containers belonging to the environment/service gets renamed.

I tested with Rancher v1.6.14, when rename the service name, all running containers' name stay same, until I delete them and start new one, the container will have the name name
