### ISSUE TITLE
After purging containers in a service, if I stop and restart services, they come back

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#556]
v0.16.3
Steps:
1.  Create an environment
2.  Add a service and set scale to 3
3.  Delete and purge two of the containers
4.  Click on stop services button, then start services button

Results:
The two containers I deleted and purged come back.

Expected:
They shouldn't come back?

**Comment by vincent99** [comment]
This is a feature.. The service defines how to create a container for it and how many of them there should be (3).  So when you start it, if there are less than that they get (re)created.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
