### ISSUE TITLE
Going back from Add LB Config takes you to back to Balancers instead of configurations

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#559]
v0.16.3
Steps:
1.  Go to LB Configuration page
2.  Click on Add Balancer Config
3.  Click on < Back

Results:
Takes you to Balancer page

Expected:
Take you back to Configurations page

**Comment by vincent99** [comment]
There is no back button now... so.. there.

**Comment by tfiduccia** [comment]
v0.21.3
Verified Fixed
