### ISSUE TITLE
Renaming a container in a service containers causes new containers to be created

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#561]
v0.16.3
Steps:
1.  Create service with scale set to 1
2.  Go to Container page and rename the container
3.  Go back to service page and stop/restart service

Results:
Creates a new container in service so now you have two

Expected:
Shouldn't create a new one

**Comment by alena1108** [comment]
We shouldn't allow renaming service container as their names are constructed using environment-service name (just as docker-compose does). I will add an api filter for that.

**Comment by alena1108** [comment]
Ignore my last comment. We shouldn't be strict, and should allow to rename environment/service and individual instances within the service. Some refactoring needs to be done in the way we map service instance to the service

**Comment by tfiduccia** [comment]
v0.18.1
Verified fixed
