### ISSUE TITLE
Containers in service doesn't restart if you rename one

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#562]
v0.16.3 - Probably related to #561 

Steps:
1.  Create a service with a scale of 2
2.  Rename one of the containers
3.  Click on Stop Services
4.  Click on Start Services
5.  You may need to Stop/Start again

Results:
Containers don't restart.

Expected:
Containers to restart.

**Comment by alena1108** [comment]
Tani, can't reproduce it on the latest. Could you please re-test?

**Comment by tfiduccia** [comment]
Build from master - June 9th
Verified fixed or no longer reproducible - :)
