### ISSUE TITLE
Add back operations to agents

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#563]
While I would like to assume our code is perfect it is not.  It makes it very difficult to troubleshoot things if I can not do operations or get to the console of agents.  Can we please add back the operation?  I propose we actually just show agents as smaller boxes in a region above/below the containers on the host.  That way they are not as prominent, but the user can still get to them.

**Comment by cloudnautique** [comment]
+1

**Comment by vincent99** [comment]
Un-removed in rancherio/ui@c482083daffd8429937084476db815e5a1b7ce4b for now, we can try to figure out something else later.

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
