### ISSUE TITLE
Service Name with "-" should not be allowed . docker-compose validation for service name fails

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#565]
Server version - V0.16.3

Steps to reproduce the problem:

Create Environment.
Create a service with name "test-366326" and activate service.

Use "Export Config" for Environment to generate the docker-compose.yml 

Use this docker-compose.yml file to create the instances.

Following error is seen:

"Invalid service name "test-366326" - only [a-zA-Z0-9] are allowed"

**Comment by vincent99** [comment]
@alena1108 I think this is resolved in rancherio/cattle@0a5ecaaf93db996c911430153d0682a372d3d65a ?

**Comment by alena1108** [comment]
@vincent99 yes, it was, marking as resolved

**Comment by sangeethah** [comment]
Tested with server version - V.0.17.0
When adding service , we are not allowed to have "-" or another special characters in name.
Following error presented to user - "Validation failed: name"
