### ISSUE TITLE
Deleting an instance in service and then trying to scaledown the instance by 1, results in instance being created and destroyed

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#570]
Server Version - V0.16.3

Steps to reproduce the problem:

Create an environment -env1
Add service (s1) with scale set to 5.
Delete one of the instances (say the 4th one).
Now edit the service and set the scale to 4.

There needs to be no addition/deletion of the services done.
But we see an instance being created ( env1_s1_4) and existing instance (env1_s1_5) being removed.

**Comment by alena1108** [comment]
Today we always try to ensure that the instances name reflect the scale. If scale is 4, then we expect names _1, _2, _3, _4 to be set on the services names. This behavior will most likely change once I relax the restriction on the services' names (once we let user modify service/environment/individual instances' names)

**Comment by sangeethah** [comment]
Tested with server version - V.0.18.1
Create an environment -env1
Add service (s1) with scale set to 5.
Delete one of the instances (say the 4th one).
Now edit the service and set the scale to 4.

I see that the deleted instance is no longer associated with the service and the instances that are in the service are "_1","_2","_3" and "_5".

Works as expected.
