### ISSUE TITLE
[Services] - Not able to create instances using docker-compose.yml when image points to private registry 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#573]
Server version - V0.16.3

Steps to reproduce the problem:

Create a private registry - quay.io with valid credentials.

Create environment.
Create service using a private image in  this private registry (that requires credentials) or a public image in this registry.

In both the cases , I am not able to use the generated docker-compose.yml to create the instances using docker-compose command.

contents of docker-compose.yml 
tregistry1:
  tty: true
  image: quay.io/sangeetha/test2
  privileged: false
  stdin_open: true

Sangeethas-MacBook-Pro:~ sangeethahariharan1$ docker-compose up ( test1 is private registry)
Creating sangeethahariharan1_tregistry1_1...
Pulling image quay.io/sangeetha/test1:latest...
v1 ping attempt failed with error: Get https://quay.io/v1/_ping: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry quay.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/quay.io/ca.crt

Sangeethas-MacBook-Pro:~ sangeethahariharan1$ docker-compose up( test2 is public registry)
Creating sangeethahariharan1_tregistry1_1...
Pulling image quay.io/sangeetha/test2:latest...
v1 ping attempt failed with error: Get https://quay.io/v1/_ping: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry quay.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/quay.io/ca.crt
Sangeethas-MacBook-Pro:~ sangeethahariharan1$

**Comment by alena1108** [comment]
Sangeetha, can't reproduce it on my setup. Here is the docker-compose.yml:
alena:
  restart: 'no'
  tty: true
  image: quay.io/sangeetha/test2
  privileged: false
  stdin_open: true

And I am able to launch instances of this service. Can you follow the instructions in "If this private registry supports only HTTP or HTTPS with an unknown CA certificate..." and see if it fixes the problem?
