### ISSUE TITLE
GitHub proxy doesn't return correct status code

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#575]
Actual GitHub API:
`GET https://api.github.com/v3/users/nonexistent123` -> `404 Not Found` + JSON body with message

Rancher GitHub Proxy:
`GET /github/users/nonexistent123` -> `200 OK` + JSON body with message

**Comment by ibuildthecloud** [comment]
The cattle fix is on master now

**Comment by vincent99** [comment]
@tfiduccia This doesn't change anything of significance but test that adding valid github users/orgs (to a project or to access controls) works and adding an invalid one shows an error.

**Comment by tfiduccia** [comment]
v0.18.1
Verified fixed
