### ISSUE TITLE
RHEL6 innodb Errors

### ISSUE THREAD

**Issue by cloudnautique** [rancherio/rancher#580]
From Rancher mailing list:
https://groups.google.com/forum/#!topic/rancherio/YNOcIe9TUhE

I'm having trouble getting the Master server running on a rhel 6 docker host and I was wondering if anyone has ran into this issue before. I looked in google but I can't find something similar to my issue.

command:
docker  run -d --privileged -p 8080:8080 --name=rancher-dev rancher/server

Here is the error log
./finish: line 3: s6-svcscanctl: command not found
150421 15:16:14 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150421 15:16:14 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
150421 15:16:14 [Note] Plugin 'FEDERATED' is disabled.
/usr/sbin/mysqld: Table 'plugin' is read only
150421 15:16:14 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
150421 15:16:14 InnoDB: The InnoDB memory heap is disabled
150421 15:16:14 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150421 15:16:14 InnoDB: Compressed tables use zlib 1.2.8
150421 15:16:14 InnoDB: Using Linux native AIO
/usr/sbin/mysqld: Can't create/write to file '/tmp/ibt5dyJY' (Errcode: 13)
150421 15:16:14  InnoDB: Error: unable to create temporary file; errno: 13
150421 15:16:14 [ERROR] Plugin 'InnoDB' init function returned error.
150421 15:16:14 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
150421 15:16:14 [ERROR] Unknown/unsupported storage engine: InnoDB
150421 15:16:14 [ERROR] Aborting

150421 15:16:14 [Note] /usr/sbin/mysqld: Shutdown complete

**Comment by deniseschannon** [comment]
This was most likely the version of docker and rhel6 and rancher. 

RHEL6 works with
Docker Version: 1.6.2 (Need to download latest binary)
Rancher Version: v0.23.0-rc1

**Comment by viperfishELM** [comment]
I added this to the docker command:
-e CATTLE_DB_CATTLE_DATABASE=h2

Seems to be working.

**Comment by deniseschannon** [comment]
If your DB is H2, then your Rancher server version must be prior to v0.10.x because we moved to MySQL in v0.10.x+. We've made significant changes in Rancher over the last couple of months. Please feel free to try latest!
