### ISSUE TITLE
AD/LDAP support

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#582]
* WIP for AD/LDAP integration with Rancher

**Comment by will-chan** [comment]
- Get Project support working end to end with UI.

**Comment by clemenko** [comment]
Is ldap implemented?

**Comment by vincent99** [comment]
@clemenko I can see how this would be confusing but no.. the issues labeled `task` are things that someone is supposed to work on during a weekly release cycle.  In this case starting on LDAP was moved out of this release in favor of fixing a bunch of issues with projects.

**Comment by clemenko** [comment]
Ok cool. I need this to sell it to my management. :)

**Comment by vincent99** [comment]
There was no actual issue to track AD so I've created one you can follow here @clemenko : #688
