### ISSUE TITLE
When service2 is created with dataVolumesFromService to service1, the volumes of the containers from service1 is not available for the container in the service2

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#585]
Server Version - V0.16.3

Create environment.
Add service - S1. Activate this service.
Add another service S2 with dataVolumesFromService set to service S1.

Activate S2.

When instances are launched for this service , they do not have the volumes from containers of service S1 being mounted.

docker inspect for the instance shows "VolumesFrom" to be empty:

    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": null,
        "Dns": [],
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },

mysql> select data from service where id =4;
| {"fields":{"scale":2,"launchConfig":{"startOnCreate":true,"publishAllPorts":false,"privileged":false,"stdinOpen":true,"tty":true,"commandArgs":[],"environment":{},"dataVolumes":[],"dataVolumesFrom":[],"dns":[],"dnsSearch":[],"capAdd":[],"capDrop":[],"devices":[],"imageUuid":"docker:ubuntu:14.04.1","restartPolicy":{"name":"no"},"ports":[],"instanceLinks":{},"count":null,"description":null,"hostname":null,"name":null,"directory":null,"user":null,"domainName":null,"memorySwap":null,"memory":null,"cpuSet":null,"cpuShares":null},"dataVolumesFromService":[2],"transitioningMessage":"start service instance 634340d9-1c05-46c8-b05a-0441b0aba87c","transitioningProgress":50}} |
1 row in set (0.00 sec)

mysql>  select data from instance where name like "%testy%"
| {"fields":{"imageUuid":"docker:ubuntu:14.04.1","dns":[],"instanceLinks":{},"domainName":null,"stdinOpen":true,"dnsSearch":[],"memory":null,"ports":[],"environment":{},"networkIds":[2],"directory":null,"dataVolumesFrom":[],"capAdd":[],"tty":true,"capDrop":[],"dataVolumes":[],"restartPolicy":{"name":"no"},"privileged":false,"cpuShares":null,"user":null,"transitioningMessage":"post network","transitioningProgress":95,"dockerHostIp":"104.154.38.159","dockerPorts":{},"dockerIp":"172.17.0.25","primaryIpAddress":"10.42.253.214"},"dockerInspect":{"State":{"Pid":24920,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-04-22T21:46:59.935747653Z","ExitCode":0},"Config":{"PortSpecs":null,"Hostname":"e82e860ca4d1","Entrypoint":null,"Env":["RANCHER_IP=10.42.253.214/16","RANCHER_UUID=4f4a6dda-5485-489d-b7bd-881b1d100dde","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":true,"MacAddress":"02:f8:02:58:37:c6","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/bin/bash"],"StdinOnce":false,"AttachStdin":false,"Volumes":null,"MemorySwap":0,"Tty":true,"CpuShares":0,"Domainname":"","Image":"ubuntu:14.04.1","Labels":{},"ExposedPorts":null},"HostsPath":"/var/lib/docker/containers/e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418/hosts","Args":[],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/bin/bash","HostnamePath":"/var/lib/docker/containers/e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418/hostname","VolumesRW":{},"MountLabel":"","RestartCount":0,"Name":"/4f4a6dda-5485-489d-b7bd-881b1d100dde","Created":"2015-04-22T21:46:59.788902115Z","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"docker0","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"fe80::f8:2ff:fe58:37c6","GlobalIPv6Address":"","IPAddress":"172.17.0.25","PortMapping":null,"IPPrefixLen":16,"LinkLocalIPv6PrefixLen":64,"MacAddress":"02:f8:02:58:37:c6","IPv6Gateway":"","Gateway":"172.17.42.1","Ports":{}},"AppArmorProfile":"","Image":"5ba9dab47459d81c0037ca3836a368a4f8ce5050505ce89720e1fb8839ea048a","LogPath":"/var/lib/docker/containers/e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418/e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418-json.log","HostConfig":{"PortBindings":null,"Dns":[],"Memory":0,"CgroupParent":"","Privileged":false,"Ulimits":null,"CpusetCpus":"","DnsSearch":null,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"PublishAllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"NetworkMode":"","ExtraHosts":null,"LxcConf":null,"Devices":null,"Binds":null,"MemorySwap":0,"PidMode":"","VolumesFrom":null,"CapDrop":null,"Links":null,"IpcMode":"","ContainerIDFile":"","SecurityOpt":null,"CapAdd":null,"LogConfig":{"Config":null,"Type":"json-file"}},"Id":"e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418","ResolvConfPath":"/var/lib/docker/containers/e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418/resolv.conf"},"dockerContainer":{"Status":"Up Less than a second","Created":1429739219,"Image":"ubuntu:14.04.1","Labels":{},"Id":"e82e860ca4d1c225a67b8f2f06dea1608000d1fb2f3f1bd239fff5056b84a418","Command":"/bin/bash","Names":["/4f4a6dda-5485-489d-b7bd-881b1d100dde"],"Ports":[]}} |
| {"fields":{"imageUuid":"docker:ubuntu:14.04.1","dns":[],"instanceLinks":{},"domainName":null,"stdinOpen":true,"dnsSearch":[],"memory":null,"ports":[],"environment":{},"networkIds":[2],"directory":null,"dataVolumesFrom":[],"capAdd":[],"tty":true,"capDrop":[],"dataVolumes":[],"restartPolicy":{"name":"no"},"privileged":false,"cpuShares":null,"user":null,"transitioningMessage":"post network","transitioningProgress":95,"dockerHostIp":"146.148.36.68","dockerPorts":{},"dockerIp":"172.17.0.13","primaryIpAddress":"10.42.133.45"},"dockerInspect":{"State":{"Pid":18619,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-04-22T21:47:00.012174057Z","ExitCode":0},"Config":{"PortSpecs":null,"Hostname":"e115703100d5","Entrypoint":null,"Env":["RANCHER_IP=10.42.133.45/16","RANCHER_UUID=e9a03413-bedf-4995-8a19-edd30fb960c2","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":true,"MacAddress":"02:f8:02:53:c7:b9","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/bin/bash"],"StdinOnce":false,"AttachStdin":false,"Volumes":null,"MemorySwap":0,"Tty":true,"CpuShares":0,"Domainname":"","Image":"ubuntu:14.04.1","Labels":{},"ExposedPorts":null},"HostsPath":"/var/lib/docker/containers/e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f/hosts","Args":[],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/bin/bash","HostnamePath":"/var/lib/docker/containers/e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f/hostname","VolumesRW":{},"MountLabel":"","RestartCount":0,"Name":"/e9a03413-bedf-4995-8a19-edd30fb960c2","Created":"2015-04-22T21:46:59.862491603Z","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"docker0","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"fe80::f8:2ff:fe53:c7b9","GlobalIPv6Address":"","IPAddress":"172.17.0.13","PortMapping":null,"IPPrefixLen":16,"LinkLocalIPv6PrefixLen":64,"MacAddress":"02:f8:02:53:c7:b9","IPv6Gateway":"","Gateway":"172.17.42.1","Ports":{}},"AppArmorProfile":"","Image":"5ba9dab47459d81c0037ca3836a368a4f8ce5050505ce89720e1fb8839ea048a","LogPath":"/var/lib/docker/containers/e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f/e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f-json.log","HostConfig":{"PortBindings":null,"Dns":[],"Memory":0,"CgroupParent":"","Privileged":false,"Ulimits":null,"CpusetCpus":"","DnsSearch":null,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"PublishAllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"NetworkMode":"","ExtraHosts":null,"LxcConf":null,"Devices":null,"Binds":null,"MemorySwap":0,"PidMode":"","VolumesFrom":null,"CapDrop":null,"Links":null,"IpcMode":"","ContainerIDFile":"","SecurityOpt":null,"CapAdd":null,"LogConfig":{"Config":null,"Type":"json-file"}},"Id":"e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f","ResolvConfPath":"/var/lib/docker/containers/e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f/resolv.conf"},"dockerContainer":{"Status":"Up Less than a second","Created":1429739219,"Image":"ubuntu:14.04.1","Labels":{},"Id":"e115703100d53b395ee4c1159a43f188fa889439566ca6c300d2ddc24a51301f","Command":"/bin/bash","Names":["/e9a03413-bedf-4995-8a19-edd30fb960c2"],"Ports":[]}} |

**Comment by alena1108** [comment]
Happens because dependent services (referenced by volumesFromService param) are not being launched when the service activation is called on the individual service. Today it works only when activation is called on the environment level (environment.activateServices)

**Comment by alena1108** [comment]
Based on the original design, service activate order will be respected only if environment.activateServices is called. If user calls activate on per individual service basis, he should maintain the order himself, and start data service (referenced via volumesFrom) beforehand by himself.
