### ISSUE TITLE
When service2 is created with dataVolumesFromService to service1 which is not activated yet, activating service2 does not result in activating service1

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#586]
Server version - V0.16.3

Add service - S1. Do not activate this service.
Add another service S2 with dataVolumesFromService set to service S1.

Activate S2.

Expected Behavior:
As part of activating S2, we should see S1 getting activated.

Actual Result:
As part of activating S2,  S1 is not getting activated.
When instances gets launched for this service , they do not have the volumes from containers of service S1 being mounted.

**Comment by alena1108** [comment]
Same root cause as in https://github.com/rancherio/rancher/issues/585. Just diff steps to reproduce.

**Comment by alena1108** [comment]
Based on the original design, service activate order will be respected only if environment.activateServices is called. If user calls activate on per individual service basis, he should maintain the order himself, and start data service (referenced via volumesFrom) beforehand by himself.
