### ISSUE TITLE
[Install] [Agent] Error response from daemon: No such container:

### ISSUE THREAD

**Issue by brycekottke** [rancherio/rancher#59]
getting error when trying to register docker nodes:

"Error response from daemon: No such container:"

It appears to be different than the following issues - #26 #33 

see below for details of docker version, docker info, and docker images (from rancher/server)

**docker version - NODE:**
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f/1.3.3
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f/1.3.3

**docker info - NODE:**
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f/1.3.3
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f/1.3.3

**nmap from NODE to RANCHER SERVER:**
Starting Nmap 5.51 ( http://nmap.org ) at 2015-01-28 20:39 UTC
Nmap scan report for 10.0.0.143
Host is up (0.0026s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
8080/tcp open  http-proxy

**docker images - RANCHER SERVER:**
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rancher/server      latest              fc50e07ee16a        8 days ago          338.6 MB
rancher/server      v0.4.3              fc50e07ee16a        8 days ago          338.6 MB
rancher/server      v0.4.3-rc1          fc50e07ee16a        8 days ago          338.6 MB

**docker ps - RANCHER SERVER:**
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS                    NAMES
6d21b12f162f        rancher/server:latest   "/usr/share/cattle/c   32 minutes ago      Up 32 minutes       0.0.0.0:8080->8080/tcp   rancher

This is all within a VPC in our dev AWS environment using the new amazon-ecs ami. If you need anything else just let me know.

Best Regards,
Bryce Kottke

**Comment by ibuildthecloud** [comment]
If you do `docker ps -a` do you see any containers from the image `rancher/agent`?  If so can you do a `docker logs` and send that?

**Comment by deniseschannon** [comment]
Closing this as we have updated the command for registering docker nodes, per https://github.com/rancherio/rancher/issues/267. 

@brycekottke, if you still have this issue and can send the requested info, please re-open.

**Comment by Mohamedcond** [comment]
Jai obtenu la meme ereur en faisant un docker stop le nom du container.  Error response from daemon: No such container: a83e62051f72. j'ai besoin d'aide
