### ISSUE TITLE
Incorrect credential gets picked when creating container with private registry that has more than 1 credential.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#598]
Server version - V0.17.0

Steps to reproduce the problem:
Create a registry with 2 credentials.
1st one is a valid credential.
2nd is invalid one.

Now launch add container/add service page.

Add image for the private registry and pick the valid credential from the dropdown ( the default was the invalid one - 2nd credential list).

Container fails to launch since it tried to use the invalid credential:

Request sent from API indicates the incorrect credential being used.
{startOnCreate: true, publishAllPorts: false, privileged: false, stdinOpen: true, tty: true,…}
allocationState: null
capAdd: []
capDrop: []
commandArgs: []
count: null
cpuSet: null
cpuShares: null
created: null
dataVolumes: []
dataVolumesFrom: []
description: "testp"
devices: []
directory: null
dns: []
dnsSearch: []
domainName: null
environment: {}
externalId: null
firstRunning: null
hostname: null
imageUuid: "docker:quay.io/ubuntu:14.04.1"
instanceLinks: {}
kind: null
memory: null
memorySwap: null
name: "testp"
networkIds: ["1n2"]
ports: []
privileged: false
publishAllPorts: false
registryCredentialId: "1c10"
removeTime: null
removed: null
restartPolicy: {name: "no"}
startOnCreate: true
stdinOpen: true
systemContainer: null
token: null
tty: true
user: null
uuid: null

**Comment by vincent99** [comment]
You cannot create more than one credential per registry in the UI as of rancherio/ui#152, and the backend automatically picks the first (oldest) matching registry/credential.

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed
