### ISSUE TITLE
Can't see project I created when auth is off

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#603]
v0.17.0
Steps:
1.  Authenticate
2.  Go to Manage projects and add two projects
3.  Go to Access Control and disable authentication

Results:
All the projects I created are no longer in the Project: drop-down

Expected:
Since I created them, they should be in my list.

**Comment by vincent99** [comment]
Changed to show all projects in the dropdown if access control is disabled.

**Comment by tfiduccia** [comment]
v0.17.1
Verified fixed
