### ISSUE TITLE
As a member you shouldn't be able to deactivate a project

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#605]
v0.17.0
Steps:
1.  As an admin create a project and add rancherdev as member
2.  Log in as rancherdev
3.  Go to Manage Projects
4.  For project, go to menu and select deactivate

Results:
project becomes inactive

Expected:
Deactivate (and especially Delete) should not be options in menu.  Also Edit should not be there since a member cannot edit anything.  Only for owner or admin.

**Comment by vincent99** [comment]
The options showing up in the menu is duplicate of #578, but the deactivate action must be missing an auth check since it actually works when you're only a member.

**Comment by tfiduccia** [comment]
v Local Project Build - Verified fixed (recheck in v 0.19.0)

**Comment by tfiduccia** [comment]
v0.19.2
Verified fixed
