### ISSUE TITLE
Deactivated project by member/owner are not visible to admin

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#606]
v0.17.0
Steps:
1.  Create a project as Admin and add rancherdev as member
2.  Log in as rancherdev in another browser
3.  Go to Projects and add a couple of projects
4.  Go back to admin browser and refresh manage projects page
5.  Deactivate one of rancherdevs projects
6.  Refresh page

Results:
The project disappears from admin screen and I can't get it back unless I activate project from rancherdev

Expected:
Since Admin can delete any project, I would expect to see all projects even if they are deactivated

**Comment by vincent99** [comment]
`GET /v1/projects?all=true` doesn't seem include inactive projects.

**Comment by tfiduccia** [comment]
v Local Project Build - Verified fixed (recheck in v0.19.0)

**Comment by tfiduccia** [comment]
v0.19.2
Verified Fixed
