### ISSUE TITLE
When a user project is automatically created, it should be externalIdType=github_user

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#607]
When you automatically create a "[github username] Default" project, the projectMember record is created with `{externalId: '1a42', externalIdType: 'rancher_id'}`.  `rancher_id` should only be used for the admin default project when auth is off, these should be `{externalId: '[github username]', exernalIdType: 'github_user'}`.

**Comment by vincent99** [comment]
Or don't create projects automatically... #595

**Comment by vincent99** [comment]
A '[github username] project' should be created only if BOTH these conditions are met:
  - The user previously had no account in rancher, so we're creating one for them right now.
  - The user will have no access to any other project (they weren't added as a member to an existing project).

**Comment by tfiduccia** [comment]
duplicate of #684
