### ISSUE TITLE
Adding target with empty rows, adds the target but doesn't close target overlay

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#608]
v0.17.0
Steps:
1.  Create a LoadBalancer
2.  Click on Add Target
3.  Click on + Add Container (leave this as Select a container...)
4.  Click on + Add External IP Address
5.  Put an ip address in second field
6.  Click Add

Results:
Looks like nothing happened.  But the IP address was added.

Expected:
Empty rows should be ignored and others should be saved.

**Comment by deniseschannon** [comment]
The target overlay doesn't exist anymore in v0.23.0-rc1. @tfiduccia please re-open if i'm incorrect.
