### ISSUE TITLE
Editing Balancing Config Button does not work

### ISSUE THREAD

**Issue by bscott** [rancherio/rancher#613]
Clicking the Editing button does nothing for me in Chrome. Rancher/Server:v017.0

![image](https://cloud.githubusercontent.com/assets/191290/7325342/9c8dd972-ea72-11e4-862e-f98fe5f55ef6.png)

**Comment by vincent99** [comment]
Fixed, though the config edit isn't very useful yet.  Should be able to add listener/healthcheck/etc editing for next week.

**Comment by tfiduccia** [comment]
v0.18.2
Verified fixed
