### ISSUE TITLE
If I edit service name from submenu on left pane, the page comes back blank

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#614]
v0.17.1
Steps:
1.  Go to Services page
2.  Add a Environment
3.  Add a target to environment
4.  Use the left submenu to edit environment
5.  Edit the Name and save

Results:
Page comes back and edit happens but the services are missing.  I have to hard refresh to get them back.

Expected:
Should show services.

I had dev tool on and it stopped in debugger and gave me this.
// Copy in the services
     for (i = 0; i < services.get("length"); i++) {
       columns[nextIndex()].push(services.objectAt(i));
     }
the debugger stopped me.  it said "Uncaught type error: Cannot read property ‘push’ of undefined"

**Comment by vincent99** [comment]
I don't think this is relevant any more...

**Comment by tfiduccia** [comment]
Build from master - June 9th
Verified fixed
