### ISSUE TITLE
Renaming a service causes all new containers to be created

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#616]
v0.17.1
Steps:
1.  Create Environment
2.  Create a service with scale of 2
3.  Edit the service name
4.  Restart the service

Results:
The service creates another 2 containers.  So now it has four.

Expected:
Should stay with the original two containers.

**Comment by alena1108** [comment]
Should work in the latest.

**Comment by tfiduccia** [comment]
build from master - june 9th
Verified fixed
