### ISSUE TITLE
Agent running on same box as server uses container IP, not public IP

### ISSUE THREAD

**Issue by adamkdean** [rancherio/rancher#618]
An agent running on the same box as the management server uses the container IP, meaning that monitoring in the UI does not work. 

![test](https://cloud.githubusercontent.com/assets/1639527/7338626/fb4b1cda-ec49-11e4-9588-3eefc7cf69ac.png)

Unsure if anything else breaks due to this as well?

**Comment by bscott** [comment]
@adamkdean I can't reproduce this. What version of Rancher are you using and how did you invoke the Rancher agent?

Thanks

**Comment by cloudnautique** [comment]
When you launch the cattle agent on the master you need to add the env variable CATTLE_AGENT_IP= the public up of the host.

**Comment by adamkdean** [comment]
@bscott I started the agent on the same machine as the server using the default agent command that the UI gives you. This is from my bash history:

    sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://snip/v1/scripts/90F5BA57193C25553524:1430071200000:0fV2koJ1EdCDTJsYOdhxMsexU

@cloudnautique Thanks Bill, I'll give that a go.

**Comment by adamkdean** [comment]
That worked, thanks.

    sudo docker run -d -e CATTLE_AGENT_IP=46.101.X.X --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://snip/v1/scripts/CD18D99C43173E42BEB3:1430157600000:RGT4YjWvaCh7x9iOX1XtjdXUM

**Comment by maslick** [comment]
Can you add ```-e CATTLE_AGENT_IP=``` to the UI?

**Comment by deniseschannon** [comment]
@maslick I've created an issue that talks about adding `-e CATTLE_AGENT_IP` to the UI in #728. This is more related to machines created using the UI. You could follow that issue to see what happens.

**Comment by adamkdean** [comment]
Just FYI this is now in the UI, when you try to add a host:

Optional: Specify the public IP that should be used for this host. This is required if you're trying to add the host the rancher/server container is on.
