### ISSUE TITLE
rancher/server & rancher/agent containers on the same host not working

### ISSUE THREAD

**Issue by hbokh** [rancherio/rancher#623]
As mentioned here: https://twitter.com/BOK/status/591931295414001664, when you first start a `rancher/server`-container, followed by a `rancher/agent`-container in the same host, the `docker0` IP is used for the host - instead of the public IP. 
Since the last couple of months I'm always starting a Rancher-server in *stand-alone* mode.  

**Versions:**
CoreOS 618.0.0 (server) and 633.1.0 (hosts) Stable on VMware ESXi 6.0
rancher/agent:v0.5.2
rancher/server:v0.16.3  
FYI I just tried to reproduce this on my running Rancher, where "coreos01" is the server and "coreos02" and "coreos03" are the hosts, but now the agent / host "coreos01" is not even showing up in the GUI...

**Comment by cloudnautique** [comment]
@hbokh when starting an agent on the same host as the master, you need to set the environment variable CATTLE_AGENT_IP=<public ip>

Are there any logs from the agent containers from your coreos01 host? Are you using Authentication?

**Comment by hbokh** [comment]
Using `CATTLE_AGENT_IP` makes no difference:
```
$ docker run -d -e CATTLE_AGENT_IP=192.168.X.Y --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://coreos01.internal:8080/v1/scripts/CF0D6B21EA6E81B07111:1430244000000:emoYnoWxLPunLTs4vTLykCwqA
7235456021fdbbd5faff1314e63d54f80409678b606798843d80c4f523eac148
```
The container is started but the new host still does not show up in the GUI, even after restarting the `rancher/server`-container too.

```
$ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                              NAMES
f4b329bbddc7        rancher/agent:v0.5.2             "/run.sh run"          7 minutes ago       Up 7 minutes                                           rancher-agent
8e571055a178        rancher/agent:v0.5.2             "/run.sh state"        11 minutes ago      Exited (0) 11 minutes ago                                      rancher-agent-state
5587d2fab8fd        rancher/server:beta              "/usr/bin/s6-svscan    3 days ago          Up 3 days           3306/tcp, 0.0.0.0:8080->8080/tcp   modest_ardinghelli
```

No authentication used.
Interesting logs from the `rancher/server` Java-related, so huge, `rancher/agent` only INFO-related stuff.

I will try by *destroying* my current setup and start from scratch.

**Comment by hbokh** [comment]
That did the trick! "coreos01" `rancher/host` has the expected public IP-address and monitoring shows up fine.
I also had to reboot both other clients (02 & 03) after stopping, deleting and purging them, with countless messages like these: `unregister_netdevice: waiting for lo to become free. Usage count = 1`.
