### ISSUE TITLE
[services] - Scaling down service results in the last instance of the service to be retained when the first instance was deleted/purged.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#624]
Server Version - V0.17.1

Steps to reproduce the problem:

Created an environment with scale set to 4.
Delete/Purge the first instance.
Scale down the service to 1.

After scaling down , I see that the 4th instance of the service being retained.

Expected Behavior:
We should have all the existing instances of the service removed and a new instance with name as "_1" be created.

**Comment by vincent99** [comment]
It shouldn't remove *all* of them or create a new container, but it would be nice to remove in reverse order so the lowest 1-$scale stay.

**Comment by alena1108** [comment]
@vincent99 yes, my PR covers it. It will discover all the "gaps" in the order, and fill them

**Comment by sangeethah** [comment]
@alena1108 , if the first instance of service  is deleted and then service is  scaled down to 1 , with your fix , we expect  second instance to be the one that is preserved and all other instances removed ?

**Comment by alena1108** [comment]
@sangeethah yes

**Comment by sangeethah** [comment]
Tested with server version - V0.18.1

Created an environment with scale set to 4.
Delete/Purge the first instance.
Scale down the service to 1.

After scaling down , I see that the 2nd instance being retained , all others removed.
Works as expected.
