### ISSUE TITLE
When the target Host of the Load balancer is in "Inactive" state , adding targets causes the target to be stuck in "activating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#627]
Server version - V0.17.1

Steps to reproduce the problem:
Create a LB and add a host , say H1 with 2 targets.
Deactivate host H1.
LB rule continues to work after this.

Try to add another target to this LB.
This results in the target to be stuck in "activating" state forever until the Host is activated again.

| 138 | NULL | loadBalancerTarget | 8f707dc3-172f-4efa-b2c2-ccc7ec654dee | NULL        | activating | 2015-04-28 15:06:58 | NULL                | NULL                | {"fields":{}} | NULL       |         274 |               59 |          5 |

When the host is activated , we see that the target addition succeeds.

When hosts are put in "Inactive" state , we would expect them to be in inactive state for a long time.
Instead of having to repeatedly attempt adding the target , it would be better to not allow for addition/deletion of targets in such cases and make the API return error.

**Comment by alena1108** [comment]
Should be fixed in the latest

**Comment by sangeethah** [comment]
Tested with server version - v0.25.0-rc1

Create a LB and add a host , say H1 with 2 targets.
Deactivate host H1.
LB rule continues to work after this.

Try to add another target to this LB.
Targets are not stuck in activating state anymore.

|  6 | NULL | loadBalancerTarget | ee8c4c2f-e2b5-4505-80b5-355316bcc18e | NULL        | active | 2015-06-19 14:49:59 | NULL    | NULL        | {}   | NULL       |          18 |                2 |          5 |

But I dont see the rules being programmed in the LB Agent.

**Comment by alena1108** [comment]
Its fine. They will get programmed on the subsequent rule addition or/and instance restart.
