### ISSUE TITLE
deactivateservices() for Environment / deactivate() for services does not wait for all the instances in environment/service to be stopped before changing state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#630]
Server version - V0.17.1

Create environment and add service with scale 2.
Activate service.

Now try to deactivateservices() for Environment / deactivate() the service .
Notice that the environment/service changes state to "Inactive" immediately without waiting for all the instances in the service to be deleted.

Environment/Service state change to "Inactive" should happen after all the instances relating to the environment/service is stopped.

**Comment by alena1108** [comment]
Environment never reflects the state of the service; it always stays in active state. As for the services, we might think if we need to wait for the instances to be fully stopped before considering service as inactive

**Comment by alena1108** [comment]
Spoke with Darren yesterday about this case; by now, we will wait only during the service activate for the instances to start. In deactivate/remove, we will schedule the stop/remove processes for instances, but we won't wait for its completion.
