### ISSUE TITLE
Load balancer across hosts is not working. 

### ISSUE THREAD

**Issue by clemenko** [rancherio/rancher#635]
Not sure if this working yet. But I can't seem to load balance across hosts. I have tested this with Centos7 and Ubuntu 14.04.

**Comment by deniseschannon** [comment]
We have been working on bugs within Load Balancer. In the next version of latest, it should be working much more reliably. 

Also, if you are testing the load balancer using a web browser, it might get cached and you won't be able to see the load balancing in action.

**Comment by deniseschannon** [comment]
@clemenko LB should definitely be working in the latest. Can you let me know if you are still having issues?

**Comment by clemenko** [comment]
It is.. thanks!

**Comment by deniseschannon** [comment]
@clemenko I'm going to close this issue. :)
