### ISSUE TITLE
[NATIVE-DOCKER] Backfill native create and start fields

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#636]
Once a container that was started outside of rancher is discovered by rancher, the parameters that were used to create and start it should be backfilled into the rancher container resource.

**Comment by sangeethah** [comment]
Following are the docker run options that gets synced to the cattle server successfully:
—name 
-d 
-it 
-p 
-e 
-v
—cpuset
--dns-search 
—dns 
--restart on-failure:10 
-m
-c 
--cpu-shares 
--cap-add AUDIT_CONTROL 
-u 
-w 
-h 
--cap-add
--cap-drop 
—privileged
-P
--device 

Imagename
Command 
Entry point


--volumes-from amd --link options are not working and this is tracked in  https://github.com/rancherio/rancher/issues/662
