### ISSUE TITLE
rancher-compose.yml should include networkId information.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#640]
Server version - V0.18.0

We do not include networkId information in the rancher-compose.yml currently. It would be good to include this information similar to requestedHostId which is included in ancher-compose.yml .

**Comment by alena1108** [comment]
We only support services on the managed network, so this info would be irrelevant. Closing by now

**Comment by sangeethah** [comment]
Lb is supported only in managed network. Even services can be supported only for containers in managed network? If that is the case , should we restrict deploying containers in unmanaged network from both from UI and at API level?

**Comment by alena1108** [comment]
yes. Services make sense only when the network - and dns - is controlled by rancher.
