### ISSUE TITLE
When service is deleted , the instances associated with the service do not get purged immediately.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#642]
Server Version - V0.18.0

Steps to reproduce the problem:
Create Environment and add service with scale 1.
Activate service.
Delete the service. Service get marked as "Removed" and the containers associated with the service are not listed in the service anymore.

But the service is in "Removed" state now. Can the services be purged at this point ? Or do we want to allow for the scenario to restore this instance and make it exist outside of the service?

**Comment by alena1108** [comment]
Instances won't get purged; they will be left in Destroyed state, and the purge cleanup thread will be responsible for cleaning them up, just like the regular instances.

**Comment by sangeethah** [comment]
If the instances get restored , they will be standalone instances not related with the service ?

**Comment by alena1108** [comment]
yes, they should be
