### ISSUE TITLE
docker-compose.xml has external_links for all its instances when the service linked to it is removed.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#643]
Server version - v0.18.0

Steps to reproduce the problem:
Create environment.
Add service test1
Add another service test4 with scale 2 and link it with service test1.
Remove service test1.
Observe the docker-compose.xml  generated for test4.
It has external_links pointing to its own instances.

test4:
  restart: 'no'
  external_links:
    f860486c-2566-4b9a-afc9-16858bde1255: f860486c-2566-4b9a-afc9-16858bde1255
    d8734353-415f-4e01-9c4c-fc4fe9c5c726: d8734353-415f-4e01-9c4c-fc4fe9c5c726
  tty: true
  image: ubuntu:14.04.1
  privileged: false
  stdin_open: true

**Comment by alena1108** [comment]
Most likely it has links to the instances of removed test1 as I can't reproduce this bug after fixing https://github.com/rancherio/rancher/issues/638.

**Comment by sangeethah** [comment]
Tested with server version - V18.0.2
Create environment.
Add service test1
Add another service test2 with scale 2 and link it with service test1.
Remove service test1.
 docker-compose.xml generated for test1 does not have any links or external_links as expected.
