### ISSUE TITLE
2nd time deactivating project, have to refresh for it to turn inactive

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#650]
v0.18.1
Steps:
1.  Go to manage projects
2.  Add a project
3.  Deactivate project
4.  Activate project
5.  Deactivate project

Results:
The project will keep spinning "deactivating" and not refresh to inactive like the first time

Expected:
Page should refresh and it should change to inactive

**Comment by vincent99** [comment]
I think this is fixed in #686

**Comment by tfiduccia** [comment]
v0.19.2
Verified fixed
