### ISSUE TITLE
When containers are renamed , they will be first ones to be picked up for deletion when instances are scaled down.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#653]
Server Version - V0.18.1

Create Environment.
Add service with scale 2.
Rename container to say "abc"
Scale down service to 1.

Instance "abc" is deleted and instance with index "_2" is retained.

This behavior is different from the use case where the user has not renamed the container , where scaling down to 1 would have resulted in instance "_2" being removed and "_1" retained. 

Is there a need to maintain any kind of ordering of what instances will need to be removed in case of scale down?

**Comment by alena1108** [comment]
I do have to maintain the order, because we always try to end up having instances w/o "gaps" in their names. And we always aim to have names that qualify for env_service_number pattern, therefore name defined on the container level has a lower priority
