### ISSUE TITLE
Environment name should be unique on per project basis not globally

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#659]
v0.18.1
Steps:
1.  Go to default project
2.  Go to Services
3.  Create a environment named "Environment1"
4.  Add another project and switch to that project
5.  Go to Services
6.  Create a environment named "Environment1"

Results:
Validation failed: name

Expected:
Should allow me to have unique names per project.

Additional Info:
This is also happening across users, so if I create a project and add a member.  Log in as member and try to create Environment with same name as one from a different Admin project, it won't let me.

**Comment by alena1108** [comment]
Ah, forgot to include account information when search for existing environments. Good catch, @tfiduccia

**Comment by tfiduccia** [comment]
v0.19.2
Verified fixed
