### ISSUE TITLE
link from wordpress container to mysql container doesnt work

### ISSUE THREAD

**Issue by baabeetaa** [rancherio/rancher#666]
I'm trying to add mysql and wordpress on two different hosts as demo ( https://vimeo.com/116803858 ).
This is the picture of the rancher server:

![rancher_server](https://cloud.githubusercontent.com/assets/11970690/7427835/44fc39be-f00e-11e4-8cba-7b5d73bffa56.png)

However, the link from wordpress container to mysql container doesnt work.
When creating wordpress container, the WORDPRESS_DB_PASSWORD is set.
I'm not sure what the problem is and how to fix it.

This is the log on h004 host:

root@h004:~# docker ps -a
CONTAINER ID        IMAGE                                                                     COMMAND                CREATED             STATUS                    PORTS                                          NAMES
5e1075acc8c6        wordpress:latest                                                          "/entrypoint.sh apac   12 hours ago        Exited (1) 12 hours ago                                                  ae30b012-734b-4559-b9c2-cf99fe1c002e
d04a7ba71b2f        rancher/agent-instance:v0.3.0                                             "/etc/init.d/agent-i   14 hours ago        Up 14 hours               0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   e24305db-a09a-4e64-bdba-8397987b36a9
e19ddb975ab5        9687c2da5bdc70f7016d2ee49d6d8e85b2343b43ee9d62bb999fd6c5e9faa22b:latest   "/run.sh run"          17 hours ago        Up 16 hours                                                              rancher-agent
d7309f7e2da3        9687c2da5bdc70f7016d2ee49d6d8e85b2343b43ee9d62bb999fd6c5e9faa22b:latest   "/run.sh register"     17 hours ago        Dead                                                                     high_swartz
7a250b847c60        9687c2da5bdc70f7016d2ee49d6d8e85b2343b43ee9d62bb999fd6c5e9faa22b:latest   "/run.sh state"        17 hours ago        Exited (0) 17 hours ago                                                  rancher-agent-state
root@h004:~# docker logs -f 5e1075acc8c6
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

---
Thank you

**Comment by vincent99** [comment]
Rancher does not currently support copying all the environment variables from a container into a linked container (as native docker does).  Philosophically, we feel like this is a significant security hazard (exposing e.g. MYSQL_ROOT_PASSWORD to any container  that asks).  Technically, we support dynamically changing the target of a link... but there is no way to dynamically change out the environment variables of a running container according to where the link currently points.

The error message you posted indicates that it is not even resolving a name or establishing a connection, so the password doesn't matter yet.  If you run `env` from within the container (or the "Execute Shell" action in the UI) you'll see what variables are available.  There will be entries for the host and port of each link.  As above, there will NOT be entries of variables copied from the other container, so you will need to pass in the credentials as variables on the Wordpress host itself, hardcode them in, or something more creative.

Then you'd need to edit the appropriate WordPress config file to use them for its database connection.  Environment variables are available as `$_ENV['VAR_NAME']` in PHP.

**Comment by baabeetaa** [comment]
Thanks @vincent99 It works now
