### ISSUE TITLE
Registry is not remembered in Add Container

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#673]
v0.18.2
Steps:
1.  Add the quay.io registry
2.  Go to Containers page
3.  Click on Add Container button
4.  Create a container using the quay.io registry
5.  Click on Add Container button

Results:
The registry is set back to docker.  The image is still there.  This is also broken in the Add Container from Host Page.

Expected:
Registry should be set to quay.io

**Comment by tfiduccia** [comment]
Either we should remember the whole path or nothing at all, this would include credentials for registry.

**Comment by vincent99** [comment]
There is no dropdown or credential list as of rancherio/ui#152.

**Comment by tfiduccia** [comment]
v0.20.1
Verified Fixed
