### ISSUE TITLE
using ranchervm

### ISSUE THREAD

**Issue by sainath14** [rancherio/rancher#674]
Hello rancher,
 I am trying to use ranchervm, after using 
docker run -e "RANCHER_VM=true" --cap-add NET_ADMIN -v \
    /tmp/ranchervm:/ranchervm --device /dev/kvm:/dev/kvm \
    --device /dev/net/tun:/dev/net/tun rancher/vm-rancheros

how do I connect to the unix socket that it prints? looks like vncviewer does not support unix sockets
i am using vncviewer 1.3.9
Any help is appreciated

**Comment by sheng-liang** [comment]
There are two ways to do this:

1. Use a VNC viewer that supports Unix sockets, like ssvncviewer.
2. Start the rancher/vmmgmt container to view the console.

**Comment by deniseschannon** [comment]
@sainath14 If you have further questions about ranchervm, can you please open them up at https://github.com/rancherio/vm/issues. I'll close this issue.
