### ISSUE TITLE
View in API shows only default project if auth is off

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#675]
v0.18.2
Steps:
1.  Make sure Authentication is off
2.  Add another project
3.  Switch to that project
4.  Add a host
5.  View in API

Results:
No host information because it only see default project

Expected:
Should see host info

Additional test info:
You can see this as well by clicking on Endpoint in the API & Keys page

**Comment by vincent99** [comment]
Fixed in rancherio/ui#155, "View in API" links go to /v1/project/**project_id**/resource now

**Comment by tfiduccia** [comment]
v0.20.1
Verified Fixed
