### ISSUE TITLE
Can't delete service if container fails

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#676]
v0.18.2
Steps:
1.  Add a service but put bad info into the uuid so it doesn't create
2.  Wait for containers to fail.
3.  Try to stop Service and deactivate

Result:
Service just keeps running and the container keep restarting

Expected:
Service to stop and containers to purge

**Comment by alena1108** [comment]
Good catch. The reason for the deactivation failure - service-instance map fails to remove as an instance.purge process. And the reason why map removal fails - one state transition is missing for the map removal process

**Comment by tfiduccia** [comment]
v0.19.2
Can stop and delete service.
