### ISSUE TITLE
"Waiting for host to check in..." on DigitalOcean node

### ISSUE THREAD

**Issue by DrewEaster** [rancherio/rancher#682]
I've just spun up a new node on DigitalOcean from the management server UI (running on a separate DigitalOcean droplet). I'm seeing the message "Waiting for host to check in..." and it's not going away - it's been in this state for 15 minutes or so now.

Am I missing something? It was my understanding that DigitalOcean droplets leave all ports open by default so I wasn't aware that I'd have to do anything specific to let traffic in/out of the node.

Any ideas what might be wrong?

**Comment by deniseschannon** [comment]
I just had the same issue. Is your RancherServer on a public IP address? without a public IP address, the node has no way to communicate back to Rancher.

**Comment by deniseschannon** [comment]
@DrewEaster please re-open if you haven't been able to fix it. typically if Rancher server isn't on a public IP, then the node can't communicate back.
