### ISSUE TITLE
After Adding/Editing a project, the Manage projects title keeps changing

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#683]
v0.18.2
Steps:
1.  Go to Manage projects page (notice the Manage Projects title in upper left corner)
2.  Create a project (notice the Manage Projects title is gone and replaced by dimmed < All Projects, which does nothing)
3.  Edit a project

Results
Now the < All Projects is gone and replace by a < Back which is clickable and takes me back to edit page.

Expected
Should stay with "Manage Project" title

**Comment by vincent99** [comment]
These buttons and titles don't exist anymore..

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
