### ISSUE TITLE
Allow any Github user but no projects, new user can't see default

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#684]
vLocal Project Build
Steps:
1.  Go to Access and authenticate as yourself
2.  Set Site Access to Allow any GitHub user
3.  Go to different browser and login as rancherdev

Results:
You are logged in and put in the project screen, but there are no projects.  If you go back to admin you will see that a "rancherdev Default" was created.

Expected:
I would assume rancherdev should be able to see their default project, or don't create one at all.

**Comment by tfiduccia** [comment]
v Local Project Build - Verified fixed.  Reverify in v0.19

**Comment by vincent99** [comment]
A project is being created but there is no projectMember entry for the new user, so they can't see it.

**Comment by tfiduccia** [comment]
v0.19.2
Verified Fixed
