### ISSUE TITLE
Hiding Site Access only works part of the time

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#689]
v0.18.2
Steps:
1.  Go to Access Control
2.  Authenticate
3.  Click on Customize
4.  Switch it to Allow any Github user and Save
5.  Go to host page or any other page and back.  Also do a hard refresh (nothing happens and Site Access is still fully visible)
6.  Click on Restrict to specific GitHub users and organization members: and Save
7.  Change pages and go back to Access Control (nothing happens)
8.  Do a hard refresh of the page

Result:
Finally Site Access is hidden again and the Customize button is showing.

Expected:
After leaving page and coming back or hard refresh Site Access should always be hidden with customize button, or never hidden.

**Comment by tfiduccia** [comment]
v Local Project build - Verified fixed (recheck in 0.19.0)

**Comment by tfiduccia** [comment]
v0.19.2
Failed

**Comment by vincent99** [comment]
lies

**Comment by tfiduccia** [comment]
v0.19.2
Reviewed with Vince and working as designed - Verified fixed
