### ISSUE TITLE
After removing service link, Environment UI does not refresh to reflect the removed links. 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#694]
Server Version - V0.18.2

Steps to reproduce the problem:
Create an environment 1 Lb service and 1 regular service.
Linked Lb service with service.
Edit the Lb service and remove the existing link.
When we are brought back to the environment view , we still see the service linked to LB service.

Once the environment page is refreshed , the link disappears from the UI.

**Comment by will-chan** [comment]
This looks resolved, but Vince should verify.

**Comment by vincent99** [comment]
yup..

**Comment by tfiduccia** [comment]
v0.23.0-rc1
