### ISSUE TITLE
[Install] [Agent] client and server don't have same version (client : 1.16, server: 1.15)

### ISSUE THREAD

**Issue by brycekottke** [rancherio/rancher#70]
**Command to register node - node**
docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://MANAGMENT_IP:8080/v1/scripts/FROM_RANCHER_SERVER

*also tried:*

docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://MANAGMENT_IP:8080

**Error - node**
8d2c89aad98e: Download complete 
Status: Downloaded newer image for rancher/agent:latest
time="2015-01-29T18:25:05Z" level="fatal" msg="Error response from daemon: client and server don't have same version (client : 1.16, server: 1.15)" 
Please ensure Host Docker version is >= 1.4.1 and container has r/w permissions to docker.sock

**docker version - server**
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**docker info - server**
Containers: 1
Images: 14
Storage Driver: devicemapper
 Pool Name: docker-202:1-152213-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 730 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.364 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: ip-10-0-0-70
ID: DEHI:VRO4:JOYE:ZNUS:C7FM:4W6Y:ENYV:Q7LX:IUIU:VHIA:7XJR:EH6K
WARNING: No swap limit support

**Comment by deniseschannon** [comment]
@brycekottke We've updated the command for registering docker nodes (per https://github.com/rancherio/rancher/issues/267). Please try that and see if you have any issues. If so, please re-open.
