### ISSUE TITLE
When host is unreachable (host destroyed/down), host continues to be shown as being in "Active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#701]
Server Version - V0.18.2

Add a host to rancher.
Destroy the host/ power down the host.
Host continues to be shown as being in "Active" state.

Deploying containers on this host errors out with "Unable to find Placement" error.
Trying to deactivate the host , it is stuck in "deactivating" for ever.

I am able to delete this host even when the host is stuck in "deactivating" state.

Expected Behavior:
We should be able to show the status of host as being unreachable .

The states of the containers continue to be shown as "running" . This will be fixed as part of native docker state sync?

**Comment by deniseschannon** [comment]
verified fix in v0.24.0-rc2

**Comment by deniseschannon** [comment]
Verified fix - v0.24.0-rc2

There is issues in deleting this host, but that's addressed in another bug.
