### ISSUE TITLE
Support for Rancher installation using a proxy

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#716]
Current Rancher installation requires direct access to the internet to pull various artifacts.  We need to support the capability of configuring a proxy in the event the installation is behind a company firewall.

**Comment by AnthonySendra** [comment]
Hello,

I know it's not exactly what you excepted, but you can use this container https://registry.hub.docker.com/u/klabs/forgetproxy/ waiting a solution from Rancher. This is how I launch rancher behind my company firewall. Hope that could help.

**Comment by foobarto** [comment]
When starting the rancher agent container you can pass https_proxy environment variable - this will make the scripts configuring the agent use your proxy...

docker run ...... -e https_proxy=https://your.proxy.com:1234/
