### ISSUE TITLE
rancher-agent container label fails to update after Rancher upgrade

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/rancher#72]
After I upgraded Rancher agent from 0.2.1 to 0.3, the label "latest" for rancher-agent still points to the old version and as a result the wrong Rancher agent was started.

A fresh install works fine. An in-place upgrade will always fail.

**Comment by ibuildthecloud** [comment]
The way Docker works is that if a tag is already pulled locally, it will not remotely check if there is a new version of that tag.  In general this works fine if tags never change, but specifically "latest" is also changing.

There's two aspects to this issue.  First, if a new release "N+1" is released a user may have the rancher/agent image for N locally cached as "latest".  What this means is that when the host registration process happens they will be registering with rancher/server N+1 using rancher/agent version N.  This essentially means we need to come up with a forward compatible approach to the agent registration process.

The second part is that Rancher dynamically updates the agent images.  It the rancher/server requires N+1 and the server has N, it will upgrade the agent to N+1.  Assuming that the registration process between N and N+1 is compatible, this works fine.  Between 0.2.1 and 0.3.1 of rancher/agent the host registration process was drastically changed to support GitHub authentication and that is what is causing the current issue with Rancher v0.5.0.

During the agent upgrade process we should pull latest at that time in addition to the specific version.

**Comment by deniseschannon** [comment]
This agent upgrade has been working fine based on what Rancher server requires.
