### ISSUE TITLE
API to determine version of Rancher Server

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#721]
It's already been requested by someone if they could use the API to find out the version of Rancher that is running.

**Comment by vincent99** [comment]
+1, then I could add an about screen the UI showing it.

**Comment by deniseschannon** [comment]
We need this by 1.0 so that we can start showing the version in the UI.

**Comment by will-chan** [comment]
Would like to see all versions of any system services we launch or use.  (i.e. GMS, agents, network/lb services, zookeeper, redis, mysql, etc.)

**Comment by ibuildthecloud** [comment]
We can get the versions of rancher code easily in, MySQL, zk, redis are more work

**Comment by deitch** [comment]
I see this was closed last year, but how do I do it? What is the API call?
