### ISSUE TITLE
wrong -m option to curl command

### ISSUE THREAD

**Issue by sheng-liang** [rancherio/rancher#73]
The rancher-agent calls the following curl script:

curl -s -m 15 --retry 2 -L --retry 5 'https://github.com/rancherio/python-agent/releases/download/v0.8.0/python-agent.tar.gz?current='

"-m 15" means terminate the command after 15 seconds. "-m" option does not specify connection timeout.

As a result rancher-agent cannot start if python-agent takes more than 15 seconds to download.

**Comment by ibuildthecloud** [comment]
This parameter was erroneously used.  The intention was to set a socket timeout but something got lost in translation.  Unfortunately curl does not support a socket timeout.  We do not want connections to hang forever if there is a communication error, so `-m` will probably just be increased to 30 minutes.  Additionally `--connect-timeout` should be set too.
