### ISSUE TITLE
Validation tests for Service Discovery

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#731]
Add integration tests for Service Discovery.
- [x] Validation tests for Service Discovery basic functionality relating to Activate/Deactivate services/scale/Activate/Deactivate environment
- [x] Validation tests for  Load Balancing Services
- [x] Validation test cases for port conflicts relating to LB services
- [x] Validation tests for Service linking
- [x] Validation tests for Service Data Volume Mounts 

Service Discovery test cases are being tracked in - https://github.com/rancherlabs/the-ranch/wiki/Rancher-Validation-Test-cases

**Comment by sangeethah** [comment]
Service Discovery test cases are being tracked in - https://github.com/rancherlabs/the-ranch/wiki/Rancher-Validation-Test-cases
