### ISSUE TITLE
Service Links - When one of the instances in the consumed service is down , accessing the service results in accessing the stopped instance and then redirected to healthy instances.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#737]
Service Links - When one of the instances in the consumed service is down , accessing the service results in accessing the stopped instance and then redirected to healthy instances.

Version - V0.19.1

Create service - test1 with 2 instances.
Create service - test2 with 3 instances.
Link test2 to test1.

From instances of service1 , tried to access service2 multiple times.
I see that only 1 instance (the first instance from the resolved list of container ips) is being accessed all the time.
Stop this instance that is being picked all the time.
Now try to access service2.

Notice that accessing the service results in accessing the stopped instance and then gets redirected to healthy instances

--2015-05-07 17:05:57--  http://test2/name.html
Resolving test2 (test2)... 10.42.145.192, 10.42.160.153, 10.42.180.65
Connecting to test2 (test2)|10.42.145.192|:80... failed: No route to host.
Connecting to test2 (test2)|10.42.160.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13 [text/html]
Saving to: `name.html'

100%[================================================================================================================================================================>] 13          --.-K/s   in 0s      

2015-05-07 17:06:02 (2.03 MB/s) - `name.html' saved [13/13]

**Comment by sangeethah** [comment]
This the same issue seen when the costumed service is deactivated . All the instance in the service is down. But when trying to access this service , there is an attempt made to access each of the stopped instances , before reporting a connection error.

**Comment by vincent99** [comment]
`wget` got back multiple IPs and its behavior is to try each one of them until it gets a connection opened.  That part is a feature.

Seems like containers with status != 'active' should not be included in the DNS responses though.  @alena1108 Can you remove them from the rancher-dns config file and send a `kill -HUP ${rancher-dns-pid}` to reload it?

**Comment by sangeethah** [comment]
Tested with server Version - V0.20.0

When one of the instance in the cosumed service is stopped , it gets removed from the list of ip addresses resolving to the service name.

When access the service , it gets resolved to one of the instances  that is still up.
