### ISSUE TITLE
Feature: Service Discovery

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#74]
Support a DNS based for registering and discovery of "Services" across multiple environments.  
Support for a basic "Red/Green" health checks.

**Comment by hrwebasst** [comment]
There have been some strides with (Registrator)[https://github.com/progrium/registrator] and consul. Maybe that could be pulled in or used. I think that the maintainer may be interested for this to be pulled in somewhere else as I know he has been sponsored for work on Dokku his pet project.
