### ISSUE TITLE
[Native Docker] Support for other native docker commands

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#745]
Running these commands should all result in the proper state being reflected in rancher:
create (state will be stopped in rancher), run stop, destroy, kill

**Comment by cjellick** [comment]
in the 0.19.* release

**Comment by sangeethah** [comment]
Tested with server version - 0.19.2

Tested Create , run , stop , kill commands from host side . Status of the container gets synced to the rancher server.

By destroy , i assume it is docker rm (-f) command. When i remove docker containers from host , I see status of the host is set to "Destroyed" and eventually it gets purged.In this case , should we be marking the container as being in "purged" state directly?  When I attempt to restore this instance , a new instance gets created. This doesn't seem ideal.

Also when I do docker restart , I see the container state being synced as "stopped".

**Comment by cjellick** [comment]
The destroy/remove behavior is working as intended. A new instance being created is what is supposed to happen. I'll talk it over with Darren again just to double check that that's what we want.

The container going to "stopped" on a restart is a bug. Will address.

**Comment by will-chan** [comment]
I assume this bug is done?

**Comment by cjellick** [comment]
yes, this is done. In particular, the "The container going to "stopped" on a restart is a bug." bug is addressed.

**Comment by sangeethah** [comment]
Tested with server version - V0.23.0-rc6.

When containers are restarted on hosts , they get synced correctly on the  rancher server. I see them move to "stopped" state and then get to"running" state.
