### ISSUE TITLE
Machine/Host Name is being saved but not recognized on re-enter

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#746]
v0.19.2
Steps:
1.  Create a DO or Amazon host
2.  Re-enter Add Host
3.  Click on Create

Results:
When you enter, you will notice that the host name is saved from previous Add.  Also when you click on Create it gives the "name" is required error.  Even if you fill out everything, it still thinks there is nothing in the name field until you go into that field and do something.

Expected:
I don't think we should save the previous name of the host.  But if we do, it should recognize that there is text in there.

**Comment by vincent99** [comment]
Fixed in https://github.com/rancherio/ui/pull/153

**Comment by tfiduccia** [comment]
v0.20.1
Verified fixed - host name is no longer saved.
