### ISSUE TITLE
Ease of adding Containers

### ISSUE THREAD

**Issue by hibooboo2** [rancherio/rancher#75]
Currently when you add a container through the us on rancher you have to type in the image name. It would be much better if cattle had an endpoint to add images associated with users/groups/projects/everyone and have this list popup as part of the ui in cattle when creating a container.  

It would also be nice to be able to have an option to start multiple of the same container with one click... 

 Maybe a box in the ui with number to deploy and a default of 1.

**Comment by vincent99** [comment]
Image validation/autocomplete and starting multiple containers are all part of other newer issues...
