### ISSUE TITLE
Default project id is being stored after deleting and creating new build

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#752]
v0.19.2
1.  Build 19.2
2.  Add a bunch of project and set your default to later one
3.  Delete 19.2
4.  Re-build 19.2
5.  Enter Rancher

Results:
Host and everything is blank because it's still trying to to project that was removed.

Expected:
Should start on default project

**Comment by vincent99** [comment]
Fixed in rancherio/ui#150 (0.9.3)

**Comment by tfiduccia** [comment]
This is also happening if I just delete the project.  It is still stored as default.

**Comment by vincent99** [comment]
Fixed in https://github.com/rancherio/ui/pull/156 , the default project is now a preference stored in the database instead of in a local browser setting, so if you switch backends it doesn't remember the old default.

**Comment by tfiduccia** [comment]
v0.20.2
Verified Fixed
