### ISSUE TITLE
Not able to ping between containers on different hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#754]
Server version - V 0.19.2

Steps to reproduce the problem:

Create container1 in host1.
Create container2 in host2.

Not able to ping container2 from container1.

I see that the the ip address of container1 is programmed in Network Agent of host2 but not in host1.

In my set up , I have been doing some testing withlink services to check for DNS resolution. When containers where on different host , DNS resolution was getting a connection error.  This is when I noticed that the containers are not able to ping each other across hosts. 

Note- DNS resolution works as expected when all the instances that it resolves to are in the same host as the client container from which we are accessing the DNS.

**Comment by sangeethah** [comment]
This issue is not reproducible all the time.
In a fresh set up I have , I am able to ping containers across hosts.
Also the DNS resolution works for containers across host.

**Comment by vincent99** [comment]
As far as I can tell the overlay network works fine.. Reopen if you have a reproducible problem.
