### ISSUE TITLE
State system requirements (ram/cpu)

### ISSUE THREAD

**Issue by basickarl** [rancherio/rancher#756]
If you guys could please state the recommended system requirements in terms of cpu and ram that would be great, just spent half an hour trying to figure out why I couldn't log into rancher, was due to memory issues (wasn't expecting rancher to use so much ram).

**Comment by deniseschannon** [comment]
@basickarl sorry about that! 

@ibuildthecloud what's the minimum system requirements that we could add to the README?

**Comment by deniseschannon** [comment]
Duplicate of #617.

@basickarl We're hoping to get some official docs out in the next couple of weeks so we'll make sure to include that in the docs as well as the README.
