### ISSUE TITLE
DNS resolution takes ~15 sec to return the containers ip address list.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#757]
Server Version - V.0.19.2

Steps to reproduce the problem:
Scenario 1:
Create service - test1 with 2 instances.
Create service - test2 with 3 instances.
Link test2 to test1.

From instances of test2 , tried to access test2 multiple times.
Every time I access the DNS name , there is a delay of ~15 secs before the  containers ip address lists are provided.

Scenario 2:
Create container - c1 and link it with container c2 using name as - web1.

From container1 , try to ping web1 or access the exposed ports in web1 using link name - web1.
Every time I access the link name , there is a delay of ~15 secs.

**Comment by sangeethah** [comment]
The same issue is also seen with server Version - V0.20.0 and agent version - v0.7.6

**Comment by vincent99** [comment]
Fixed in rancherio/cattle#429

**Comment by vincent99** [comment]
This should be fixed in v0.20.1

**Comment by sangeethah** [comment]
Tested with Server version - V0.20.1

Steps to reproduce the problem:
Scenario 1:
Create service - test1 with 2 instances.
Create service - test2 with 3 instances.
Link test2 to test1.

From instances of test1 , tried to access test2 . The containers ip address lists are provided immediately and there is no delay in accessing the containers in service using service names.


Scenario 2:
Create container - c1 and link it with container c2 using name as - web1.

From container1 , try to ping web1 or access the exposed ports in web1 using link name - web1.
There is no delay when accessing the links.
