### ISSUE TITLE
Rancher Server should be a startup process on host

### ISSUE THREAD

**Issue by keyscores** [rancherio/rancher#759]
My expectation would be that Rancher Server would startup when I boot the host again.

I've had to reboot the host for Rancher Server more than once during my testing (it uses a surprising amount of RAM). 

It would be safer in production environments if Rancher Server container would be started on the host's startup. (same for agents likely)

Seems a bit inelegant to have to ssh and run a container if the Rancher Server fails for whatever reason.

As a short term solution your quick-start tutorial should simple include these scripts for coreOs, Ubuntu, etc.

**Comment by ibuildthecloud** [comment]
The amount of memory Rancher uses is high and will likely reduce over time.  At the moment memory optimization is not a high priority.

Regarding the startup of rancher server, are you referring to 'rancher/server' container?   If you wish the container to restart and reboot then add "--restart=always" to the docket command.  For example

    docker run --restart=always -p 80:80 rancher/server

**Comment by keyscores** [comment]
Ok interesting, i didn't know that config. Wouldn't it be nice to have that in the 'getting started' docs. My intuition is that this should be the default (only?) way to run rancher/server.
Thanks
