### ISSUE TITLE
[Private Registry] Design spec for Private Registry Support

### ISSUE THREAD

**Issue by wlan0** [rancherio/rancher#76]
This feature can be divided into two phases

Phase 1 
Change cattle container start lifecycle to allow private repos
        1.1 - The cattle container lifecycle should stop validation docker images by talking to docker hub on Instance Create. It should directly pass through the image-Uuid to rancher agent.
        1.2 - On 'reply-to' event of Instance create,  update the database to create record in the appropriate tables.

Phase 2
        2.1 - Add support to store registry address in storagePool table
        2.2 - Create a registry credential table that holds username, password and email and add a link to storage pool table
        2.3 - Send credentials to rancher agent for the appropriate registry on instance create 
        2.4 - Update python agent to accept credentials and pass them over to docker

**Comment by sheng-liang** [comment]
What is the user experience like?

1. How are private registries added into the system?
2. Who can add private registries?
3. I assume private registries are visible globally? Or can they be private for a given user?

**Comment by sidharthamani** [comment]
1. The user can add private registry information through the UI
2. Any authenticated user can add private registries.
3. Private registries are owned by the account that creates it

**Comment by smw355** [comment]
Can more than one private repository be added per user?

Best Regards,

Shannon Williams
+1 (650) 521-6902
shannon@rancher.com<mailto:shannon@rancher.com>


On Feb 3, 2015, at 7:18 PM, Sidhartha Mani <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  The user can add private registry information through the UI
  2.  Any authenticated user can add private registries.
  3.  Private registries are owned by the account that creates it

-

**Comment by sidharthamani** [comment]
Yes multiple repositories be added per user.
