### ISSUE TITLE
Digital Ocean integration, please include CoreOS images

### ISSUE THREAD

**Issue by keyscores** [rancherio/rancher#760]
Pretty please, can we have CoreOS in the Digital Ocean hosts workflow, and not only Ubuntu?

**Comment by ibuildthecloud** [comment]
We use docker machine to provision hosts.  I don't expect CoreOS support to come to machine soon (if ever).  As a consultation RancherOS support is coming to machine soon.  https://github.com/docker/machine/pull/1096

**Comment by keyscores** [comment]
Will we see rancherOS be a default image in Digital Ocean soon?

Lucas Geiger
