### ISSUE TITLE
Can't see hosts and containers created with API in UI

### ISSUE THREAD

**Issue by AnthonySendra** [rancherio/rancher#763]
Hello,

Rancher server v0.19.2

In order to use an automatic deployment tool, I can’t get the url like 
```
http://myip:8080/v1/scripts/4CCF7BCDE67E62FBDBA8:1431248400000:Q1gxB9s6n3rthyIa54GVZueAA
```
when I create an host, because I only use the api (or maybe there is a way to retrieve the samed IDs with api ?).

Because of this, when I run
```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.0 http://myip:8080
````
on my host, I can see it in the api but not in the UI interface.
It’s seems because when I create an host without script it’s created with a different accountId that from the UI interface. And when I create my containers from API it’s the same problem: created with a different accountId and can’t see them in UI.
But my containers are running and I can even ping two containers linked, it's just a problem in the UI.

There is a solution for manage hosts and containers only from the API without using the UI and retrieve my created hosts and containers in the UI (in other words: only use the UI for control what is created from the API) ?

Thanks for all your great job on this tool !

**Comment by ibuildthecloud** [comment]
Hey, sorry about this.  The v0.19.x releases are terribly broken.  When we do a build we test it out and if it's good we label it as beta.  After further QA we then label it as latest.

We do a very poor job of communicating this.  Currently beta points to 0.18.x.

This specific issue you are encountering is what is broken in v0.19.x.  We revamped the internals of accounts and projects but we found that through the API it was quite easy to accidentally do the wrong thing and put resources into the wrong account.

This will be fixed in the next build (it's already on master) which will be 19.3 or 20.

**Comment by AnthonySendra** [comment]
Ok thanks for this information.
I tried to use version v0.19.x because in previous version I was not able to ping a container A from a container B. I don't know if I have to open an issue for that ?

Thanks again for your job, and I'll wait for the next version :)

**Comment by deniseschannon** [comment]
@AnthonySendra no need to open an issue for not being able to ping containers. it's a known issue that should already be filed and is being worked on.

**Comment by deniseschannon** [comment]
@AnthonySendra As previously discussed the v0.19.x releases were really broken. Do you want to try latest (v0.20.4) to see if you are still having this issue?

**Comment by AnthonySendra** [comment]
@deniseschannon with rancher server v0.20.4: 

- host A with a container ubuntu linked to redis in host B
- host A with container ubuntu2 linked to ubuntu
- host B with a container redis

In host A, in container ubuntu, try to reach container redis don't work:
```
PING redis.rancher.internal (10.42.16.158) 56(84) bytes of data.
^C
--- redis.rancher.internal ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3021ms
```

In host A, in ubuntu2, try to reach container ubuntu work fine.

**Comment by deniseschannon** [comment]
What type of machine are you running the hosts/server? Are you running any of the hosts on the same machine as rancher server? Trying to mimic your environment. 

Also, there is typically a 10-15 second delay the first time you try to ping, so you might need to send more than 4 packets. 

Pinging between containers should be working with v0.22.0-rc1.

**Comment by AnthonySendra** [comment]
On v0.20.4 and v0.22.0-rc1, even after a long time waiting, ping display nothing
```
PING redis.rancher.internal (10.42.184.144) 56(84) bytes of data.
^C
--- redis.rancher.internal ping statistics ---
197 packets transmitted, 0 received, 100% packet loss, time 196739ms
```

I'm running two VM with vagrant and both can talk to each other.

I'm runing vagrant on mac OSX, I'm not sure, but maybe that could help, there is my Vagrantfile:
```
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "node1" do |node1|
    node1.vm.network :private_network, :ip => "172.16.255.251"
    node1.vm.hostname = "node1"

    node1.ssh.private_key_path = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa' ]
    node1.ssh.forward_agent = true
    node1.vm.synced_folder "../", "/my-project"
  end

  config.vm.define "node2" do |node2|
      node2.vm.network :private_network, :ip => "172.16.255.252"
      node2.vm.hostname = "node2"

      node2.ssh.private_key_path = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa' ]
      node2.ssh.forward_agent = true
      node2.vm.synced_folder "../", "/my-project"
    end

end
```

Server run on node1, and agent on node1 and node2.

**Comment by deniseschannon** [comment]
Since the agent/server are running on node1, you'll need to update the command to add in `-e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER>`. 

https://github.com/rancherio/rancher/issues/872

You won't be able to stop the agent and restart it with `-e`. I think you'll need to stop and remove the agent container and just start a new container.

**Comment by AnthonySendra** [comment]
In my case, host node1 with IP 172.16.255.251 (like we can see in my Vagrantfile) even with the command:
```
sudo docker run -d --privileged -e CATTLE_AGENT_IP=172.16.255.251 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.6 http://172.16.255.251:8080/v1/scripts/DE068FF37171AE400466:1432832400000:1XfJSvk5D5YY8rWbaxyGZnx730
````
for starting my agent on node1 and normal command given by the UI for starting my agent on node2 , I'm not able to reach redis (node2) container from ubuntu container (node1). Even after a while

**Comment by AnthonySendra** [comment]
Hello,

Working fine with some changes in my Vagrantfile. I don't know why, but with public network, rancher service discovery works fine !

For people who come here with the same issue, there is my working Vagrantfile:

```
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "node1" do |node1|
    node1.vm.network :public_network
    node1.vm.hostname = "node1"

    node1.ssh.private_key_path = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa' ]
    node1.ssh.forward_agent = true
    node1.vm.synced_folder "../", "/my-project"
  end

  config.vm.define "node2" do |node2|
      node2.vm.network :public_network
      node2.vm.hostname = "node2"

      node2.ssh.private_key_path = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa' ]
      node2.ssh.forward_agent = true
      node2.vm.synced_folder "../", "/my-project"
    end

end
```

**Comment by deniseschannon** [comment]
Glad to hear that it's working. @AnthonySendra I'm wondering if the private network didn't work because Rancher picked up the wrong IP (which sometimes happens with a private IP). In that you case, you could try adding `-e CATTLE_AGENT_IP=<private_ip>` to the custom commands when adding the agent to the server. You'd need to insert the environment variable before the image name.

**Comment by AnthonySendra** [comment]
Event with <code>-e CATTLE_AGENT_IP=<private_ip></code> in command when I'm running both agents, I still can reach my redis container from ubuntu. The only solution I found, it's to create a public network. I'm not an expert in vagrant, but I would liked to use private network instead :/

**Comment by deniseschannon** [comment]
I copied your Vagrantfile with the private networking and had no issues launching Rancher and the scenario you setup. 

Do you mind starting with a fresh environment and trying latest (v0.23.0-rc6), which was released last Saturday. 

Whenever you add the host to the same node as where you have rancher server launched, make sure to add in the `-e CATTLE_AGENT_IP=172.16.255.251` if you launch server on Node 1 or  `-e CATTLE_AGENT_IP=172.16.255.252` if you launch server on Node 2. 

Command would look something like this:

```
sudo docker run -d --privileged -e CATTLE_AGENT_IP=172.16.255.251 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://172.16.255.251:8080/v1/scripts/A37F9AA828E6E03F2965:1433800800000:vD2o0gmWUd0xc6g6vgtJrcl15XU
```

**Comment by AnthonySendra** [comment]
$ vagrant up
    $ vagrant ssh node1

When I'm on my node1, run the server:

    vagrant@node1:~$ docker run -d -p 8080:8080 rancher/server:v0.23.0-rc6

Get the url from UI and add the CATTLE_AGENT environment for run agent on node1

    vagrant@node1:~$ sudo docker run -d --privileged -e CATTLE_AGENT_IP=172.16.255.251 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://172.16.255.251:8080/v1/scripts/9BE91CA480A854434906:1433876400000:h5nW1UBiFIlet3ju1TmWslsuG58

Get the url from UI and run the agent on node2:

    vagrant@node2:~$ sudo docker run -d --privileged -e CATTLE_AGENT_IP=172.16.255.251 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://172.16.255.251:8080/v1/scripts/9BE91CA480A854434906:1433876400000:h5nW1UBiFIlet3ju1TmWslsuG58

 Next, I created a redis on agent 2 and a linked ubuntu on agent 1.

    $ vagrant@node1:~$ docker exec -ti <ubuntu_container_id> /bin/bash
    $ root@5f74bb49ed8c:/# ping redis
```
PING redis.rancher.internal (10.42.181.3) 56(84) bytes of data.

^C
--- redis.rancher.internal ping statistics ---
72 packets transmitted, 0 received, 100% packet loss, time 71387ms
```

I'm still not able to reach redis from ubuntu.
It's weird if it works for you... I'll try on a new computer with a fresh install

**Comment by deniseschannon** [comment]
Can you try one more thing? Add a second container on each node and try to ping again? Sometimes there is an issue with the first container. It's rare, but could happen.

**Comment by AnthonySendra** [comment]
Still not working :/

1. Create redis1 on host 2
2. Create ubuntu1 on host 1 with a link to redis1
3. Create redis2 on host 2
4. Create ubuntu2 on host 1 with a link to redis2
5. Enter in ubuntu2 and trying ping redis2 -> nothing happen
6. Create a ubuntu3 on host 2 with a link to ubuntu2
7. Enter in ubuntu3 and trying ping ubuntu2 -> nothing happen

When I create my container I change nothing in advanced option (except the link) and I have in network field the value "managed", am I right ?

**Comment by deniseschannon** [comment]
I have followed the steps that you have outlined with the same Vagrantfile and I am able to ping redis2 from ubuntu2. 

Since we're doing the exact same thing, I have no idea why it works for me and not for you....

**Comment by dxxxxxg** [comment]
Hi Anthony.  Can you email me at dgetzler@rancher.com so that we can help troubleshoot the issue you're having.  Thanks.   Dave

**Comment by deniseschannon** [comment]
@AnthonySendra you only need to add the `-e CATTLE_AGENT_IP` to the host that is also running Rancher server (ie. node1). This helps the rancher/agent select the correct IP for node 1.

For node 2, do not edit the command and it will pick up the correct IP (172.16.255.252) in the host screen.

This should fix your issue. Please retry and let me know.

**Comment by AnthonySendra** [comment]
Unfortunately, I have already tried to add `-e CATTLE_AGENT_IP` only on the host where server running (node1 in my case) and let the command given by the UI without the `CATTLE_AGENT_IP` for running the agent on the other host (node2). But still not working :/

In the UI, I have 172.16.255.251 under node1 host and 172.16.255.252 under node2 host.
The only way I find for see Rancher works with Vagrant, is to configure public_network, but it's not what I want :/

**Comment by AnthonySendra** [comment]
Ok, I find the problem:

* I miss a step in docker installation, forget to install linux-image-generic-lts-trusty and linux-headers-generic-lts-trusty
* Sometimes (many times) link just doesn't work

By doesn't work, I mean, when I link a container with the UI, when the container is started, if I edit the container, I see "This container has no links.". I tried to add container until I see correct information, and in this case (an ubuntu on node2 linked to the ubuntu on node1) I can ping. 
The weird thing, it's even if I tried to create 6 ubuntu containers on node1, I'm still not able to ping redis from one of them (and I don't see the link on edit modal in UI) but on the first ubuntu on node2 I was able to ping ubuntu on node1

**Comment by deniseschannon** [comment]
Regardless of the links, you should be able to ping from the container 1 on node 1 to the IP of container 2 on node 2. It isn't dependent on link functionality. When you are pinging, are you pinging by link name or IP of container?

We don't allow linking individual containers after creation. If you wanted to add it in later, you'd need to clone the container and add the link and start a new container.

It does look like there is a bug with container linking as I was able to see exactly what you saw. I've created a new issue: https://github.com/rancherio/rancher/issues/1294

Alternatively, you could try creating services (of scale 1) and can edit links after the service is created. Since you can select the host that you want your services to be on, you can mimic the same setup with using services instead. We support editing links in services as we have our own DNS server.

**Comment by AnthonySendra** [comment]
I ping always by link name.

Tried with services and works as expected ! Thank you!

**Comment by deniseschannon** [comment]
Great! I'll close this. If you have any other issues, please open a new one.
