### ISSUE TITLE
When LB service that is stuck in "updating-active" state is removed , more LB Agent are spawned to satisfy the scale.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#767]
Server version - V0.20.0

Create LB service with scale 2 and link it to another service in the same environment.
Set up has 3 hosts.
Edit Lb service and set scale to 4.
This results in another LB agent being created on the 3rd host , as expected.

The service is stuck in "updating-active" state forever , since there is no host available for scaling to 4.

At this point , there is an option to remove the service .
Deleting the service succeeds. But this also results in creating another LB agent, which is later on purged. 

mysql> select id,name,external_id , state from instance;
+----+---------------+------------------------------------------------------------------+---------+
| id | name          | external_id                                                      | state   |
+----+---------------+------------------------------------------------------------------+---------+
|  1 | test_test1_1  | 31f6bc52be1da1b5514352303b6d1bf6fd8aab65bdda65d63653b16d96c62b46 | running |
|  2 | test_test1_2  | d7c47848e76daff9790c40fd86b46f74e5d4afe19f9b2f49b3a7e75ebe340ce9 | running |
|  3 | Lb Agent      | 6db17e89fb748ca70f1c3b07af3de7c6eafe940b23012013a797281e0295f3a0 | purged  |
|  4 | Lb Agent      | 25a5ca1806a9066dfa32cf28e511977a51383c6c4f312743fa9a59c403eb973d | purged  |
|  5 | Network Agent | 7ee13ec8fe947ff38e277e8a66a2265813e7957547359db17e462a9e7448e750 | running |
|  6 | Network Agent | bd28f51dd21abc2da3180f43b7fe6eec436d2fb9c76b598be7f73787dae73a2c | running |
|  7 | Network Agent | 5283253b474226d5cea6c2b151238ff2e7704f83004ff0e15f8eb1df22bd9129 | running |
|  8 | Lb Agent      | 70f5b0cc51854e8de32fd9bece9c24cef3e6b8aff35477f9cfb00ea82b813a9e | purged  |
|  9 | Lb Agent      | NULL                                                             | purged  |
| 10 | Lb Agent      | NULL                                                             | purged  |
| 11 | Lb Agent      | NULL                                                             | purged  |
| 12 | Lb Agent      | NULL                                                             | purged  |
| 13 | Lb Agent      | NULL                                                             | purged  |
| 14 | Lb Agent      | NULL                                                             | purged  |
| 15 | Lb Agent      | NULL                                                             | purged  |
| 16 | Lb Agent      | ebe7bdd1995312edbfe54ab8d921ed74a4a84707f9537435265c8f9be9180954 | purged  |
+----+---------------+------------------------------------------------------------------+---------+

**Comment by alena1108** [comment]
As long as the instance gets removed eventually, its fine. It happens that the instance is scheduled for start and came up Running till the lb service process kicks in and removes this instance as a part of the lb removal.
