### ISSUE TITLE
[rancher-compose] scripts/build fails

### ISSUE THREAD

**Issue by defunctzombie** [rancherio/rancher#771]
```
./scripts/build
./scripts/build: line 9: ./scripts/common_functions: No such file or directory
```

Using rancherio/rancher-compose@22c2b870

cc /@ibuildthecloud

**Comment by deniseschannon** [comment]
@ibuildthecloud it looks like in the scripts/build file in rancher-compose, you added `. ./scripts/common_functions` to in https://github.com/rancherio/rancher-compose/commit/22c2b870151ab3fa7f3727cfc4504e326ea512e1

But is there a file that you need to also add to the scripts folder?

**Comment by defunctzombie** [comment]
@ibuildthecloud can we get this fixed? currently that repo can't be used per the build instructions

**Comment by usmanismail** [comment]
Bump

**Comment by ibuildthecloud** [comment]
I know I'm dragging on this.... but trust it will be awesome when it's done.  The problem right now is that rancher-compose will not work against the current release of Rancher it requires a bunch of PR's that have yet to be merged.  I hope this will finally be done by tomorrow.

**Comment by defunctzombie** [comment]
<3

**Comment by ibuildthecloud** [comment]
But I'll let you know, 100% of the docker compose syntax will be supported.

**Comment by ibuildthecloud** [comment]
`rancher-compose` should compile now.  To run what is currently on master in rancher-compose you need at least rancher/server:v0.23.0-rc4

**Comment by deniseschannon** [comment]
@defunctzombie @usmanismail I'm going to close this issue. Please re-open or open a new one if you have any issues.
