### ISSUE TITLE
Environment Service - Adding Volumes From throws JS error related to addVolumeFromService

### ISSUE THREAD

**Issue by stephenlawrence** [rancherio/rancher#772]
v0.19.2:

When I am adding a new service to an environment and I try to link it to a volume via the Volumes From setting, clicking the "+" icon does nothing and shows this error in the JS console.

```Uncaught Error: Nothing handled the action 'addVolumeFromService'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.```

**Comment by jonpugh** [comment]
Still getting this in today's rancher/server:latest

**Comment by tfiduccia** [comment]
v0.23.0-rc1
Verified fixed
