### ISSUE TITLE
When adding machines , we always pull rancher/agent:latest image instead of using a particular agent version.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#784]
Server version - V0.20.0

When adding machines , we always pull rancher/agent:latest image instead of using a particular agent version.
When adding custom hosts - user is presented with exact version of agent - like "rancher/agent:v0.7.6" in the command to register the host.

When adding machine , we should also be using the exact version of agent.

logs indicating that machine pulls rancher/agent:latest image:

time="2015-05-12T22:08:11Z" level=info msg="Machine Created" machineExternalId="04dbf74b-0b4b-4c42-90e1-a2ca60e6c009" resourceId=1ph26 
time="2015-05-12T22:08:11Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph26 
time="2015-05-12T22:08:11Z" level=info msg="Machine config file created and encoded." destFile="/var/lib/cattle/machine/04dbf74b-0b4b-4c42-90e1-a2ca60e6c009/test-126024.tar.gz" resourceId=1ph26 
time="2015-05-12T22:08:11Z" level=info msg="Activating Machine" eventId="6bb359d7-a680-47f5-a3d7-311875435a3b" resourceId=1ph26 
time="2015-05-12T22:08:12Z" level=info msg="Pulling rancher/agent:latest image."

**Comment by cjellick** [comment]
This is causing further problems with sync and import because the intermediate containers created when starting rancher/agent dont have the system container label that would cause them to be excluded from syncing and they are showing up in the UI.

If we properly used a specific image version, those containers would be excluded.

**Comment by sangeethah** [comment]
Tested with server version - V0.20.4

Added a Rackspace host. 
As part of install rancher agent ,it pulls rancher/agent:v0.7.6 image.
