### ISSUE TITLE
Launching edit service page which have service links redirects to http://<ip>:8080/static/fail page

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#792]
Server version - V0.20.1

Steps to reproduce the problem:

Create service1.
Create service2.
Link service2 to service1.

Start both service1 and service2.
Now try to edit service1. We are redirected to  http://<ip>:8080/static/fail page with following content:

Error
a.get is not a function
Reload to try again or log out

**Comment by vincent99** [comment]
Ugh, this is because labels are in the API now and the keys have dots in them ("io.rancher.service.name") and that doesn't play nicely with Ember, which uses that to mean io['rancher']['service']['name'].

**Comment by vincent99** [comment]
Fixed.. duplicating the service object for editing wasn't duplicating child resources correctly

**Comment by tfiduccia** [comment]
v0.20.2
Verified fixed
