### ISSUE TITLE
Not able to add a service link to a service when it is in active state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#794]
Server Version - V0.20.1

Steps to reproduce the problem:
Create a service.start it.
Now Edit the service.
When a service link is added , clicking on the "save" /"cancel" button does nothing

**Comment by vincent99** [comment]
Ugh, this is because labels are in the API now and the keys have dots in them ("io.rancher.service.name") and that doesn't play nicely with Ember, which uses that to mean labels['io']['rancher']['service']['name'].

**Comment by tfiduccia** [comment]
v0.20.2
Verified fixed
