### ISSUE TITLE
Default container - ubuntu:14.04.2 fails to start

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#795]
Server version - V0.20.1

Steps to reproduce the problem:

Start  container with defualt image - ubuntu:14.04.2 with out changing any other  parameters.
Container starts and then stops.

This is because of the  interactive & terminal options being defaulted to false.

**Comment by vincent99** [comment]
It starts but immediately stops because tty and stdinopen aren't the default in the schema.  Changed to force them on by default for new containers.

**Comment by tfiduccia** [comment]
v0.20.2
Verified fixed
