### ISSUE TITLE
Not able to create LB services from UI

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#797]
Server version - V0.20.1

Steps to reproduce the problem:
Create an environment.
Create a service activate it.
Create a LB service with target set to service.

LB service creation fails with error message - "Validation failed: environment"

API returns - "422 Unprocessable Entity"

Request Parameters sent from UI:
{scale: 2, type: "loadBalancerService", name: "lb-123", description: "lb-123", environmentId: "1e1",…}
consumedServicesUpdated: 0
created: null
description: "lb-123"
environmentId: "1e1"
headers: null
id: null
kind: null
launchConfig: {startOnCreate: true, publishAllPorts: false, privileged: false, stdinOpen: false, tty: false,…}
actions: null
allocationState: null
command: null
commandArgs: null
count: null
cpuSet: null
cpuShares: null
created: null
dataVolumes: null
dataVolumesFrom: null
description: null
devices: null
directory: null
domainName: null
environment: null
externalId: null
firstRunning: null
headers: null
hostname: null
id: null
imageUuid: null
instanceLinks: null
kind: null
links: null
memory: null
memorySwap: null
name: null
networkIds: null
ports: ["7777:80"]
primaryAssociatedIpAddress: null
primaryIpAddress: null
privileged: false
publishAllPorts: false
registryCredentialId: null
removeTime: null
removed: null
requestedHostId: null
restartPolicy: null
startOnCreate: true
state: null
stdinOpen: false
systemContainer: null
token: null
transitioning: null
transitioningMessage: null
transitioningProgress: null
tty: false
type: "container"
user: null
uuid: null
loadBalancerConfig: {type: "loadBalancerConfig",…}
actions: null
appCookieStickinessPolicy: null
created: null
description: "lb-123"
headers: null
healthCheck: {type: "loadBalancerHealthCheck", interval: 2000, responseTimeout: 2000, healthyThreshold: 2,…}
id: null
kind: null
lbCookieStickinessPolicy: null
links: null
name: "lb-123 config"
removeTime: null
removed: null
state: null
transitioning: null
transitioningMessage: null
transitioningProgress: null
type: "loadBalancerConfig"
uuid: null
name: "lb-123"
removeTime: null
removed: null
scale: 2
state: null
transitioning: null
transitioningMessage: null
transitioningProgress: null
type: "loadBalancerService"
uuid: null

**Comment by vincent99** [comment]
Fixed, environment can't be null..

**Comment by tfiduccia** [comment]
v0.20.2
Verified fixed
