### ISSUE TITLE
Dead containers are not sync properly

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#799]
If a container gets to the state "dead" it is not being synced properly.

This is because it shows up with `docker ps -a` but not in `docker ps -a -f status=exited`(or in any of the other status filters). This basically makes it appears as running to the sync logic.

This behavior can be observed in the 10-acre environment (which creates intermediate system containers that show up in the UI because they are from an old image without the system container label).

**Comment by cjellick** [comment]
This is fixed. Dead containers will now show up as stopped containers in the Rancher.

**Comment by cjellick** [comment]
Here are less-than-ideal steps to create a "Dead" container:
1. Create and run a container, then stop it.
2. Stop the docker daemon on your host. Will be a command like `sudo /etc/init.d/docker stop` or `sudo service docker stop` 
3. cd /var/lib/docker/containers. then vi <id of the container from step 1>/config.json
4. This will be a single line json file. There will be a "Dead" property in there somewhere. Change its value to true.
5. Start the docker daemon. Container should show up as dead.

**Comment by sangeethah** [comment]
Tested with latest master:
1. Create and run a container. Container is in "running" state on server.
2. Stop the docker daemon on your host. Will be a command like sudo /etc/init.d/docker stop or sudo service docker stop 
3. cd /var/lib/docker/containers. then vi /config.json
4. This will be a single line json file. There will be a "Dead" property in there somewhere. Change its value to true.
5. Start the docker daemon.

Container gets marked as being in "stopped" state in server.
