### ISSUE TITLE
404 Page when viewing logs on a service container that has failed to find a placements

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#804]
Rancher Version: v0.21.1

Steps to Reproduce
1. Start a new Rancher instance
2. Create a service
3. Start service (no hosts have been created).
4. Containers failed to find placement. Click on dropdown menu and click "View Logs".

Result: 404 Page

**Comment by vincent99** [comment]
This is in the API.. the logs action shouldn't show up on a container until it's going to work.

**Comment by hibooboo2** [comment]
This is fixed on master.

**Comment by deniseschannon** [comment]
verified fix in v0.24.0-rc2
