### ISSUE TITLE
If an image uses links to obtain env variables from the linked container, there is no way to handle services of these images

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#807]
Rancher Version: v0.21.1

Per issue #666, we are not planning on supporting the copying of environment variables from a linked container. This is fine when we are working from launching containers on hosts, but has issues when you try to scale and use services.

Wordpress Example when launching containers:
1. Launch a mysql container.
2. Launch a wordpress container and link to mysql container. In docker, the link functionality would use the mysql container's IP and port to define one of the environment variables of the wordpress container. Since we don't support the copying, we have to manually put in the env variables into the wordpress container upon creation.

Wordpress Issues when launching services.
Create mysql service with 2 containers
Trying to create wordpress service and link to the mysql service. Similar to example above, I still need to find the IPs of the mysql service and set them as env variables. 

If no service has been started, there is no IP of the mysql services yet. By hardcoding the env variables, it's forcing me to choose 1 environment variable that will be applied to all of the wordpress service.

**Comment by vincent99** [comment]
For services wouldn't you just use the DNS name for the `mysql` service as the host instead of environment variables?

**Comment by deniseschannon** [comment]
@alena1108 should what @vincent99 is describing work? 

Usually in a non-service, I would set
`WORDPRESS_DB_HOST` = containerIPofmysql:3306

I tried it for my wordpress example. My env variable that I tried to set in my service: 
`WORDPRESS_DB_HOST` = mysql:3306

In the host that the stopped container is on in the UI, there is no container that was started/stopped on the host.

**Comment by deniseschannon** [comment]
@vincent99 it works just as you described. :) thanks for explaining how it should work. I will note that needs to be in included in the docs.
