### ISSUE TITLE
Go-Machine-Service does not handle idempotency well

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#809]
The current implementation of GMS checks for whether machine.data has been set before moving further on handling the creation of a machine.  Unfortunately, it can't handle things well if machine.data has been set and a event without that is sent to GMS.  In this case, GMS will report a failure and the host gets set into an error state even though it is healthy.

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc2.

root@97c16797b4be:/# docker-machine -v
docker-machine version 0.3.0-dev (ccb7f0a)
root@97c16797b4be:/# go-machine-service -v
go-machine-service	 gitcommit=480875d
root@97c16797b4be:/# 

Existing set of validation test cases for digital Ocean machine and amazon ec2 machines work fine.
