### ISSUE TITLE
Edit existing credentials instead of adding duplicate entries for the same registry address

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#810]
Rancher v0.21.1

When adding registries, if a registry exists for Docker Hub or Quay.io, we should have the registry be updated instead of added to the list.

It's confusing that  the registry page can show multiple registries/credentials, but there is no indication that only the LAST registry/credential is used when trying to pull images. There is no point to show both DockerHub entries if we are only going to use the denise@rancher.com credential.

![screen shot 2015-05-14 at 2 59 15 pm](https://cloud.githubusercontent.com/assets/11410997/7642934/cdbd4956-fa49-11e4-93b0-49923d784ddd.png)

**Comment by will-chan** [comment]
If this is possible, and there's no way to select which cred to use, we need to be able to select one as a default and show it in the UI.

**Comment by tfiduccia** [comment]
build from master - June 10th (afternoon)
Verified fixed
