### ISSUE TITLE
User is taken to latest created project instead of first one as default

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#812]
v0.20.1
Steps:
1. In Chrome log in as you and authenticate
2. Create project named Project1 and add rancherdev
3. In Firefox log in as rancherdev
4. In Chrome create another project named Project2 and add rancherdev
5. In Firefox Log Out then log back in as rancherdev

Results:  Default project is now Project2

Expected:  Default project should be Project1 and shouldn't change every time I add them to another project.

**Comment by vincent99** [comment]
Changed the logic to **set** a default project if I don't find one when the page loads.  So once it's set it will be that project until you change it yourself, or deactivate/lose access to the default.

Requires rancherio/cattle#609 before this will really work.

**Comment by vincent99** [comment]
(restart build-master to get the backend change)

**Comment by tfiduccia** [comment]
build from master - June 12th
Verified fixed
