### ISSUE TITLE
Cloned container adds docker: to image url

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#815]
v0.20.2
Steps:
1.  Add a container (don't add the docker:)
2.  Clone container

Results:
docker:<imagename>

Expected:
<imagename>  Since we don't require docker: and the user didn't put it in, we should strip it.

**Comment by will-chan** [comment]
I assume if you add another registry, it still prepends with docker:?

**Comment by vincent99** [comment]
The API requires `docker:`, so the UI normally hdies it and adds it to the request.  But when you clone the value is just getting put in and not going through the same filtering as if the user typed it.  Just need to call that after initializing with the original container info.

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
