### ISSUE TITLE
Upon service delete, graph is no longer generated

### ISSUE THREAD

**Issue by smw355** [rancherio/rancher#816]
In Rancher 0.20, when I delete a service from an environment, and click the graph icon, I no longer see any services or the graph.

**Comment by smw355** [comment]
When I refresh the browser, the graph is regenerated.

**Comment by vincent99** [comment]
I think this was fixed by other issues, it's always showing up for me now.

**Comment by tfiduccia** [comment]
build from master - June 9th
Verified fixed
