### ISSUE TITLE
Clicking on "Cancel" on the "Add LoadBalancer" page that was launched from service page takes us back to "Load Balancer" view.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#817]
Server version - V0.20.2

Clicking on "Cancel" on the "Add LoadBalancer" page that was launched from Environments page takes us back to "Load Balancer" view.

Steps to reproduce the problem:
From Environment page , click on "Add LoadBalancer" page to launch Add LoadBalancer" page.
Click "Cancel" on this page.
You are taken to "Load Balancers" page.

Expected Behavior:
You should be taken back to Environments page.

**Comment by tfiduccia** [comment]
Duplicate #748
