### ISSUE TITLE
First time you set Default Project the checkmark doesn't show up

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#818]
v0.20.2
Steps:
1.  Install fresh version of Rancher
2.  Go to Manage Projects
3.  Add a bunch of projects
4.  Pick one from list and "Set as my default Project"

Results:
It looks like nothing happens

Expected:
The checkmark to show up.  If I do a refresh of browser page, it shows up

**Comment by vincent99** [comment]
Pending fixes from James for userprefs

**Comment by hibooboo2** [comment]
What is the problem here @vincent99? What fix do you need from me?

**Comment by vincent99** [comment]
I need edit and delete userprefs to work in master.. then I will look at what's still wrong here, if anything.

**Comment by vincent99** [comment]
Fixed in rancherio/cattle#609

**Comment by vincent99** [comment]
(restart build-master to get the backend change)

**Comment by tfiduccia** [comment]
build from master - June 12th
Verified fixed
