### ISSUE TITLE
Quantity not functioning for Host

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#821]
v0.20.2
Steps:
1.  Add Hosts
2.  Select DO, Quantity 2 and enter Access token
3.  Click on Create

Results:
TypeError: this.get(...).clone is not a function.  The first host actually does start to create as well.

Expected:
NO error and two hosts to create

**Comment by deniseschannon** [comment]
This also happens with packet.

**Comment by tfiduccia** [comment]
v0.20.4
Verified fixed
