### ISSUE TITLE
Lose default environment setting when I authenticate

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#822]
v0.20.2
Steps:
1.  Install rancher and don't authenticate
2.  Go to Manage environments and add a couple of environments
3.  Select a environment and set it as default
4.  Go to Access Control and Authenticate
5.  Go to Manage environment

Results:
Your default environment is not longer selected.  I also tried to refresh and log out and logged back in.  Default environment is lost.

Expected:
Default should stay set.

**Comment by will-chan** [comment]
For a private installation, this becomes important.  A user may play around with the product with no auth, and decide to enable it later on.  I wouldn't want to lose what was there before.

**Comment by vincent99** [comment]
@will-chan This was just remembering which of the environments is the default when you log in.  The actual environments are not lost when switching auth.

Anyway this looks more like the setting was never set in userPreferences because of name uniqueness constraints that will be fixed via #1117.

**Comment by vincent99** [comment]
rancherio/cattle#609 fixes this, probably..

**Comment by vincent99** [comment]
(restart build-master to get the backend change)

**Comment by tfiduccia** [comment]
build from master - June 12th
Verified fixed
