### ISSUE TITLE
Cloning container from Services is confusing

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#824]
v0.20.2
Steps:
1.  Create a Service with scale of 1
2.  From Service page, click on container menu
3.  Select Clone
4.  Click Create

Results:
Container is created, but you don't really see it because it's not related to Service so it doesn't show up on current page.

Expected:
Not sure here.  If we stay on service page, you don't see the results of the action.  If you take them to Container list view to see it, it's strange because you changed out of the view they purposely went to.  Not sure if clone in service view is useful either?

**Comment by vincent99** [comment]
I'm going to go with cloning a service into a separate container isn't useful, until someone comes up with a good use for that.

Also disabled cloning of system services, as that will cause confusion.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed - clone removed from menu
