### ISSUE TITLE
Cloned containers do not have Ip address.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#826]
Server version - V0.20.2

Steps to reproduce the problem:
Create a container.
Clone a container from this.

Notice that the cloned container has no Ip address assigned to it.

Expected Behavior:
Cloned containers should be launched in managed network.

**Comment by deniseschannon** [comment]
Similar issue. 

I chose to clone a service container from the hosts page, and it launched a new container in a new host (that did not have network agent running). It didn't try to launch network agent for the host.

**Comment by sangeethah** [comment]
Tested with Server version - V0.20.4

When I clone a container , it gets ip address from the managed network.
