### ISSUE TITLE
Name Validation Error Message - Add more explanation of valid input

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#828]
Is it possible to add additional context to understand why the name validation fails? How different are the validations for the different pages?

In Services, I tried creating a service with a "denise:1" or "denise_" in the name. I just got the validation name failure, but it doesn't tell me what is wrong.

**Comment by vincent99** [comment]
Will now say `name contains invalid character: '_"`.  There aren't many other resource types that have valid characters listed in the API, but this works for any types that do.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
