### ISSUE TITLE
Replacing "Host" with "Machine" in API

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#83]
Our current API references both VM and physical machines as "Host".  However, since we are closely aligning to Docker, this might cause confusion given that they use "Machine" to describe this.  By changing the API to "Machine", you would not need to explain what a Host vs a Machine is anymore.

**Comment by sheng-liang** [comment]
I agree. It also does not make sense for a host to be a VM, while a machine can be a physical or virtual machine.

Sheng

**Comment by ibuildthecloud** [comment]
Where did this come from?  This doesn't make sense in the context of our API.  We can't try to align our API with Dockers marketing names.  A host in our API is not even the same as a machine.

**Comment by sheng-liang** [comment]
How is a host in our API not the same as a machine?

Sheng

**Comment by ibuildthecloud** [comment]
A host in our API is basically the same as the docker daemon.  We have a separate type that is already called something like dockerMachine.  That's is why I'm confused here, where did this issue come from?  @cjellick and I already discussed this and host is a seperate.

But yes,

**Comment by ibuildthecloud** [comment]
Sorry, accidentally closed

**Comment by ibuildthecloud** [comment]
But yes, our API does not perfectly match Docker, but that is fine.

**Comment by ibuildthecloud** [comment]
@will-chan Do you want to call a host a machine in the UI?  That seems odd to me.  Again, "machine" is a product name.  People either call them servers or hosts, but if we really want we can make the UI be machine.

**Comment by sheng-liang** [comment]
Also I don’t think machine is a Docker marketing term. It is being used to generically describe physical and virtual machines in the context of containers. Cadvisor, for example, also has a machine construct:

https://github.com/google/cadvisor/blob/master/docs/api.md

Machine Information
The resource name for machine information is as follows:
/api/vX.Y/machine
This resource is read-only. The machine information is returned as a JSON object containing:

  *   Number of schedulable logical CPU cores
  *   Memory capacity (in bytes)
  *   Maximum supported CPU frequency (in kHz)
  *   Available filesystems: major, minor numbers and capacity (in bytes)
  *   Network devices: mac addresses, MTU, and speed (if available)
  *   Machine topology: Nodes, cores, threads, per-node memory, and caches
The actual object is the marshalled JSON of the MachineInfo struct found in info/machine.go<https://github.com/google/cadvisor/blob/master/info/machine.go>

**Comment by will-chan** [comment]
@ibuildthecloud the fact you need to explain that a host in Rancher API is synonymous with a docker daemon can already be a bit confusing.  I'm not as tied to the definition of a host vs a machine as @sheng-liang is but I am more concerned that once the API is out, Rancher will end up having to explain what adding a host is if we expect our users to continue to use Docker natively.  In Docker, they are using the term of adding a Machine as a "Docker host" for their containers.  That is exactly what adding a Host in Rancher means.  Is it different?

**Comment by vincent99** [comment]
@will-chan @sheng-liang @ibuildthecloud Can we call this resolved since we have already shipped the functionality with "a computer created by docker machine" === `machine` and "a docker daemon running on a computer" == `host`?

**Comment by thaJeztah** [comment]
FYI there's a similar discussion in the Machine upstream; https://github.com/docker/machine/issues/727

**Comment by sheng-liang** [comment]
Yes the community seems fine with the term host.

Sheng
