### ISSUE TITLE
Textfield box doesn't clear for name if I have quantity >1

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#832]
v0.20.0

Steps to Reproduce:
1. Go to "Add Host" page
2. Put a name in DO page
3. Increase quantity up to 2+
4. Click on Amazon page
5. Go back to DO page

Result: Scale goes back down to 1 (resetting), but name is still there

Expected Result: scale goes back down to 1 and name is also cleared

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
