### ISSUE TITLE
Remove services don't dissapear

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#834]
v0.20.3
Steps:
1.  Create a Service and a LB service
2.  Start the Service (it won't finish activating until you refresh)
3.  Stop and delete Service and LB service

Results:
Service and LB Service will stay on page until I manually refresh browser or leave page and come back.

Expected:
Should remove.

**Comment by tfiduccia** [comment]
This seems to be a problem with anything on the main service page.  It's not updating and I have to manually refresh it to see changes that should be automatic.

**Comment by vincent99** [comment]
This seems to be updating fine to me.  Maybe you ran into a separate problem with the event websocket being disconnected for for the wrong environment somehow?  If you can reproduce this I'll take a look on your compute.

**Comment by tfiduccia** [comment]
build from master - June 9th
Failed - removed services are still showing up until I refresh page.

**Comment by vincent99** [comment]
Fine, if you're going to *read* the description instead of just the title...

**Comment by tfiduccia** [comment]
build from master - June 10th
Verified fixed
