### ISSUE TITLE
Can access and use project that is inactive

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#837]
v0.20.4
Steps:
1.  Authenticate
2.  Create 2 projects and give member access to rancherdev
3.  Log in on another browser as rancherdev and go to host page for 1st project
4.  Go back and as admin deactivate the 1st project
5.  As rancherdev, click around, create host, containers, anything you want.

Results:
Everything works fine for rancherdev even thou the project has been deactivated.

Expected:
Shouldn't be able to stay and create things in project that is deactivated.

**Comment by hibooboo2** [comment]
hmm ill look into it.

**Comment by vincent99** [comment]
Ping @hibooboo2 is this fixed now?  If so pls mark and assign back to @tfiduccia

**Comment by tfiduccia** [comment]
0.23.0-rc5
Verified fixed
