### ISSUE TITLE
Connecting to rancher server is not possible

### ISSUE THREAD

**Issue by teon** [rancherio/rancher#838]
INFO: Running Agent Registration Process, CATTLE_URL=http://XXX:39001/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 96
INFO: docker info: Images: 911
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /srv/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 1270
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.16.0-4-amd64
INFO: docker info: Operating System: Debian GNU/Linux 8 (jessie)
INFO: docker info: CPUs: 16
INFO: docker info: Total Memory: 63.03 GiB
WARNING: No memory limit support
INFO: docker info: Name: XXX
WARNING: No swap limit support
INFO: docker info: ID: 5S7I:NG64:4I43:7C24:F2OQ:KP2Q:CPKZ:SLEQ:XVI2:WJVA:M3EJ:5AJD
INFO: Attempting to connect to: http://XXX:39001/v1
INFO: http://XXX:39001/v1 is accessible
INFO: Inspecting host capabilities
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 260, in _get_response
    self._error(r.text)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 249, in _error
    raise ApiError(self._unmarshall(text))
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 294, in _unmarshall
    object_pairs_hook=self.object_pairs_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by deniseschannon** [comment]
Can you provide the Rancher/Server version as well as the command that you ran? 

And what type of servers are you running for the hosts? Are you using the same server for rancher/server as well as the host? If so, you'll need to edit the command from the UI to launch Rancher Agent.

**Comment by teon** [comment]
Latest versions available on docker hub, but I've checked both :latest tag and latest version that was in beta - result the same. My Docker host is: Debian Jessie.

**Comment by deniseschannon** [comment]
Debian seems to have an issue: https://github.com/rancherio/rancher/issues/22

I will make an attempt to test Debian today.

**Comment by deniseschannon** [comment]
I have been unable to reproduce this issue. I was able to install rancher server and agent using Debian Jessie with no issues. I had some issues trying to get Docker installed onto my Debian Jessie box because I tried to follow the Docker instructions which are incorrect. I just used `curl -sSL https://get.docker.com/ | sh` to get the latest Docker versions. We tagged a new latest. Would you be able to try that?

**Comment by teon** [comment]
The version of agent+server works:

```INFO: Launched Rancher Agent: ....```
