### ISSUE TITLE
Start up steps are broken

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#84]
The latest version of rancher server and agent do now match

    docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://localhost:8080
    time="2015-02-05T19:12:52Z" level="fatal" msg="Error response from daemon: client and server don't have same version (client : 1.16, server: 1.15)"

**Comment by cloudnautique** [comment]
Hi, that message is coming from Docker, and is typically caused by a mismatch in versions between the container and the host. The rancher/agent container has docker version 1.4.1, and needs to run on a host with a 1.4.x binary. To resolve the host Docker needs to be upgraded.

**Comment by ibuildthecloud** [comment]
We used to have a nice message for this.  @cloudnatique, I wonder if I broke this in v0.3.2 of the agent container.

**Comment by zbyte64** [comment]
Had the same issue, @cloudnautique is correct
The coreos ami ships with docker 1.3.3
Looks like I need to switch to beta: https://coreos.com/releases/

**Comment by usmanismail** [comment]
Yeah that was it, Thx
