### ISSUE TITLE
Deleting custom host and cannot add it back in to same Rancher instance

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#843]
v0.20.4

Steps to Reproduce:
1. Add a host using the custom `sudo docker` command.
2. Delete the host from Rancher
3. Stop the rancher/agent on the host.
4. Run the custom `sudo docker` command from the same Rancher instance.

Result: Container starts but host is never connected to Rancher

Expected result: Container starts and host shows up in Rancher UI.

**Comment by vincent99** [comment]
Duplicate of #225
