### ISSUE TITLE
Single LB for multiple applications?

### ISSUE THREAD

**Issue by cweagans** [rancherio/rancher#848]
In a few other PaaS solutions, there's a single "router" component, which is the public entry point for all web applications. The router does load balancing between all containers in an app and does health checks, but it handles *multiple* applications.

Does the current load balancing implementation support that sort of setup? If not, are there plans to add that feature? Or does it have to be one LB container per application?

If the node that's running the LB container only has one IP address, how can I run multiple web applications (aside from adding other nodes)?

**Comment by blackjid** [comment]
probably has to do with this issue https://github.com/rancherio/rancher/issues/544

I would love to have this ability...

**Comment by vincent99** [comment]
Yes, this is basically the same thing as in #544 so I'm going to call it a duplicate.  @cweagans please subscribe to that issue if you want to receive updates.

We agree more advanced layer-7 options for the balancer are a good idea, and multiple apps on the same IP is common use case.
