### ISSUE TITLE
user API key support for projects

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#853]
- Today, a user's API does not allow access to projects the user belongs to.  Adding support to address this.
- Fix project tests.

**Comment by will-chan** [comment]
- Start with cookie-auth.

**Comment by hibooboo2** [comment]
This is now on master. Both of them.

**Comment by sangeethah** [comment]
Tested with build from master jun/09

Github user test1 belongs to github group - g1.

Add g1 as member to Default environment.
Create env1. 
Create env2 and add g1 as member.

Create API keys for a github user account - test1.

Using this apikey , able to use /v1/projects/<envid>/<resource> to view and create resources for the project for both env2 and Default environment.

There is 1 issue where proper error code is not returned when attempting unauthorized access to projects which is tracked in #1127 -Attempting to access resources from a project that user does not have access to should result in API failing with "Unauthorized" error code.
