### ISSUE TITLE
RancherOS: Image preloading and NFS support

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#859]
* Add support for imagine preloading
* Add support for NFS (any distributed filesystem) support

**Comment by imikushin** [comment]
Docker image preloading impl: rancherio/os#317

**Comment by will-chan** [comment]
- preloading for ISO not done
- working on refactoring build for RancherOS.

**Comment by will-chan** [comment]
Azure RancherOS images have been pushed and waiting for approval

**Comment by danipolo** [comment]
You finally added NFS kernel support to RancherOS by default? I'm going to install RancherOS 0.6.
