### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by zbyte64** [rancherio/rancher#86]
What are the memory requirements of the orchestrator?

I loaded this up on an ec2 micro instance and I found myself out of memory.

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND      
  826 root      20   0 1369576 411828    172 S  1.7 67.9   3:55.29 java         
  629 root      20   0  728952  83208   6268 S  0.0 13.7   1:41.90 docker  
```

**Comment by ibuildthecloud** [comment]
Those numbers are about right for what it is today.  Honestly, it's way too big right now.  There's some simple factors for that that were addressing in about a week from now.  I think the realistic expectation will be that the orchestration process will need about 200mb in the short term.  I'd hope to get that much smaller in the future. It is Java which is memory hungry but I think a good goal would be 100mb.  

I'll leave this issue open and continue to update it with progress as we reduce the footprint.

**Comment by ibuildthecloud** [comment]
Fyi, part of the reason it's so big is we are running H2 which is an embedded database in Java.  We are switching to mysql.

**Comment by vincent99** [comment]
The default is now MySQL.
