### ISSUE TITLE
Project list page has a Add Service but no Add Balancer button

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#865]
v0.21.2
Steps:
1.  Create a project
2.  Go back to project list page

Results:
There is a Add Service button but no Add Balancer button

**Comment by sangeethah** [comment]
Should "Export Config" option also be shown in this view?

**Comment by vincent99** [comment]
I'm going with the other way and trying removing export as a button on the other screen.  It'll be in the actions menu on the right

**Comment by tfiduccia** [comment]
v0.21.3
Verified Fixed
