### ISSUE TITLE
Cancel button on Add Service doesn't work from Project list page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#868]
v0.21.2
Steps:
1.  Add a Project
2.  Go back to project list page
3.  Click on Add Service
4.  Click on Cancel

Results:
Nothing happens

Expected:
Go back to project list page

**Comment by vincent99** [comment]
Same as #903

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
