### ISSUE TITLE
Switching Environment takes me to Host page instead of Project list page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#871]
v0.21.2
Steps:
1.  Go to Manage Environments
2.  Add another Environment
3.  Switch to that Environment (using either the menu drop-down or the Environment's submenu)

Results:
Takes me to the Host page for that Environment

Expected:
Should take me to the Project list page for that Environment

**Comment by vincent99** [comment]
Half-fixed, it goes to projects now.  I'd still like it to to the same section you were in, but that's tracked in #612.

**Comment by tfiduccia** [comment]
v0.21.3
Verified Fixed
