### ISSUE TITLE
Start/Stop All Services buttons not showing up

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#879]
version: v0.21.2

In the old UI, there used to be two buttons for "Start Services" and "Stop Services" that would start ALL services or stop ALL services whenever a service was added. They no longer show up.

![screen shot 2015-05-21 at 2 00 25 pm](https://cloud.githubusercontent.com/assets/11410997/7758869/d6d8d262-ffc1-11e4-819e-e0878435070c.png)

**Comment by vincent99** [comment]
Added the project state and actions to the top-right like the other screens, so it's in there now.  And removed export config button since that is too.

![image](https://cloud.githubusercontent.com/assets/753917/7764392/8aa0526e-0005-11e5-8b38-91356f33f38e.png)

**Comment by tfiduccia** [comment]
v0.21.3
Verified fixed
