### ISSUE TITLE
Clicking on "Export Config" on Environment detail page does nothing.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#887]
Server version - V0.21.2

Create environment.
Create a service.
Open environment detail view.
Click on "Export Config" button.
Nothing happens.

Expected Behavior:
It should result in downloading rancher-compose.yml and docker-compose.yml

**Comment by vincent99** [comment]
Seems fine to me, if you can still reproduce this please send me a link to an example.  The button is gone in newer builds and hte action is on the upper-right.

**Comment by sangeethah** [comment]
With Server version - V0.21.3 , there is no "Export Config" button . Instead it is available as an option in actions dropdown menu. "Export Config" from this menu works fine.
