### ISSUE TITLE
DNS Name resolution fails in containers. 

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#893]
Server version - V0.21.3

Create containers.
From within the container try to ping google.com. Not able to ping.
Try to ping 8.8.8.8. This succeeds.
DNS Name resolution fails in containers. 
```
root@ce51d5e0970d:/# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# nameserver 169.254.169.254
# nameserver 10.240.0.1
search c.rancher-dev.internal 117741801349.google.internal google.internal rancher.internal
nameserver 169.254.169.250
root@ce51d5e0970d:/# ping google.com
^C
root@ce51d5e0970d:/# 
```
DNS Name resolution succeeds in Network agent which uses name server 169.254.169.254.

Links are also not working.

**Comment by deniseschannon** [comment]
I am running CentOS 7, but do **not** have the same issue. 

```
root@484597b25bea:/#  cat /etc/resolv.conf
# Generated by NetworkManager
search c.rancher-dev.internal. 117741801349.google.internal. google.internal. c.rancher-dev.internal rancher.internal
# nameserver 169.254.169.254
# nameserver 10.240.0.1
nameserver 169.254.169.250
```

**Comment by clemenko** [comment]
I can repeat this using centos hosts. docker 1.6.2, rancher v0.21.3. I am not able to ping the Network Agent from any container. The containers are pointing to a DNS of 169.254.169.250 which is not pingable. I was not even able to ping the network agent 10.42 address.

**Comment by ibuildthecloud** [comment]
@clemenko thanks for testing this out, but just a heads up 0.21.x is not stable yet.  We need to change how we version things because it's not clear for users what is stable and what is not.  Safest bet is to use latest and beta tags.  But if you like bleeding edge, we always appreciate people testing.

**Comment by clemenko** [comment]
I love the bleeding edge. Just keeping you guys on your toes!

**Comment by will-chan** [comment]
Please test this on 0.23.0-rc6+

**Comment by sangeethah** [comment]
Tested on both master and version - 0.23.0-rc6.

DNS resolution in containers as well as DNS resolution for links works as expected.
