### ISSUE TITLE
v0.21.3: registry is no more available in the UI

### ISSUE THREAD

**Issue by xinity** [rancherio/rancher#895]
i've taken a look at latest release, and i saw that registry configuration has gone missing in the updated UI.

did i missed something ?

**Comment by vincent99** [comment]
D'oh.. you are not, it's missing.  Will get it put back before it gets promoted to `:beta`

**Comment by vincent99** [comment]
In the meantime you can change the URL to `/static/settings/registries` to get to it

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Registry is now in setting menu
Verified fixed
