### ISSUE TITLE
If I try to add service right after switching Environments, I get an error page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#899]
v0.21.3
Steps:
1.  Have at least two environments
2.  Have each environment have at least 1 project
3.  Switch environments using the drop-down in upper right
4.  Click on Add Service for the project

Results:
I get an error page.
![image](https://cloud.githubusercontent.com/assets/11514927/7777487/56072154-0078-11e5-828e-02eecc72b243.png)

Expected:
No error page

**Comment by vincent99** [comment]
I think this was fixed by something else, or there's more to reproducing it...

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified Fixed
