### ISSUE TITLE
Project stays sitting in Activating if created in any other environment then Default

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#900]
v0.21.3
Steps:
1.  Create another environment
2.  Switch to that environment
3.  Add Project

Results:
Project says Activating until I refresh page
![image](https://cloud.githubusercontent.com/assets/11514927/7777616/6427d0b6-0079-11e5-9b64-33fd2cfc5a11.png)

Expected:
Change from Activating to Active

Comments:
This only happens in environments other than Default

**Comment by vincent99** [comment]
Works for me™

**Comment by tfiduccia** [comment]
Build from master - June 11th
Verified fixed
