### ISSUE TITLE
Stopping LB Service, stops agent then restarts agent

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#902]
v0.21.3
Steps:
1.  Create Project
2.  Add Service
3.  Add Balancer
4.  Click on Project name to go to details page
5.  Stop the Balancer
6.  Stop the Service that it's linked to

Results:
the Lb Agent restarts in the Balancer Service, the Balancer Service itself stays stopped.

Expected:
Lb Agent should not restart

Comment:  This seems to be happening because of the Service that it's linked to.  If the Lb Agent is stopped when I try to stop the Service, the Lb Agent restarts.

You can use http://104.197.74.164:8080/ to see, it's in Project1

**Comment by tfiduccia** [comment]
v0.24.0-rc1
The Lb Agent is still restarting on stopped Load Balancer when associated Service is stopped.

**Comment by alena1108** [comment]
Turns out that to test the fixes I've done, I have tried all the scenarios but the one mentioned in the bug. Sorry, Tani, will place the fix for this use case shortly.

**Comment by tfiduccia** [comment]
build from master - June 12th
Verified fixed
