### ISSUE TITLE
Adding Host for the first time goes from Host Registration back to Hosts instead of Add Host

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#905]
v0.21.3

Steps to Reproduce:
1. In a clean setup, click on Add Host.
2. Click on Save on the Host Registration page.

Result: Brings me back to the Hosts page. 
Expected Result: Bring me to the "Add Host" page.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
