### ISSUE TITLE
Can add two containers to host with same public port

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#907]
v0.21.3
Steps:
1.  Add a host
2.  From the container list view Create a sql container, public & Private port 3306, add password environment variable, change Host from Auto to point to specific host
3.  Clone the container and make sure that host is pointed to same host

Results:
Both containers are created and started.  But if I try to access their details, it get hung up

Expected:
I'm not supposed to be able to start a container in a host that already has a container using that specific port.

**Comment by deniseschannon** [comment]
Duplicate https://github.com/rancherio/rancher/issues/182. @sonchang I assigned you to the other issue.
