### ISSUE TITLE
LB service scaled without updating the scale value when it volume mounted a service with a different scale.  

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#909]
Server Version - V0.21.3

Steps to reproduce the probelm:
Created environment - e1.
Created a service S1 with scale 2 in e1.
Created a LB service S2 with scale 1 and dataVolumesFromService pointing to S1.
Activate environment.

When the environment gets activated , there are 2 LB agents created in service S2. But the scale of S2 is still 1.

Expected Behavior:
Scale of S2 should be 2.

This issue is not reproducible if S2 is a regular service( not a LB service). In this case , we see the scale being updated to 2.

**Comment by will-chan** [comment]
Retest when new Sidekick feature is implemented.
