### ISSUE TITLE
API should error out if "io.rancher.service.sidekick" label  is not set on both the volume mounted service and the service the mounts the volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#910]
Server Version - V0.21.3

Steps to reproduce the probelm:
Created environment - e1.
Created a service S1 with scale 2 in e1.
Created a LB service S2 with scale 1 and dataVolumesFromService pointing to S1 with out "io.rancher.service.sidekick" label .

This operation is allowed. When services are activated , the volume mounts are not done since "io.rancher.service.sidekick" labels are not set.

In such cases , it is better to error out when creating a service without "io.rancher.service.sidekick" label  in either volume mounted service and the service the mounts the volumes.

**Comment by will-chan** [comment]
Sidekick is being completely refactored.  Closing this issue.
