### ISSUE TITLE
Memory Utilization Wrong Scale

### ISSUE THREAD

**Issue by vladvetu** [rancherio/rancher#911]
rancher/server:v0.21.3

In the detailed host view the scale from the "Memory Utilization" graph has a wrong scale.
![screen shot 2015-05-23 at 17 46 11](https://cloud.githubusercontent.com/assets/6614640/7784593/b5edb942-0173-11e5-9fcc-9cbbbbdddb8d.png)

**Comment by ibuildthecloud** [comment]
Lol, I think it just makes it more exciting!  Will fix...

**Comment by vincent99** [comment]
Yup, it's not wide enough so the left half of the numbers are getting cut off.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified Fixed
