### ISSUE TITLE
Boot freezed on Vmware Fusion

### ISSUE THREAD

**Issue by captain08** [rancherio/rancher#916]
Using VMware Fusion 7.0.0 on MacBook Pro 2012
Using iso v.3.0 : no problem. Boot ok, network ok
Trying to install by rancheros-install command : 
rancheros-install -c cloud-init.yml -d /dev/sda      (cloud-init.yml contains my ssh key)
-> rancheros install correctly
Boot on hard disk and OS freeze with these lines : 
9pnet : Could not find request transport : virtio
IPv6 : ADDRCONF(NETDEV_UP): docker0 : link is not ready
And OS is freezed : unable to connect by ssh, unable to continue boot

**Comment by deniseschannon** [comment]
Ideally, this should be filed in the OS repository, but can you share what the cloud-init.yml file looks like?

Usually it freezes at that section if if can't unmarshal files.

**Comment by deniseschannon** [comment]
@captain08 I'm going to close this issue. If you re-open in the OS repo, that'd be great!
