### ISSUE TITLE
Add a way to import an existing docker-compose.yml file

### ISSUE THREAD

**Issue by Nicofuma** [rancherio/rancher#917]
When we know what we are doing it's faster (and maybe easier) to write directly the docker-compose.yml file than using the interface provided by rancher (which, I have to say, is pretty great).

By the way, I use docker-compose to manage all my projects and if I use the web interface to rewrite everything it will take a long time

**Comment by vincent99** [comment]
This is available with the [rancher-compose](https://github.com/rancherio/rancher-compose) CLI now, and will be added to the API & UI later.

**Comment by Nicofuma** [comment]
nice for rancher-compose, I didn't know that :)

**Comment by will-chan** [comment]
Related to #718

**Comment by will-chan** [comment]
You can find out rancher cli here. https://github.com/rancherio/rancher-compose
