### ISSUE TITLE
Scale changes in the UI

### ISSUE THREAD

**Issue by cloudnautique** [rancherio/rancher#923]
When adjusting the scale in the UI a user should be able to:
- [ ] Click and hold the + symbol 
- [ ] When clicking the + symbol multiple times the "Message" field should not move the + box so that the pointer is not in a random spot.
- [ ] Type in a number

**Comment by vincent99** [comment]
How about 1.5 out of 3.. You can't click and hold, but you can click repeatedly and it will wait a bit for you to stop now before making the call to the API and causing the change to happen.
