### ISSUE TITLE
Editing project brings back blank page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#926]
v0.22.0-rc1
Steps;
1.  Add a project
2.  Go to main project list page
3.  From the right-menu drop-down for that specific project select Edit
4.  Click on save

Results:
Nothing shows up on page
![image](https://cloud.githubusercontent.com/assets/11514927/7818081/4392ffd4-038e-11e5-86a4-10c087fc0fe3.png)

Expected:
Main project list page should show back up, if I hit refresh page, it redraws.

**Comment by vincent99** [comment]
Works for me™.  I think this was fixed via another issue.

**Comment by tfiduccia** [comment]
build from master - June 11th (afternoon)
Verified fixed
