### ISSUE TITLE
When container is in "Destroyed" state , starting the container from the host results in 2 container entries being synced to the server - 1 in "removed" state and other in "stopped" state.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#933]
Server version - v0.22.0-rc1

Steps to reproduce the problem:

Destroy a container from rancher server UI.
Before it gets purged , from the host start this container.

This results in another container entry that moves from "start" to "stopped" state being created in the rancher server. This is in addition to the container that is in "removed" state.

Expected Behavior:

There should never be 2 container entries being synced to server for 1 container.

**Comment by cjellick** [comment]
To clarify, "Destroyed" state actually means the Rancher container is in the Removed state

**Comment by sangeethah** [comment]
Server version - v0.23.0-rc1

Steps to reproduce the problem:

Destroy a container from rancher server UI.
Before it gets purged , from the host start this container.
After ~5 seconds , the container is stopped.

When the container is purged in the rancher server , it gets destroyed in the host.
