### ISSUE TITLE
If stop and destroy events come in close together, the destroy is removed

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#934]
With native docker integration, if you do something like:
`docker run --rm -it ubuntu bash`
when you exit the container, it will be killed and immediately destroyed.
When rancher receives those events so closely together, it drops the destroyed event and the container stays in a stopped state.

**Comment by cjellick** [comment]
Addressed by:
https://github.com/rancherio/cattle/commit/15b30ee9d3642a6623282f3277060e4f00d98387

**Comment by cjellick** [comment]
This can also happen if a container fails to start, as reported by jonpugh_ in IRC.

**Comment by sangeethah** [comment]
Tested with latest build from master - jun/08
From host, Launched a containerusing the following command:
docker run --rm -it ubuntu bash

Container gets synced to be in "running" state in cattle server.

From host , Exit the container.

When rancher receives the events , container gets marked in "Destroyed" state and eventually gets purged.
