### ISSUE TITLE
Non-200 Response from Github while configuring Access Control

### ISSUE THREAD

**Issue by arthurbarros** [rancherio/rancher#935]
When I try to setup access controll in at my Rancher with Github it show the following error
```
Non-200 Response from Github
``` 
I'm hosting it on Digital Ocean in a $5 instance.

I've double checked the credentials of my Github Application, and everything seems to be right. Any ideias?

**Comment by deniseschannon** [comment]
@hibooboo2: Can you help him out? I believe it means that it's an issue on the Github side.

Can you let us know what rancher version you're running?

Also, we'd recommend using at least a 1GB box ($10 on DigitalOcean) to run rancher server. Otherwise, you will have some issues launching hosts. If it still seems to slow, bump to the next level. We have plans to optimize further down the line.

**Comment by arthurbarros** [comment]
I'm using the latest build available on hub.docker

**Comment by deniseschannon** [comment]
Are you behind a firewall? Those have been issues before in the past where GitHub is unable to communicate back to Rancher.

**Comment by arthurbarros** [comment]
@deniseschannon No, the droplet isn't

**Comment by hibooboo2** [comment]
@arthurbarros  Can you please  do a docker inspect and tell me what the environment ver  CATTLE_RANCHER_SERVER_IMAGE is set too.

**Comment by deniseschannon** [comment]
@arthurbarros We haven't been able to reproduce on our side, but if you are able to provide the environment variable per requested, please reopen and we can try to continue to debug.

**Comment by desmondmorris** [comment]
@deniseschannon I am having the same issue:

```bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=f320f98dd7a7
DEBIAN_FRONTEND=noninteractive
CATTLE_HOME=/var/lib/cattle
CATTLE_API_UI_INDEX=http://releases.rancher.com/ui/0.18.2/static/index.html
CATTLE_DB_CATTLE_DATABASE=mysql
S6_SERVICE_DIR=/service
RANCHER_SERVER_IMAGE=v0.18.2
CATTLE_MACHINE_EXECUTE=true
HOME=/root
```

**Comment by vincent99** [comment]
@desmondmorris That version is about 2 months old, can you try the latest release?

**Comment by desmondmorris** [comment]
@vincent99 hmm interesting.  I installed it from the docker image.  Perhaps, I need to re-pull.

**Comment by vincent99** [comment]
Yes.. if you do `docker run some/image` and there is already a copy of `some/image` on your machine then it will be used without re-pulling a newer copy from the internet.
