### ISSUE TITLE
Main menu is not always drawing properly in Safari

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#938]
v0.22.0-rc1
Steps:
1. Load rancher in safari

results:
![image](https://cloud.githubusercontent.com/assets/11514927/7846628/b6731436-0473-11e5-8ffe-7c7ef064f2b2.png)

The main menu at top is not drawing properly.   This happens in the Infrastructure menu.

Expected:
Should draw properly

**Comment by vincent99** [comment]
This seems ok on the newer header..

**Comment by tfiduccia** [comment]
build from master - June 11th (afternoon)
Verified fixed
