### ISSUE TITLE
Adding a new project and going to project page doesn't show project

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#939]
v0.22.1-rc1

Steps to reproduce:

1. Add Project. Provide name, click Create.
2. Click to go to "Projects" page either by clicking projects tab or clicking on the "Projects" link before the project name. 

Result: New project is not listed.

Expected Result: New project to be listed. For example, if you click on "Services" right after you create the project, the new project is shown.

**Comment by vincent99** [comment]
This was fixed at some point..

**Comment by tfiduccia** [comment]
Build from master - June 10th
Verified fixed
