### ISSUE TITLE
Switching from config to graph view causes inability to click on view icons

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#944]
v0.22.0-c2
Steps:
1  Add a project
2.  Add a couple of services and a couple of balancers
3.  Click on project name to go into project 
4.  Now click between graph and config view a couple of times using the icons

Results:
Once you go from config to graph view, you can't click on any of the view icons anymore

Expected:
Should still be able to click on the different view icons.

**Comment by vincent99** [comment]
I don't think this was actually possible any more unless the header is wrapped into 2 lines, but I moved the z-index of the header above the graph anyway.

**Comment by tfiduccia** [comment]
build from master - june 9th
Verified fixed
