### ISSUE TITLE
Project services don't load properly until you resize browser

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#945]
v0.22.0-rc2
Steps:
1.  Create 4 services
2.  Go to infrastructure and back to services
3.  Use the ^ to view services

results:  4th service is cut off on end
![image](https://cloud.githubusercontent.com/assets/11514927/7850939/2f41884c-049d-11e5-9161-b1d620224b94.png)

Expected:  Should size properly on initial load

**Comment by vincent99** [comment]
This is not a problem any more now that the projects default to open instead of closed.

**Comment by tfiduccia** [comment]
build from master - June 11th (afternoon)
Verified fixed
