### ISSUE TITLE
Should not allow for adding host/adding targets to LB that was created as part of LB service.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#946]
Server version - v0.22.0-rc2

Create LB service that is linked to another service S1.
Activate LB service and service S1.

This will result in an LoadBalancer being created.

We are allowed to add hosts and targets to the existing LoadBalancer.

This should not be allowed.

**Comment by alena1108** [comment]
Similar to https://github.com/rancherio/rancher/issues/947; the same fix would apply to both bugs.
