### ISSUE TITLE
Rancher Install on Air-Gapped Network

### ISSUE THREAD

**Issue by clemenko** [rancherio/rancher#948]
Enhancement : 
 This is similar to #924 
 We would like to install and run Rancher Server/Agent on an air-gapped network. We can transfer the images over in a manual way. The network however does not have access to any other network. 

Is this possible by August?

**Comment by ibuildthecloud** [comment]
Yep.  We've been getting this request a lot.  On master it's already possible to run behind a proxy, the next step it no internet at all.  We will be working on this probably in about 3 weeks from now.  It is technically feasible at the moment, but it just requires a lot of manual configuration.  We would like to make it a bit more seemless.

Currently Rancher uses three Docker images plus it dynamically downloads some 5-10 other artifacts, plus the UI is hosted on a CDN.  The end goal is to just have rancher be three docker images.  You upload those to your private repo and then your done.

**Comment by clemenko** [comment]
fantastic. is there an issue I can follow for the progress?

**Comment by deniseschannon** [comment]
@clemenko I would assume that #924 would be where we place any updates or close the issue when it's fixed.

**Comment by clemenko** [comment]
Sure close this issue and append #924!
