### ISSUE TITLE
UI sometimes display multiple hosts when an agent connects

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#95]
I'm not sure this is the only way to reproduce this bug but I have seen this multiple times where you do the following:

- Open browser to Rancher Server
- Install an agent on a host
- After the agent connects, the browser will show 2 hosts of the same name.  If you refresh the page, it correct itself by showing the single host that has registered.

**Comment by ibuildthecloud** [comment]
This would happen if you were on the host screen as it registered.  I believe it's fixed though.

**Comment by vincent99** [comment]
This should be fixed in master but I will check again before closing

**Comment by will-chan** [comment]
I was running latest which as of this moment should be 0.5.

**Comment by deniseschannon** [comment]
I have yet to see this issue and have been testing with v0.10 and later. Closing. Please re-open if you see it happening again.
