### ISSUE TITLE
When logging into authenticated rancher, it takes me to Hosts page instead of Services

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#952]
v0.22.0-rc1
Steps:
1.  Go to rancher and authenticate
2.  Log out then log back in

Results:
Takes me to Host page as default

Expected:
Should take me to Services main list page

**Comment by vincent99** [comment]
This was fixed at some point..

**Comment by tfiduccia** [comment]
build from master - June 10th
Verified fixed
