### ISSUE TITLE
Once I select and use Enterprise, I can't use regular GitHub

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#958]
v0.22.0-rc2
Steps:
1.  Authenticate with enterprise account
2.  Disconnect
3.  Try to authenticate with regular GitHub account

Results:
Sits "waiting to hear from back from GitHub

Expected:
Should authenticate

Additional info:
I notice if I leave the page and come back, the enterprise checkbox is still checked and ghe.rancher.io is in the Enterprise host text field.  I have tried to manually delete it, but still same thing happens and refresh makes them reappear.

**Comment by vincent99** [comment]
@hibooboo2: Sending a new githubConfig with `hostname: null` is not causing the setting to be put back to default public github.

**Comment by hibooboo2** [comment]
Ok ill fix that.

**Comment by tfiduccia** [comment]
v0.23.0-rc5
Failed

Now if I do the above steps, I actually end up on a error page and I can't get back into the app.

**Comment by hibooboo2** [comment]
https://github.com/rancherio/cattle/pull/585/ Addresses this. I will let @tfiduccia know when it hits master.

**Comment by tfiduccia** [comment]
build from master - June 11th
Verified fixed
