### ISSUE TITLE
[UI] [Container] Invalid Command error

### ISSUE THREAD

**Issue by smw355** [rancherio/rancher#96]
When trying to launch a container I get an error that says invalid command. This should be a specific error that tells me how to fix it. I don't know what is causing the error.  I was trying to create a container with this image: itzg/minecraft-server
I passed in the port information, and an environnment variable EULA = TRUE
Image attached.

![image](https://cloud.githubusercontent.com/assets/9849879/6175163/2c9e201e-b2a9-11e4-9d14-3e17fa67071b.png)

**Comment by vincent99** [comment]
Yeah the UI needs validation/cleanup on all the fields.. What's happening is you clicked/focused on the command field, which internally changed the value I send from null to empty string, and the API doesn't accept empty string.

**Comment by vincent99** [comment]
Created rancherio/ui#60 to address this

**Comment by smw355** [comment]
Thanks.

**Comment by deniseschannon** [comment]
Moved RancherIO/UI issue into RancherIO/Rancher: https://github.com/rancherio/rancher/issues/239

**Comment by vincent99** [comment]
This should no longer happen.  What was happening is when you focus the field the value internally stored changed from null to an empty string (input fields can't really be null).  The API was then sent empty string, which it doesn't accept.

With the new validation against schema, fields are: trimmed, converted to numbers if they're supposed to be numeric, then converted to null if the value is empty string and the field is nullable.  (like command, user, and a bunch of other fields in a container are).

**Comment by tfiduccia** [comment]
v0.16.0
Clicked in every field to shift focus and then created container.
Verified Fixed
