### ISSUE TITLE
Support Host label on Rancher agent registration

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#961]
Support capability to pass in a host-label on a rancher agent registration so that Rancher can automatically tag/label the host when the agent connects.

Related to #957

**Comment by faddat** [comment]
This is a good idea.  It would be nice to be able to re-name hosts, too.  

I will be testing a larger and more complex deployment today, structured as:

15 local boxes (i5/16g/network storage)
3 azure (8g/4 core)
1 vultr (will be the server node)

Hoping to publish my metareview of the state of container managers today or tomorrow, and will link you.  I also noticed that some rancher based products are cropping up on GitHub-- great! On the rancher homepage I noticed a section on storage management-- am I correct that is not ready?

**Comment by vincent99** [comment]
Host rename will be in the next release, along with editing the labels.

I believe we'll have something to demo at DockerCon for storage.
