### ISSUE TITLE
If I edit Service it automatically restarts my container

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#969]
v0.22.0-rc1
Steps:
1.  Create a docker:mysql service with scale of 1
2.  Stop mysql container
3.  Edit the Service and change the description

Results:
The mysql container restarts and stays on

Expected:
Any container that was stopped should stay stopped.

**Comment by will-chan** [comment]
I think this might not be an issue.  Or, perhaps the problem should be that you shouldn't be able to stop a container within a service?  The desired state of the service is 1, so our service controller is attempting to maintain that desired state.  Alena?

**Comment by alena1108** [comment]
The reason for this behavior - we trigger service reconcile when any field update happens for service in Active state. It can be scale, or description, or a name change. And as a part of reconcile, stopped containers get started.

I don't see any downsides in current behavior; but we can be more specific in the future and trigger reconcile only when the scale changes.

**Comment by vincent99** [comment]
The downside would be that the container might be doing something when we decide to restart it :-)

**Comment by alena1108** [comment]
@tfiduccia with service.reconcile happening on instance.stop, this bug is no longer relevant (the container is restarted right after it stops). So closing it.
