### ISSUE TITLE
Amazon EC2: White space before and after Access key causes authentication error

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#972]
v0.22.0-rc2

Steps to Reproduce:
1. Put in correct access key but with a couple of spaces in front of it.

Result: Error in 
AuthFailure: Authorization header or parameters are not formatted correctly.

OR

Put in correct access key but with a couple of spaces after it.

AuthFailure: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'XXXXXXXXXXXXXXX'

Expected Result: It should trim white space from front and back of text for access key.

**Comment by tfiduccia** [comment]
v0.24.0-rc1
Verified fixed
