### ISSUE TITLE
Amazon EC2: Standard Security Group should show what we are opening as ports for rancher-machine

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#973]
v0.22.1-rc2

When creating the `rancher-machine` security group, we automatically open the necessary ports to make Rancher work.

We should include in the UI what ports will be made open in the `rancher-machine` security group. 

![screen shot 2015-05-29 at 9 55 01 am](https://cloud.githubusercontent.com/assets/11410997/7887814/cb419da8-05e8-11e5-8f96-427a7b5b5bc9.png)

**Comment by vincent99** [comment]
:-1:?  If you're happy with automatic configuration you probably don't care what ports are being opened, and if you do you probably shouldn't use automatic configuration.  How about a small link to docs instead of a giant block of text?

**Comment by deniseschannon** [comment]
Yes, a small link is fine.

**Comment by vincent99** [comment]
@deniseschannon Can you add where I should link to here and send it back when that's available?

**Comment by deniseschannon** [comment]
Here is where the docs will eventually be. 

https://rancherio.github.io/rancher/docs/infrastructure/hosts/amazon/#EC2Ports

**Comment by vincent99** [comment]
Added link..

**Comment by tfiduccia** [comment]
Denise, the link is in the UI and it's correct according to your comment.  But https://rancherio.github.io/rancher/docs/infrastructure/hosts/amazon/#EC2Ports goes to a 404 File not Found page.

**Comment by deniseschannon** [comment]
@tfiduccia yep, at the current time, docs aren't posted up yet. when we release the docs, i'll verify.

**Comment by deniseschannon** [comment]
Docs are live and link is working as expected.
