### ISSUE TITLE
Amazon EC2: rancher-machine is also adding the 2376 port to the list of inbound ports

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#975]
v0.22.1-rc2

When creating a host and having Rancher create a `rancher-machine` security group, it also opens TCP port `2376`.

Why is this also being added when it's not listed in the necessary ports for a custom security group? If it's needed for us to create and manage the security group, we should list it as one of the ports being opened in the `rancher-machine` SG (#973)

![screen shot 2015-05-29 at 9 55 01 am](https://cloud.githubusercontent.com/assets/11410997/7888317/7aa9ede2-05ec-11e5-9043-3a1519ca5dda.png)

**Comment by vincent99** [comment]
`2376` is the Docker daemon port. The UI isn't setting it, the EC2 machine driver is automatically adding this to the security group if it doesn't exist, and there is no option to have them not do that.(https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L688-L713)

We don't need that port to be public, and would probably prefer that it not be by default...

**Comment by deniseschannon** [comment]
Added to documentation.
