### ISSUE TITLE
Amazon EC2: If rancher-machine ports are changed, launching a new instance doesn't open the missing ports

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#976]
v0.22.1-rc2

Steps to Reproduce:
1. Edit the rancher-machine security group by removing one of the ports.
2. Launch a Amazon EC2 host and select the "Standard" option that will re-use existing `rancher-machine` security group

Result: The missing ports are not re-opened and therefore, Rancher will not work correctly

Expected Result: Necessary ports will be re-opened.

**Comment by vincent99** [comment]
I'd really rather not mess with an existing security group the user has explicitly changed, probably for a good reason.  The UI option changes to reflect this, from "Standard: Automatically create a rancher-machine group" to "Standard: Use the existing rancher-machine group".

**Comment by deniseschannon** [comment]
But if there is a group of people using the one AWS account (like we do) and someone else could change the security group without me knowing. If I was to use the "Standard: Use the existing rancher-machine group", I would assume that everything in Rancher would work correctly. If it doesn't work, I would assume that Rancher is broken and not the fact that my "existing rancher-machine" security group didn't have the correct ports open.

There needs to be some kind of message to the user to let them know that even though we're using security group that has the rancher-machine name, the ports might not be open for Rancher.

**Comment by deniseschannon** [comment]
I've added this to the documentation for Rancher.
