### ISSUE TITLE
Support new image@sha256 syntax

### ISSUE THREAD

**Issue by vincent99** [rancherio/rancher#977]
Docker 1.6 adds support for `image@sha256:[sha value]` syntax when pulling an image, we should support it.

https://blog.docker.com/2015/04/faster-and-better-image-distribution-with-registry-2-0-and-engine-1-6/

e.g.  `google/cloud-sdk@sha256:506775439bd4f44d90a3f6784f2b625e55c43635f9f2c4cae24ac4b3dea0277a`

`500 Server Error: Internal Server Error ("Invalid repository name (cloud-sdk@sha256), only [a-z0-9-_.] are allowed")`

**Comment by hibooboo2** [comment]
Addressed with https://github.com/rancherio/cattle/pull/551

**Comment by hibooboo2** [comment]
This is now merged and on master.

**Comment by sangeethah** [comment]
Tested with build from master - Jun/10

Able to start a container with image - 
"sangeetha/shatest@sha256:50cbbc4ebb19036d0d1057d582d68db57ab9dc96174e91a735daf42aa4dac69a".

When I try to start a container with invalid digest , I get  error - "not found in repository" . Is this the correct error message ?

**Comment by sangeethah** [comment]
Tested with server version - 0.24.0-rc1

Able to start container and services with image - 
"sangeetha/shatest@sha256:50cbbc4ebb19036d0d1057d582d68db57ab9dc96174e91a735daf42aa4dac69a".

When I try to use image with invalid digest, it fails with error message - "failed to pull : Tag not found in repository sangeetha/shatest"
