### ISSUE TITLE
dataVolumesFromService is not working for LB services.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#982]
Server version - Build from master on 5/29

Steps to reproduce the problem:
Created environment - e1.
Created a service S1 in e1 and activated it.
Created a LB service S2 with dataVolumesFromService pointing to S1.
Activate environment.

LB Agents from S2, do not have VolumesFrom set.

**Comment by vincent99** [comment]
What's the use-case for a load balancer/ load balancer service needing volumesFrom?  The UI doesn't show the option on balancers.

**Comment by sangeethah** [comment]
Tested with server version - V0.23.0-rc1
Created environment - e1.
Created a service S1 in e1 and activated it.
Created a LB service S2 with dataVolumesFromService pointing to S1.
Activate environment.

LB Agents from S2 have VolumesFrom set.
