### ISSUE TITLE
No way to change or edit a load balancer

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#991]
v0.22.0-rc2

After creating a load balancer, there is no way to edit the load balancer for a service.

In the load balancer, the edit page only shows name/description.

In the load balancer configs, the edit page only shows name/description.

So currently the only way to change the load balancing a service is to delete the existing load balancer and add a completely new one.

Not sure if this is a UI issue or a load balancer issue.

**Comment by vincent99** [comment]
Duplicate of #541
