### ISSUE TITLE
Clicking on "create" button after cloning a service does nothing.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#993]
Server Version - Built from master 05/31

Steps to reproduce the problem:

Create a service and activate it.
Use clone option to clone the service.
On the "Add service" page , change the name and description of the service and click "create".
Clicking on "create" button after cloning a service does nothing.

**Comment by sangeethah** [comment]
Reopening this issue.

When testing with latest UI , when i clone a service and click on "create"button , it takes me to a empty project page.

When i refresh the project , I see the cloned service.

Expected Behavior:
Once i click on "create"button , It should take me back to the project view where I should be able to see the cloned service.

**Comment by vincent99** [comment]
@sangeethah works fine for me.. if that's still an issue please open a separate/non-blocker issue.
