### ISSUE TITLE
Host labels not set when adding Digital Ocean machine with labels.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#995]
Server Version - Built from master 05/31

Steps to reproduce the problem:

Add Digital Ocean machine by setting labels.
When the host gets added , it does not have the labels set.

Rancher agent was started with the environment variable "CATTLE_HOST_LABELS" set to nothing.
Expected behavior is for "CATTLE_HOST_LABELS" to be set to the labels that was set when adding the Digital Ocean machine.

**Comment by will-chan** [comment]
I just tried this out.  It works.  Sangeetha is going to retry with the right label.

**Comment by sangeethah** [comment]
When entering labels , I was entering name and value for the name and vakue fields. The right way is to use name as "CATTLE_HOST_LABELS"  and value as "name=value" format.

When set this way, host labels are adding correctly.
