### ISSUE TITLE
Service labels are not set when setting "global" on and setting "io.rancher.scheduler.affinity:host_label".

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#997]
Server Version - Built from master 05/31

Steps to reproduce the problem:

Create a service by setting "global" on and setting "io.rancher.scheduler.affinity:host_label" to a host label that is associted with couple hosts say host1 and host2.

When I activate the service, I dont see the containers being launched in host1 and host2.
Instead , it was launched in another host which did not have the host_label specified.

There are no labels set in service.
Following are the labels (relating to scheduler) set in the container that was launched 
"io.rancher.scheduler.affinity:container_label_soft": "io.rancher.service.deployment.unit=91cfa7ee-cdac-400f-8507-db888fdf1655",

**Comment by vincent99** [comment]
I believe adding service labels was just broken at the time...

**Comment by sangeethah** [comment]
With latest master build , when service is created with "global"  set to "true" and "io.rancher.scheduler.affinity:host_label" , both the labels are set for the service.
