### ISSUE TITLE
Containers that are created as part of Services with  labels set for global - true on and "io.rancher.scheduler.affinity:host_label", have same values being added multiple times to the labels.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#998]
Server Version - Built from master 05/31

Steps to reproduce the problem:

Create a service with labels set for global - true on and "io.rancher.scheduler.affinity:host_label".

When this service is activated , we see that the containers that are deployed have  same values being added multiple times to the labels.

"labels": {
"io.rancher.scheduler.affinity:host_label": "foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar,foo=bar",
"io.rancher.scheduler.global": "true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true",
"io.rancher.service.deployment.unit": "4c9d508f-f478-4edf-af93-b2e402212537,b3306350-a9fa-4fff-a748-88882f0742b0,964b2502-769e-47ff-b76d-02b616afa1a6,b6b40a66-0876-4f03-9485-b8277f0a2229",
"io.rancher.scheduler.affinity:container_label_soft": "io.rancher.service.deployment.unit=4c9d508f-f478-4edf-af93-b2e402212537,io.rancher.service.deployment.unit=b3306350-a9fa-4fff-a748-88882f0742b0,io.rancher.service.deployment.unit=964b2502-769e-47ff-b76d-02b616afa1a6,io.rancher.service.deployment.unit=b6b40a66-0876-4f03-9485-b8277f0a2229",
"io.rancher.service.requested.host.id": "6,7,8,13",
"io.rancher.service.name": "test515507,test515507,test515507,test515507",
"io.rancher.environment.name": "test815962,test815962,test815962,test815962",
},

**Comment by sonchang** [comment]
Should be fixed now with https://github.com/rancherio/cattle/pull/539

**Comment by sangeethah** [comment]
Tested with server version - V0.23.0-rc5.

This issue is not seen anymore.
