### ISSUE TITLE
Labels are not copied from machine resource to newly created host

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#999]
Server Version - Built from master 05/31

Steps to reproduce the problem:

Add hosts with labels setting name ="CATTLE_HOST_LABELS" and value="foo=bar" .
When the hosts gets added successfully , the labels are being saved as name=foo and value=bar.

When editing hosts to set labels ,  we are allowed to set the labels as name=foo and value=bar.
There are 2 different ways we expect users to set labels on host when adding hosts and editing hosts.
This seems very confusing.

UI should  be able allow for setting labels in the format of  name=foo and value=bar when adding hosts and be able to translate it to the label format that is needed by the create machine API.

**Comment by vincent99** [comment]
@will-chan @wlan0 Why isn't the API just setting multiple labels on the machine resource? It makes no sense for them to have labels, but the only one that does anything is a magic key that matches the name of an environment variable.

**Comment by will-chan** [comment]
We left it at "labels" in case we wanted to support something else in the future.  Perhaps we can hardcode the cattle API to pass in the generic labels with "CATTLE_HOST_LABELS".

**Comment by cjellick** [comment]
@will-chan @wlan0 @vincent99 I was thinking about this too.

I think cattle should stay as is, but GMS should do all the processing of turning machine.labels into the CATTLE_HOST_LABELS env var/

**Comment by will-chan** [comment]
We can but then if we want to support other labels in the future, we'd have to fix GMS.  Anyways, it's either a UI solution of pre-appending the actual host label or have GMS translate it.

**Comment by ibuildthecloud** [comment]
@will-chan We specifically added this for rancher labels.  Machine has another concept called engine options that we can support in the future that allows setting docker labels on the daemon.  But the current implementaion `{foo: bar}` should be `-e CATTLE_HOST_LABELS=foo=bar`.  Can @wlan0 change this?

**Comment by will-chan** [comment]
Ok, let's fix GMS to do this.

**Comment by sangeethah** [comment]
Tested with server version = V0.23.0-rc5

I am able to add Digital Ocean machine by providing labels with format name=value.

When the host gets added to the server , the labels are set as name=value format .
